- MeshLib/Mesh.cpp
- MeshLib/Mesh.h
- MeshLib/Properties.h
- MeshLib/PropertyVector.h
- Tests/MeshLib/MeshProperties.cpp
This PR is based on the discussion in PR #531:
- It adds an implemention to manage properties within the Mesh.
- The properties are associated to specific mesh items like mesh nodes or mesh
elements via an enum class (see enum class MeshItemType).
- The properties are not restricted to a particular data type, you can use several types like double, vector or matrix
types at run time together (see tests).
- There is not a possibility to get the value data type.
> MeshLib add properties

- Applications/DataExplorer/DataView/CondFromRasterDialog.h
- Applications/DataExplorer/DataView/MeshElementRemovalDialog.h
- Applications/DataExplorer/DataView/MshModel.h
- Applications/DataExplorer/mainwindow.h
See https://bugreports.qt.io/browse/QTBUG-22829
This broke compilation on Mac OS, Clang 3.5, Boost 1.57.
> Fixed some compile errors due to a moc-bug in combination with Boost

- MathLib/Nonlinear/Picard-impl.h
VS interprets the following output in a custom build step as an error:
[any text] {**error** | **warning**} code####**:** localizable string
Note that only `error` and the following `:` are necessary to trigger this.
See https://msdn.microsoft.com/en-us/library/yxkt8b26.aspx
> Fixes a misbehavior of Visual Studio interpreting test output as build errors

- .travis.yml
For travis: if PETSc is used, only MPI related unit tests are performed.
> [TR] Only run MPI related tests under condition PETSC.

- Applications/DataExplorer/DataView/MeshAnalysis.ui
- Applications/DataExplorer/DataView/MeshAnalysisDialog.cpp
- Applications/Utils/MeshEdit/checkMesh.cpp
- MeshLib/MeshQuality/MeshValidation.cpp
- MeshLib/MeshQuality/MeshValidation.h
- MeshLib/MeshSurfaceExtraction.cpp
- MeshLib/MeshSurfaceExtraction.h
- Tests/MeshLib/TestMeshValidation.cpp
implements algorithm to detect "holes" within meshes (e.g. missing triangles in a 2D mesh) by using a kind of surface marching algorithm.
works for 2D and 3D meshes, as long as they don't have "weird" geometries, e.g. more than two 2D elements sharing an edge.
the test is included in gui and in nori's command line tool for mesh testing.
here's an example if you don't know what i am referring to by "holes in a mesh" (from inside Feng's Nankou study):
currently i am only returning the number of holes found in the mesh. in theory i also know the boundaries of the holes at some point. i am not sure if it'd be useful to return those, too?!
> Mesh hole detection

- Applications/CLI/ogs.cpp
- FileIO/XmlIO/Boost/BoostXmlGmlInterface.cpp
... only those, which are read by the read_xml() function.
Otherwise the comments are stored in extra xmlcomment boost::property_tree, which is not parsed by any of the config readers.
With the new function the xmlcomments are ignored.
> Ignore XML comments in input files.

- Applications/Utils/OGSFileConverter/CMakeLists.txt
This is follow-up  of #584. Sorry I created a branch in the previous PR in the UFZ repo without awareness.
> fix CMake error due to empy VTK_USE_FILE

- .travis.yml
- Tests/CMakeLists.txt
- scripts/cmake/test/Test.cmake
This replaces https://github.com/ufz/ogs/pull/591.
Additionally it removes the AssemblerLib tests from the 'tests' target when building with OGS_USE_PETSC, as requested in https://github.com/ufz/ogs/pull/582.
[Technical note: there is no second '-' required for gtest_filter.]
> Made the invocation of the testrunner more consistent

- AssemblerLib/LocalToGlobalIndexMap.cpp
- AssemblerLib/LocalToGlobalIndexMap.h
No logic change, just extracting a function. Merging this now would help with merging PETSc and NeumannBC stuff later.
This is used in the constructor and in another constructor added in #599.
> Extract findGlobalIndices() method in LocalToGlobalIndexMap.

- BaseLib/StringTools.cpp
- BaseLib/StringTools.h
- FileIO/XmlIO/Boost/BoostXmlGmlInterface.cpp
When attributes are missing the corresponding element is outputted in a JSON representation. Therefore I added `BaseLib::propertyTreeToString(boost::property_tree::ptree const& tree)`
Fixes #590.
> More verbose error output when reading GML files

- Applications/Utils/FileConverter/FEFLOW2OGS.cpp
- FileIO/FEFLOWInterface.cpp
This PR includes
- fix a bug in importing a FEFLOW file reported by Sophie. Dimension of node coords given under "supermesh" section may not be equal to the dimension of the problem (e.g. only x,y coords are given while a problem is 3d).
- minor refactoring in FEFLOW2OGS.cpp
> Fix a bug in FEFLOW import

- scripts/cmake/packaging/ArchiveTestdata.cmake
- scripts/cmake/packaging/Pack.cmake
- scripts/packaging/archive-testdata.sh
This target creates a gzipped tar and a zip-file of all files in `Tests/Data`. Symlinks are resolved and files are stored with their correct name.
Requirements:
- `zip`
- `realpath`
> Added build target archive-data on Linux / Mac.

- MeshGeoToolsLib/BoundaryElementsAlongPolyline.cpp
- MeshGeoToolsLib/BoundaryElementsAlongPolyline.h
- MeshGeoToolsLib/BoundaryElementsOnSurface.cpp
- MeshGeoToolsLib/BoundaryElementsOnSurface.h
- MeshGeoToolsLib/BoundaryElementsSearcher.cpp
- MeshGeoToolsLib/BoundaryElementsSearcher.h
- MeshGeoToolsLib/MeshNodeSearcher.cpp
- MeshGeoToolsLib/MeshNodeSearcher.h
- MeshGeoToolsLib/MeshNodesAlongPolyline.cpp
- MeshGeoToolsLib/MeshNodesAlongSurface.cpp
- NumLib/Function/LinearInterpolationAlongPolyline.h
- NumLib/Function/LinearInterpolationOnSurface.h
The namespace MeshGeoTools was renamed some time ago to MeshGeoToolsLib.
This removes or corrects the leftovers, mostly comments, but also some namespace declations.
> Correct MeshGeoTools references to MeshGeoToolsLib.

- AssemblerLib/LocalDataInitializer.h
- NumLib/Fem/Integration/GaussIntegrationPolicy.h
- ProcessLib/GroundwaterFlowProcess.h
Currently in the `GroundwaterFlowProcess` the regular Gauss integration scheme was used. There is a special integration rule for triangle elements, which is different from the "regular" elements. This is used now.
Also move the choice of the integration scheme into the `LocalDataInitializer` from the processes.
> Correct triangle Gauss integration

- Applications/DataExplorer/DataView/MeshElementRemoval.ui
- Applications/DataExplorer/DataView/MeshElementRemovalDialog.cpp
- Applications/DataExplorer/DataView/MeshElementRemovalDialog.h
we detected rounding error when string representations of double numbers are converted back to doubles (specifically in the bounding box specifications of the element extraction dialog)
this fix changes the dialog to only use text to double conversion for text fields that have been edited.
> [Fix] Extraction of mesh elements based on bounding box

- BaseLib/excludeObjectCopy.h
- Tests/BaseLib/excludeObjectCopy.cpp
PR in preparation for PR https://github.com/ufz/ogs/pull/607
The excludeObjectCopy functions will be used to copy properties later on.
> Exclude object copy

- MeshLib/Properties-impl.h
- MeshLib/Properties.cpp
- MeshLib/Properties.h
- MeshLib/PropertyVector.h
- Tests/MeshLib/MeshProperties.cpp
This PR improves the usability of the classes `Properties`and `PropertyVector` due to
- Renaming some methods in Properties.
- Adding some methods that are needed for the use.
- Using base class and derived classes instead of `boost::any` in `Properties`.
- Changed the implementation of class template `PropertyVector` in case of pointer types.
- Add more tests.
Many of the commits of this PR are broken off the PR https://github.com/ufz/ogs/pull/607 to make review easier. It will follow further PRs based on this PR. If possible I would appreciated I quick review :smile:
> Reorganize classes Properties and PropertyVector

- FileIO/CsvInterface.cpp
- FileIO/CsvInterface.h
- Tests/testrunner.cpp
The locale at my environment was set to a comma instead of a period to separate the integer part from the non-integer part (for instance 1,2 instead of 1.2). Since some of the CsvInterface methods use locale dependend functions to read floating point numbers some of the CsvInterfaceTests failed. For this reason, I suggest to set the locale at start of the testrunner to the following: `setlocale(LC_NUMERIC,"C");`
Additional, there is one commit removing some warning in clang and one commit that remove some unnecessary whitespaces.
> Csv interface issues

- Applications/Utils/MeshEdit/CMakeLists.txt
- Applications/Utils/MeshEdit/NodeReordering.cpp
- MeshLib/MeshGenerators/VtkMeshConverter.cpp
due to using InsituLib now (specifically, direct use of VTK methods for reading and writing meshes) we established in inconsistency for node ordering in prism-elements. this PR fixes that such that meshes are now again displayed correctly in OGS as well as in ParaView.
unfortunately, this also means that old ogs-meshes (created before including insitu-lib) need to have the prism nodes reordered. i adjusted the existing node-reordering tool to provide an easy way to do that (use parameter ```-m 2```).
note: the old meshes are not *per se* broken, it's just that the face-normals of prism elements point in the wrong direction. if this doesn't concern you, you need not re-order nodes.
> Prism node ordering

- Applications/Utils/MeshEdit/AddTopLayer.cpp
- Applications/Utils/MeshEdit/CMakeLists.txt
Erik and Marc requested a small tool to add a new top layer to a mesh. Hope it will be useful.
See also the [documentation](http://docs.opengeosys.org/docs/tools/meshing/addtoplayer).
> Tool to add a top layer with specified thickness to a mesh 

- FileIO/Legacy/MeshIO.cpp
- FileIO/Legacy/MeshIO.h
- MeshLib/Properties.h
- MeshLib/PropertyVector.h
Reading material ids of elements from the old ogs mesh file format (*.msh) into the new data structures.
> MeshIO using new Properties and PropertyVector.

- MeshGeoToolsLib/BoundaryElementsSearcher.cpp
- Tests/MeshLib/MeshSubsets.cpp
The compilation error:
```error: default initialization of an object of const type 'const std::vector<MeshLib::Element *>' without a user-provided default constructor```
is produced by clang-3.6.0, which is correct for the current standard, but will be corrected later as described in
http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#253
In gcc-5.1.0 this is only a warning.
See also [this SO thread](http://stackoverflow.com/questions/26077807/why-does-gcc-allow-a-const-object-without-a-user-declared-default-constructor-bu).
> Fix compilation error w/o explicit default initialization of a const object.

- GeoLib/AnalyticalGeometry.cpp
- Tests/GeoLib/TestLineSegmentIntersect.cpp
@waltherm discovered a bug while reading a geometry. See issue #662. This bug is fixed with this PR. The previous failing cases are included as new tests.
> GeoLib fix line segment intersection algorithm

- Applications/Utils/MeshEdit/CMakeLists.txt
- Applications/Utils/MeshEdit/CreateBoundaryConditionsAlongPolylines.cpp
- FileIO/XmlIO/Boost/BoostXmlGmlInterface.cpp
Small command line tool to create (OGS-5) boundary conditions along a polyline. The documentation for the tool is [here](http://docs.opengeosys.org/docs/tools/meshing/create-boundary-conditions-along-a-polyline).
> Create boundary conditions along polyline

- MeshLib/PropertyVector.h
- Tests/MeshLib/MeshProperties.cpp
@rinkk detected an issue in the usage of `PropertyVector`. If the tuple size is greater than 1 the usage of `PropertyVector` was not intuitive anymore since `size()` returned the total number of values stored in the `PropertyVector`. In this PR an implementation is proposed that changes this behaviour. The method `size()` returns now the number of tuples. The total number of values can be computes as follow: "number of tuples (i.e. size()" times "tuple size".
> Small interface change class PropertyVector

- MeshLib/MeshEditing/ElementValueModification.cpp
- MeshLib/MeshEditing/ElementValueModification.h
This is another PR that changes the handling of materials. `Properties` and `PropertyVector` are used in `ElementValueModification`.
> Using new mesh interface for Properties in class ElementValueModification 

- FileIO/VtkIO/VtuInterface.cpp
* checks if a file of the given name actually exists
* checks if the reader was able to read an unstructured grid (by testing if number of nodes is > 0 which was the most low level check i could think of)
> [Fix] Added checks for VTU reader

- Applications/DataExplorer/VtkVis/VtkMeshSource.cpp
- InSituLib/CMakeLists.txt
- InSituLib/VtkMappedMesh.cpp
- InSituLib/VtkMappedMesh.h
- InSituLib/VtkOGSEnum.cpp
- InSituLib/VtkOGSEnum.h
- MeshLib/Elements/Element.cpp
- MeshLib/Elements/Hex.h
- MeshLib/Elements/HexRule20.cpp
- MeshLib/Elements/HexRule20.h
- MeshLib/Elements/Prism.h
- MeshLib/Elements/PrismRule15.cpp
- MeshLib/Elements/PrismRule15.h
- MeshLib/Elements/Pyramid.h
- MeshLib/Elements/PyramidRule13.cpp
- MeshLib/Elements/PyramidRule13.h
- MeshLib/Elements/Tet.h
- MeshLib/Elements/TetRule10.cpp
- MeshLib/Elements/TetRule10.h
- MeshLib/Elements/TriRule6.cpp
- MeshLib/Elements/TriRule6.h
- MeshLib/MeshEnums.cpp
- MeshLib/MeshEnums.h
- MeshLib/MeshGenerators/VtkMeshConverter.cpp
- MeshLib/VtkOGSEnum.cpp
- MeshLib/VtkOGSEnum.h
- Tests/MeshLib/TestElementConstants.cpp
This PR implements quadratic version of Tri, Tet, Hex, Prism and Pyramid elements in MeshLib. I also tried to involve them in InSituLib.
> Add quadratic mesh element types

- Applications/DataExplorer/DataView/MeshLayerEditDialog.cpp
- MeshLib/MeshGenerators/MeshLayerMapper.cpp
- MeshLib/MeshGenerators/MeshLayerMapper.h
This fixes compilation error introduced by removing the empty constructor in the `MeshLayeredMapper`.
This happens with the mac's compiler, which is more strict and produces the following error:
```
<.../ogs/Applications/DataExplorer/DataView/MeshLayerEditDialog.cpp>:261:25: error: default initialization of an object of const type 'const MeshLayerMapper' requires a user-provided default constructor
MeshLayerMapper const mapper;
^
<..../ogs/Applications/DataExplorer/DataView/MeshLayerEditDialog.cpp>:308:25: error: default initialization of an object of const type 'const MeshLayerMapper' requires a user-provided default constructor
MeshLayerMapper const mapper;
^
```
... but the referred objects are not required at all: removing them.
> Fix MeshLayerMapper compilation

- Applications/Utils/MeshEdit/checkMesh.cpp
- MeshLib/Properties.cpp
- MeshLib/Properties.h
- Add `--print_properties` flag to `checkMesh` utility which is then printing the names of all available properties in the mesh file.
- Mark `Properties::hasPropertyVector()` const.
> Mesh properties; small addons.

- Applications/Utils/FileConverter/TIN2VTK.cpp
- Applications/Utils/MeshEdit/CreateBoundaryConditionsAlongPolylines.cpp
- FileIO/Legacy/OGSIOVer4.cpp
- FileIO/TINInterface.cpp
- FileIO/TINInterface.h
- FileIO/XmlIO/Boost/BoostXmlGmlInterface.cpp
- FileIO/XmlIO/Qt/XmlGmlInterface.cpp
- GeoLib/PointVec.cpp
- GeoLib/PointVec.h
The suggested implementation uses a vector of strings to speed up the access the point name. Thus, more memory is used but the access, especially for point sets with more than 100.000 points is faster (_hours vs. seconds_).
> [GeoLib] Speedup point name access.

- Documentation/Doxyfile.in
- Documentation/bibliography.bib
- GeoLib/AnalyticalGeometry-impl.h
- GeoLib/AnalyticalGeometry.cpp
- GeoLib/AnalyticalGeometry.h
- MathLib/LinAlg/Dense/DenseMatrix-impl.h
- MathLib/LinAlg/Dense/DenseMatrix.h
- MathLib/Point3d.h
- MathLib/TemplatePoint.h
- MeshLib/CoordinateSystem.cpp
- MeshLib/CoordinateSystem.h
- MeshLib/ElementCoordinatesMappingLocal.cpp
- MeshLib/ElementCoordinatesMappingLocal.h
- Tests/MathLib/TestDenseMatrix.cpp
- Tests/MeshLib/TestCoordinatesMappingLocal.cpp
- Tests/NumLib/TestFe.cpp
- scripts/cmake/cmake/FindEigen3.cmake
This PR is  a part of #595 and adds mapping of lower dimensional elements (e.g. line in 2D, tri in 3D) between global and local coordinates. The mapping functionality will be used during calculation of shape functions and mapping of tensor material properties like permeability.
> Add ElementCoordinatesMappingLocal class

- GeoLib/GEOObjects.cpp
- GeoLib/PointVec.cpp
- GeoLib/PointVec.h
This PR is based on PR https://github.com/ufz/ogs/pull/675 and must not be merged before PR https://github.com/ufz/ogs/pull/675.
- Small improvements in `GeoLib::PointVec::mergePoints()` 
- Postfix to prefix increments,
- Handles returned nullptr value,
- Rework the loop structure a little bit.
- Using the same eps value for `makePntsUnique` and `uniqueInsert` fixes a inconsistency bug.
> [GeoLib] Restructure and bug fix

- MathLib/Point3d.h
- MathLib/TemplatePoint.h
This PR is based on the comment by Tom (https://github.com/norihiro-w/ogs/commit/460d114a7241401719cf0b7c71162bd58cdea820#commitcomment-11468635), and changes the behaviour of a default constructor of MathLib::TemplatePoint to always initialize its coordinate with zero.
> Initialize with zeron in TemplatePoint default constructor

- MathLib/TemplatePoint.h
- MeshLib/CoordinateSystem.h
following #687. This fix removes MSVC warnings C4800 "'type' : forcing value to bool 'true' or 'false' (performance warning)". 
In addition, warnings introduced by #686
> fix compiler warnings C4800 with MSVC

- Applications/Utils/FileConverter/GMSH2OGS.cpp
- FileIO/GMSHInterface.cpp
- FileIO/GMSHInterface.h
Small PR to add a boolean switch to the util. Using this switch it is possible to enable (default) or disable writing of line elements to the ogs mesh file. Furthermore this PR contains changes necessary to read the material information of elements in the new data structures (PropertyVector).
> GMSH2OGS add switch

- AssemblerLib/LocalDataInitializer.h
- Documentation/bibliography.bib
- NumLib/Fem/CoordinatesMapping/NaturalCoordinatesMapping-impl.h
- NumLib/Fem/CoordinatesMapping/NaturalCoordinatesMapping.h
- NumLib/Fem/CoordinatesMapping/ShapeMatrices-impl.h
- NumLib/Fem/CoordinatesMapping/ShapeMatrices.h
- NumLib/Fem/ShapeMatrixPolicy.h
- ProcessLib/GroundwaterFlowFEM.h
- ProcessLib/GroundwaterFlowProcess.h
- ProcessLib/NeumannBc.h
- ProcessLib/NeumannBcAssembler.h
- Tests/NumLib/CoordinatesMappingTestData/TestHex8.h
- Tests/NumLib/CoordinatesMappingTestData/TestLine2.h
- Tests/NumLib/CoordinatesMappingTestData/TestQuad4.h
- Tests/NumLib/CoordinatesMappingTestData/TestTri3.h
- Tests/NumLib/FeTestData/TestFeHEX8.h
- Tests/NumLib/FeTestData/TestFeLINE2.h
- Tests/NumLib/FeTestData/TestFeLINE3.h
- Tests/NumLib/FeTestData/TestFePRISM6.h
- Tests/NumLib/FeTestData/TestFePYRA5.h
- Tests/NumLib/FeTestData/TestFeQUAD4.h
- Tests/NumLib/FeTestData/TestFeTET4.h
- Tests/NumLib/FeTestData/TestFeTRI3.h
- Tests/NumLib/TestCoordinatesMapping.cpp
- Tests/NumLib/TestFe.cpp
- Tests/NumLib/TestShapeMatrices.cpp
@endJunction sorry i forgot to upload implementations supporting mixed dimensional elements in FE part. your #698 can be merged at the moment, as it should be no problem with neumann BCs because it doesn't require dshape. To really support mixed dim ele in groundwaterflow, we need something like this PR.
> Supporting mixed dimensional elements in FE

- Applications/DataExplorer/DataView/ElementTreeModel.cpp
- Applications/DataExplorer/DataView/MeshElementRemovalDialog.cpp
- Applications/Utils/MeshEdit/moveMeshNodes.cpp
- Applications/Utils/MeshEdit/removeMeshElements.cpp
- GeoLib/AABB.h
- GeoLib/Grid.h
- GeoLib/Polygon.cpp
- GeoLib/Raster.cpp
- MeshLib/CoordinateSystem.h
- MeshLib/MeshEditing/ElementExtraction.cpp
- MeshLib/MeshEditing/ElementExtraction.h
- Tests/GeoLib/TestAABB.cpp
This PR is a result of https://github.com/ufz/ogs/issues/710. @endJunction discovered, that creating AABB objects is relative expensive. So in this PR the size of management overhead of the class `AABB<Node>` is reduced  from 304 byte to 64 byte. I am curious on the new callgraph and run time comparisons.
> Optimization of AABB

- GeoLib/AnalyticalGeometry-impl.h
- GeoLib/AnalyticalGeometry.h
- MeshLib/ElementCoordinatesMappingLocal.cpp
- MeshLib/ElementCoordinatesMappingLocal.h
- NumLib/Fem/CoordinatesMapping/NaturalCoordinatesMapping-impl.h
- Tests/MeshLib/TestCoordinatesMappingLocal.cpp
__Merge after__ ufz/ogs#706.
Based on measurements in ufz/ogs#702 following is achieved:
old measurements:
| dirichlet 1e4 | neumann 1e4   | neumann 1e5
----------|-----------|-------------|-----------
master    |848,454,453|1,118,595,144|21,346,872,940
lower_dim |941,440,774|1,200,626,996|22,149,452,336
diff      |92,986,321 |82,031,852   | 802,579,396
current measurements:
| dirichlet 1e4 | neumann 1e4   | neumann 1e5
----------|-----------|-------------|-----------
lower_dim |941,440,774|1,200,626,996|22,149,452,336
speedupECM |884,765,064|1,143,814,590|21,577,168,825
diff      |-56,675,710 |-56,812,406   | -572,283,511
> Speedup element coordinates mapping

- scripts/cmake/Find.cmake
- scripts/cmake/test/Data.cmake
All external data files are now also stored on [Amazon S3](http://aws.amazon.com/s3/) which is a cheap (3.5 cent per GByte per month) cloud storage provider. The first year is free, afterwards it will be paid by the OpenGeoSys e.V.
This PR adds the S3 download URL and a new target `upload-data` which uploads new files to S3 (requires [s3cmd](http://s3tools.org/s3cmd) and credentials, you can still use the `sync-data`-target on envinf1 to let Jenkins do this for you, see the [developer guide](http://docs.opengeosys.org/docs/devguide/testing/test-data)).
> ExternalData is stored on Amazon S3

- CHANGELOG.md
- GeoLib/OctTree-impl.h
- GeoLib/OctTree.h
- Tests/GeoLib/TestOctTree.cpp
This PR contains a rework of class `OctTree`, which will be used in another PR fixing some issues in `GeoLib::GEOObject` that is already in preparation (see branch [GeoLibReworkMergingGeometries](https://github.com/TomFischer/ogs/tree/GeoLibReworkMergingGeometries)). Also in this PR a tests for `OctTree` are added.
Maybe the `OctTree` can also be useful for other things like mesh node search?
> GeoLib OctTree

- InSituLib/VtkMappedPropertyVectorTemplate-impl.h
- MeshLib/MeshEditing/ElementExtraction.cpp
- MeshLib/MeshEditing/ElementValueModification.cpp
- MeshLib/PropertyVector.h
- Tests/InSituLib/TestVtkMappedMeshSource.cpp
- Tests/InSituLib/TestVtkMappedPropertyVector.cpp
- Tests/MeshLib/MeshProperties.cpp
For better usablility and readability of the `PropertyVector` this PR contains:
- Added `PropertyVector::getNumberOfTuples()` which returns the number of tuples.
- Changed the behaviour of `PropertyVector::size()`. The method now returns the number of tuples times the number of components per tuple.
> PropertyVector usage improvements.

- FileIO/TINInterface.cpp
- GeoLib/GEOObjects.cpp
- Tests/GeoLib/TestGEOObjectsMerge.cpp
- Tests/GeoLib/TestPointVec.cpp
In PR [673](https://github.com/ufz/ogs/pull/673) an id was introduced to the `GeoLib::Point`. At some places I missed to add this id when points are created. This PR is adding the ids to the points.
> Cleanup: Add point ids.

- Applications/DataExplorer/DataView/GEOModels.cpp
- Applications/DataExplorer/DataView/GEOModels.h
- FileIO/GmshIO/GMSHPolygonTree.cpp
- GeoLib/AnalyticalGeometry-impl.h
- GeoLib/AnalyticalGeometry.cpp
- GeoLib/AnalyticalGeometry.h
- GeoLib/GEOObjects.cpp
- GeoLib/GEOObjects.h
- GeoLib/Grid.h
- GeoLib/MinimalBoundingSphere.cpp
- GeoLib/Polyline.cpp
- GeoLib/PolylineWithSegmentMarker.cpp
- GeoLib/QuadTree.h
- GeoLib/Raster.cpp
- GeoLib/SensorData.cpp
- GeoLib/Station.cpp
- GeoLib/StationBorehole.cpp
- GeoLib/Surface.cpp
- GeoLib/Triangle.cpp
PR contains:
- Removal of unused code.
- Change how intersection points are inserted in the GMSHPolygonTree (commit 6d3685e - the only commit with some "real" changes)
- Substitutions of `size_t` with `std::size_t` and `NULL` -> `nullptr`.
> Cleanup in GeoLib

- GeoLib/OctTree-impl.h
- GeoLib/OctTree.h
- Tests/GeoLib/TestOctTree.cpp
- Handle case where the given `eps` is exactly zero -> the `eps` will be set internally to `std::numeric_limits<double>::epsilon()`
- Due to technical reasons OctTree manages now the spatial domain [_ll[0], _ur[0]**)** x [_ll[1], _ur[1]**)** x [_ll[2], _ur[2]**)**. The given upper bound at the construction time will be raised a little bit.
> GeoLib OctTree - some small improvements

- Tests/AssemblerLib/LocalToGlobalIndexMap.cpp
- Tests/AssemblerLib/TestMeshComponentMap.cpp
- Tests/AssemblerLib/TestSerialLinearSolver.cpp
... based on output of the clang's address sanitizer tool.
> [T] Remove memory leaks in AssemblerLib tests.

- FileIO/GMSHInterface.cpp
now reads "physical entity" as the MaterialIDs, before was reading "elementary geometrical entity" as MaterialIDs
from the gmsh manual:
http://www.geuz.org/gmsh/doc/texinfo/gmsh.html#MSH-ASCII-file-format
number-of-tags
gives the number of integer tags that follow for the n-th element. By default, the first tag is the number of the physical entity to which the element belongs; the second is the number of the elementary geometrical entity to which the element belongs; the third is the number of mesh partitions to which the element belongs, followed by the partition ids (negative partition ids indicate ghost cells). A zero tag is equivalent to no tag. Gmsh and most codes using the MSH 2 format require at least the first two tags (physical and elementary tags).
> fix reading of matgroups from gmsh msh

- FileIO/Legacy/OGSIOVer4.cpp
- GeoLib/AnalyticalGeometry.cpp
- GeoLib/Point.h
- GeoLib/PointVec.cpp
- GeoLib/PointVec.h
- Tests/GeoLib/TestComputeAndInsertAllIntersectionPoints.cpp
- Tests/GeoLib/TestGEOObjectsMerge.cpp
- Tests/GeoLib/TestOctTree.cpp
The main change in this PR is the substitution of the method `GeoLib::PointVec::makePntsUnique()` with an `OctTree` based algorithm. This substitution fixes some mistakes that are nearly unavoidable using the old implementation. Furthermore it is much faster to use `GeoLib::PointVec::push_back()` methods. The PR is based on PR https://github.com/ufz/ogs/pull/720 and shall be merged after https://github.com/ufz/ogs/pull/720.
> GeoLib: Rework PointVec

- MeshGeoToolsLib/HeuristicSearchLength.cpp
- MeshLib/Node.cpp
- MeshLib/Node.h
- Tests/MeshLib/MeshSubsets.cpp
- Tests/MeshLib/TestBoundaryElementSearch.cpp
- Tests/MeshLib/TestCoordinatesMappingLocal.cpp
- Tests/MeshLib/TestDuplicate.cpp
- Tests/MeshLib/TestElementConstants.cpp
- Tests/MeshLib/TestElementStatus.cpp
- Tests/MeshLib/TestMeshValidation.cpp
- Tests/MeshLib/TestMoveMeshNodes.cpp
- Tests/MeshLib/TestProjectMeshOnPlane.cpp
- Tests/MeshLib/TestVtkMeshConverter.cpp
- The Node(array) ctor simplifies code in the tests.
- One leak in HeuristicSearchLength is in production code.
> Cleanup mesh lib tests memory leaks

- MathLib/MathTools.cpp
- MathLib/MathTools.h
This reduces number of instructions executed in the `GeoLib::getNearestPoint()` from 1087e6 to 707e6 or around 34% (measured in SearchNearestPointsInDenseGrid test), which is not so bad for a single inline :)
The reason for this is that the `sqrDist` computation is around 20 instructions, but its call costs in order of 100 instructions. Use the assembly, Luke!
> [MaL] Inline sqrDist(double*,...).

- Tests/GeoLib/TestPolygon.cpp
In the previous version the variables a and b were references initialized
to the point 2 and 6 respectively. Later on, the point 2 and 6 were modified.
This modification was not intended by the test and leads to wrong testing.
> [T/GL] Fix PolygonTest.containsSegment.

- MeshLib/Mesh.cpp
currently a mesh ID starts from one. This PR proposes to change it to start from zero.
> [MSH] mesh ID starts from 0

- MeshGeoToolsLib/MeshNodeSearcher.cpp
This was overseen by me in ufz/ogs#738.
> [MGTL] Fix MeshNodeSearchers memoization due to changed mesh_id.

- Applications/Utils/FileConverter/GMSH2OGS.cpp
@waltherm discovered a bug in the GMSH2OGS tool. Using a switch it is possible that line elements are not converted to the OGS mesh. In case the GMSH mesh does not contain line elements and the switch is activated the previous code crashed. The changes in this PR/commit will fix this.
> [A/U] GMSH2OGS: Add nullptr check.

- MeshLib/MeshSurfaceExtraction.cpp
- Tests/FileIO/TestCsvReader.cpp
- Tests/GeoLib/TestAABB.cpp
- Tests/GeoLib/TestBoundingSphere.cpp
- Tests/GeoLib/TestComputeRotationMatrix.cpp
- Tests/InSituLib/TestVtkMappedMeshSource.cpp
- Tests/NumLib/TestCoordinatesMapping.cpp
Following ufz/ogs#745.
This removes all remaining memory leaks detected by clang's address-sanitizer in testrunner (caused by ogs).
There are few remaining but their traces lead to Qt.
One real memory leak (which would occur when using MeshSurfaceExtraction) is detected.
Other memory leaks are due to careless usage in the tests.
> Fix memory leaks in tests

- Applications/CLI/ogs.cpp
The lis initialization was forgotten in the ogs.cpp and resulted in failing simulations for openmp lis configuration.
> [A] Initialize lis.

- GeoLib/AnalyticalGeometry.cpp
- Tests/GeoLib/TestLineSegmentIntersect.cpp
The special case where the line segments (a,b) and (c,d) are parallel but are not located at the same straight line was not handled properly. This led to a singular matrix and to a not a number solution. This commit fixes the handling of the special case.
This PR is related to issue https://github.com/ufz/ogs/issues/734.
fixes ufz/ogs#734
> [GL] Fix bug in lineSegmentIntersect.

- Applications/Utils/MeshEdit/CreateBoundaryConditionsAlongPolylines.cpp
- FileIO/TINInterface.cpp
- GeoLib/MinimalBoundingSphere.h
- GeoLib/Point.h
- GeoLib/Raster.cpp
- MeshGeoToolsLib/GeoMapper.cpp
- MeshLib/ElementCoordinatesMappingLocal.cpp
- MeshLib/MeshSurfaceExtraction.cpp
- MeshLib/Node.cpp
- Tests/GeoLib/TestGrid.cpp
The reason for this PR is to make OGS more secure and to avoid the creation of unnecessary temporary objects.
Main changes:
- Generalized one constructor of class `GeoLib::Point` (commit f3f0b13).
- Avoid using potential insecure Point constructor (see https://github.com/TomFischer/ogs/blob/master/GeoLib/Point.h#L46-49). This constructor is potential insecure because there is not a check if the length of the given `x` is sufficient.
- Creating `Point3d` objects instead of `double [3]` fields at some places.
**Update**
Forgot to mention: Removing the insecure constructor is in preparation.
> Using other Point constructors

- Applications/DataExplorer/VtkVis/VtkCompositeNodeSelectionFilter.cpp
- Applications/Utils/MeshEdit/CreateBoundaryConditionsAlongPolylines.cpp
- Applications/Utils/MeshEdit/ResetPropertiesInPolygonalRegion.cpp
- FileIO/GmshIO/GMSHAdaptiveMeshDensity.cpp
- FileIO/TetGenInterface.cpp
- GeoLib/AABB.h
- GeoLib/AnalyticalGeometry.cpp
- GeoLib/AnalyticalGeometry.h
- GeoLib/Polygon.cpp
- GeoLib/Station.cpp
- MathLib/Point3dWithID.h
- MathLib/TemplatePoint.h
- MeshLib/convertMeshToGeo.cpp
The reason for this PR is the same as for PR #749, i.e. to make OGS more secure and to avoid the creation of unnecessary temporary objects. The PR is based on PR #749 and should be merged after 749 is merged.
The main point is the introduction of the keyword `explicit` in `TemplateVector` constructors (commit 14e2702) and removing the potential insecure constructor (commit 93741af).
> Improve point type constructors

- Applications/DataExplorer/VtkVis/VtkCompositeNodeSelectionFilter.cpp
- Applications/Utils/MeshEdit/CreateBoundaryConditionsAlongPolylines.cpp
- Applications/Utils/MeshEdit/ResetPropertiesInPolygonalRegion.cpp
- FileIO/GmshIO/GMSHAdaptiveMeshDensity.cpp
- FileIO/TetGenInterface.cpp
- GeoLib/AABB.h
- GeoLib/AnalyticalGeometry.cpp
- GeoLib/AnalyticalGeometry.h
- GeoLib/Polygon.cpp
- GeoLib/Station.cpp
- MathLib/Point3dWithID.h
- MathLib/TemplatePoint.h
- MeshLib/ElementCoordinatesMappingLocal.cpp
- MeshLib/convertMeshToGeo.cpp
Small PR based on PR #750. The data type given to `TemplatePoint::setCoords()` can be checked at compile time. Only commit fb67b52 and 167bbd8 needs a review.
> Improve TemplatePoint::setCoords()

- GeoLib/Grid.h
- GeoLib/Point.h
- GeoLib/Surface.cpp
- GeoLib/Surface.h
- GeoLib/Triangle.cpp
- GeoLib/Triangle.h
- MathLib/MathTools.h
- MeshGeoToolsLib/GeoMapper.cpp
- MeshGeoToolsLib/MeshNodeSearcher.cpp
- MeshGeoToolsLib/MeshNodesAlongSurface.cpp
- MeshLib/MeshEditing/MeshRevision.cpp
- NumLib/Function/LinearInterpolationOnSurface.cpp
- NumLib/Function/LinearInterpolationOnSurface.h
- SimpleTests/MeshTests/MeshSearchTest.cpp
PR is based on PR #750.
- It generalizes the interfaces in classes `Surface`, `Triangle` and `Grid`such that some of the methods accept `MathLib::Point3d` instead of `GeoLib::Point`. This avoids creating temporary objects.
- Because of the changes of 1. it is possible to remove the potential insecure constructor in class `GeoLib::Point` (commit eaf7f10).
- At the moment there is no need to have a templated version of `sqrDist()`. For this reason the template version is substituted with a version that takes to `MathLib::Point3d` objects. `MathLib::Point3d` is the base class of most of the in OGS used point types.
> Generalized interfaces to avoid temporaries.

- ThirdParty/tclap/CmdLine.h
`ignoreUnmatched()` was copied from TCLAP codes in vtkdiff. The official TCLAP doesn't have such function but am not sure where it comes from...
Anyway, we need the function because current TCLAP throws an error if one provides any arguments which are not registered in TCLAP. For example, this is required for PETSc which is often configured via command line arguments.
> [TCLAP] add ignoreUnmatched

- GeoLib/AABB.h
- GeoLib/TemplateVec.h
- MathLib/LinAlg/Lis/LisMatrix.cpp
- MeshLib/MeshSubsets.h
- Tests/GeoLib/TestGrid.cpp
- Tests/GeoLib/TestPointVec.cpp
- Tests/MeshLib/MeshSubsets.cpp
This are the leftovers of my DisableExceptions branch.
__Update:__ There are no logic changes anymore compared to the original PR. Only replace `throw` with ERR() + `std::abort`.
I checked on a small code sample that removing `throw`s indeed decreases binary size (by 8 bytes :-). Unfortunately this is not the case with logog messages, which are quite expensive (much more expensive as the throw solution).
bin/ogs sizes in byte (clang, O3, march=native, stripped.) :
| with logog | without logog | saved by removing logog 
---- | ------------ | ----------------- | ----------------------
base ufz/master | 1839296 | 1739496 | 99800
this PR | 1841984 | 1739472 | 102512
saved by this PR | -2688 | 24 | 
Removing logog means replacing DBUG, INFO, ERR macros with a std::printf calls, not removing …
> Remove some try catch blocks

- MeshGeoToolsLib/AppendLinesAlongPolyline.cpp
- MeshGeoToolsLib/GeoMapper.cpp
- MeshGeoToolsLib/GeoMapper.h
- MeshGeoToolsLib/HeuristicSearchLength.cpp
- MeshGeoToolsLib/HeuristicSearchLength.h
- MeshGeoToolsLib/MeshNodeSearcher.cpp
- MeshGeoToolsLib/MeshNodeSearcher.h
- MeshGeoToolsLib/MeshNodesAlongPolyline.cpp
- MeshGeoToolsLib/MeshNodesAlongPolyline.h
- MeshGeoToolsLib/MeshNodesAlongSurface.cpp
- MeshGeoToolsLib/MeshNodesAlongSurface.h
- MeshGeoToolsLib/SearchLength.h
- MeshLib/PropertyVector.h
- NumLib/Function/LinearInterpolationAlongPolyline.cpp
- Tests/MeshLib/TestBoundaryElementSearch.cpp
This PR ~~is based on #759 and~~ fixes some include issues in MeshLib and MeshGeoToolsLib, i.e. adding absolute path, forward declarations, correcting order.
> fix includes in MeshLib and MeshGeoToolsLib

- AssemblerLib/LocalToGlobalIndexMap.cpp
- AssemblerLib/LocalToGlobalIndexMap.h
- MeshLib/MeshSearcher.cpp
- MeshLib/MeshSearcher.h
- ProcessLib/NeumannBc.h
- Tests/AssemblerLib/LocalToGlobalIndexMap.cpp
as titled. I suggest not using `std::vector<MeshLib::Element const*>` if there is no easy way to cast it to `std::vector<MeshLib::Element*>`.
> change std::vector<MeshLib::Element const*> to std::vector<MeshLib::Element*>

- scripts/jenkins/gcc.groovy
Thanks to the [Workflow-plugin](https://github.com/jenkinsci/workflow-plugin/blob/master/TUTORIAL.md) Jenkins jobs can now be configured via scripts similar to Travis. This has the advantage that the Jenkins config is now part of the code itself and it allows for a compact representation of the Jenkins logic.
The script compiles the cli and gui config with gcc (via a [Docker](https://www.docker.com/whatisdocker)-environment, configuration can be found [here](https://github.com/ufz/dockerfiles/tree/master/gcc)) and runs the testrunner.
See the [Jenkins job](https://svn.ufz.de:8443/job/OGS-6/job/Docker/job/gcc-scm/) and also how the [output of every step](https://svn.ufz.de:8443/job/OGS-6/job/Docker/job/gcc-scm/5/flowGraphTable/) can be examined (click on the console icons).
Already …
> Jenkins Docker workflow script for gcc cli and gui

- .travis.yml
- Applications/ApplicationsLib/CMakeLists.txt
- NumLib/CMakeLists.txt
- scripts/cmake/ExternalProjectEigen.cmake
- scripts/cmake/ThirdPartyLibVersions.cmake
- scripts/travis/cmake.sh
- scripts/travis/vtk.sh
Travis migrates its infrastructure to a Docker-based one, all jobs then run in a Linux container. They propose to [migrate](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade) Travis scripts to the new infrastructure because they start almost instantly and the average build time is almost halved. Another advantage that installed dependencies such as CMake and VTK get cached between builds.
Installation of packages is now limited to a [whitelisted set](https://github.com/travis-ci/apt-package-whitelist) and I have not found a way to install PetSc. So PetSc builds are currently disabled.
> Use new travis infrastructure

- MeshLib/MeshEditing/RemoveMeshComponents.cpp
- MeshLib/MeshSearch/ElementSearch.cpp
- MeshLib/MeshSearch/NodeSearch.cpp
- MeshLib/MeshSearch/NodeSearch.h
- Remove unused algorithm branch from `NodeSearch::searchByElementIDs()`, cleaned up and renamed the remains.
- Implement a common `ElementSearch::filter()` (private) algorithm which is common to most of the `ElementSearch` class methods.
> Cleanup mesh lib search classes

- GeoLib/AnalyticalGeometry.cpp
PR fixes an error in `GeoLib::gaussPointInTriangle(MathLib::Point3d const& q, ...)`. In cases the point `q` and the orthogonal projection of `q` into the plane defined by the triangle are identical **and** the tolerance (`eps_pnt_out_of_plane`) is zero, the algorithm returned a wrong result.
> Small fix for error in GeoLib::gaussPointInTriangle.

- Applications/DataExplorer/DataView/MeshLayerEditDialog.cpp
- MeshLib/MeshGenerators/LayeredVolume.cpp
- MeshLib/MeshGenerators/MeshLayerMapper.cpp
- MeshLib/MeshGenerators/MeshLayerMapper.h
- MeshLib/Node.h
- Moved class `MeshLayerMapper` into namespace `MeshLib`.
- Moved method `Node::updateCoordinates()` form public to protected, which reduces the interface of class `Node`.
> Restrict the interface of class MeshLib::Node.

- Applications/DataExplorer/DataView/NetCdfConfigureDialog.cpp
- Applications/DataExplorer/VtkVis/MeshFromRasterDialog.cpp
- Applications/DataExplorer/VtkVis/MeshFromRasterDialog.h
- Applications/DataExplorer/VtkVis/VtkVisPipelineView.cpp
- MeshLib/MeshEnums.h
- MeshLib/MeshGenerators/ConvertRasterToMesh.cpp
- MeshLib/MeshGenerators/VtkMeshConverter.cpp
When raster files are converted into meshes, intensity can now be interpreted as a scalar array.
> Raster intensity to scalar array

- BaseLib/StringTools.cpp
- FileIO/FEFLOWInterface.cpp
- FileIO/FEFLOWInterface.h
This PR supports the keyword ELEMENTALSETS added in recent FEFLOW version to set material IDs to imported elements. joint work with @fabienma
> support ELEMENTALSETS in FEFLOW import

- Applications/Utils/SimpleMeshCreation/createMeshElemPropertiesFromASCRaster.cpp
- Applications/Utils/SimpleMeshCreation/generateStructuredQuadMesh.cpp
This PR fixes compiling errors due to missing MATERIAL enum type in MeshLib::UseIntensityAs, though Jenkins is strangely not complaining it. 
In this PR, I replaced MATERIAL with DATAVECTOR, but I have no idea which one should be used. Let me know if this is wrong.
> MATERIAL is not in UseIntensityAs anymore

- AssemblerLib/MeshComponentMap.cpp
fix a bug that incorrect node and element IDs could be stored in the dictionary.
> bugfix in MeshComponentMap. node ID should be taken from subset

- MeshLib/ElementStatus.cpp
- MeshLib/ElementStatus.h
- Tests/MeshLib/TestElementStatus.cpp
`MeshLib::ElementStatus` class was reworked in order to cache searched active nodes and elements  for the given condition. To enable this, all set functions in the class were removed and one can set active elements only via constructors.
> [Mesh] rework on ElementStatus. no changes allowed after construction

- GeoLib/AABB.h
- GeoLib/AnalyticalGeometry-impl.h
- GeoLib/AnalyticalGeometry.h
- GeoLib/Surface.cpp
- GeoLib/Surface.h
- GeoLib/SurfaceGrid.cpp
- GeoLib/SurfaceGrid.h
- MathLib/LinAlg/Dense/DenseMatrix-impl.h
- MathLib/LinAlg/Dense/DenseMatrix.h
- Tests/GeoLib/TestSurfaceIsPointInSurface.cpp
In this PR class `SurfaceGrid` is used to accelerate the method `Surface::isPntInSfc(Point3d const& p)`. For this reason, the triangles of the `Surface` are sorted in an axis aligned structured grid - the `SurfaceGrid`. The cell of the axis aligned structured grid that contains the point p can be computed in O(1). Then only the triangles within the computed grid cell has to be tested.
> Add SurfaceGrid for the accelaration of searching

- GeoLib/PointVec.cpp
@rinkk discovered a bug while reading shape files. The mapping from ids to the real point objects was not computed in a correct way. This PR fixes the bug.
> [GL] Fix bug computing the _pnt_id_map.

- scripts/cmake/CMakeSetup.cmake
I had a custom tag on the current commit. That made cmake raise the error message:
```
CMake Error at scripts/cmake/CMakeSetup.cmake:38 (string):
string sub-command REGEX, mode MATCH regex "^[0-9|\.]*" matched an empty
string.
Call Stack (most recent call first):
CMakeLists.txt:25 (include)
```
I hope, this commit prevents the cmake error. I don't know, however, if there are related issues with cmake parsing git commits in our setup.
> Avoid cmake error if there are git tags

- AssemblerLib/LocalToGlobalIndexMap.h
- ProcessLib/GroundwaterFlowProcess.h
- ProcessLib/InitialCondition.cpp
- ProcessLib/InitialCondition.h
- ProcessLib/ProcessVariable.cpp
- ProcessLib/ProcessVariable.h
This adds an initial condition handling to set the start vector for the linear solver.
Aside the uniform value a mesh property based initial condition is added; the latter allows one to reuse previous solutions.
There are three parts:
- clang-format
- Adding/moving InitialConditions code [middle four commits](https://github.com/endJunction/ogs/compare/a6ac6a1...496bb2c)
- Using the initial conditions in GroundwaterFlowProcess [last three commits]
(https://github.com/endJunction/ogs/compare/496bb2c...InitialConditions)
*(The commits below are ordered differently)*
> Initial conditions

- NumLib/Function/Interpolation.h
- Tests/NumLib/TestFunctionInterpolation.cpp
The provided function implements the usual shape matrix interpolation of nodal values to integration points. It can be used, e.g. in any local assembly where matrix coefficients depend on the value of the unknowns.
> Added function for shape matrix interpolation.

- BaseLib/quicksort.h
Quicksort sorts only the part [beg, end) of the array now.
> Quicksort: fix error.

- .clang-format
In consequence of ufz/ogs#799 a *suggested* .clang-format.
See http://clang.llvm.org/docs/ClangFormatStyleOptions.html for more options.
Fixes  ufz/ogs#799
See [available IDE / editor integrations](http://clang.llvm.org/docs/ClangFormat.html) or [this Sublime-plugin](https://packagecontrol.io/packages/Clang%20Format).
> Add clang-format.

- FileIO/MPI_IO/NodePartitionedMeshReader.cpp
- FileIO/readMeshFromFile.cpp
*Forgot to include this one yesterday into the NodePartitionedMesh PR.*
This makes a file name with ".vtk" extension a valid input for the partitioned mesh reader.
> Erase vtk filename extension from the base name.

- MathLib/LinAlg/Eigen/EigenLinearSolver.cpp
- ProcessLib/GroundwaterFlowProcess.h
Revert a bug fix and fix it in the same way at a different place.
This is better because it is Eigen specific.
This is *important* change unifying the LinearSolver concept.
> Move linear solver creation back process construction

- Applications/CLI/ogs.cpp
- MathLib/LinAlg/Eigen/EigenLinearSolver.cpp
- MathLib/LinAlg/Eigen/EigenLinearSolver.h
- MathLib/LinAlg/EigenLis/EigenLisLinearSolver.cpp
- MathLib/LinAlg/EigenLis/EigenLisLinearSolver.h
- MathLib/LinAlg/Lis/LisLinearSolver.cpp
- MathLib/LinAlg/Lis/LisLinearSolver.h
- MathLib/LinAlg/PETSc/PETScLinearSolver.cpp
- MathLib/LinAlg/PETSc/PETScLinearSolver.h
- MathLib/LinAlg/Solvers/GaussAlgorithm-impl.h
- MathLib/LinAlg/Solvers/GaussAlgorithm.h
- Tests/MathLib/TestLinearSolver.cpp
Make solver interface unique by adding a string argument to the constructor of linear solver classes, which could be used as a prefix for command line options of linear solvers if they are available.
PS: removed the calling ``releaseEquationMemory()`` from main to avoid compilation error.
> Make solver interface unique

- AssemblerLib/ComponentGlobalIndexDict.h
- AssemblerLib/LocalToGlobalIndexMap.h
- AssemblerLib/MeshComponentMap.cpp
- AssemblerLib/MeshComponentMap.h
- AssemblerLib/VectorMatrixBuilder.h
- MathLib/LinAlg/Dense/DenseVector.h
- MathLib/LinAlg/Dense/GlobalDenseMatrix.h
- MathLib/LinAlg/Eigen/EigenMatrix.h
- MathLib/LinAlg/Eigen/EigenVector.h
- MathLib/LinAlg/Lis/LisMatrix.cpp
- MathLib/LinAlg/Lis/LisMatrix.h
- MathLib/LinAlg/Lis/LisVector.cpp
- MathLib/LinAlg/Lis/LisVector.h
- MathLib/LinAlg/PETSc/PETScMatrix.h
- MathLib/LinAlg/PETSc/PETScVector.h
- ProcessLib/GroundwaterFlowProcess.h
- ProcessLib/NumericsConfig.h
- Tests/MathLib/TestGlobalMatrixInterface.cpp
- Tests/MathLib/TestGlobalVectorInterface.cpp
The important changes start at *Add IndexType to global matrix and vector types.* commit.
The preceding part is only a cleanup w/o any logic changes.
A concept of a global index type is introduced.
The type of global indices stored in the DOF table must correspond to the index type used for addressing global matrix/vector entries. And the currently used `std::size_t` type requires additional type casts which are not always possible w/o copies.
The decision is to use the index types given by global matrices/vectors from corresponding linear equation system solver libraries.
> Global index type

- AssemblerLib/LocalToGlobalIndexMap.h
- AssemblerLib/MeshComponentMap.cpp
- AssemblerLib/MeshComponentMap.h
This is independent part of the https://github.com/ufz/ogs/pull/580 PR.
Rename and documentation.
> [AL] Rename getGlobalIndices<ORDER>() functions.

- Applications/ApplicationsLib/LinearSolverLibrarySetup.h
- Applications/ApplicationsLib/LogogSetup.h
- Applications/CLI/ogs.cpp
- BaseLib/LogogSimpleFormatter.h
Move initialization of linear solver libraries into own class `LinearSolverLibrarySetup` (which is chosen by preprocessor for now and will be chosen by cmake soon)  with purpose of correct initialization and *shutdown* of the external libraries.
This resolves the issue of core dumps in the pFEM4 PR (https://github.com/ufz/ogs/pull/580) because of improper order of matrix/vectors/linear-solver destruction. No explicit `releaseEquationsMemory()` workaround is longer necessary.
Logog is set up same way too.
- First fix some issues on logog first,
- then move logog initialization to LogogSetup,
- finally implement LinearSolverLibrarySetup for PETSc, LIS, and a default (which is empty).
This closes https://github.com/ufz/ogs/pull/851.
> Linear solver library setup

- InSituLib/VtkMappedMeshSource.cpp
- MeshLib/MeshGenerators/VtkMeshConverter.cpp
- MeshLib/MeshGenerators/VtkMeshConverter.h
This PR deals with the conversion of `vtkCharArray` and `vtkBitArray` to `PropertyVector`. These conversion is needed for a tool (PR in preparation).
> [MeshLib] Add char and bool properties to VtkMeshConverter.

- MathLib/LinAlg/Eigen/EigenMatrix.h
- MathLib/LinAlg/SetMatrixSparsity.h
This significantly speeds up the global matrix assembly:
`ctest -E LARGE` runtime decreases from 20.0s to 1.86s.
> [MaL] Add SetMatrixSparsity for EigenMatrix.

- scripts/cmake/CMakeSetup.cmake
You can toggle through possible values for CMAKE_BUILD_TYPE with ENTER
in ccmake and by popup-menu in cmake-gui.
> Switch behaviour for CMAKE_BUILD_TYPE in CMake gui

- Applications/DataExplorer/mainwindow.cpp
- Applications/Utils/FileConverter/ConvertSHPToGLI.cpp
- Applications/Utils/FileConverter/TIN2VTK.cpp
- Applications/Utils/GeoTools/TriangulatePolyline.cpp
- Applications/Utils/MeshEdit/CreateBoundaryConditionsAlongPolylines.cpp
- FileIO/FEFLOWInterface.cpp
- FileIO/GmshIO/GMSHPolygonTree.cpp
- FileIO/Legacy/OGSIOVer4.cpp
- FileIO/PetrelInterface.cpp
- FileIO/SHPInterface.cpp
- FileIO/TetGenInterface.cpp
- FileIO/XmlIO/Boost/BoostXmlGmlInterface.cpp
- FileIO/XmlIO/Boost/BoostXmlGmlInterface.h
- FileIO/XmlIO/Qt/XmlGmlInterface.cpp
- FileIO/XmlIO/Qt/XmlGmlInterface.h
- FileIO/XmlIO/Qt/XmlStnInterface.cpp
- GeoLib/GEOObjects.cpp
- GeoLib/GEOObjects.h
- GeoLib/Grid.h
- GeoLib/PointVec.cpp
- GeoLib/PointVec.h
- GeoLib/TemplateVec.h
- MeshGeoToolsLib/GeoMapper.cpp
- MeshLib/convertMeshToGeo.cpp
- Tests/FileIO/TestXmlGmlReader.cpp
- Tests/GeoLib/TestComputeAndInsertAllIntersectionPoints.cpp
- Tests/GeoLib/TestGEOObjectsMerge.cpp
- Tests/GeoLib/TestPointVec.cpp
- Tests/NumLib/TestDistribution.cpp
Follow up of https://github.com/ufz/ogs/pull/866 *Separate GEOObjects and GEOModels.*
This improves (and actually fixes few memory leaks) memory management.
Especially use of unique_ptr indicates ownership of the data, whereas raw memory pointer are just pointers and are not allowed to be released or reset.
Main change is only in `TemplateVec` class; all other changes just required changes to keep the code correct.
The bulk of changes follow the same pattern:
- replace `std::vector<Point*>* points` with `std::unique_ptr<std::vector<Point*>>`
- move in the call of e.g. `geo_objects.addPointVec(std::move(points), ...)`
- the points pointer is no longer usable (ownership transferred to `geo_objects`) and if needed is fetched by `auto points = geo_objects.getPointVec(name)`.
> Use unique_ptr in TemplateVec for data.

- AssemblerLib/LocalAssemblerBuilder.h
- AssemblerLib/LocalToGlobalIndexMap.cpp
- AssemblerLib/LocalToGlobalIndexMap.h
- AssemblerLib/MeshComponentMap.cpp
- AssemblerLib/MeshComponentMap.h
- AssemblerLib/VectorMatrixAssembler.h
- MeshGeoToolsLib/MeshNodeSearcher.cpp
- MeshGeoToolsLib/MeshNodeSearcher.h
- ProcessLib/GroundwaterFlowFEM.h
- ProcessLib/GroundwaterFlowProcess.h
- ProcessLib/NeumannBc.h
- ProcessLib/NeumannBcAssembler.h
- ProcessLib/ProcessVariable.cpp
- ProcessLib/ProcessVariable.h
- ProcessLib/UniformDirichletBoundaryCondition.h
- Tests/AssemblerLib/LocalToGlobalIndexMapMultiComponent.cpp
- Tests/AssemblerLib/SteadyDiffusion2DExample1.h
- Tests/AssemblerLib/TestSerialLinearSolver.cpp
This PR is a reincarnation of #821.
It allows for using multiple degrees of freedom per node.
Changes are:
* VectorMatrixAssembler computes local nodal values for each degree of freedom and passes them on to the local assembler.
* Thus, local assemblers have to accept parameters: `assemble(x, xold)`
* MeshComponentMap stores number of components and global matrix order (by location vs. by component)
* some methods now have component id and dof_table as additional input parameters.
* dof table now saves global indices in a matrix indexed by mesh element and component id
TODOs (will not be handled in this PR):
* VectorMatrixAssembler passes all local nodal values in a single vector. In the future that might be changed to passing each component separately.
* using …
> Multiple nodal d.o.f.

- scripts/travis/cmake.sh
Old wget on Travis (Ubuntu 12.04) has some bugs checking certificates, see e.g.:
https://github.com/haskell/cabal/issues/1796
> Replace wget by curl

- FileIO/CMakeLists.txt
- FileIO/writeGeometryToFile.cpp
- FileIO/writeGeometryToFile.h
- MathLib/Point3d.h
- At the moment the 2-D (xy-plane) (squared) distance of of two nodes / points is accomplished by copying the nodes or points and setting the *z*-coordinate explicitely to zero. Then the usual 3-D `sqrDist()` is used. To omit the copies and setting zero of the *z*-coordinate this PR suggest a function `sqrDist2d()`.
- The second commit is a function `writeGeometryToFile()` that takes the file name extension for the decision which format the data will be written. This will be used in several simulation model preprocessing tools.
> srqDist2d() and writeGeometryToFile()

- FileIO/XmlIO/Boost/BoostXmlGmlInterface.cpp
- FileIO/XmlIO/Boost/BoostXmlGmlInterface.h
- Tests/FileIO/TestXmlGmlReader.cpp
The functionality is needed for tools running on computer that do not have Qt installed. Furthermore more properties are tested after writing and (re-)reading the data.
> Surface and polyline output for class BoostXmlGmlInterface.

- CMakeLists.txt
- MathLib/LinAlg/Eigen/EigenMatrix.h
- MathLib/LinAlg/Eigen/EigenTools.cpp
- MathLib/LinAlg/EigenLis/EigenLisLinearSolver.cpp
- MathLib/LinAlg/Lis/LisMatrix.cpp
- ProcessLib/NumericsConfig.h
- Tests/MathLib/TestEigenCSR.cpp
Changes of this PR are made for improving Lis performance.
Currently there is an issue with slow performance of Lis matrix assembly: Repeated invocation of `LisMatrix::add()` triggers many unnecessary checks in Lis. This PR makes using some workaround easier.
* There is the class `EigenLisLinearSolver` in master. This PR adds a CMake configuration option `OGS_USE_EigenLis` which makes ogs use this linear solver.
* EigenMatrix and LisMatrix now do not set values of 0.0 anymore. In the TES process I have many zeroes in local matrices. This filter speeds up the linear solvers quite a bit
* `applyKnownSolution()` for `EigenMatrix` has been updated to not degrade matrix condition by inserting 1.0 on the diagonal.
* A simple Test has been added to check if the internal storage of …
> Lis performance

- Applications/Utils/MeshEdit/ResetPropertiesInPolygonalRegion.cpp
- Tool can reset different property data types (int, boolean and character).
- Updated [documentation](http://docs.opengeosys.org/docs/tools/meshing/set-properties-in-polygonal-region)
> Rework reset properties in polygonal region

- Applications/DataExplorer/DataView/ElementTreeModel.cpp
- MeshLib/Elements/Element.cpp
- MeshLib/Elements/Element.h
- MeshLib/Elements/TemplateElement-impl.h
- MeshLib/Elements/TemplateElement.h
- Tests/InSituLib/TestVtkMappedMeshSource.cpp
The remains of the original "algprops" PR https://github.com/ufz/ogs/pull/897.
The `value` is finally removed from the `Element` class.
A changelog entry would be good.
Closes https://github.com/ufz/ogs/pull/897
> Element value

- GeoLib/GEOObjects.cpp
Use removeSurfaceVec() instead of removePointVec().
> [GL]  Fix bug in GEOObjects.

- Applications/DataExplorer/DataView/ElementTreeModel.cpp
- Applications/DataExplorer/DataView/MeshElementRemovalDialog.cpp
- Applications/Utils/MeshEdit/MoveMesh.cpp
- Applications/Utils/MeshEdit/checkMesh.cpp
- Applications/Utils/MeshEdit/moveMeshNodes.cpp
- Applications/Utils/MeshEdit/removeMeshElements.cpp
- CHANGELOG.md
- GeoLib/AABB.h
- GeoLib/Grid.h
- GeoLib/PointVec.h
- GeoLib/Polygon.h
- GeoLib/Surface.cpp
- GeoLib/Surface.h
- GeoLib/SurfaceGrid.h
- MeshGeoToolsLib/GeoMapper.cpp
- MeshLib/CoordinateSystem.cpp
- MeshLib/CoordinateSystem.h
- MeshLib/MeshEditing/Mesh2MeshPropertyInterpolation.cpp
- MeshLib/MeshInformation.cpp
- MeshLib/MeshInformation.h
- MeshLib/MeshSearch/ElementSearch.cpp
- MeshLib/MeshSearch/ElementSearch.h
- Tests/GeoLib/TestAABB.cpp
- Tests/GeoLib/TestOctTree.cpp
Removing the template stuff makes 
- AABB more flexible and
- easier to use.
This PR is based on the PR #911 and must not be merged before PR #911.
**Update 2016-01-05**
All changes from PR #911 are included now in the PR.
> Transformed class template AABB -> class AABB

- Applications/ApplicationsLib/ProjectData.cpp
- Applications/ApplicationsLib/ProjectData.h
- BaseLib/ConfigTreeNew-impl.h
- BaseLib/ConfigTreeNew.cpp
- BaseLib/ConfigTreeNew.h
- CHANGELOG.md
- ProcessLib/InitialCondition.cpp
- ProcessLib/InitialCondition.h
- ProcessLib/NeumannBcConfig.h
- ProcessLib/ProcessVariable.cpp
- ProcessLib/ProcessVariable.h
- ProcessLib/UniformDirichletBoundaryCondition.h
- Tests/BaseLib/TestConfigTree.cpp
This PR introduces a wrapper class for the Boost Property Tree. The purpose of the wrapper is:
* to tell the user about settings that have not been read. The messages include some hints about where something went wrong.
* to enforce (to some extent) that each setting is parsed exactly once
* to make (by rather long method names) settings easily greppable from source code. I think this way it will be more easy later on to provide a comprehensive documentation of all possible OGS-6 input parameters.
* to enforce a certain style of XML tag names [a-z0-9_].
* to avoid or reduce the amount of input error handling code in OGS-6 routines.
* to enforce that a particular parameter is always read with the same type.
Those points are basically implemented by keeping track of how many times a routine …
> ConfigTree with some checks added

- Applications/Utils/OGSFileConverter/FileList.ui
- Applications/Utils/OGSFileConverter/FileListDialog.cpp
- Applications/Utils/OGSFileConverter/FileListDialog.h
- Applications/Utils/OGSFileConverter/OGSFileConverter.h
Added a warning for vtu to msh conversion that all scalar data will be lost (except mat ids).
Geometry + mesh conversion work in both directions, bc's are still deactivated.
> Conversion tool + warning

- scripts/jenkins/clang-log-parser.rules
- scripts/jenkins/clang.groovy
Adds Jenkins scripts to compile with clang sanitizers enabled which are run in Docker containers.
Sanitizer errors are shown under *Parsed Console Output* in a run job, e.g. [here](https://svn.ufz.de:8443/job/OGS-6/job/Docker/job/clang-scm/54/parsed_console/).
Closes #954.
> Clang Jenkins workflow script with sanitizers

- Applications/ApplicationsLib/ProjectData.cpp
- Applications/ApplicationsLib/ProjectData.h
- ProcessLib/GroundwaterFlowProcess.h
- ProcessLib/Process.h
This is one step (of many following) to separate process specific functionality (like for the GroundwaterFlowProcess) from common parts of all monolithic processes. This is required for introduction of non-linear solver loop which will control the linear solver solve calls.
In this PR there is no functionality change nor their is any (but unavoidable) generalization, for example to handle multiple DOF per node. It's just moving some of the GroundwaterFlowProcess variables up into the Process class. Following the variables there are some functions.
Major changes in functions are:
- Process::solve() is split into two parts: GroundwaterFlowProcess::assemble() followed common linear solver solve call.
- Process::initialize() is split into two parts: Common process initialization and specific …
> Move up linear solver

- GeoLib/AnalyticalGeometry.cpp
- GeoLib/AnalyticalGeometry.h
- GeoLib/LineSegment.h
- Tests/GeoLib/AutoCheckGenerators.h
- Tests/GeoLib/TestLineSegmentIntersect2d.cpp
This PR not only contains the algorithm itself, there are also 
- some new point and line segment generators used within the 
- tests of the algorithm.
The lineSegmentIntersection2d algorithm is an important to fix the GeoMapper, see issue #944.
> [GL] Algorithm for computing line segment intersections in the xy-plane

- Jenkinsfile
- Tests/CMakeLists.txt
- scripts/cmake/test/Test.cmake
- scripts/jenkins/clang-log-parser.rules
- scripts/jenkins/clang.groovy
- scripts/jenkins/gcc.groovy
This PR adds functionality to automatically create Jenkins jobs for a given git repository and then automatically build all branches when pushed (i.e. pull request testing before submitting the pull request). The only thing to be done is to mark a repo to be tested (see [my repo](https://svn.ufz.de:8443/job/OGS-6/job/Docker/job/bilke/) and the [ufz repo](https://svn.ufz.de:8443/job/OGS-6/job/Docker/job/bufz/)).
For the moment these tests will be run in addition to other tests as I am using the [Jenkins Pipeline](https://github.com/jenkinsci/workflow-plugin)-functionality which still misses some features. Also the tests are a little bit slow because they are run on an old machine.
Starting point is the `Jenkinsfile` which loads the `gcc.groovy` where the actual job config is given:
- …
> Automated Jenkins job creation

- BaseLib/ConfigTreeNew.cpp
- BaseLib/ConfigTreeNew.h
- ProcessLib/Process.h
When examining #971 it was found that there was—additionally to the tag issue—a nullptr dereference. This PR introduces a methods that can savely be run on nullptrs, avoiding such errors.
Note: the call in `Process.h` now uses argument dependent lookup.
> make ConfigTreeNew more robust against nullptr accesses

- MeshLib/MeshSearch/MeshElementGrid.cpp
- MeshLib/MeshSearch/MeshElementGrid.h
The purposes of the class `MeshElementGrid`, introduced by this PR, is a faster geometric search. This will be used in a subsequent PR for the GeoMapper, see issue #944.
> [MeL/MeshSearch] MeshElementGrid

- ProcessLib/GroundwaterFlowProcess.h
- ProcessLib/Process.h
- ProcessLib/ProcessVariable.h
Second chunk of moves from GroundwaterFlowProcess up into the Process class.
As the result the GWFP now has only the local assemblers and the hydraulic conductivity members.
Initial and both types of boundary conditions were directly moved. To generalize the initialization the Process class has a new member _process_variables pointing to the used set of process variables (defined in ProjectData).
Initialization of the mesh subsets (components) was finally moved up.
Next steps are:
- move up post() for output
- extend the Process class to handle multiple components. (For now at the corresponding places there is a 0 passed around.)
> Move up process bcs

- Applications/Utils/MeshEdit/CMakeLists.txt
- GeoLib/Station.cpp
- GeoLib/Station.h
- GeoLib/StationBorehole.cpp
- GeoLib/StationBorehole.h
- MeshGeoToolsLib/GeoMapper.cpp
- MeshGeoToolsLib/GeoMapper.h
The main points of the PR are:
- Using C++11 features like `std::unique_ptr`and range based loops
- Introducing readable type checks for classes `Station`and `Borehole`
- Fix a mem leak (and hopefully not introduce new ones)
- Split of `mapData()` of class `GeoMapper` into several methods:
- `mapStationData()`
- `mapPointDataToDEM()`
- `mapPointDataToMeshSurface()`
- Cleanup (remove old code)
- Improve the speed (the test in PR #972 takes only half of the time)
> GeoMapper refactorization

- Applications/Utils/MeshEdit/AddTopLayer.cpp
- MeshLib/MeshEditing/AddLayerToMesh.cpp
- MeshLib/MeshEditing/AddLayerToMesh.h
This PR fixes the bug from issue #968. The property vectors "MaterialIDs" is updated correctly. All other property vectors of the original mesh are removed from the new mesh. Furthermore a mem leaks is removed. The tool can output the new mesh in vtu or old mesh format.
> AddLayer properties

- FileIO/GmshIO/GMSHAdaptiveMeshDensity.cpp
Insert points using a valid/correct id used for the visualization of the Quadtree. Before the ids were invalid which leads to crash the DataExplorer (see issue #991).
> [FileIO] GMSH

- NumLib/Fem/CoordinatesMapping/ShapeMatrices-impl.h
- NumLib/Fem/CoordinatesMapping/ShapeMatrices.h
- NumLib/Fem/ShapeFunction/ShapeStaticConsts.cpp
- ProcessLib/GroundwaterFlowFEM.h
- ProcessLib/NeumannBcAssembler.h
- Tests/NumLib/TestFunctionInterpolation.cpp
This PR fixes #987 and therefore is a precursor to #988.
The error causing #987 was a forgotten call to `resize()` in the setup of the test. In order to rule out such errors, in this PR the default constructor of the `ShapeMatrices` struct has been deleted along with the `resize()` methods. Therefore `ShapeMatrices` now always have to be given the correct size upon construction.
Deleting the default constuctor entails minor changes in GWFlow and NeumannBCs.
Additionally a new `cpp` file has been added in order to prevent some linker error.
> Fix dynamically allocated shape matrices

- Applications/DataExplorer/DataView/DirectConditionGenerator.cpp
- Applications/Utils/MeshEdit/CreateBoundaryConditionsAlongPolylines.cpp
- MeshLib/MeshEditing/AddLayerToMesh.cpp
- MeshLib/MeshSurfaceExtraction.cpp
- MeshLib/MeshSurfaceExtraction.h
- MeshLib/Node.h
Copy subsurface node ids to a MeshLib::PropertyVector of the surface mesh.
> Rework MeshSurfaceExtraction::getSurfaceMesh

- Applications/CLI/ogs.cpp
- BaseLib/ConfigTree.cpp
- BaseLib/ConfigTree.h
- BaseLib/ConfigTreeNew-impl.h
- BaseLib/ConfigTreeNew.cpp
- BaseLib/ConfigTreeNew.h
- BaseLib/ConfigTreeUtil.cpp
- BaseLib/ConfigTreeUtil.h
- FileIO/XmlIO/Boost/BoostXmlGmlInterface.cpp
- FileIO/XmlIO/Boost/BoostXmlGmlInterface.h
- Tests/AssemblerLib/TestSerialLinearSolver.cpp
- Tests/BaseLib/TestConfigTree.cpp
- Tests/MathLib/TestLinearSolver.cpp
Said support is necessary in order to be able to process our geometry files with ConfigTreeNew.
This PR actually does many things:
* adds support for XML attributes in `ConfigTreeNew`
* along with that adds `getValue()` methods to access data from XML nodes,
* adds `_filename` member to `ConfigTreeNew` that will be printed in error messages,
* contains some cleanup of `ConfigTreeNew`, and extends its documentation
* adds some functionality to conveniently read an XML file into a `ConfigTreeNew`.
Furthermore, in order to demonstate the handiness of the introduced changes:
* parsing of GML files now happens through `ConfigTreeNew`.
* Therefore the old `ConfigTree` typdefs and functions are not needed anymore and have been removed
The tests for `ConfigTreeNew` have been extended to cover …
> ConfigTreeNew: Added support for XML attributes

- Applications/Utils/CMakeLists.txt
- Applications/Utils/MeshEdit/CMakeLists.txt
- Applications/Utils/MeshEdit/ExtractSurface.cpp
- Applications/Utils/MeshEdit/ResetPropertiesInPolygonalRegion.cpp
- Applications/Utils/ModelPreparation/CMakeLists.txt
- Applications/Utils/ModelPreparation/ComputeNodeAreasFromSurfaceMesh.cpp
- InSituLib/VtkMappedMeshSource.cpp
- MeshLib/MeshGenerators/VtkMeshConverter.cpp
This PR consists of two new simple tools
- ExtractSurface
- ComputeNodeAreasFromSurfaceMesh
and some additional functionality to the already existing tool ResetPropertyInPolygonalRegion.
The tools can be used in a workflow setting Neumann boundary conditions for different regions of the top surface (for instance groundwater recharge):
1. Extract top surface (ExtractSurface)
2. Mark the surface elements in the region the Neumann conditions should be set: ResetPropertyInPolygonalRegion
3. Remove those parts of the surface mesh the Neumann condition shouldn't be set to deploying the tool removeMeshElements which results in a surface patch
4. For OGS-5 modelling use the surface patch to generate Neumann condition using the tool ComputeNodeAreasFromSurfaceMesh
Using this workflow the bug …
> Tools for Neumann boundary condition preparation

- FileIO/XmlIO/Boost/BoostXmlGmlInterface.cpp
- Tests/FileIO/TestXmlGmlReader.cpp
This PR should fix the failing tests. It partially supersedes #1022.
> GML reader: Explicitly ignore polylines/surfaces without name

- GeoLib/AnalyticalGeometry.cpp
- GeoLib/AnalyticalGeometry.h
- MeshGeoToolsLib/GeoMapper.cpp
Fix a memory leak detected by clang's address sanitizer in the testrunner.
> [MGTL] Fix GeoMapper tri/line intersection memleak

- Applications/CLI/Tests.cmake
- AssemblerLib/LocalToGlobalIndexMap.h
- AssemblerLib/MeshComponentMap.cpp
- AssemblerLib/MeshComponentMap.h
- MathLib/LinAlg/Dense/DenseVector.h
- MathLib/LinAlg/Eigen/EigenVector.h
- MathLib/LinAlg/Lis/LisVector.h
- MathLib/LinAlg/PETSc/PETScMatrix.cpp
- MathLib/LinAlg/PETSc/PETScMatrix.h
- MathLib/LinAlg/PETSc/PETScVector.cpp
- MathLib/LinAlg/PETSc/PETScVector.h
- ProcessLib/Process.h
- Tests/MathLib/TestGlobalVectorInterface.cpp
- Create vector with ghost entries
To save memory when the solution is fetched.
- Use local size to create vector and matrix
To improve the computational and communication load balance in the global assembly and the linear solver.
(c.f. issue #965)
> Improvement in the usage of PETSc matrix and vector

- scripts/cmake/test/Test.cmake
The check was there but disabled because it did not work in the past on Travis. But now it works. If `time` is not found there is CMake warning that corresponding are disabled.
Closes #1044.
> Check for time binary

- GeoLib/Surface.cpp
- GeoLib/Surface.h
- GeoLib/SurfaceGrid.cpp
- GeoLib/SurfaceGrid.h
The construction of the class `SurfaceGrid` within the `Surface` is moved to the method `isPntInSfc()`. This avoids the repeatedly update of the surface grid and the warning/error/debug messages connected to the update. Since `SurfaceGrid` does not need the `Surface` as friend class a better encapsulation is realized.
**Update** In a run time test the new impl. took only ~77 % of the time the previous code needed.
> Avoid warning/error/debug messages in SurfaceGrid

- Applications/CLI/Tests.cmake
- AssemblerLib/LocalToGlobalIndexMap.h
- AssemblerLib/MeshComponentMap.cpp
- AssemblerLib/MeshComponentMap.h
- InSituLib/VtkMappedPropertyVectorTemplate-impl.h
- MeshLib/Properties-impl.h
- MeshLib/Properties.h
- MeshLib/PropertyVector.h
- ProcessLib/InitialCondition.cpp
- ProcessLib/InitialCondition.h
- ProcessLib/Process.h
- ProcessLib/ProcessVariable.cpp
- ProcessLib/ProcessVariable.h
- Tests/InSituLib/TestVtkMappedMeshSource.cpp
- Tests/MeshLib/MeshProperties.cpp
Process variable is now aware of its number of components. This is reflected in the tests by new `<components>` tag: [Tests data PR](https://github.com/ufz/ogs-data/pull/3/files).
Creation of the mesh property for each process variable is now handled by the process variable itself.
And finally the output is now generalized to all process variables of a process and is independent of number of components.
> Multicomponent process variables and their output.

- Applications/ApplicationsLib/LogogSetup.h
- Applications/CLI/ogs.cpp
- CHANGELOG.md
- Tests/CMakeLists.txt
- Tests/testrunner.cpp
- Added `-l` command line arguments to OGS cli and the testrunner. Possible values: `none`, `error`, `warn`, `info`, `debug`, `all`.
- `make tests` log-level is now `warn` (this suppresses verbose logging in [recent Jenkins builds](https://svn.ufz.de:8443/job/OGS-6/job/Tests_Linux/511/consoleFull)).
> Set log level at runtime

- ProcessLib/Process.h
One step towards multi-variable processes
MeshSubset initialization across all process variables.
> initializeMeshSubsets() across process vars and components.

- MeshLib/MeshEditing/MeshRevision.cpp
- MeshLib/MeshSearch/MeshElementGrid.cpp
- NumLib/Fem/CoordinatesMapping/NaturalCoordinatesMapping-impl.h
- SimpleTests/MatrixTests/DenseGaussEliminationChecker.cpp
- SimpleTests/MatrixTests/MatMult.cpp
- SimpleTests/MatrixTests/MatVecMultPthreads.cpp
With the changes introduces Jenkins should no longer point us to, e.g.
```
***error: det|J|=-1.000000e+00 is not positive.
```
> Unclutter Jenkins error parser

- AssemblerLib/LocalToGlobalIndexMap.cpp
- AssemblerLib/LocalToGlobalIndexMap.h
- AssemblerLib/MeshComponentMap.cpp
- AssemblerLib/MeshComponentMap.h
- ProcessLib/NeumannBc.h
- ProcessLib/Process.h
- Tests/AssemblerLib/LocalToGlobalIndexMap.cpp
- Tests/AssemblerLib/LocalToGlobalIndexMapMultiComponent.cpp
- Tests/AssemblerLib/TestMeshComponentMap.cpp
- Tests/AssemblerLib/TestSerialLinearSolver.cpp
- Tests/AssemblerLib/TestVectorMatrixBuilder.cpp
Starting with usage of `vector<unique_ptr<MeshSubsets>>` in Process the ownership is transferred to the DOF-table (`LocalToGlobalIndexMap`). All the interfaces involved in construction of the `MeshComponentMap` and the DOF-table are changed either to accept references or rvalues.
While implementation of the ownership improvement the difference between a variable_id (_e.g._ pressure is nr 5), component_id (_e.g._ the z-component is nr 2), and global component_id used in the DOF-table arouse. Most of the functions involving the variable/component ids are broken. _i.e._ the ids are always 0, which is fine for single-variable/single-component id.
The variable_id/component_id are marked as todo.
> Transfer ownership of mesh_subsets to the DOF-table.

- FileIO/GMSHInterface.cpp
This PR closes the issue #1074 by introducing the following changes
- fix a bug (?) that material IDs for line elements are always set zero
- condense material IDs after reading a GMSH mesh file.  
closes #1074
> Fix material ID issues with line elements in GMSH import

- Tests/AssemblerLib/LocalToGlobalIndexMap.cpp
- Tests/AssemblerLib/LocalToGlobalIndexMapMultiComponent.cpp
- Tests/AssemblerLib/TestMeshComponentMap.cpp
- Tests/AssemblerLib/TestVectorMatrixBuilder.cpp
- Tests/CMakeLists.txt
- Tests/FileIO/TestTetGenInterface.cpp
- Tests/InSituLib/TestVtkMappedMeshSource.cpp
- Tests/NumLib/TestODEInt.cpp
This PR
* removes the catch-all regular expression filters that disable unit tests for PETSc
* disables only the segfaulting tests for PETSc one by one
Thus, new unit tests will by default also be run in the PETSc build. Furthermore, it will be possible to run `testrunner` also for PETSc without having to pass filters.
> Disable Segfaulting PETSc unit tests one by one

- Applications/ApplicationsLib/LinearSolverLibrarySetup.h
- Applications/ApplicationsLib/UncoupledProcessesTimeLoop.h
- MathLib/LinAlg/BLAS.cpp
- MathLib/LinAlg/Eigen/EigenMatrix.h
- MathLib/LinAlg/Eigen/EigenTools.h
- MathLib/LinAlg/GlobalMatrixProviders.cpp
- MathLib/LinAlg/GlobalMatrixProviders.h
- MathLib/LinAlg/MatrixProviderUser.h
- MathLib/LinAlg/MatrixVectorTraits.cpp
- MathLib/LinAlg/MatrixVectorTraits.h
- MathLib/LinAlg/SimpleMatrixVectorProvider-impl.h
- MathLib/LinAlg/SimpleMatrixVectorProvider.h
- MathLib/LinAlg/Solvers/GaussAlgorithm.h
- MathLib/LinAlg/UnifiedMatrixSetters.cpp
- MathLib/LinAlg/UnifiedMatrixSetters.h
- NumLib/ODESolver/EquationSystem.h
- NumLib/ODESolver/MatrixTranslator.h
- NumLib/ODESolver/NonlinearSolver-impl.h
- NumLib/ODESolver/NonlinearSolver.h
- NumLib/ODESolver/ODESystem.h
- NumLib/ODESolver/TimeDiscretization.h
- NumLib/ODESolver/TimeDiscretizedODESystem.h
- NumLib/ODESolver/TimeLoopSingleODE.h
- NumLib/ODESolver/Types.h
- ProcessLib/Process.h
- Tests/NumLib/ODEs.h
- Tests/NumLib/TestODEInt.cpp
- Tests/testrunner.cpp
This matrix pool will make it possible to use global matrices and vectors in different processes. Furthermore, this PR adds builders for global matrices, which abstract away, e.g., the differences between PETSc and Eigen matrix creation. However, for PETSc there will be a follow-up PR.
Maybe we should discuss this PR as we did with #1040 and #1050.
Note: This is a follow-up PR of #1050!
To do:
> Added a matrix pool

- FileIO/SHPInterface.cpp
- GeoLib/AnalyticalGeometry.cpp
- GeoLib/Polygon.cpp
- GeoLib/Polygon.h
- First bug was that empty polygons were created and the AABB of an empty point set is not allowed.
- Second bug was inproper handling parallel line segments.
> Fix surface creation bugs in SHPInterface

- scripts/cmake/ThirdPartyLibVersions.cmake
I uploaded Boost 1.56.0 to our Amazon S3 bucket.
Fixes #1064
> Download Boost from non-encrypted website

- Tests/AssemblerLib/LocalToGlobalIndexMapMultiComponent.cpp
- Tests/AssemblerLib/TestSerialLinearSolver.cpp
- scripts/cmake/ClangSanitizer.cmake
- scripts/jenkins/clang.groovy
- scripts/test/clang_sanitizer_blacklist.txt
__1.__ I have checked all of the undefined behaviour checked by clang's sanitizer and think that the blacklisted are not caused by wrong usage from our side.
Because the names in the blacklist are mangled, they could be different on the envinf1 machine; Then the blacklist shall be updated.
__2.__ Removed remaining memory leaks in the testrunner.
@chleh There are no more memleaks as of now.
> Clang sanitizer cleanup

- Applications/ApplicationsLib/UncoupledProcessesTimeLoop.h
- Applications/CLI/Tests.cmake
- MathLib/LinAlg/BLAS.cpp
- MathLib/LinAlg/BLAS.h
- MathLib/LinAlg/MatrixProviderUser.h
- MathLib/LinAlg/MatrixVectorTraits.cpp
- MathLib/LinAlg/PETSc/PETScLinearSolver.cpp
- MathLib/LinAlg/PETSc/PETScLinearSolver.h
- MathLib/LinAlg/PETSc/PETScMatrix.cpp
- MathLib/LinAlg/PETSc/PETScMatrix.h
- MathLib/LinAlg/PETSc/PETScVector.cpp
- MathLib/LinAlg/PETSc/PETScVector.h
- MathLib/LinAlg/UnifiedMatrixSetters.cpp
- MathLib/LinAlg/UnifiedMatrixSetters.h
- MeshLib/NodePartitionedMesh.h
- NumLib/ODESolver/TimeDiscretizedODESystem.h
- ProcessLib/Process.h
- Tests/BaseLib/TestConfigTree.cpp
- Tests/CMakeLists.txt
- Tests/MathLib/TestLinearSolver.cpp
- Tests/NumLib/ODEs.h
- Tests/NumLib/TestODEInt.cpp
- Tests/TestTools.cpp
- Tests/TestTools.h
- scripts/cmake/Functions.cmake
This is a follow-up PR of #1059.
To do
```xml
<petsc>
<prefix>gw</prefix>
<params>-ksp_type cg -pc_type bjacobi -ksp_rtol 1e-16 -ksp_max_it 10000</params>
</petsc>
```
Subsequent PRs:
* remove name argument from linear solver constructors
* clean up matrix and vector classes
Biggest changes:
* implemented missing functionality for PETSc
* PETScMatrix/Vector now stores a pointer to matrix/vector. Thereby it is possible to default construct them.
* The option prefix for PETSc linear solvers is now directly obtained from the `<petsc>` config tree section.
* Extended matrix specifications, s.t. now they include the DOF table, the mesh and the sparsity pattern.
> Fix ODE solver lib with PETSc

- Applications/ApplicationsLib/UncoupledProcessesTimeLoop.h
- AssemblerLib/VectorMatrixAssembler.h
- ProcessLib/Process.h
- Splitting of `postTimestep()` and `output()`. (No changes, just copy&paste).
- Implementation of preTimestep and postTimestep executors for local asm.
To use in particular process one needs an implementation in FEM part of the process of
```c++
void FEM::preTimestep(std::vector<double> const& local_x) override;
```
and an implementation in the Process calling `FEM::preTimestep`
```c++
void SpecificProcess::preTimestep() override
{
Base::_global_setup.execute(
[&](std::size_t const id, LocalAssembler* const local_assembler, GlobalVector const& x) -> void
{
Base::_global_assembler->preTimestep(id, local_assembler, x);
},
_local_assemblers, x);
}
```
> Pre post timestep for local asm

- GeoLib/Grid.h
- Tests/GeoLib/TestGrid.cpp
This PR fixes issue #999.
This PR substitutes the absolute criterion for the decision which spatial dimension for the setup of the Grid should be taken into account to an relative one (commit 5ed53fd). Furthermore the manual resize of the bounding box is deleted since this is already done in the AABB class in a previous PR.
> Fix Grid Bug

- Applications/CMakeLists.txt
- AssemblerLib/CMakeLists.txt
- AssemblerLib/LocalDataInitializer.h
- CMakeLists.txt
- FileIO/CMakeLists.txt
- ProcessLib/CMakeLists.txt
- Tests/CMakeLists.txt
- scripts/cmake/OGSEnabledElements.cmake
This PR adds the following cmake options, which enable selection of element types to be built via cmake. That possibly saves compile time. The effect will be more significant for fixed-size shape matrices, not so much for dynamically allocated ones.
```
OGS_ENABLE_ELEMENT_CUBOID
OGS_ENABLE_ELEMENT_PRISM
OGS_ENABLE_ELEMENT_PYRAMID
OGS_ENABLE_ELEMENT_SIMPLEX
OGS_MAX_ELEMENT_DIM
OGS_MAX_ELEMENT_ORDER
```
> Select element types/dimension/order to be built via cmake

- Applications/ApplicationsLib/UncoupledProcessesTimeLoop.h
- ProcessLib/Process.h
As titled. Really nothing fancy.
Now more information is passed via the `preTimestep()` hook. Those information (`delta_t`) is needed in the TES and mechanics processes.
Other processes can use the information, e.g., to initialize some data.
> Extended preTimestep() hook

- FileIO/GMSHInterface.cpp
- FileIO/GMSHInterface.h
- FileIO/GmshIO/GMSHPoint.cpp
- GeoLib/AnalyticalGeometry-impl.h
- GeoLib/AnalyticalGeometry.cpp
- GeoLib/AnalyticalGeometry.h
This fixes issue #663.
The original input data is rotated to the x-y-plane. All intermediate computations are done and finally to data is rotated back to the original location.
> [Fix] Generate Gmsh mesh in xz plane

- Applications/ApplicationsLib/UncoupledProcessesTimeLoop.h
- NumLib/ODESolver/EquationSystem.h
- NumLib/ODESolver/NonlinearSolver-impl.h
- NumLib/ODESolver/NonlinearSolver.h
- NumLib/ODESolver/NonlinearSystem.h
- NumLib/ODESolver/ODESystem.h
- NumLib/ODESolver/TimeDiscretizedODESystem.h
Said hooks are called before and after each iteration of the nonlinear solver.
I need that functionality for TES in order to be able to drop some nonsensible iteration results.
> ODESolver: Added pre and post iteration hooks

- NumLib/Fem/ShapeMatrixPolicy.h
- ProcessLib/LocalAssemblerTraits.h
The struct introduced makes it possible to use the right version of Eigen's `block()` methods transparently for both fixed-size and dynamically allocated shape matrices.
Currently this code is not used anywhere, but will be in the TES process.
Caveat: The given implementation only works if all process variables are single-component and use the same shape functions!
> LocalAssemberTraits

- Applications/Utils/MeshEdit/ResetPropertiesInPolygonalRegion.cpp
Resets properties inside instead outside.
> Tiny fix for wrong behaviour of tool ResetPropertiesInPolygonalRegion

- BaseLib/ConfigTree-impl.h
- BaseLib/ConfigTree.h
- Tests/BaseLib/TestConfigTree.cpp
Provides reading of list of values from a config file.
```xml
<values>0 1 2 5</values>
```
can now be read with
```c++
auto v = config.getConfParam<std::vector<int>>("values");
```
The idea behind this is to overload the implementation on `*T` parameter. (The idea is from [stackoverflow](http://stackoverflow.com/a/8315197).)
> Parsing of a space delimited config values

- Applications/ApplicationsLib/ProjectData.cpp
- Applications/ApplicationsLib/ProjectData.h
- Applications/ApplicationsLib/UncoupledProcessesTimeLoop.h
- Applications/CLI/Tests.cmake
- Applications/CLI/ogs.cpp
- AssemblerLib/LocalDataInitializer.h
- FileIO/VtkIO/PVDFile.cpp
- FileIO/VtkIO/PVDFile.h
- ProcessLib/GroundwaterFlowFEM.h
- ProcessLib/GroundwaterFlowProcess.h
- ProcessLib/NeumannBc.h
- ProcessLib/NeumannBcAssembler.h
- ProcessLib/Output.cpp
- ProcessLib/Output.h
- scripts/cmake/test/AddTest.cmake
This PR:
* adds a class for writing basic PVD files
* adds a class that handles output configuration
Output files now have names like `square_1e4_pcs_0_ts_1_t_1.000000.vtu`.
The output is configured by a snippet like the following in the prj file:
```
<output>
<type>VTK</type>
<prefix>line_1</prefix>
<timesteps>
<pair><repeat> 10 </repeat><each_steps>  1 </each_steps></pair>
<pair><repeat> 10 </repeat><each_steps>  1 </each_steps></pair>
<pair><repeat> 10 </repeat><each_steps>  1 </each_steps></pair>
<pair><repeat> 10 </repeat><each_steps>  1 </each_steps></pair>
<pair><repeat> 10 </repeat><each_steps>  1 </each_steps></pair>
<pair><repeat> 10 </repeat><each_steps>  1 </each_steps></pair>
<pair><repeat>  1 </repeat><each_steps> 10 </each_steps></pair>
</timesteps>
</output>
```
where the …
> Output Config

- AssemblerLib/LocalDataInitializer.h
- ProcessLib/GroundwaterFlowFEM.h
- ProcessLib/GroundwaterFlowProcess.h
- ProcessLib/NeumannBc.h
- ProcessLib/NeumannBcAssembler.h
The changes in this PR are the following:
* the `LocalDataInitializer` now supports local assemblers with non-default constructors
* therefore the `init`-method of the local assemblers can be dropped. Its functionality is merged into the constructor
This way, const correctness of the local assemblers can be improved. All data members can be initialized at construction time, which means that one probably needs less heap allocations (for more complicated processes) and that most data can be passed around as references at construction time.
> Use non-default constructors for local assemblers

- MeshLib/MeshEditing/RemoveMeshComponents.cpp
- MeshLib/Properties.cpp
- MeshLib/Properties.h
- MeshLib/PropertyVector.h
This PR adds a second argument to the method `Properties::excludeCopyProperties()` such that both property types, cell and node properties can be correctly copied. Furthermore it was necessary to move some attributes / methods from `PropertyVector` to the abstract  base class `PropertyVectorBase`.
This fixes issue #1117 .
> Fix Properties::excludeCopyProperties()

- AssemblerLib/VectorMatrixAssembler.h
This PR provides one central building block to be able to assemble processes for a Newton scheme.
Currently the code introduced is not used, but will be, e.g., in @endJunction's mechanics process.
> Added assembleJacobian method

- NumLib/ODESolver/ODESystem.h
- NumLib/ODESolver/TimeDiscretizedODESystem.h
- ProcessLib/Process.h
For time-variable boundary conditions the current time is needed.
~~I'm not sure if this is the right solution, therefor it's for discussion.~~
The time is injected in the `TimeDiscretizedODESystem` now and the nonlinear solver is not touched.
The dirichlet bcs needs an update too, but this the point of this PR.
> Pass time to ODESystem::getKnownSolutions();

- Applications/ApplicationsLib/UncoupledProcessesTimeLoop.h
- MathLib/LinAlg/MatrixVectorTraits.cpp
- MathLib/LinAlg/MatrixVectorTraits.h
- MathLib/LinAlg/UnifiedMatrixSetters.cpp
- MathLib/LinAlg/UnifiedMatrixSetters.h
- NumLib/ODESolver/NonlinearSystem.h
- NumLib/ODESolver/TimeDiscretizedODESystem.h
The `applyKnownSolutions()` methods in the time loop do safe downcasting, similar to the `setEquationSystem()` methods that are already present.
The provided implementations of `applyKnownSolutions()` in NumLib are definitely not perfect, but they should work. Performance optimizations to be done later on.
This is a follow-up PR of #1127.
> Apply Dirichlet BCs in the Newton scheme

- NumLib/ODESolver/NonlinearSolver-impl.h
The old approach of taking the residual norm was erroneous: It was computed too early (before applying Dirichlet BCs), thus it did not converge.
This PR changes that. And it switches to norm of delta x for now. That's then consistent with the way the Picard solver currently computes errors. Of course, later on there will be more error calculation methods to choose from.
> Use norm of delta x within Newton scheme

- AssemblerLib/GlobalSetup.h
- AssemblerLib/SerialExecutor.h
- AssemblerLib/VectorMatrixAssembler.h
- ProcessLib/GroundwaterFlowProcess.h
- ProcessLib/NeumannBc.h
- ProcessLib/Process.h
- Tests/AssemblerLib/TestSerialExecutor.cpp
- Tests/AssemblerLib/TestSerialLinearSolver.cpp
Changes:
1. `operator()()` in `VectorMatrixAssembler` renamed to `assemble()`.
That change makes the assembly routine an "ordinary" member, like all the other methods.
2. `LocalAssembler` now is a tpl param of the class `VectorMatrixAssembler`, not of its methods anymore (needed for the next point)
3. added `executeMemberDereferenced()` to `SerialExecutor`. Thereby one does not have to use lambdas when executing member methods other than `operator()()`, cf. https://github.com/ufz/ogs/compare/master...chleh:execute-overload?expand=1#diff-f2f37a7122ad44875cbf665ce72096deR153.
4. the `GlobalAssembler` now is owned by the concrete process (since it now depends on the specific `LocalAssembler`).
Point (3) makes `GlobaLSetup::execute...()` calls more readable in the specific process. I admit, …
> Added executeMemberDereferenced() + (minor) cleanup

- Applications/DataExplorer/mainwindow.cpp
- FileIO/XmlIO/Qt/XmlGspInterface.cpp
- FileIO/XmlIO/Qt/XmlGspInterface.h
~~Follow up of ufz/ogs#1133.~~ This PR adds only the one commit [[DE] Break ApplicationLib dependency.](https://github.com/ufz/ogs/pull/1138/commits/7cf6b6068e9984949d35a41ce81d8558bfe7cf4d)
The dependency is caused by usage of ProjectData::addMesh by XmlGspInterface.
Unfortunately the programming of that class and its parents, the XMLInterface and XMLQtInterface is not as separate as it could be, therefore the current solution can be seen as a quickfix.
Clean solution would be, for example, a separation of the reader and the writer parts of the XMLInterface(s) and to use standalone functions for qt's xml validation.
> Break fileIO ApplicationsLib dependency

- Applications/DataExplorer/DataView/MeshLayerEditDialog.cpp
- Applications/Utils/MeshEdit/createLayeredMeshFromRasters.cpp
- FileIO/AsciiRasterInterface.cpp
- FileIO/AsciiRasterInterface.h
- MeshLib/CMakeLists.txt
- MeshLib/MeshGenerators/LayeredMeshGenerator.cpp
- MeshLib/MeshGenerators/LayeredMeshGenerator.h
Move reading of raster files out of layered mesh generator.
Add convenience function to read all raster files given by a list of file names.
> Split FileIO MeshLib dependency in LayeredMeshGenerator

- Applications/ApplicationsLib/ProjectData.cpp
- AssemblerLib/GlobalSetup.h
- AssemblerLib/LocalDataInitializer.h
- NumLib/Function/Interpolation.h
- ProcessLib/CMakeLists.txt
- ProcessLib/GroundwaterFlow/GroundwaterFlowFEM.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess-fwd.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.cpp
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcessData.h
- ProcessLib/GroundwaterFlowProcess.h
- ProcessLib/LocalAssemblerInterface.h
- ProcessLib/NeumannBc.h
- ProcessLib/Process.cpp
- ProcessLib/Process.h
- ProcessLib/ProcessUtil.h
- ProcessLib/ProcessVariable.h
- Tests/AssemblerLib/TestSerialLinearSolver.cpp
- Tests/NumLib/TestFunctionInterpolation.cpp
This is a follow-up of #1136.
Changes:
* interpolation (necessary for nonlinear processes) does not require passing arrays anymore
* GWFlow moved to separate subdir, and entirely to separate namespace
* defined common local assembler interface for all processes
* store process data in a separate struct
Thereby it is easier for users to add own properties to a process, to read those properties from file, etc.
* process_variables are passed as a list – first step towards multi-variable processes
* `createLocalAssemblers()` now done by a general function – users see less template stuff.
The aim of this PR is that we can tell users who start implementing their processes: "Copy and paste GWFlow and be happy.". The changes should cover most things needed to implement nonlinear, monolithic …
> Simplify concrete processes

- AssemblerLib/GlobalSetup.h
- ProcessLib/GroundwaterFlowProcess.h
- ProcessLib/NeumannBc.h
- ProcessLib/Process.h
- ProcessLib/ProcessVariable.h
- Tests/AssemblerLib/TestSerialLinearSolver.cpp
Changes
* some more private instead of protected members
* `GlobalSetup` now does not have any instances anymore.
follow-up of #1135
> Process cleanup

- Applications/ApplicationsLib/ProjectData.cpp
- Applications/ApplicationsLib/ProjectData.h
- MathLib/InterpolationAlgorithms/PiecewiseLinearInterpolation.cpp
- MathLib/InterpolationAlgorithms/PiecewiseLinearInterpolation.h
- NumLib/Function/LinearInterpolationAlongPolyline.cpp
- Tests/MathLib/TestPiecewiseLinearInterpolation.cpp
Adds a `_curves` map from names to `MathLib::PiecewiseLinearInterpolation`s to project data when
```xml
<curves>
<curve>
<name>curveA</name>
<coords>0 1 1.5</coords>
<values>10 11 12.3</values>
</curve>
</curves>
```
is present in the project file.
I currently use this feature to create time-dependent boundary conditions (but this is too early for PR); and @yonghui56 started work on Richard's flow, where the curves are used for parameters.
> Add parsing of piecewise linear curves.

- Applications/DataExplorer/DataView/MshView.cpp
- MeshLib/MeshGenerators/MeshLayerMapper.cpp
- MeshLib/MeshGenerators/MeshLayerMapper.h
Somehow this dependency slipped past my mind.
Moving reading of the file into DE.
Use instead layered mesh constructor taking a GeoLib::Raster.
Reading of the raster happens inside the application now.
Typo was "wher". No changes to the comment otherwise.
> Remove mesh lib on file io dependency

- Applications/ApplicationsLib/UncoupledProcessesTimeLoop.h
- AssemblerLib/LocalDataInitializer.h
- AssemblerLib/MeshComponentMap.cpp
- AssemblerLib/SerialExecutor.h
- MathLib/LinAlg/BLAS.cpp
- MathLib/LinAlg/BLAS.h
- MathLib/LinAlg/Eigen/EigenVector.h
- MathLib/LinAlg/MatrixProviderUser.h
- MathLib/LinAlg/PETSc/PETScVector.cpp
- MathLib/LinAlg/SimpleMatrixVectorProvider-impl.h
- MathLib/LinAlg/SimpleMatrixVectorProvider.h
- NumLib/ODESolver/TimeDiscretizedODESystem.h
- Tests/MathLib/AutoCheckTools.h
This PR is a prerequisite for #1145.
Review component-wise.
Probably the biggest change is that `MatrixVectorProvider` gets not passed a `MatrixSpecificationsProvider` anymore, but rather is called directly with `MatrixSpecifications`.
> Misc changes

- BaseLib/ConfigTree.h
This PR explicitly deletes the ctor of ConfigTree that takes an r-value reference of boost::property_tree. That way passing temporaries will lead to a compilation error.
It is tempting to pass temporaries in unit tests, e.g. when there is only an empty config tree needed to construct some objects. However, passing a temporary leads to dangling references and program crash.
The change in this PR of course will only prevent passing temporaries directly to the ctor. If they are passed, e.g., via `const&` to a function that passes them on, you are screwed :smile:
> Prevent passing temporaries to ConfigTree ctor

- ProcessLib/GroundwaterFlow/GroundwaterFlowFEM.h
- ProcessLib/LocalAssemblerTraits.h
GWFlow shall serve as a template for any other processes, at least for the time being. This PR extends GWFlow s.t. it can easily be extended to multiple variables.
Note: The given changes only allow extension to multi-variables if each of them has one component and uses the same shape functions. Generalizations of that are future work. Probably then we will need to discuss if generalizations can be done using fixed matrices (theoretically, yes, but the code could be complicated).
> Fixed-size local matrices for multi-variable processes

- FileIO/GmshIO/GMSHPolygonTree.cpp
- GeoLib/AnalyticalGeometry.cpp
- GeoLib/AnalyticalGeometry.h
- GeoLib/LineSegment.cpp
- GeoLib/LineSegment.h
- GeoLib/Polygon.cpp
- GeoLib/Polygon.h
- GeoLib/Polyline.cpp
- GeoLib/Polyline.h
- Tests/GeoLib/AutoCheckGenerators.h
- Tests/GeoLib/TestLineSegmentIntersect.cpp
- Tests/GeoLib/TestLineSegmentIntersect2d.cpp
- Tests/GeoLib/TestPolygon.cpp
- Tests/GeoLib/TestPolyline.cpp
PR improves the existing class `LineSegment` and establishs it at some places in the `GeoLib`. The changes should improve the readability.
Furthermore the PR introduces a `SegmentIterator` in class `Polyline`. The iterator class allows to use algorithms from the standard library and makes the code more readable at some places.
> [GL] Introducing class LineSegment.

- scripts/cmake/Find.cmake
- scripts/jenkins/gcc.groovy
The first commit was already pushed a few days ago but maybe was overwritten by a fast-forward. No worries.
The second commit fixes currently failing Pull Requests because of Jenkins marking builds as unstable when there were warnings detected by the console log parser.
> Fix for Windows submodule and disable unstable builds on warnings (Jenkins)

- GeoLib/Polygon.cpp
- GeoLib/Polygon.h
- GeoLib/Polyline.cpp
- GeoLib/Polyline.h
- Tests/GeoLib/TestPolygon.cpp
As titled.
Fixes issue #1155.
**Update (2016-04-25)**
Removed the assignment operator since it isn't used anywhere and marked it explicitly as deleted.
> [GL] Polygon: Impl. of copy constructor and assignment operator

- AssemblerLib/ComputeSparsityPattern.cpp
- AssemblerLib/LocalToGlobalIndexMap.cpp
- AssemblerLib/LocalToGlobalIndexMap.h
- AssemblerLib/MeshComponentMap.cpp
- AssemblerLib/MeshComponentMap.h
- MathLib/LinAlg/MatrixVectorTraits.cpp
- Tests/AssemblerLib/LocalToGlobalIndexMap.cpp
- Tests/AssemblerLib/TestMeshComponentMap.cpp
- Tests/AssemblerLib/TestSerialLinearSolver.cpp
- Tests/AssemblerLib/TestVectorMatrixBuilder.cpp
- Remove unused code.
- Rename two of very similar named dofSize* functions to clarify their meaning.
- Remove not strictly required includes.
> Rename and cleanup dofSize relate functions

- MathLib/MathTools.h
The runtime pow() is slow (i.e. it does not do exponentiation by squaring). I think the template-meta-POW would only work for integral bases and exponents.
Both things are used nowhere.
> Removed custom pow() implementation

- AssemblerLib/ComputeSparsityPattern.cpp
- AssemblerLib/ComputeSparsityPattern.h
- MathLib/LinAlg/MatrixProviderUser.h
- MathLib/LinAlg/SparsityPattern.h
- ProcessLib/GlobalSetup.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowFEM.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.h
- ProcessLib/NeumannBc.h
- ProcessLib/NumericsConfig.h
- ProcessLib/Process.cpp
- ProcessLib/Process.h
- ProcessLib/ProcessUtil.h
- ProcessLib/Utils/CreateLocalAssemblers.h
- ProcessLib/Utils/InitShapeMatrices.h
- ProcessLib/Utils/LocalDataInitializer.h
- Tests/NumLib/TestExtrapolation.cpp
- Move SparsityPattern typedef to MathLib; Breaking one small bit of circular dependency.
- Those parts dealing with creation of the local assemblers belong to the ProcessLib.
- The `GlobalSetup` is used in ProcessLib/NumericsConfig.h; so it is moved to ProcessLib too.
The previously ProcessUtils.h is split into two files for `createLocalAssemblers` and `initShapeMatrices` both placed in ProcessLib/Utils/. I can imagine that ProcessLib/LocalAssemblerUtils would be a better directory name.
No code changes, just includes and moves.
> Move AssemblerLib parts to MathLib and ProcessLib

- Applications/DataExplorer/DataView/NetCdfConfigureDialog.cpp
- Applications/DataExplorer/DataView/NetCdfConfigureDialog.h
This would probably require a complete rework but the fixes here will at least fix some pressing issues:
* 2D arrays can be converted into mesh/raster (prev. only 3D)
* the correct scalar array is now transfered onto a mesh even if 0-D/1-D arrays are present
* some dialogue fixes (enabling/disabling widgets depending on scalar array choice)
> Fixing several issues with NetCDF-configure dialogue

- Applications/ApplicationsLib/CMakeLists.txt
- Applications/CLI/CMakeLists.txt
- Applications/DataExplorer/Base/CMakeLists.txt
- Applications/DataExplorer/DataExplorer.cmake
- Applications/DataExplorer/DataView/CMakeLists.txt
- Applications/DataExplorer/DataView/DiagramView/CMakeLists.txt
- Applications/DataExplorer/DataView/StratView/CMakeLists.txt
- Applications/DataExplorer/VtkAct/CMakeLists.txt
- Applications/DataExplorer/VtkVis/CMakeLists.txt
- Applications/Utils/OGSFileConverter/CMakeLists.txt
- AssemblerLib/CMakeLists.txt
- BaseLib/CMakeLists.txt
- FileIO/CMakeLists.txt
- GeoLib/CMakeLists.txt
- InSituLib/CMakeLists.txt
- MathLib/CMakeLists.txt
- MeshGeoToolsLib/CMakeLists.txt
- MeshLib/CMakeLists.txt
- NumLib/CMakeLists.txt
- ProcessLib/CMakeLists.txt
- SimpleTests/MeshTests/CMakeLists.txt
- SimpleTests/MeshTests/MPI/CMakeLists.txt
- Tests/CMakeLists.txt
- scripts/cmake/CompilerSetup.cmake
~~Fixing metis linkage;~~ Remove STATIC from add_library().
With this changes and configuring the build for debug and with `-DBUILD_SHARED_LIBS=On` the compile + linking time for the ogs target (from scratch, no ccache) reduces (for that particular branch endJunction/M2 with dynamic eigen matrices) from 3:45 to 2:55.
The default build process should not change with this PR, because the static linking is chosen by default.
__Update:__ On another machine there is no change, unfortunately, which I don't understand yet.
> Enable shared linking

- MathLib/Nonlinear/Root1D.h
- Tests/MathLib/TestNonlinear1D.cpp
This PR adds a class implementing the regula falsi method for one-dimensional root finding.
The idea is to use this class in order to become a rough estimate of a root in only very few iterations with only very few calls of the user-provided function. Additionally, no tangents are needed.
Hence, this method should be suitable for being used inside local assemblers.
> one dimensional root finding

- BaseLib/uniqueInsert.h
- NumLib/Extrapolation/LocalLinearLeastSquaresExtrapolator.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowFEM.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.h
- ProcessLib/Process.h
- ProcessLib/ProcessOutput.h
- ProcessLib/SecondaryVariable.h
This PR integrates the extrapolator class into the processes.
Changes:
* new classes handling output, especially of 2ndary vars. They configure which data to write to file.
* the output scheme is suitable both for extrapolation of integration point values as well as computation of secondary variables directly on the mesh nodes.
* GWFlow now computes the Darcy velocity, solely for output purposes, as an example.
Problems:
* I think `std::vector<std::vector<double>> _darcy_velocities` is bad. One could do better if `getIntegrationPointValues()` would return a reference to some Eigen type.
* ~~The ctor of GWFlowProcess now demands less encapsulation, breaks our current init scheme and is somewhat fishy.~~ Fixed.
The new `<process>` subtree in the input files looks like:
```
<process> …
```
> Output secondary variables

- MathLib/LinAlg/PETSc/PETScLinearSolver.cpp
Archlinux now has PETSc 3.7.0 in its repos. This PR accounts for a small API change.
> Fix compilation for PETSc 3.7.0

- .clang-format
I would like to suggest setting `AllowShortIfStatementsOnASingleLine: false` in clang-format. Without this, 
```
if (!someVar) {
return;
}
```
will be changed to 
```
if (!someVar) return;
```
However I intentionally use the former because I can set a breakpoint to the line `return;`.
> set false to AllowShortIfStatementsOnASingleLine in clang-format 

- Applications/DataExplorer/mainwindow.cpp
- Applications/Utils/FileConverter/GMSH2OGS.cpp
- FileIO/GMSHInterface.cpp
- FileIO/GMSHInterface.h
- FileIO/GmshIO/GMSHPolygonTree.cpp
- FileIO/GmshIO/GMSHPolygonTree.h
- GeoLib/PolygonWithSegmentMarker.cpp
- GeoLib/PolygonWithSegmentMarker.h
- GeoLib/Polyline.cpp
- GeoLib/Polyline.h
- GeoLib/PolylineWithSegmentMarker.cpp
- GeoLib/PolylineWithSegmentMarker.h
The PR 
- Reintroduces the possibility to orthogonal project the input points to the x-y-plane instead of rotating it. (Rotating is still possible.)
- Introduces `PolygonWithSegmentMarker` and `PolylineWithSegmentMarker` in `GeoLib` in order to mark already preprocessed line segments in the GMSHPolygonTree.
- Fixes some mem leaks.
- Uses C++11 style at some places.
> [FileIO] GmshInterface 

- AssemblerLib/VectorMatrixAssembler.h
- ProcessLib/LocalAssemblerInterface.h
This adds missing functions to the interface for the jacobian assembly and the pre/post timestep operations.
> Extend local asm interface

- CMakeLists.txt
- MathLib/LinAlg/MatrixTools.h
- MeshLib/ElementCoordinatesMappingLocal.cpp
- MeshLib/ElementCoordinatesMappingLocal.h
- NumLib/Fem/CoordinatesMapping/ShapeMatrices.h
- NumLib/Fem/ShapeMatrixPolicy.h
- Tests/MathLib/TestLocalMatrixFunctions.cpp
- Tests/MeshLib/MeshProperties.cpp
- Tests/MeshLib/TestCoordinatesMappingLocal.cpp
- Tests/NumLib/TestCoordinatesMapping.cpp
- Tests/NumLib/TestFe.cpp
- Tests/NumLib/TestShapeMatrices.cpp
as titled. #ifdef OGS_USE_EIGEN is still used for global matrix, vector, and linear solver.
> remove #ifdef OGS_USE_EIGEN from local matrix related files

- scripts/cmake/test/Test.cmake
> Target ctest-large now runs all tests.

- scripts/cmake/ProjectSetup.cmake
Can be forced by setting `OGS_32_BIT=ON`.
In general Windows 32-bit builds are not supported but often are accidentally configured (because CMake defaults to a 32-bit generator). Beside running OGS on Win XP there is no reason to build for 32-bit Windows.
> Disallow 32-bit Windows builds.

- GeoLib/IO/XmlIO/Boost/BoostXmlGmlInterface.cpp
- GeoLib/IO/XmlIO/Qt/XmlGmlInterface.cpp
The increase of the output precision solves problem that sometimes not all boundary conditions set via a geometry are found. This can be caused by the different precision the mesh and the geometry are written. This PR tries to resolve the problem.
> [GL/IO] Increase output precision for gml output.

- GeoLib/Surface.cpp
- GeoLib/Surface.h
- GeoLib/Triangle.cpp
- GeoLib/Triangle.h
- Impl. of Surface copy construtor
- Cleanup unused code
- Clang format
- Make classes Triangle and Surface final
- Readability improvements
> [GL] Impl. of copy constructor of Surface and minor improvements

- MathLib/LinAlg/BLAS.cpp
- MathLib/LinAlg/PETSc/PETScMatrix.cpp
- MathLib/LinAlg/PETSc/PETScMatrix.h
- MathLib/LinAlg/PETSc/PETScVector.cpp
- MathLib/LinAlg/PETSc/PETScVector.h
It doesn't make sense to use std::unique_ptr for PETSc vec mat objects because Vec and Mat types are actually pointers, i.e. `typedef struct _p_Mat* Mat`. 
and it can mislead people that std::unique_ptr can delete a PETSc Mat object, which is not true.
> Remove std::unique_ptr for PETSc vec mat

- NumLib/Fem/CoordinatesMapping/ShapeMatrices.h
- Tests/NumLib/TestFe.cpp
The Eigen alignment is not used anywhere else and so far the code runs fine w/o
this alignment.
Between the decisions to add Eigen alignment for all Eigen-containing structs
and containers or remove completely the latter is easier.
This is related to https://github.com/ufz/ogs/pull/1221.
Closes https://github.com/ufz/ogs/pull/1221.
> [NL] Remove Eigen alignment from shape matrices.

- CHANGELOG.md
- Documentation/ProjectFile/initial_condition/Uniform/c_Uniform.md
- Documentation/ProjectFile/initial_condition/Uniform/t_value.md
- Documentation/ProjectFile/initial_condition/Uniform/t_values.md
- NumLib/DOF/LocalToGlobalIndexMap.cpp
- NumLib/DOF/LocalToGlobalIndexMap.h
- ProcessLib/InitialCondition.cpp
- ProcessLib/InitialCondition.h
- ProcessLib/NeumannBc.h
- ProcessLib/NeumannBcConfig.h
- ProcessLib/Process.h
- ProcessLib/ProcessVariable.cpp
- ProcessLib/ProcessVariable.h
- ProcessLib/UniformDirichletBoundaryCondition.cpp
- ProcessLib/UniformDirichletBoundaryCondition.h
Introduce variable_id to get multivariable/multicomponent processes set up correctly with their ICs and BCs. Also see the Tests/Data, where `<component_value_0>` is used for example for the second component instead of `<value>`. Other ideas to mark the components are welcome.
The uniform initial conditions for multicomponent variable can be given in the form
```xml
<values>0.5 0.7 0.9</values>
```
for a three component variable.
Not implemented and explicitly marked as such is the reading of the multicomponent boundary conditions.
> Multicomponent ICs/BCs

- ProcessLib/ProcessOutput.h
- ProcessLib/SecondaryVariable.h
Thus it will be less likely to configure them wrong in custom processes.
The underlying "problem" is that the tag name has to be written twice in the source code in order to set up one secondary variable. Cf.
https://github.com/ufz/ogs/blob/master/ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.h#L108
and
https://github.com/ufz/ogs/blob/master/ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.h#L188
> Tag names of secondary variables better checked

- MathLib/LinAlg/BLAS.cpp
- MathLib/LinAlg/BLAS.h
- MathLib/LinAlg/Eigen/EigenMatrix.h
- MathLib/LinAlg/Eigen/EigenVector.h
- MathLib/LinAlg/Lis/LisMatrix.cpp
- MathLib/LinAlg/Lis/LisMatrix.h
- MathLib/LinAlg/Lis/LisVector.cpp
- MathLib/LinAlg/Lis/LisVector.h
- MathLib/LinAlg/PETSc/PETScMatrix.h
- MathLib/LinAlg/PETSc/PETScVector.cpp
- MathLib/LinAlg/PETSc/PETScVector.h
- MathLib/LinAlg/UnifiedMatrixSetters.cpp
- MeshLib/IO/VtkIO/VtuInterface.cpp
- NumLib/ODESolver/TimeDiscretization.h
- Tests/MathLib/TestGlobalMatrixInterface.cpp
- Tests/MathLib/TestGlobalVectorInterface.cpp
- Tests/MathLib/TestLinearSolver.cpp
follow up of #1246 
moved all linear algebraic operations in global mat vec classes to BLAS namespace. The next step is renaming "BLAS" to something else.
> Clean up global Mat Vec class interface

- NumLib/Assembler/VectorMatrixAssembler.h
@endJunction suggested that some lambdas can be removed. That might increase performance a bit, and it makes the code easier to understand.
There are no logic changes in this PR, it is merely a rewrite of existing code.
> Simplified VecMatAssembler

- BaseLib/ConfigTree.cpp
- Tests/BaseLib/TestConfigTree.cpp
The problem is the following:
1. Something goes wrong → exception thrown
2. stack unwinds
3. ConfigTree gets destroyed
4. The check detects that it has not been processed entirely → throws again, leading to an error message from a point that would have been OK if the (1.) would not have occured.
This PR fixes point no. (4.).
> Quickfix for confusing error messages from ConfigTree

- NumLib/Extrapolation/LocalLinearLeastSquaresExtrapolator.h
It is rather easy to get the extrapolation calls wrong. @endJunction asked me to provide a debug notice for that.
Please have a look if my note is understandable, and if not, please make some better suggestions.
> [PL] added debug note to ProcessOutput

- GeoLib/DuplicateGeometry.cpp
- GeoLib/DuplicateGeometry.h
- Tests/GeoLib/TestDuplicateGeometry.cpp
This adds a class for creating a deep copy of an existing geometry. I needed this for a number of external tools and we discussed that it might make sense to put this into GeoLib.
@TomFischer : maybe you can use the surface-copy routine as a blueprint for the surface copy ctor.
> Duplicate geometry

- Applications/DataExplorer/DataView/DirectConditionGenerator.cpp
- Applications/Utils/MeshGeoTools/ComputeSurfaceNodeIDsInPolygonalRegion.cpp
- MeshLib/MeshSurfaceExtraction.cpp
- MeshLib/MeshSurfaceExtraction.h
In the commits 04582f8, 3b57c33 and 38b2b67 main work is done, other two commits are only reformating. This is one of the steps to make `MeshLib` independent from `GeoLib`.
> Make MeshSurfaceExtraction independent from GeoLib

- Applications/DataExplorer/Base/CMakeLists.txt
- Applications/DataExplorer/DataView/CMakeLists.txt
- Applications/DataExplorer/DataView/DiagramView/CMakeLists.txt
- Applications/DataExplorer/VtkAct/CMakeLists.txt
- Applications/DataExplorer/VtkVis/CMakeLists.txt
- Applications/Utils/OGSFileConverter/CMakeLists.txt
- MaterialsLib/CMakeLists.txt
fix dynamic linking errors on mac. Note that STATIC is explicitly given to some DE libraries due to their circular dependency.
> add missing dependency for dynamic linking

- Applications/DataExplorer/DataView/StationTreeModel.cpp
- Applications/DataExplorer/DataView/StationTreeModel.h
- Applications/DataExplorer/DataView/StationTreeView.cpp
- Applications/DataExplorer/DataView/StationTreeView.h
- Applications/DataExplorer/mainwindow.cpp
- Applications/DataExplorer/mainwindow.h
- GeoLib/Station.h
- Tests/GeoLib/TestDuplicateGeometry.cpp
...as requested for the GW tutorial book.
> Adding/changing names of stations 

- Applications/ApplicationsLib/UncoupledProcessesTimeLoop.cpp
- Applications/ApplicationsLib/UncoupledProcessesTimeLoop.h
- NumLib/ODESolver/NonlinearSolver-impl.h
- NumLib/ODESolver/NonlinearSolver.h
- NumLib/ODESolver/TimeLoopSingleODE.h
- ProcessLib/Output.cpp
- ProcessLib/Output.h
... after every iteration of the nonlinear solver.
This adds PR adds a callback to the nonlinear solvers' `solve()` method that can be used for output.
The output file name is the same as usual, but with `_iter_#ITER` appended.
The places in the code are not performance-critical, so it is runtime-checked if there shall be output. It can bve configured with the tag `<output_iteration_results>` in the output config.
> Output iteration results

- Applications/CLI/ogs.cpp
- BaseLib/ConfigTree.cpp
- BaseLib/ConfigTree.h
With the default strict config checks, the dtor of ConfigTree threw exceptions. There are many problems with throwing dtors. This PR makes sure, `~ConfigTree()` won't throw.
The drawback is, that now we have to manually check from time to time if all config stuff went fine. (And I really like to keep the strict config checks.)
> Nothrow ConfigTree destructor

- MathLib/LinAlg/Eigen/EigenMatrix.h
For dynamic shape matrix policy the matrix/vector size parameters are unused.
> [NL] Remove unneded template parameter names.

- GeoLib/Surface.cpp
- GeoLib/Surface.h
- MeshGeoToolsLib/BoundaryElementsOnSurface.cpp
- MeshGeoToolsLib/MeshNodeSearcher.cpp
- MeshGeoToolsLib/MeshNodesAlongSurface.cpp
- MeshGeoToolsLib/MeshNodesAlongSurface.h
- Tests/GeoLib/TestSurfaceIsPointInSurface.cpp
Until now the default value of `std::numeric_limits<double>::epsilon()` was used. This PR changes the behaviour, i.e., the user can give some epsilon value different from the default value.
> Change Surface search tolerance.

- scripts/cmake/ExternalProjectBoost.cmake
fix a problem that a environmental variable BOOST_ROOT doesn't work
> fix internally setting BOOST_ROOT from env var

- Applications/DataExplorer/DataView/DirectConditionGenerator.cpp
- Applications/DataExplorer/DataView/MeshLayerEditDialog.cpp
- Applications/DataExplorer/DataView/MshView.cpp
- Applications/DataExplorer/VtkVis/VtkRaster.cpp
- Applications/DataExplorer/mainwindow.cpp
- Applications/FileIO/AsciiRasterInterface.cpp
- Applications/FileIO/AsciiRasterInterface.h
- Applications/FileIO/CsvInterface.cpp
- Applications/FileIO/CsvInterface.h
- Applications/Utils/MeshEdit/CMakeLists.txt
- Applications/Utils/MeshEdit/createLayeredMeshFromRasters.cpp
- Applications/Utils/SimpleMeshCreation/CMakeLists.txt
- Applications/Utils/SimpleMeshCreation/createMeshElemPropertiesFromASCRaster.cpp
- MeshGeoToolsLib/GeoMapper.cpp
- MeshGeoToolsLib/GeoMapper.h
- Tests/FileIO/TestCsvReader.cpp
As discussed, interfaces for external file formats are moved back into Applications/FileIO.
> Moving CSV-/Raster-interface back to FileIO

- GeoLib/PointVec.cpp
- GeoLib/PointVec.h
- GeoLib/TemplateVec.h
This fixes an issue where point names would get lost when merging or saving geometries.
> [GL] Correctly setting point names

- GeoLib/PointVec.h
Removes the warning: 'push_back' overrides a member function but is not marked 'override'.
> [GL] Add override specifier to one of push_backs.

- Applications/ApplicationsLib/LinearSolverLibrarySetup.h
- Applications/ApplicationsLib/UncoupledProcessesTimeLoop.cpp
- NumLib/DOF/GlobalMatrixProviders.cpp
- NumLib/DOF/GlobalMatrixProviders.h
- NumLib/DOF/MatrixProviderUser.h
- NumLib/DOF/SimpleMatrixVectorProvider-impl.h
- NumLib/DOF/SimpleMatrixVectorProvider.cpp
- NumLib/DOF/SimpleMatrixVectorProvider.h
- NumLib/Extrapolation/LocalLinearLeastSquaresExtrapolator.h
- NumLib/ODESolver/EquationSystem.h
- NumLib/ODESolver/MatrixTranslator.cpp
- NumLib/ODESolver/MatrixTranslator.h
- NumLib/ODESolver/NonlinearSolver.cpp
- NumLib/ODESolver/TimeDiscretization.h
- NumLib/ODESolver/TimeDiscretizedODESystem.cpp
- NumLib/ODESolver/TimeLoopSingleODE.h
follow up of #1261
- fix that some classes in NumLib/DOF dir have MathLib namespace
- remove Mat/Vec templates in NumLib/DOF (i.e. GlobalMatrix/VectorProvider, Matrix/VectorProvider)
> Fixing namespaces and removing Mat/Vec templates in NumLib/DOF

- Applications/DataExplorer/Base/CMakeLists.txt
- Applications/DataExplorer/DataView/ColorTableModel.cpp
- Applications/DataExplorer/DataView/ColorTableModel.h
- Applications/DataExplorer/DataView/DiagramView/DetailWindow.cpp
- Applications/DataExplorer/DataView/StationTreeView.cpp
- Applications/DataExplorer/DataView/StratView/StratBar.cpp
- Applications/DataExplorer/DataView/StratView/StratBar.h
- Applications/DataExplorer/DataView/StratView/StratScene.cpp
- Applications/DataExplorer/DataView/StratView/StratScene.h
- Applications/DataExplorer/DataView/StratView/StratView.cpp
- Applications/DataExplorer/DataView/StratView/StratView.h
- Applications/DataExplorer/DataView/StratView/StratWindow.cpp
- Applications/DataExplorer/DataView/StratView/StratWindow.h
- Applications/DataExplorer/VtkVis/VtkAlgorithmProperties.cpp
- Applications/DataExplorer/VtkVis/VtkColorLookupTable.cpp
- Applications/DataExplorer/VtkVis/VtkColorLookupTable.h
- Applications/DataExplorer/VtkVis/VtkCompositeColorByHeightFilter.cpp
- Applications/DataExplorer/VtkVis/VtkCompositeColormapToImageFilter.cpp
- Applications/DataExplorer/VtkVis/VtkCompositeElementSelectionFilter.cpp
- Applications/DataExplorer/VtkVis/VtkPointsSource.cpp
- Applications/DataExplorer/VtkVis/VtkPolylinesSource.cpp
- Applications/DataExplorer/VtkVis/VtkStationSource.cpp
- Applications/DataExplorer/VtkVis/VtkStationSource.h
- Applications/DataExplorer/VtkVis/VtkSurfacesSource.cpp
- Applications/DataExplorer/VtkVis/VtkVisPipeline.h
- Applications/DataHolderLib/Color.cpp
- Applications/DataHolderLib/Color.h
- Applications/DataHolderLib/ColorLookupTable.cpp
- Applications/DataHolderLib/ColorLookupTable.h
- Applications/FileIO/XmlIO/Qt/XmlLutReader.h
Moves Color to DataHolderLib, introduces a new data holder for lookup-tables and removes the circular dependency.
> Removing circular dependency with XmlLutReader

- NumLib/Fem/ShapeFunction/ShapeHex20.h
- NumLib/Fem/ShapeFunction/ShapeHex8.h
- NumLib/Fem/ShapeFunction/ShapeLine2.h
- NumLib/Fem/ShapeFunction/ShapeLine3.h
- NumLib/Fem/ShapeFunction/ShapePoint1.h
- NumLib/Fem/ShapeFunction/ShapePrism15.h
- NumLib/Fem/ShapeFunction/ShapePrism6.h
- NumLib/Fem/ShapeFunction/ShapePyra13.h
- NumLib/Fem/ShapeFunction/ShapePyra5.h
- NumLib/Fem/ShapeFunction/ShapeQuad4.h
- NumLib/Fem/ShapeFunction/ShapeQuad8.h
- NumLib/Fem/ShapeFunction/ShapeQuad9.h
- NumLib/Fem/ShapeFunction/ShapeStaticConsts.cpp
- NumLib/Fem/ShapeFunction/ShapeTet10.h
- NumLib/Fem/ShapeFunction/ShapeTet4.h
- NumLib/Fem/ShapeFunction/ShapeTri3.h
- NumLib/Fem/ShapeFunction/ShapeTri6.h
The elements' dimensions (DIM and NPOINTS) are declared
'unsigned' is the MeshLib (MeshElement::dimension and
MeshElement::n_all_nodes) and should be of the same
type for the shape functions.
This is automated change with sed.
> [NL] Unify unsigned type usage in shape functions.

- NumLib/ODESolver/TimeDiscretizedODESystem.cpp
as titled. Although the results of the PETSc related tests are correct after introducing BLAS (now LinAlg), PETSc errors occur in the log file. This PR fixed the problem.
> Added finalizeAssembly(x) to avoid PETSc errors in the vector copying

- NumLib/Extrapolation/Extrapolator.h
- NumLib/Extrapolation/LocalLinearLeastSquaresExtrapolator-impl.h
- NumLib/Fem/ShapeMatrixPolicy.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowFEM.h
- ProcessLib/LocalAssemblerTraits.h
- ProcessLib/TES/TESLocalAssembler-impl.h
- ProcessLib/TES/TESLocalAssembler.h
- ProcessLib/TES/TESLocalAssemblerInner-impl.h
- Tests/NumLib/TestCoordinatesMapping.cpp
- Tests/NumLib/TestExtrapolation.cpp
- Tests/NumLib/TestFe.cpp
as issued in #1244. 
In the first commit, I changed 	template parameter `NIntPts` in `LocalAssemblerTraitsFixed` to `NNodes` based on how it is used, though I'm not sure if it is correct.
Fixes https://github.com/ufz/ogs/issues/1244
> Change shape vector to a row vector

- Applications/FileIO/XmlIO/Qt/XmlGspInterface.cpp
- Applications/FileIO/XmlIO/Qt/XmlNumInterface.cpp
- BaseLib/BuildInfo.cpp.in
- BaseLib/BuildInfo.h
- BaseLib/FileFinder.cpp
- BaseLib/FileFinder.h
- GeoLib/IO/XmlIO/Qt/XmlGmlInterface.cpp
- GeoLib/IO/XmlIO/Qt/XmlStnInterface.cpp
To get rid of specific directory paths in BaseLib/FileFinder and make it general, this PR introduces
- add new FileFinder constructor taking a directory search path
- add XML scheme paths to BaseLib::BuildInfo
and definitions of FileFinder were moved to cpp file.
> Make FileFinder general

- Applications/CLI/Tests.cmake
- MathLib/LinAlg/PETSc/PETScLinearSolver.cpp
- MathLib/LinAlg/PETSc/PETScMatrix.cpp
- MeshLib/IO/MPI_IO/NodePartitionedMeshReader.cpp
- MeshLib/IO/readMeshFromFile.cpp
- MeshLib/IO/readMeshFromFile.h
- MeshLib/Node.h
- MeshLib/NodePartitionedMesh.h
- NumLib/DOF/ComputeSparsityPattern.cpp
- Tests/MathLib/TestGlobalMatrixInterface.cpp
Allow PETSc run with only one CPU core with reading original mesh data directly, e.g.
```
orterun -np 1   ogs -o ~/temp ~/code/ogs6/sources/Tests/Data/Elliptic/cube_1x1x1_GroundWaterFlow/cube_1e3_neumann.prj
```
where orterun could also be mpirun.
> Allow PETSc run with only one CPU core

- NumLib/Extrapolation/ExtrapolatableElement.h
- NumLib/Extrapolation/ExtrapolatableElementCollection.h
- NumLib/Extrapolation/Extrapolator.h
- NumLib/Extrapolation/LocalLinearLeastSquaresExtrapolator.cpp
- NumLib/Extrapolation/LocalLinearLeastSquaresExtrapolator.h
- ProcessLib/ExtrapolatorData.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowFEM.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.cpp
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.h
- ProcessLib/Process.cpp
- ProcessLib/Process.h
- ProcessLib/SecondaryVariable.h
- ProcessLib/TES/TESLocalAssembler-impl.h
- ProcessLib/TES/TESLocalAssembler.h
- ProcessLib/TES/TESLocalAssemblerInner-impl.h
- ProcessLib/TES/TESLocalAssemblerInner.h
- ProcessLib/TES/TESProcess.cpp
- ProcessLib/TES/TESProcess.h
- Tests/NumLib/TestExtrapolation.cpp
Follow-up of #1306.
* Core Extrapolation is now template-free
* there is an adaptor `ExtrapolatableElementCollection` passing information from local assemblers to the `Extrapolator`
* the `Extrapolator` is managed by the base `Process`, now
* there is no per-process enum telling what to extrapolate, anymore
* instead there has to be a member function for each property to be extrapolated.
The last point means somewhat more code is required. However, the other points save some code.
The introduced changes maka a better separation between individual processes and extrapolation. In the future the extrapolation logic maybe can be entirely moved to some output class.
> Extrapolation moved to base Process

- Tests/MathLib/TestLinearSolver.cpp
LIS build failed if Eigen and LIS index types are different.
> Fix LIS build

- Applications/CLI/Tests.cmake
- MeshLib/IO/VtkIO/VtuInterface.cpp
Since SetFileName of ``vtkSmartPointer<UnstructuredGridWriter>`` drops characters starting from '.' in a string, the previous changes in the output file names cause a problem in writing a correct pvtu file. This PR fixes the problem, meanwhile it removes some compilation warnings.
> Fix pvtu name

- BaseLib/Functional.cpp
- BaseLib/Functional.h
- BaseLib/TMPUtil.h
- Tests/BaseLib/TestFunctional.cpp
Follow-up of #1309.
Example:
```{.cpp}
using std::placeholders;
Object some_object;
auto f_bind = std::function<ReturnType(Arg1, Arg2, Arg3)>(
std::bind(&Object::methodWithThreeArguments,
std::ref(some_object), _1, _2, _3));
auto f_easy = easyBind(&Object::methodWithThreeArguments, some_object);
```
The lines generating `f_bind` and `f_easy` produce equivalent results.
Features:
* less typing
* result type can be used for type deduction (I'll use that in a follow-up PR)
* no accidental copies of the object being bound to.
* easyBind guarantees that all types involved match up.
> Added a wrapper for std::bind

- BaseLib/Subdivision.h
The name of _L causes a compilation error by using gcc under Cygwin.
> [Compile] Fixed a potential compilation error

- Applications/CLI/Tests.cmake
- GeoLib/AnalyticalGeometry-impl.h
- MeshLib/ElementCoordinatesMappingLocal.cpp
- MeshLib/ElementCoordinatesMappingLocal.h
- NumLib/Fem/CoordinatesMapping/NaturalCoordinatesMapping.cpp
- NumLib/Fem/CoordinatesMapping/NaturalCoordinatesMapping.h
- NumLib/Fem/FiniteElement/TemplateIsoparametric.h
- ProcessLib/NeumannBcAssembler.h
- ProcessLib/Utils/InitShapeMatrices.h
- Tests/MathLib/TestIntegration.cpp
- Tests/MeshLib/TestCoordinatesMappingLocal.cpp
- Tests/NumLib/TestCoordinatesMapping.cpp
- Tests/NumLib/TestFe.cpp
- Tests/NumLib/TestFunctionInterpolation.cpp
In our shape matrix computation routines there was some code detecting the special case when a 2D element lies in the x-y plane. This code led to Neumann BCs being added sign-flipped if the surface at which it was applied was in the x-y-plane with surface normal (0, 0, -1).
This PR fixes the special cases in the code. A small end-to-end test example has been added. Cf. image: Groundwaterflow process; upper row before the PR, lower row after the PR; one surface is kept at Dirichlet 1, the other has Neumann 1, i.e., the point at which the Neumann BC is applied must be the maximum over the entire z-axis; that did not always hold before this PR (upper right case).
Furthermore the det J > 0 check has been made strict in this PR. I.e., elements with zero volume or wrong orientation are …
> Fix surfaces lying in x-y-plane

- ProcessLib/LocalAssemblerInterface.cpp
- ProcessLib/LocalAssemblerInterface.h
See also "[PL] moved index computation to local assembler interface" 2d891b068ba0864ba8826818085de8c2cab808b5 .
Follow up of ufz/ogs#1306.
> [PL] Update pre/postTimestep as in #1306.

- BaseLib/FileTools.cpp
- MeshLib/IO/VtkIO/VtuInterface.cpp
- Tests/BaseLib/TestFilePathStringManipulation.cpp
#1319 fixed pvtu file names. But the solution causes an issue if some directories in the file path contains dots in their name. This PR makes sure that only dots in the basename of the pvtu file are replaced. For the rest see the commit messages.
> Fix dots in VTU file names

- Applications/CLI/Tests.cmake
- scripts/cmake/test/AddTest.cmake
In #1239 I messed up the vtkdiff tests: One filename and two fieldnames are given, e.g.,
`tes_zeolite_discharge_small_pcs_0_ts_19_t_0.100000.vtu pressure pressure`.
If the two field names are equal, that field is compared to itself yielding zero error norms.
This PR fixes that.
~~TODO: Parallel PETSc tests.~~
> Fix AddTest

- NumLib/NamedFunction.cpp
- NumLib/NamedFunction.h
- NumLib/NamedFunctionCaller.cpp
- NumLib/NamedFunctionCaller.h
- NumLib/NamedFunctionProvider.h
- Tests/BaseLib/TestFunctional.cpp
- Tests/InstanceCounter.h
- Tests/NumLib/TestNamedFunction.cpp
Follow-up of #1312.
This PR adds classes that enable the construction of expression trees dynamically at runtime.
That roughly goes into the direction discussed recently in the frame of constitutive relations.
However, I want to use the code provided here at first to compute secondary variables.
For a usage example, please have a look at the tests. There will be a follow-up PR coupling this PR with FEM processes, soon.
> Named Functions

- NumLib/ODESolver/NonlinearSolver.cpp
Otherwise it behaves different than the Picard iterations: [NonlinearSolver.cpp, Picard solve method](https://github.com/ufz/ogs/blob/master/NumLib/ODESolver/NonlinearSolver.cpp#L53)
> [NL] Fix Newton max iterations counter comparison.

- Applications/Utils/MeshEdit/queryMesh.cpp
This PR includes the following changes in queryMesh
- print a list of connected nodes (for the given node)
- add --show-node-with-max-elements option to print information about a node having the maximum number of connected elements in the given mesh
> small improvements of queryMesh 

- CHANGELOG.md
- Documentation/ProjectFile/boundary_condition/t_component.md
- ProcessLib/ProcessVariable.cpp
The main work was done before, but the parser was missing.
The default value for the component is 0 such that there is no need to add <component> for single component variables.
TODO:
> [PL] Add multicomponent boundary conditions.

- Applications/CLI/Tests.cmake
- ProcessLib/BoundaryCondition/BoundaryCondition.cpp
- ProcessLib/BoundaryCondition/UniformRobinBoundaryCondition.cpp
- ProcessLib/BoundaryCondition/UniformRobinBoundaryCondition.h
- ProcessLib/BoundaryCondition/UniformRobinBoundaryConditionLocalAssembler.h
This is a successor of #1337.
Missing features:
* The Robin BC currently cannot be used with the Newton-Raphson scheme out of the box. Currently there is no process ready for Newton, so I postponed this feature.
> Added uniform Robin BC

- Applications/Utils/ModelPreparation/CMakeLists.txt
- Applications/Utils/ModelPreparation/scaleProperty.cpp
- Applications/Utils/SimpleMeshCreation/createMeshElemPropertiesFromASCRaster.cpp
- GeoLib/AABB.h
- MathLib/GeometricBasics.cpp
- MathLib/GeometricBasics.h
- MeshLib/Elements/Element.cpp
- MeshLib/Elements/Element.h
- MeshLib/Mesh.cpp
- MeshLib/Mesh.h
- MeshLib/MeshEditing/Mesh2MeshPropertyInterpolation.cpp
- MeshLib/MeshEditing/Mesh2MeshPropertyInterpolation.h
Rework of tool to transmit raster data to a mesh.
> Transmit raster data to element properties

- Applications/Utils/ModelPreparation/CMakeLists.txt
- Applications/Utils/ModelPreparation/createNeumannBc.cpp
`createNeumannBc  --result-out <output file name> --property-name <string (property name)>
--in-mesh <filename for mesh input>`
The tool integrates the given element property (given via switch `property-name`) and writes the computed data as a `PropertyVector` with the name *node_aggregated_gwn* into the mesh. The tool also outputs an OGS-5 direct source term (Neumann boundary condition) data file, i.e., first column is the id of the mesh node and second column contains the integrated value.
> Create OGS-5 direct Neumann boundary conditions (in OGS-5: source terms)

- scripts/doc/append-xml-tags.py
- scripts/doc/check-project-params.py
- scripts/doc/linked-xml-file.py
- scripts/doc/normalize-param-cache.py
- scripts/doc/print23.py
Jenkins' doc build failed because my new scripts used a non-standard python module. This PR fixes this.
Maybe it would be good to add `make internal_pre_doc_qa_page` to some of Jenkins' PR jobs in order to test the python and shell scripts?
> Fix Jenkins python 2/3 compatibility

- scripts/doc/check-project-params.py
- scripts/doc/linked-xml-file.py
Sorry for the change again.
This PR fixes the `ValueError: zero length field name in format` error.
This time I tried it on envinf1.
> [scr] fixed format() for python 2.6 compatibilty

- Applications/Utils/FileConverter/CMakeLists.txt
- Applications/Utils/FileConverter/convertGEO.cpp
- Applications/Utils/MeshEdit/appendLinesAlongPolyline.cpp
- GeoLib/IO/readGeometryFromFile.cpp
This PR includes 
- add a new CLI tool (`convertGEO`) for geometric file conversion, e.g. *.gli -> *.gml 
- support all geometric file formats in `appendLinesAlongPolyline` tool
- fix misleading variable setting in readGeometryFromFile.cpp
> New tool convertGEO and some minor fixes

- Applications/Utils/MeshEdit/CMakeLists.txt
- Applications/Utils/MeshEdit/swapNodeCoordinateAxes.cpp
- Applications/Utils/SimpleMeshCreation/generateStructuredMesh.cpp
Adding a CLI tool named `flipNodeCoordinates` to flip node coordinates, e.g. XY to XZ plane.
> add a CLI tool flipNodeCoordinates

- Applications/ApplicationsLib/ProjectData.cpp
- Applications/ApplicationsLib/UncoupledProcessesTimeLoop.cpp
- Applications/ApplicationsLib/UncoupledProcessesTimeLoop.h
- NumLib/ODESolver/ConvergenceCriterion.cpp
- NumLib/ODESolver/ConvergenceCriterion.h
- NumLib/ODESolver/ConvergenceCriterionDeltaX.cpp
- NumLib/ODESolver/ConvergenceCriterionDeltaX.h
- NumLib/ODESolver/ConvergenceCriterionPerComponent.h
- NumLib/ODESolver/ConvergenceCriterionPerComponentDeltaX.cpp
- NumLib/ODESolver/ConvergenceCriterionPerComponentDeltaX.h
- NumLib/ODESolver/ConvergenceCriterionPerComponentResidual.cpp
- NumLib/ODESolver/ConvergenceCriterionPerComponentResidual.h
- NumLib/ODESolver/ConvergenceCriterionResidual.cpp
- NumLib/ODESolver/ConvergenceCriterionResidual.h
- NumLib/ODESolver/NonlinearSolver.cpp
- NumLib/ODESolver/NonlinearSolver.h
- NumLib/ODESolver/TimeLoopSingleODE.h
- ProcessLib/GroundwaterFlow/CreateGroundwaterFlowProcess.cpp
- ProcessLib/GroundwaterFlow/CreateGroundwaterFlowProcess.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.cpp
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.h
- ProcessLib/Process.cpp
- ProcessLib/Process.h
- ProcessLib/TES/CreateTESProcess.cpp
- ProcessLib/TES/CreateTESProcess.h
- ProcessLib/TES/TESProcess.cpp
- ProcessLib/TES/TESProcess.h
- Tests/NumLib/TestODEInt.cpp
~~Follow-up of #1315 and of #1349.~~
Closes #1339.
Core things:
* The [ConvergenceCriterion](https://github.com/chleh/ogs6/blob/conv-crit/NumLib/ODESolver/ConvergenceCriterion.h) interface
* Its usage in the [nonlinear solvers](https://github.com/ufz/ogs/pull/1342/files#diff-bf2c8423f053d67a6d9d9a91d8ac0a87) 
* The changes to the input files ufz/ogs-data#17
TODO
For later:
* There is currently no residual-norm check class implemented. I think that an be done later on as soon as it is needed.
> Added flexible nonlinear solver convergence criteria

- MeshGeoToolsLib/GeoMapper.cpp
Fixes a bug for LineSegments that are complete outside of the mesh area.
> [MGTL] Deep copy of seg to avoid modifying orig. pnts.

- MeshLib/MeshGenerators/VtkMeshConverter.cpp
This makes it possible to read and write std::size_t under linux and windows.
> Read and write data arrays of type std::size_t under linux and windows in the vtu io.

- Applications/Utils/SimpleMeshCreation/generateStructuredMesh.cpp
- MeshLib/MeshGenerators/MeshGenerator.cpp
- MeshLib/MeshGenerators/MeshGenerator.h
This PR adds support of tetrahedral element type in generateStructuredMesh tool
> support tetrahedra in generateStructuredMesh

- GeoLib/Grid.h
> [GL] Enlarge delta for grid meta data computation.

- Documentation/ProjectFile/parameter/Constant/c_Constant.md
- Documentation/ProjectFile/parameter/Constant/t_value.md
- Documentation/ProjectFile/parameter/Constant/t_values.md
- ProcessLib/BoundaryCondition/NeumannBoundaryConditionLocalAssembler.h
- ProcessLib/BoundaryCondition/RobinBoundaryConditionLocalAssembler.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowFEM.h
- ProcessLib/Parameter/ConstantParameter.cpp
- ProcessLib/Parameter/ConstantParameter.h
- ProcessLib/Parameter/MeshElementParameter.h
- ProcessLib/Parameter/MeshNodeParameter.h
- ProcessLib/Parameter/Parameter.h
- ProcessLib/Process.cpp
- Extend the ConstantParameter to read `<values>`. The `<value>` tag remains for scalar parameters.
This is needed for the [Mechancis PR](https://github.com/ufz/ogs/pull/1340) where the initial conditions are multi-component, constants. Before we had multi-component InitialCondition, which is replaced by Parameter.
- ~~Also add two Parameter::operator() for scalar and component-wise value access.~~
Renames `getTuple(t,x)` into call operator. This is for convenience: `rho(t, x)[0]` for scalar parameter rho, or `K(t,x)[i]` for three-dim conductivity/permeability parameter K (accessing the i-th component) is much nicer/less noisier than `rho.getTuple(t,x)[0]` or `K.getTuple(t,x)[i]`.
> Multi component ConstantParameter and Parameter access operators.

- NumLib/Fem/Integration/IntegrationGaussPrism.h
- NumLib/Fem/Integration/IntegrationGaussPyramid.h
- NumLib/Fem/Integration/IntegrationGaussRegular-impl.h
- NumLib/Fem/Integration/IntegrationGaussRegular.h
- NumLib/Fem/Integration/IntegrationGaussTet.h
- NumLib/Fem/Integration/IntegrationGaussTri.h
- NumLib/Fem/Integration/IntegrationPoint.h
- ProcessLib/BoundaryCondition/GenericNaturalBoundaryConditionLocalAssembler.h
- ProcessLib/BoundaryCondition/NeumannBoundaryConditionLocalAssembler.h
- ProcessLib/BoundaryCondition/RobinBoundaryConditionLocalAssembler.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowFEM.h
- ProcessLib/TES/TESLocalAssembler-impl.h
- ProcessLib/TES/TESLocalAssembler.h
- ProcessLib/Utils/InitShapeMatrices.h
- Tests/NumLib/TestExtrapolation.cpp
- Consistent use of unsigned int for order and integration point number
- Store IntegrationMethod object instead of integratin order. This saves creation of that object every time assemble functions are called. sizeof(IntegrationMethod) == 8.
For this to work nicely I had to reorder shape_matrices creation and integration method.
Testing with `cube_1e5_neumann.prj` yields a win (in cpu cycles) in about 2%.
This PR (1a09e0):
```
Performance counter stats for 'bin/ogs ../Tests/Data/Elliptic/cube_1x1x1_GroundWaterFlow/cube_1e5_neumann.prj' (30 runs):
12,527,021,011      cycles:u                  #    3.928 GHz                      ( +-  0.17% )
5,904,757,008      stalled-cycles-frontend:u #   47.14% frontend cycles idle     ( +-  0.54% )
22,607,073,869      instructions:u            # …
```
> unsigned int in Gauss integration methods

- Applications/Utils/ModelPreparation/ComputeNodeAreasFromSurfaceMesh.cpp
- Applications/Utils/ModelPreparation/createNeumannBc.cpp
- MeshLib/MeshEditing/AddLayerToMesh.cpp
- Tests/MeshLib/MeshProperties.cpp
The called `getPropertyVector<T>()` did not return an optional to a const reference (there are two versions of that function), but an `optional<T&>`.
With boost 1.61 this conversion is no longer possible.
Fixes #1383
> Fix usage of optional<T const&>.

- scripts/cmake/CompilerSetup.cmake
- Is fixed since CMake 2.8.5, see http://stackoverflow.com/a/6274608/80480
- Will enable Ninja generator on Windows.
> [CMake] Removed adding of -isystem include flag

- Applications/ApplicationsLib/ProjectData.cpp
- Applications/CLI/Tests.cmake
- Documentation/ProjectFile/process/SMALL_DEFORMATION/c_SMALL_DEFORMATION.md
- Documentation/ProjectFile/process/SMALL_DEFORMATION/constitutive_relation/LinearElasticIsotropic/c_LinearElasticIsotropic.md
- Documentation/ProjectFile/process/SMALL_DEFORMATION/constitutive_relation/LinearElasticIsotropic/t_poissons_ratio.md
- Documentation/ProjectFile/process/SMALL_DEFORMATION/constitutive_relation/LinearElasticIsotropic/t_youngs_modulus.md
- Documentation/ProjectFile/process/SMALL_DEFORMATION/process_variables/t_process_variable.md
- Documentation/ProjectFile/process/SMALL_DEFORMATION/t_dimension.md
- MaterialLib/SolidModels/CreateLinearElasticIsotropic.h
- MaterialLib/SolidModels/LinearElasticIsotropic.cpp
- MaterialLib/SolidModels/LinearElasticIsotropic.h
- MaterialLib/SolidModels/MechanicsBase.h
- ProcessLib/CMakeLists.txt
- ProcessLib/Deformation/BMatrixPolicy.h
- ProcessLib/Deformation/LinearBMatrix.h
- ProcessLib/SmallDeformation/CreateLocalAssemblers.h
- ProcessLib/SmallDeformation/CreateSmallDeformationProcess.h
- ProcessLib/SmallDeformation/LocalDataInitializer.h
- ProcessLib/SmallDeformation/SmallDeformationFEM.h
- ProcessLib/SmallDeformation/SmallDeformationProcess-fwd.h
- ProcessLib/SmallDeformation/SmallDeformationProcess.cpp
- ProcessLib/SmallDeformation/SmallDeformationProcess.h
- ProcessLib/SmallDeformation/SmallDeformationProcessData.h
... including linear and Burger's materials.
Todo:
> Mechanics Process

- Jenkinsfile
- scripts/cmake/ProjectSetup.cmake
- scripts/jenkins/clang.groovy
- scripts/jenkins/gcc.groovy
- scripts/jenkins/msvc.groovy
- scripts/jenkins/msvc32.groovy
- Added one more Jenkins node *win1* (Windows)
- Windows builds are now better parallelized with [ninja](https://ninja-build.org/)
- Disabled S3 binary uploads for now (will be reimplemented in a different job)
- Win builds use Conan for all required libraries except of Qt ([Qt is in the works too](https://github.com/osechet/conan-qt/issues/7))
- All in all speed up of build time from roughly 1 h before to 10-15 mins now
> Refactored Jenkins pipeline

- MaterialLib/SolidModels/NewtonRaphson.h
- Tests/MaterialLib/NewtonRaphson.cpp
A very simple abstraction of the named method required in the current visco-elastic Burgers material model (#1391) and in the following single surface yield function material model (currently in development).
~~I put it into NumLib/NewtonMethods for now, but if this is not general enough (and you don't want extend it), it can be~~ It is placed near the material models implementations, where it is used.
No aspect of the solver can be configured by input files.
> Newton-Raphson for dense systems

- Applications/FileIO/FEFLOW/FEFLOWMeshInterface.cpp
- Tests/FileIO_Qt/TestFEFLOWInterface.cpp
> [FEFLOW] fix a bug that a property vector was not allocated before use

- MeshLib/Elements/LineRule2.h
- Tests/MeshLib/TestLineMesh.cpp
Without this in pure line meshes the min- and max-length for edges will be wrong.
> Changed edge number for line elements

- Applications/Utils/MeshEdit/ExtractSurface.cpp
- MeshLib/Mesh.h
- MeshLib/MeshSurfaceExtraction.cpp
- MeshLib/MeshSurfaceExtraction.h
The class `MeshSurfaceExtraction` extracts the surface of a subsurface mesh. For the balance process it is also important to know the subsurface element id and the number of the face of the subsurface element that belongs to the surface. 
The PR adds the possibility to write subsurface/bulk element ids and face ids to the mesh.
> Preparations for the BalanceProcess

- .gitignore
- ProcessLib/CMakeLists.txt
- ignore Visual Studio Code project files in git
- include ProcessLib/Deformation directory (so far header only) in CMake. Otherwise the dir is not shown in QtCreator.
> small fixes

- BaseLib/FileTools.cpp
- Tests/BaseLib/TestFilePathStringManipulation.cpp
I had to activate the windows tests only for windows since at one place a path separator is added. In general in my opinion we should switch to something like [boost::filesystem](http://www.boost.org/doc/libs/1_61_0/libs/filesystem/doc/index.htm).
**update**
`BaseLib::copyPathToFileName` takes two arguments: a file name and a path. The method puts them together. If the given `path` argument does not end with a path separator the previous version removed the part of the path from the last path separator till the end, i.e., for example `path/smth` was reduced to the path `path/`. This behaviour is changed with this PR. Now a path separator will be appended, i.e., the path will be modified: `path/smth/`.
> Fix an issue in `BaseLib::copyPathToFileName`

- Applications/Utils/MeshEdit/NodeReordering.cpp
Currently `NodeReordering` tool assumes that all elements in the given mesh have wrong node ordering. This PR extends it to checking ordering of each element and modifying only those having wrong ordering.
> [NodeReordering] check each element

- .gitignore
- Jenkinsfile
- scripts/jenkins/clang.groovy
- scripts/jenkins/docs.groovy
The job is always run. Should this be done on ufz master only?
> [Jenkins] Docs generation

- MaterialLib/CMakeLists.txt
- MaterialLib/Fluid/ConstantFluidProperty.h
- MaterialLib/Fluid/Density/IdealGasLaw.h
- MaterialLib/Fluid/Density/LinearTemperatureDependentDensity.h
- MaterialLib/Fluid/Density/LiquidDensity.h
- MaterialLib/Fluid/Density/createFluidDensityModel.cpp
- MaterialLib/Fluid/Density/createFluidDensityModel.h
- MaterialLib/Fluid/FluidProperty.h
- MaterialLib/Fluid/FluidPropertyHeaders.h
- Tests/MaterialLib/TestFluidDensity.cpp
This PR is the fluid density part of PR #1365, which has been revised according to your comments and it is closed now. 
In this PR, class FluidProperty is the base class of the classes for fluid density models and viscosity models.
> Classes for fluid density models

- scripts/jenkins/gcc.groovy
Possibly fixing sporadic ldd errors. Closes #1416.
> [Jenkins] Exclude CLI from gcc Data Exlorer build.

- BaseLib/Error.h
- CMakeLists.txt
This PR adds a new CMake option `OGS_FATAL_ABORT` which enables calling `abort()` in `OGS_FATAL()` instead of throwing exceptions.  The changes is helpful in debugging because it stops at at abort() and can backtrace from there.
> Abort in OGS_FATAL()

- MeshGeoToolsLib/BoundaryElementsAlongPolyline.cpp
- MeshLib/Elements/EdgeRule.h
- MeshLib/Elements/LineRule2.h
- MeshLib/Elements/LineRule3.h
fix #1419 
To keep the same behavior as before, I also changed `BoundaryElementsAlongPolyline` class ignores line elements.
> make Line elements return an edge

- MeshLib/PropertyVector.h
Currently `PropertyVector<T*> ` works only with a single component.
> Fix PropertyVector<T*> for multi-component case

- Applications/CLI/Tests.cmake
- Tests/MaterialLib/KelvinVector.cpp
- The Kelvin inverse unit test fails sometimes for large (in norm) input vectors.
- The GWF time dependent Neumann tests started failing on Jenkins [Tests_Linux_Large job](https://svn.ufz.de:8443/job/OGS-6/job/Tests_Linux_Large/) since the 21. Sep. but there was no related code change. Maybe something changed in the infrastructure (new LIS/Eigen/compilation options/...).
Fixes https://github.com/ufz/ogs/issues/1421
Fixes https://github.com/ufz/ogs/issues/1415
> Relax tests tolerances

- .travis.yml
- scripts/cmake/CompilerSetup.cmake
Mainly for upgrading clang from version 3.4 which cannot compile certain
code (in https://github.com/ufz/ogs/pull/1444), which is fine on newer version or MSVC or gcc.
I tested the mentioned PR and the clang compilation issue is resolved.
> Enable travis' trusty ci-environment.

- MeshLib/MeshSubset.h
- NumLib/DOF/LocalToGlobalIndexMap.cpp
- NumLib/DOF/LocalToGlobalIndexMap.h
- ProcessLib/BoundaryCondition/BoundaryCondition.cpp
- ProcessLib/Process.cpp
- ProcessLib/ProcessOutput.cpp
When creating dof table, setting initial conditions, creating boundary conditions, and in output
currently all nodes of the mesh are involved. If the underlying mesh subsets do not consist of all nodes (e.g. only base nodes) then the mentioned algorithms do return wrong results.
Maybe there are more places with similar patterns, please tell me then.
> Use mesh subsets instead of mesh nodes

- MaterialLib/CMakeLists.txt
- MaterialLib/FractureModels/CreateLinearElasticIsotropic.cpp
- MaterialLib/FractureModels/CreateLinearElasticIsotropic.h
- MaterialLib/FractureModels/CreateMohrCoulomb.cpp
- MaterialLib/FractureModels/CreateMohrCoulomb.h
- MaterialLib/FractureModels/FractureModelBase.h
- MaterialLib/FractureModels/LinearElasticIsotropic.cpp
- MaterialLib/FractureModels/LinearElasticIsotropic.h
- MaterialLib/FractureModels/MohrCoulomb.cpp
- MaterialLib/FractureModels/MohrCoulomb.h
- MathLib/MathTools.h
- Tests/MaterialLib/TestFractureModels.cpp
This PR adds two models for fracture deformation, linear elastic and Mohr-Coulomb.
Remarks
- Mohr-Coulomb model is limited to 2D case
- Fixed-size Eigen matrix/vectors are not considered. let me know if it's really important...
> Material model for fracture deformation

- ProcessLib/BoundaryCondition/BoundaryCondition.cpp
- ProcessLib/BoundaryCondition/BoundaryCondition.h
- ProcessLib/ProcessVariable.cpp
- ProcessLib/ProcessVariable.h
In #1452, I need [a custom local assembler for Neumann boundary conditions](https://github.com/norihiro-w/ogs/blob/1b30d78beddf459bed84be64f74062c6f159b9d4/ProcessLib/SmallDeformationWithLIE/BoundaryCondition/NeumannBoundaryConditionLocalAssembler.h) .  In order to enable it, I came to a solution introducing `BoundaryConditionBuilder` class. The class can be derived and Primary variable class owns a pointer to the base class. Thus I can set a custom builder for some variables. Let me know if you have a better solution for it.
> BoundaryConditionBuilder

- NumLib/DOF/LocalToGlobalIndexMap.cpp
- NumLib/DOF/LocalToGlobalIndexMap.h
- ProcessLib/Process.cpp
- Tests/NumLib/LocalToGlobalIndexMap.cpp
- Tests/NumLib/LocalToGlobalIndexMapMultiComponent.cpp
This PR fixes a problem that `LocalToGlobalIndexMap` cannot correctly handle multiple variables & multiple variable components cases (e.g. pressure and displacement vector in HM). Important changes to the interface is that you need to pass a vector of the number of variable components to `LocalToGlobalIndexMap` constructor, if you have any variables having more than one components.
> Fix LocalToGlobalIndexMap with mutliple variables and with multiple componets

- ProcessLib/GroundwaterFlow/GroundwaterFlowFEM.h
- ProcessLib/HeatConduction/HeatConductionFEM.h
- ProcessLib/TES/TESLocalAssembler-impl.h
as titled.
in ProcessLib/GroundwaterFlow/GroundwaterFlowFEM.h 
Replaced the size of the secondary variable vector as the number of integration points
> Fix a bug in the initialization of the secondary variable

- ProcessLib/CalculateSurfaceFlux/CalculateSurfaceFlux.cpp
- ProcessLib/CalculateSurfaceFlux/MapBulkElementPoint.cpp
- ProcessLib/Process.h
Fixing the boost::optional<T const&> usage, which causes compilation error when using boost-1.61.
Second one is small safety net feature.
> Calculate surface flux; small fixes

- NumLib/DOF/LocalToGlobalIndexMap.cpp
- ProcessLib/BoundaryCondition/BoundaryCondition.cpp
Follow up of https://github.com/ufz/ogs/pull/1461 (otherwise it does not compile for me) but the changes are independent.
The loops over all nodes of mesh subsets are rewritten in the findGlobalIndices and createBoundaryCondition. The new version uses a sorted vector of nodes (or ids) for faster lookup on large meshes.
> Optimization loop over mesh subsets nodes

- scripts/cmake/test/AddTest.cmake
This allows for:
```bash
cmake ../ogs -DOGS_BUILD_UTILS=ON
make ctest
```
This will build the required executables bedore running the tests.
Fixes missing executables on clang-sanitizer Jenkins job.
> [CMake] Added dependency from ctest to its test executable.

- scripts/jenkins/docs.groovy
16.04 has a more up-to-date doxygen package and so this
fixes some non-html-ized characters in the navigation.
> [Jenkins] Run doxygen job in Ubuntu 16.04 container.

- NumLib/DOF/LocalToGlobalIndexMap.cpp
- NumLib/DOF/LocalToGlobalIndexMap.h
- Tests/NumLib/LocalToGlobalIndexMap.cpp
follow up of #1433 
Untill now, `LocalToGlobalIndexMap` assumes every DoF is distributed over all mesh elements, and creates `_rows` object storing all the DoF data for every elements. However in my application, some DoF are defined only on lower-dimension mesh element nodes (e.g. lines in 2D case), and `_rows` object stores unnecessary empty DoF data for some elements. This PR tries to avoid creating the unnecessary DoF data with the following changes
- add a constructor which can take a vector of active elements for each DoF. "Active elements" means elements which contains DoF in at least one of its nodes and should be involved in local assembly.
- add another version of `findGlobalIndices()` (`findGlobalIndicesWithElementID()`), which creates `_rows` object from an element ID. The …
> Supporting heterogeneously distributed DoF

- Applications/ApplicationsLib/ProjectData.cpp
- ProcessLib/CalculateSurfaceFlux/CalculateSurfaceFlux.cpp
- ProcessLib/CalculateSurfaceFlux/CalculateSurfaceFlux.h
- ProcessLib/GroundwaterFlow/CreateGroundwaterFlowProcess.cpp
- ProcessLib/GroundwaterFlow/CreateGroundwaterFlowProcess.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.cpp
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.h
- ProcessLib/HeatConduction/CreateHeatConductionProcess.cpp
- ProcessLib/HeatConduction/CreateHeatConductionProcess.h
- ProcessLib/HeatConduction/HeatConductionProcess.cpp
- ProcessLib/HeatConduction/HeatConductionProcess.h
- ProcessLib/Process.cpp
- ProcessLib/Process.h
- ProcessLib/SmallDeformation/CreateSmallDeformationProcess.cpp
- ProcessLib/SmallDeformation/CreateSmallDeformationProcess.h
- ProcessLib/SmallDeformation/SmallDeformationProcess.h
- ProcessLib/TES/CreateTESProcess.cpp
- ProcessLib/TES/CreateTESProcess.h
- ProcessLib/TES/TESProcess.cpp
- ProcessLib/TES/TESProcess.h
Until now the integration order was hardcoded into default value of 2 in Process class.
I introduced a new tag `<integration_order>` for each `<process>` which is parsed and propagated to the `Process` ctor.
> Integration order in project files.

- Applications/CLI/Tests.cmake
- MeshGeoToolsLib/BoundaryElementsAlongPolyline.cpp
- MeshLib/Elements/Element.h
- MeshLib/Elements/TemplateElement.h
- Tests/NumLib/LocalToGlobalIndexMapMultiComponent.cpp
In the current implementation the Neumann boundary conditions applied on second order meshes (e.g. quad8) is not working correctly.
To fix it the BoundaryElementsAlongPolylines searcher is extended for Line3 element type.
Also a MeshLib::Element::construct function is required to construct new elements polymorphically.
> Boundary element search along polylines for Line3 elements.

- ProcessLib/SmallDeformationWithLIE/LocalAssembler/SmallDeformationLocalAssemblerFracture-impl.h
- ProcessLib/SmallDeformationWithLIE/LocalAssembler/SmallDeformationLocalAssemblerFracture.h
- ProcessLib/SmallDeformationWithLIE/LocalAssembler/SmallDeformationLocalAssemblerInterface.h
- ProcessLib/SmallDeformationWithLIE/LocalAssembler/SmallDeformationLocalAssemblerMatrix-impl.h
- ProcessLib/SmallDeformationWithLIE/LocalAssembler/SmallDeformationLocalAssemblerMatrix.h
- ProcessLib/SmallDeformationWithLIE/LocalAssembler/SmallDeformationLocalAssemblerMatrixNearFracture-impl.h
- ProcessLib/SmallDeformationWithLIE/LocalAssembler/SmallDeformationLocalAssemblerMatrixNearFracture.h
part of #1452, follow up of #1475, followed by #1476. ~~Relevant commits are d472a6a and 	3cdb30d~~
This PR includes 
- SmallDeformationLocalAssemblerInterface
- SmallDeformationLocalAssembler for matrix elements, matrix elements having fracture nodes, fracture elements
There are mainly two points to be remarked
- There are three local assemblers for 1) matrix elements (quad or triangle elements) including no fracture nodes,  2) matrix elements including fracture  nodes, and 3) fracture elements (line elements). Case 1) should be identical to the assembler of the standard SD process. Case 2 involves enrichment variables (i.e. displacement jumps) in addition to displacement variables. Case 3 deals only with the enrichment variables.
- In case 2 and 3, the size of local matrix is not equal …
> [SD-LIE] Local assemblers - part 2

- Applications/CLI/Tests.cmake
- Applications/Utils/Tests.cmake
- BaseLib/DateTools.cpp
- CHANGELOG.md
- scripts/cmake/ExternalProjectEigen.cmake
- scripts/cmake/ThirdPartyLibVersions.cmake
- scripts/cmake/test/AddTest.cmake
- scripts/cmake/test/AddTestTester.cmake
- scripts/cmake/test/Test.cmake
- scripts/jenkins/msvc.groovy
- `time`-wrapper is now optional and was removed from all tests
- All tests using the `vtkdiff`-tester run on Windows
> CTests on Windows

- MathLib/LinAlg/Eigen/EigenMapTools.h
- NumLib/Extrapolation/LocalLinearLeastSquaresExtrapolator.cpp
- NumLib/Extrapolation/LocalLinearLeastSquaresExtrapolator.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.h
- ProcessLib/HeatConduction/HeatConductionProcess.h
- Tests/NumLib/TestExtrapolation.cpp
I recognized that the shape matrices N are the same for a given element with a given set of integration points.
Therefore the extrapolation matrices only need to be computed once for each (element/integration point) combination, which speeds extrapolation up by roughly a factor of 10 (the TestExtrapolation unit test with 4th integration order, release build, fixed-size shape matrices, 20^3 hex elements; time needed for extrapolation before this PR: 0.075s, afterwards: 0.0072s).
The central assumption of this PR is that the set of shape matrices is uniquely defined by the number of nodes and the number of integration points in an element.
That should work with our current element types. I'd leave any better identification method for later refactoring.
Actually, the precomputation could …
> Accelerate extrapolation

- BaseLib/reorderVector.h
- Tests/BaseLib/TestreorderVector.cpp
As tilted. Although BaseLib::quicksort can be used to reorder a vector, it changes the given index vector as well.
The application of this function is in PR #1468, the which the function re-orders several vectors with one index vector.
> Reorder vector with a set of given indices

- Applications/ApplicationsLib/ProjectData.cpp
- Applications/CLI/Tests.cmake
- NumLib/DOF/LocalToGlobalIndexMap.cpp
- ProcessLib/Process.h
- ProcessLib/SmallDeformation/SmallDeformationProcess-fwd.h
- ProcessLib/SmallDeformationWithLIE/Common/FractureProperty.h
- ProcessLib/SmallDeformationWithLIE/CreateSmallDeformationProcess.cpp
- ProcessLib/SmallDeformationWithLIE/CreateSmallDeformationProcess.h
- ProcessLib/SmallDeformationWithLIE/LocalAssembler/SmallDeformationLocalAssemblerMatrix.h
- ProcessLib/SmallDeformationWithLIE/LocalAssembler/SmallDeformationLocalAssemblerMatrixNearFracture.h
- ProcessLib/SmallDeformationWithLIE/SmallDeformationProcess-fwd.h
- ProcessLib/SmallDeformationWithLIE/SmallDeformationProcess.cpp
- ProcessLib/SmallDeformationWithLIE/SmallDeformationProcess.h
followup of #1455, #1456 and #1457
This PR adds the new process type "SMALL_DEFORMATION_WITH_LIE", which includes lower-dimensional interface elements for modeling fracture deformations. To make review easier, I would like to keep this first PR as simple as possible and focus on deformation with a single fracture cutting a domain. This is indeed enough for the DECOVALEX benchmark. Complexity can be increased later on step by step.
> [SD-LIE] Small deformation process with lower-dimensional interface elements

- Applications/FileIO/FEFLOW/FEFLOWGeoInterface.cpp
- Applications/FileIO/FEFLOW/FEFLOWMeshInterface.cpp
- Applications/FileIO/FEFLOW/FEFLOWMeshInterface.h
- Tests/FileIO_Qt/TestFEFLOWInterface.cpp
Now it is possible to read
- pure tetrehedral meshes and
- mixed element meshes (prisms, hexes and tets).
Furthermore the PR contains some very basic tests.
> Add functionality to Feflow reader

- MeshLib/Mesh.cpp
- MeshLib/Mesh.h
Current implementation of `Mesh` class assumes nodes are stored in the order: 1. base nodes, 2. nonlinear nodes. But the assumption has not been checked by ogs and it's possible a user provides a mesh with wrong node ordering.
> [Mesh] check IDs of nonlinear nodes

- Applications/CLI/Tests.cmake
- ProcessLib/SmallDeformationWithLIE/Common/MeshUtils.cpp
follow up of #1452
Current implementation supports a fracture cutting through an entire domain. This PR will extend it to enabling to have fracture tips inside of a domain. What the implementation does is simply, not to create DoFs for those tip nodes, meaning displacement jumps are zero at those nodes.
> [SD-LIE] supporting fracture tips

- Applications/Utils/CMakeLists.txt
- Applications/Utils/PostProcessing/CMakeLists.txt
- Applications/Utils/PostProcessing/postLIE.cpp
- Applications/Utils/Tests.cmake
- ProcessLib/SmallDeformationWithLIE/Common/PostUtils.cpp
- ProcessLib/SmallDeformationWithLIE/Common/PostUtils.h
This PR adds a post-processing tool for results obtained with the LIE approach. The tool reads a PVD file and process each VTU file with the following jobs:
- create a new mesh which includes duplicated fracture nodes. This is needed to compute discontinuities in displacement field and visualize it on ParaView
- compute total displacements based on regular displacements, displacement jumps, and levelset functions
> [SD-LIE] post-processing tool

- Applications/Utils/MeshEdit/CMakeLists.txt
- Applications/Utils/MeshEdit/createQuadraticeMesh.cpp
- MeshLib/Properties.cpp
- MeshLib/Properties.h
This PR adds a new CLI tool `createQuadraticMesh` for creating a quadratic order mesh based on an existing linear order mesh. At the moment, it supports only Line2 and Quad4 elements, which are converted to Line3 and Quad8. To copy MaterialIDs to the new mesh, I had to modify `MeshLib::Properties`.
> New tool: createQuadraticMesh

- Applications/CLI/Tests.cmake
as Titled.
Note: The tests use a mesh with one million hexahedra. Each  test requires at least 8.2 GB RAM. If you run them on eve via job system, you have to specify h_vmem=9G. Otherwise, you will get  an error message about std::bad_alloc.
~~Question: Can travis CI handle such tests with high RAM usage?~~
> [Test] Added two large size tests for liquid flow process

- ProcessLib/BoundaryCondition/BoundaryCondition.cpp
- ProcessLib/BoundaryCondition/BoundaryCondition.h
- ProcessLib/BoundaryCondition/DirichletBoundaryCondition.cpp
- ProcessLib/BoundaryCondition/GenericNaturalBoundaryCondition-impl.h
- ProcessLib/BoundaryCondition/GenericNaturalBoundaryCondition.h
- ProcessLib/BoundaryCondition/NeumannBoundaryCondition.cpp
- ProcessLib/BoundaryCondition/NeumannBoundaryCondition.h
- ProcessLib/BoundaryCondition/RobinBoundaryCondition.cpp
- ProcessLib/BoundaryCondition/RobinBoundaryCondition.h
- ProcessLib/CalculateSurfaceFlux/CalculateSurfaceFlux.cpp
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.cpp
- ProcessLib/HeatConduction/HeatConductionProcess.cpp
- ProcessLib/LiquidFlow/LiquidFlowProcess.cpp
- ProcessLib/ProcessVariable.cpp
- ProcessLib/ProcessVariable.h
- ProcessLib/RichardsFlow/RichardsFlowProcess.cpp
- ProcessLib/SmallDeformationWithLIE/BoundaryCondition/BoundaryConditionBuilder.cpp
- ProcessLib/SmallDeformationWithLIE/BoundaryCondition/BoundaryConditionBuilder.h
- ProcessLib/SmallDeformationWithLIE/BoundaryCondition/GenericNaturalBoundaryCondition-impl.h
- ProcessLib/SmallDeformationWithLIE/BoundaryCondition/GenericNaturalBoundaryCondition.h
- ProcessLib/SmallDeformationWithLIE/BoundaryCondition/NeumannBoundaryCondition.cpp
- ProcessLib/SmallDeformationWithLIE/BoundaryCondition/NeumannBoundaryCondition.h
- ProcessLib/TES/TESProcess.cpp
- ProcessLib/Utils/CreateLocalAssemblers.h
- ProcessLib/Utils/LocalDataInitializer.h
- Tests/NumLib/TestExtrapolation.cpp
Until now, the shape function order is decided by the order of the given mesh. This PR enables users to specify the shape function order in a config file, which can be different from the order of the given mesh, though appropriate mesh (e.g. 2nd order mesh for use of linear or quadratic order shape functions) should be provided. 
This PR is extracted & modified after Dima's HM branch and is needed for implementing HM and "HM with LIE" processes, which use linear order for pressure and quadratic order for displacements. Major changes are
- add the shape function order to ProcessVariable class
- create local assemblers with the order provided in ProcessVariable
- support the order in BC handling
- pass the shape function order to local assembler creations in every process classes
Remarks
- …
> Add the shape function order to ProcessVariable class

- Tests/NumLib/CoordinatesMappingTestData/TestLine3.h
- Tests/NumLib/TestCoordinatesMapping.cpp
The tests of coordinates mapping for quadratic order elements/shape functions are not all implemented.
This one is mainly a copy of the TestLine2 with an additional node (the origin 0,0,0) for the middle node of the line3 element.
In principle only the expected values `nat_exp_N`, `nat_exp_dNdr`, and `ir_exp_dNdx` have to be checked.
> Test Line3 coordinates mapping

- ProcessLib/BoundaryCondition/DirichletBoundaryCondition.cpp
This optimization is not working correctly with time-dependent boundary
conditions and result in a "step" of the values for the second time step.
This is required for upcoming HM Process PR. The shown plots are from the HM test case with and without the optimization. The boundary condition is a constant parameter scaled with curve.
> [PL] DirichletBC: Comment out the already computed

- Applications/Utils/MeshEdit/createQuadraticeMesh.cpp
I forgot to specify the number of base nodes in createQuadraticMesh, though it doesn't change the result.
> minor fix in createQuadraticMesh

- Applications/CLI/ogs.cpp
- CMakeLists.txt
- scripts/cmake/ProjectSetup.cmake
This PR suggests  
- to change the default compilation logog level in release builds from info to debug
- to change the default runtime logog level in release builds from all to info 
IMO the default setting should be configured for normal users who download the OGS executable from the website. With current setting, users cannot see debug messages even if they set the runtime logog level with `-l debug`. This also helps us/developers to support users because we can ask them to run ogs with debug level to get detailed logs and we don't need to run it by ourselves (of course, sometimes it's not enough).
> [CMake] set the default OGS_LOG_LEVEL to debug also in release build

- Jenkinsfile
- scripts/jenkins/deploy.groovy
As we now have a publicly accessible Jenkins we can now host OGS binaries directly on Jenkins (before they were hosted on Amazon S3). This will also make the Deploy-jobs obsolete.
I also added useful output of timestamps in the Jenkins build log.
TODO after merge:
> [Jenkins] Keep build when commit is tag 

- Applications/CLI/ogs.cpp
as titled. This is helpful for those who saves/forwards stadard output to a file and wants to trace real-time output from ogs.
> [CLI] add --unbuffered-std-out option to deactivate buffer for cout

- NumLib/ODESolver/ConvergenceCriterionPerComponentResidual.cpp
- NumLib/ODESolver/ConvergenceCriterionPerComponentResidual.h
- NumLib/ODESolver/ConvergenceCriterionResidual.cpp
- NumLib/ODESolver/ConvergenceCriterionResidual.h
With this PR, I want to print norms of delta x in Newton-Raphson iterations although only residual is used for convergence checks. This helps to understand why the iteration is not converging, e.g. the criteria for residual is too strict.
> [Nonlinear] print norms of delta x in ConvergenceCriterionPerComponentResidual

- Applications/CLI/Tests.cmake
- Applications/Utils/PostProcessing/postLIE.cpp
- BaseLib/makeVectorUnique.h
- ProcessLib/SmallDeformationWithLIE/Common/FractureProperty.h
- ProcessLib/SmallDeformationWithLIE/Common/MeshUtils.cpp
- ProcessLib/SmallDeformationWithLIE/Common/MeshUtils.h
- ProcessLib/SmallDeformationWithLIE/Common/PostUtils.cpp
- ProcessLib/SmallDeformationWithLIE/Common/PostUtils.h
- ProcessLib/SmallDeformationWithLIE/CreateSmallDeformationProcess.cpp
- ProcessLib/SmallDeformationWithLIE/LocalAssembler/SmallDeformationLocalAssemblerFracture-impl.h
- ProcessLib/SmallDeformationWithLIE/LocalAssembler/SmallDeformationLocalAssemblerFracture.h
- ProcessLib/SmallDeformationWithLIE/LocalAssembler/SmallDeformationLocalAssemblerMatrixNearFracture-impl.h
- ProcessLib/SmallDeformationWithLIE/LocalAssembler/SmallDeformationLocalAssemblerMatrixNearFracture.h
- ProcessLib/SmallDeformationWithLIE/SmallDeformationProcess.cpp
- ProcessLib/SmallDeformationWithLIE/SmallDeformationProcess.h
- ProcessLib/SmallDeformationWithLIE/SmallDeformationProcessData.h
This PR introduces a support of multiple non-intersecting fractures in SD-LIE process. Major changes are
- extend `getFractureMatrixDataInMesh()` to looking for multiple fracture groups having distinct material IDs
- extend the local assembler for matrix near fractures. Now the displacement function is given as `u(x) =  N(x) {u} + sum_i [phi_i(x) N(x) {g_i}]` where `phi_i(x)` is the levelest function, `g_i` is  the nodal enrichment values for `i` th fracture.
- extend the post processing tool
> [SD-LIE] Multiple fractures

- CMakeLists.txt
- MathLib/CMakeLists.txt
- MathLib/LinAlg/Eigen/EigenLinearSolver.cpp
- MathLib/LinAlg/Eigen/EigenOption.cpp
- MathLib/LinAlg/Eigen/EigenOption.h
- scripts/cmake/Find.cmake
- scripts/cmake/cmake/FindMKL.cmake
Credit goes to @chleh, because it's based on his branch (see #1175) and enables to use Pardiso solver with Eigen interface. To use it, one needs to set CMake as `-DOGS_USE_EIGEN=ON -DOGS_USE_MKL=ON -DMKL_DIR=(a path to MKL root directory)`. In a config file, you can set `PardisoLU` as a solver type.
@chleh Let me know if I miss something from your branch.
> support Pardiso in Eigen

- MeshLib/Mesh.cpp
- MeshLib/Mesh.h
fix #1495. The check doesn't work if the number of base nodes is provided to a constructor, which is the case in VtuInterface.
> [Mesh] fix the nonlinear node ID check

- CMakeLists.txt
- MathLib/LinAlg/Eigen/EigenLinearSolver.cpp
- MathLib/LinAlg/Eigen/EigenOption.cpp
- MathLib/LinAlg/Eigen/EigenOption.h
This PR introduces
- add `OGS_USE_EIGEN_UNSUPPORTED` CMake option (default is ON) to support unsupported modules in Eigen. If this option is ON, the followings become available:
- support scaling of a linear system before solve. `<scaling>1</scaling>` should be specified under `<eigen>` tag in a config file.
- support GMRES solver type
> support scaling and GMRES in Eigen linear solvers

- Applications/Utils/MeshEdit/NodeReordering.cpp
- BaseLib/makeVectorUnique.h
This PR adds the method 3 to NodeReordering tool to correct ordering of nonlinear nodes. In a nonlinear mesh, all the nonlinear nodes should be stored after the base nodes.
> extend NodeReordering to correct ordering of nonlinear nodes

- Applications/CLI/Tests.cmake
- ProcessLib/GroundwaterFlow/GroundwaterFlowFEM.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.cpp
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.h
- ProcessLib/HeatConduction/HeatConductionFEM.h
- ProcessLib/HeatConduction/HeatConductionProcess.cpp
- ProcessLib/HeatConduction/HeatConductionProcess.h
- ProcessLib/LiquidFlow/LiquidFlowLocalAssembler-impl.h
- ProcessLib/LiquidFlow/LiquidFlowLocalAssembler.h
- ProcessLib/LiquidFlow/LiquidFlowProcess.cpp
- ProcessLib/LiquidFlow/LiquidFlowProcess.h
- ProcessLib/LocalAssemblerInterface.cpp
- ProcessLib/LocalAssemblerInterface.h
- ProcessLib/Process.cpp
- ProcessLib/Process.h
- ProcessLib/UncoupledProcessesTimeLoop.cpp
Follow up PR ufz/ogs#1468, this PR corrected the calculations of  heat flux and flow velocity
by
1 introducing a member of computeSecondaryVariable to class Process.
2. calling the new member after UncoupledProcessesTimeLoop
This is the 1st PR for the staggered scheme.
> Added computeSecondaryVariable to class Process

- Applications/Utils/MeshEdit/createQuadraticeMesh.cpp
- MeshLib/ElementStatus.cpp
- MeshLib/Elements/Element.cpp
- MeshLib/Mesh.cpp
- MeshLib/MeshEditing/DuplicateMeshComponents.cpp
- MeshLib/MeshGenerators/QuadraticeMeshGenerator.cpp
- MeshLib/MeshGenerators/QuadraticeMeshGenerator.h
- MeshLib/MeshSearch/NodeSearch.cpp
- Tests/MeshLib/TestQuadraticMesh.cpp
I've just realized some Mesh routines ignore nonlinear nodes, e.g. in constructing a list of connected elements to a node. This PR tries to fix them by using `getNumberOfNodes()` instead of `getNumberOfBaseNodes()`, except for `Mesh::setNodesConnectedByEdges()` where special care is required for nonlinear case. I haven't looked into classes used only in utility.
> [Mesh] fix incorrect use of getNumberOfBaseNodes()

- Applications/ApplicationsLib/ProjectData.cpp
- Applications/CLI/Tests.cmake
- Documentation/ProjectFile/process/t_HYDRO_MECHANICS_biot_coefficient.md
- Documentation/ProjectFile/process/t_HYDRO_MECHANICS_constitutive_relation.md
- Documentation/ProjectFile/process/t_HYDRO_MECHANICS_fluid_density.md
- Documentation/ProjectFile/process/t_HYDRO_MECHANICS_fluid_viscosity.md
- Documentation/ProjectFile/process/t_HYDRO_MECHANICS_intrinsic_permeability.md
- Documentation/ProjectFile/process/t_HYDRO_MECHANICS_porosity.md
- Documentation/ProjectFile/process/t_HYDRO_MECHANICS_solid_density.md
- Documentation/ProjectFile/process/t_HYDRO_MECHANICS_specific_body_force.md
- Documentation/ProjectFile/process/t_HYDRO_MECHANICS_storage_coefficient.md
- MeshLib/Elements/Utils.h
- NumLib/Fem/FiniteElement/LowerDimShapeTable.h
- ProcessLib/CMakeLists.txt
- ProcessLib/HydroMechanics/CreateHydroMechanicsProcess.cpp
- ProcessLib/HydroMechanics/CreateHydroMechanicsProcess.h
- ProcessLib/HydroMechanics/CreateLocalAssemblers.h
- ProcessLib/HydroMechanics/HydroMechanicsFEM.h
- ProcessLib/HydroMechanics/HydroMechanicsProcess-fwd.h
- ProcessLib/HydroMechanics/HydroMechanicsProcess.cpp
- ProcessLib/HydroMechanics/HydroMechanicsProcess.h
- ProcessLib/HydroMechanics/HydroMechanicsProcessData.h
- ProcessLib/HydroMechanics/LocalDataInitializer.h
Two other changes outside 'ProcessLib/HM' are:
- Move `Process::_process_variables` into protected section; direct access in the HMProcess is needed for creating specialized dof-table.
- Add `getBaseNodes()` is added to 'MeshLib/Elements/Utils.h'; it's used in creation of the mesh subset for the pressure variable which is not using the quadratic elements' nodes.
Theory questions to @nagelt.
A confined compression test is included.
TODO:
- Documentation:
- doxygen
- conifg parameters
- docs.opengeosys.org/Selected Benchmarks.
> HM process.

- ProcessLib/HydroMechanics/HydroMechanicsProcessData.h
- ProcessLib/SmallDeformation/SmallDeformationFEM.h
- ProcessLib/SmallDeformation/SmallDeformationProcessData.h
fixes an uninitialized warning
A similar change would be sensible for SmallDeformationProcessData. Furthermore there the naming of members is inconsistent: _material, t, dt.
> Tiny change

- Applications/CLI/Tests.cmake
Just checking for now.
Replace expected vtu based on a new grid with reordered nodes. -- no difference.
Relaxed the absolute tolerance to 1e-15 for displacement field comparison.
> Fix failing Mechanics_SDL_square_1e2_quad8_traction_topBC

- Applications/ApplicationsLib/ProjectData.cpp
- ProcessLib/LIE/SmallDeformation/CreateSmallDeformationProcess.cpp
- ProcessLib/Parameter/ConstantParameter.cpp
- ProcessLib/Parameter/ConstantParameter.h
- ProcessLib/Parameter/CurveScaledParameter.cpp
- ProcessLib/Parameter/CurveScaledParameter.h
- ProcessLib/Parameter/GroupBasedParameter.cpp
- ProcessLib/Parameter/GroupBasedParameter.h
- ProcessLib/Parameter/MeshElementParameter.cpp
- ProcessLib/Parameter/MeshElementParameter.h
- ProcessLib/Parameter/MeshNodeParameter.cpp
- ProcessLib/Parameter/MeshNodeParameter.h
- ProcessLib/Parameter/Parameter.cpp
- ProcessLib/Parameter/Parameter.h
- Tests/MaterialLib/TestFractureModels.cpp
- Tests/ProcessLib/TestParameter.cpp
... since it is rather likely that users mess up their input files.
- ProjectData now stores parameters and process variables in a std::map
- ParameterBase::name is const now
I think it's best to review commit-wise since there are some commits with search & replace changes.
Note, however, that the "dependent changes for SD with LIE" are a tiny bit more than search & replace.
> Assert unique parameter and process variable names

- MaterialLib/FractureModels/FractureIdentity2.cpp
- MaterialLib/FractureModels/FractureIdentity2.h
- NumLib/Fem/FiniteElement/LowerDimShapeTable.h
- ProcessLib/LIE/Common/FractureProperty.h
- ProcessLib/LIE/Common/MeshUtils.cpp
a part of #1535
This PR includes changes required for implementing HM process with the LIE approach. Please check each commit
> LIE/HM part 1: prerequisite

- MeshLib/Elements/Utils.h
- NumLib/DOF/ComputeSparsityPattern.cpp
- Tests/NumLib/TestSparsityPattern.cpp
`computeSparsityPatternNonPETSc()` is computing a wrong sparsity pattern if a process uses multiple variables with linear and quadratic order nodes, e.g. Hydromechanics.
> Fix computing sparsity pattern

- ProcessLib/LIE/SmallDeformation/LocalAssembler/LocalDataInitializer.h
- ProcessLib/SmallDeformation/LocalDataInitializer.h
- ProcessLib/Utils/LocalDataInitializer.h
As of now the local assemblers were instantiated for example for Hex8 and GlobalDim=1, 2, 3, but the dimensions 1 and 2 do not make any sense. These are excluded from the instantiation.
For Line3 still all GlobalDims are used.
See for example output of `nm -C bin/ogs | grep Hex8 | grep GroundwaterFlow::LocalAssemblerData | grep assemble`
There exist a computer s.t. the compilation took before and after (in Release, with fixed size matrices, clang-4.0 and LTO):
CCACHE_DISABLE=1 make -j5  1135.72s user 31.24s system 400% cpu 4:51.06 total
CCACHE_DISABLE=1 make -j5  1047.01s user 28.57s system 413% cpu 4:20.00 total
so around 8% less cpu time.
> Reduce number of instantiated local asms

- NumLib/DOF/LocalToGlobalIndexMap.cpp
This PR suggests speeding up `LocalToGlobalIndexMap` construction by using `unordered_map` in `LocalToGlobalIndexMap::findGlobalIndices()`.
> speedup LocalToGlobalIndexMap construction

- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerFracture-impl.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerFracture.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerInterface.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrix-impl.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrix.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrixNearFracture-impl.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrixNearFracture.h
a part of #1535, depends on #1538
This PR focuses on local assemblers of LIE/HM for matrix elements, matrix near fracture elements, and fracture elements. 
Remarks
- `HydroMechanicsLocalAssemblerInterface` is the base class for all the three assemblers. The base class calls `assembleWithJacobianConcrete()` and the derived classes implement the virtual function.
- Major difference in the governing equations from the HydroMechanics process is the additional flow equation for fractures, which is `b S p^dot + alpha b^dot + div(-b k/mu grad(head))` where `b` is fracture aperture and `k=b^2/12`.
> LIE/HM part 3: Local assembler implementations

- Applications/Utils/MeshEdit/CMakeLists.txt
- Applications/Utils/MeshEdit/convertToLinearMesh.cpp
- MeshLib/MeshEditing/ConvertToLinearMesh.cpp
- MeshLib/MeshEditing/ConvertToLinearMesh.h
This PR adds the new tool `convertToLinearMesh` which will convert a nonlinear mesh to a linear mesh while keeping property values for base nodes.
> New tool: convertToLinearMesh

- Applications/ApplicationsLib/ProjectData.cpp
- Applications/CLI/Tests.cmake
- ProcessLib/LIE/HydroMechanics/CreateHydroMechanicsProcess.cpp
- ProcessLib/LIE/HydroMechanics/CreateHydroMechanicsProcess.h
- ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess-fwd.h
- ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.cpp
- ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.h
a part of #1535, depends on #1540
This PR adds implementations of the process class and a test for a single fracture case.
TODO
> LIE/HM part 5: Process implementation

- NumLib/DOF/LocalToGlobalIndexMap.cpp
it seems `_rows.conservativeResize()` isn't working as expected on Windows or with MSVC. I observed entries in `_rows` are overwritten after the call.  `_rows` stores `std::vector<GlobalIndex>` in `Eigen::Matrix`, and maybe `conservativeResize()` cannot work well with this data type on MSVC.  
Instead of resizing each time, I changed it to compute the size beforehand and resize it only once.
> [Num/DOF] don't use conservative resize in DoF table 

- MaterialLib/CMakeLists.txt
- MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/CreateRelativePermeabilityModel.cpp
- MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/CreateRelativePermeabilityModel.h
- MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/NonWettingPhaseBrookCoreyOilGas.cpp
- MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/NonWettingPhaseBrookCoreyOilGas.h
- MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/NonWettingPhaseVanGenuchten.cpp
- MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/NonWettingPhaseVanGenuchten.h
- MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/RelativePermeability.h
- MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/RelativePermeabilityCurve.h
- MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/ReletivePermeabilityCurve.h
- MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/WettingPhaseBrookCoreyOilGas.cpp
- MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/WettingPhaseBrookCoreyOilGas.h
- MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/WettingPhaseVanGenuchten.cpp
- MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/WettingPhaseVanGenuchten.h
- Tests/MaterialLib/TestRelativePermeabilityModel.cpp
This PR presents:
- base class for relative permeability models
- class for WettingPhaseVanGenuchten model
- class for NonWettingPhaseVanGenuchten model
- class for WettingPhaseBrookCoreyOilGas model
- class for NonWettingPhaseBrookCoreyOilGas model
- class for curve type model
- unit tests for these classes.
> Relative permeability model

- MaterialLib/FractureModels/FractureIdentity2.h
Avoids a warning by clang-3.9, details in the commit message.
I'm not sure if this is the correct way to fix it.
> [Mat] FractureModel. Add explicit tpl declaration.

- scripts/doc/linked-xml-file.py
the mismatched tags are easier to find this way ;)
> When XML parse error occures, print good message.

- Applications/Utils/MeshEdit/CMakeLists.txt
- Applications/Utils/PostProcessing/CMakeLists.txt
- Applications/Utils/PostProcessing/postLIE.cpp
- ProcessLib/LIE/Common/PostUtils.cpp
follow up of #1554 
Besides ~~a bugfix~~ two bugfixes, this PR extends the post-processing tool `postLIE` to
- converting the original quadratic mesh data to the linear mesh data
- supporting VTU files in command line arguments
> Extend postLIE

- scripts/doc/linked-xml-file.py
Problem reported by @endJunction .
It currently occurs e.g. in the `darcy_gravity.g` tag in https://doxygen.opengeosys.org/ogs_ctest_prj__Parabolic__LiquidFlow__AxiSymTheis__axisym_theis__prj.html
(the blank line) 
Reason for the error as far as I understand it:
The formatted XML file content is (implicitly) in the `\brief` section of `\page ogs_ctest_prj__Parabolic__LiquidFlow__AxiSymTheis__axisym_theis__prj axisym_theis.prj`.
Somehow the sequence `.<` (from the tag `<g>0.</g>`) is interpreted as "end of first sentence", i.e., also as "end of brief section". Therefore Doxygen generates an empty line at that point.
Note: In contrast strings like `1.e-6` or `mesh.vtu` don't confuse Doxygen.
Inserting `\parblock` fixed the issue on my system.
> Docu: Fix linked prj files containing dots.

- Documentation/Doxyfile.in
- scripts/jenkins/docs.groovy
- Fixed Mathjax (formulas)
- Changed Jenkins to mark build as unstable (yellow) when there are new Doxygen warnings
> Doxygen Mathjax fix and warnings build status

- MaterialLib/PorousMedium/UnsaturatedProperty/CapillaryPressure/BrookCoreyCapillaryPressureSaturation.cpp
- MaterialLib/PorousMedium/UnsaturatedProperty/CapillaryPressure/BrookCoreyCapillaryPressureSaturation.h
- MaterialLib/PorousMedium/UnsaturatedProperty/CapillaryPressure/CapillaryPressureSaturation.h
- MaterialLib/PorousMedium/UnsaturatedProperty/CapillaryPressure/CapillaryPressureSaturationCurve.h
- MaterialLib/PorousMedium/UnsaturatedProperty/CapillaryPressure/CreateCapillaryPressureModel.cpp
- MaterialLib/PorousMedium/UnsaturatedProperty/CapillaryPressure/VanGenuchtenCapillaryPressureSaturation.cpp
- MaterialLib/PorousMedium/UnsaturatedProperty/CapillaryPressure/VanGenuchtenCapillaryPressureSaturation.h
- Tests/MaterialLib/TestCapillaryPressureSaturationModel.cpp
This PR:
1 adds  a model of Curve for capillary pressure saturation,
2. changes some member names starting with an underscore and followed by a capital letter,
3. moves common members of capillary pressure saturation classes to their base class,
4. corrects some documentations.
> Add a model of Curve for capillary pressure saturation

- MaterialLib/Fluid/Density/IdealGasLaw.h
- MaterialLib/Fluid/Density/LiquidDensity.h
- MaterialLib/Fluid/FluidProperty.h
- MaterialLib/Fluid/Viscosity/LinearPressureDependentViscosity.h
- MaterialLib/TwoPhaseModels/TwoPhaseFlowWithPPMaterialProperties.cpp
- ProcessLib/LiquidFlow/LiquidFlowMaterialProperties.cpp
- Tests/MaterialLib/TestFluidDensity.cpp
- Tests/MaterialLib/TestFluidViscosity.cpp
Removed MaterialLib::Fluid::FluidProperty::pg because it is unnecessary to distinguish the type of pressure, which is one of variables of  fluid property models.
This change is driven by the implementation of the IAPWS fluid properties, which will be in another PR.
> Removed one unused variable type for the fluid property

- Documentation/ProjectFile/material/porous_medium/relative_permeability/Curve/c_Curve.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/Curve/curve/i_curve.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/Curve/curve/t_coords.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/Curve/curve/t_values.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/NonWettingPhaseBrookCoreyOilGas/c_NonWettingPhaseBrookCoreyOilGas.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/NonWettingPhaseBrookCoreyOilGas/t_krel_min.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/NonWettingPhaseBrookCoreyOilGas/t_m.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/NonWettingPhaseBrookCoreyOilGas/t_smax.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/NonWettingPhaseBrookCoreyOilGas/t_sr.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/NonWettingPhaseVanGenuchten/c_NonWettingPhaseVanGenuchten.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/NonWettingPhaseVanGenuchten/t_krel_min.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/NonWettingPhaseVanGenuchten/t_m.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/NonWettingPhaseVanGenuchten/t_smax.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/NonWettingPhaseVanGenuchten/t_sr.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/WettingPhaseBrookCoreyOilGas/c_WettingPhaseBrookCoreyOilGas.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/WettingPhaseBrookCoreyOilGas/t_krel_min.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/WettingPhaseBrookCoreyOilGas/t_m.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/WettingPhaseBrookCoreyOilGas/t_smax.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/WettingPhaseBrookCoreyOilGas/t_sr.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/WettingPhaseVanGenuchten/c_WettingPhaseVanGenuchten.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/WettingPhaseVanGenuchten/t_krel_min.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/WettingPhaseVanGenuchten/t_m.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/WettingPhaseVanGenuchten/t_smax.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/WettingPhaseVanGenuchten/t_sr.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/t_type.md
- MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/CreateRelativePermeabilityModel.cpp
- MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/RelativePermeabilityCurve.h
This PR
1.  replaces the local curve parsing of curve input of relative permeability with function of  createPiecewiseLinearCurve,
2. adds documentattions of input keywords of relative permeability models.
> Documentation of input keywords of relative permeability models

- Applications/DataExplorer/DataView/DiagramView/DiagramPrefsDialog.h
- CHANGELOG.md
- MaterialLib/FractureModels/MohrCoulomb.h
- MaterialLib/SolidModels/Ehlers-impl.h
- scripts/jenkins/docs.groovy
[12 warnings left ...](https://jenkins.opengeosys.org/job/OGS-6/job/bilke/job/doxygen-parser/5/warnings15Result/)
There were no warnings concerning max graph ...
> [Jenkins] Ignore some warnings in Docs job.

- Documentation/ProjectFile/material/fluid/viscosity/Vogels/t_CH4.md
- Documentation/ProjectFile/material/fluid/viscosity/Vogels/t_CO2.md
- Documentation/ProjectFile/material/fluid/viscosity/Vogels/t_Water.md
- Documentation/ProjectFile/material/porous_medium/porosity/t_Constant_value.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/Curve/curve/t_coords.md
- Documentation/ProjectFile/material/porous_medium/relative_permeability/Curve/curve/t_values.md
- Documentation/ProjectFile/material/porous_medium/storage/constant/i_constant.md
- Documentation/ProjectFile/material/porous_medium/storage/constant/t_value.md
These are files which are not referenced from the source code via any of the `\ogs_file_param{}` commands. Usually leftovers after renames and moves. Though it can indicate a wrong .md file name.
> Remove documentation pages not referenced in code.

- Documentation/ProjectFile/i_ProjectFile.md
- Documentation/ProjectFile/prj/time_loop/processes/process/convergence_criterion/PerComponentDeltaX/t_norm_type.md
- Documentation/ProjectFile/prj/time_loop/processes/process/convergence_criterion/PerComponentDeltaX/t_reltols.md
- Documentation/ProjectFile/prj/time_loop/processes/process/convergence_criterion/PerComponentResidual/t_norm_type.md
- Documentation/ProjectFile/prj/time_loop/processes/process/convergence_criterion/PerComponentResidual/t_reltols.md
- Documentation/ProjectFile/prj/time_loop/processes/process/convergence_criterion/Residual/t_norm_type.md
- scripts/doc/append-xml-tags.py
- scripts/doc/check-project-params.py
- scripts/doc/linked-xml-file.py
- scripts/doc/normalize-param-cache.py
- scripts/jenkins/docs.groovy
This are few final fixes for the documentation of the input files.
The ignore pattern for ogs_file_param is now removed from the doxygen warning/error parser, so proper documentation of the input parameters is obligatory now.
> Documentation

- Applications/CLI/Tests.cmake
Ehlers material model reduces to Drucker-Prager model as verification of the implementation;
Compare the variations of the stress states with Drucker-Prager yield function.
> Drucker-Prager test based on reduction of Ehlers material model

- MaterialLib/SolidModels/Ehlers-impl.h
- MaterialLib/SolidModels/Lubby2-impl.h
- NumLib/NewtonRaphson.h
- Tests/NumLib/NewtonRaphson.cpp
As titled, the local NewtonRaphson is moved from MaterialLib/SolidModels to NumLib in order for further reusing. 
This class provides a basic NewtonRaphson routine to handle the nonlinear constitutive relationships existing in the local problem. After being moved to NumLib , it can be reused by other processes, e.g the two-phase multicomponent process which I am working on now.
(p.s. Some of the changes are caused by running clang-format)
> Move local NewtonRaphson from the Material\Solid to NumLib

- Applications/CLI/Tests.cmake
As titled.  The unconfined compression is divided into two steps. In early time, the drainage process is ongoing and the displacement behaviour is related to water pressure and solid properties. In late time, the drainage process is finished and the displacement of the porous media is only a result of solid properties. 
Todo:
> add the unconfined compression test compared with analytical solution

- Jenkinsfile
Corresponds to a tag at https://gitlab.opengeosys.org/bilke/jenkins-library/tags.
This allows to make and test breaking changes in the library without affecting other branches / forks / PRs.
> [Jenkins] Pipeline library is now pinned to a specific version.

- Documentation/ProjectFile/material/fluid/density/t_type.md
- MaterialLib/CMakeLists.txt
- MaterialLib/Fluid/Density/WaterDensityIAPWSIF97Region1.h
- MaterialLib/Fluid/Density/createFluidDensityModel.cpp
- MaterialLib/Fluid/GibbsFreeEnergy/DimensionLessGibbsFreeEnergyRegion1.cpp
- MaterialLib/Fluid/GibbsFreeEnergy/DimensionLessGibbsFreeEnergyRegion1.h
- Tests/MaterialLib/TestDimensionLessGibbsFreeEnergy.cpp
- Tests/MaterialLib/TestFluidDensity.cpp
Based on  IAPWS Industrial Formulation 1997, this PR presents classes of:
- dimensionless Gibbs free energy (region1), which is used to calculate density and heat capacity etc.
- density model.
- unit tests of the presented classes.
> Fluid density model based on IAPWS Industrial Formulation 1997

- ProcessLib/CMakeLists.txt
Fixes previous merge https://github.com/ufz/ogs/pull/1619 : the actual ctests were not added, because cmake's `add_subdirectory` is not recursive.
> [PL] Add cmake files for ctests.

- Jenkinsfile
> [Jenkins] Use checkoutWithTag to fetch tags correctly.

- ProcessLib/HydroMechanics/HydroMechanicsFEM.h
The unconfined compression test is axsymmetric. But the integralMeasure term was missed in HM process and influence the axsymmetric result. The missing term is added in this PR and the unconfined compression test works well now.
> fix the error in HM unconfined test

- scripts/jenkins/docs.groovy
-> no ssh setup required on executing node.
> [Jenkins] Deploy doxygen with ssh-agent.

- CHANGELOG.md
- CMakeLists.txt
The performance differences between static and dynamic matrices are not obvious and some accidently use dynamic matrices when doing performance measurements (using release compilation modes).
> [CMake] OGS_EIGEN_DYNAMIC_SHAPE_MATRICES defaults to OFF on Release.

- MaterialLib/SolidModels/CreateLubby2.h
- MaterialLib/SolidModels/Ehlers-impl.h
- MaterialLib/SolidModels/Ehlers.h
- MaterialLib/SolidModels/Lubby2-impl.h
- MaterialLib/SolidModels/Lubby2.h
See second commit's message for some details.
Small restructuring: Moving the nested class MaterialProperties outside (Lubby2MaterialProperties) and introducing a new class to save temporary variables.
> Fixing Lubby2 initialization of local variables.

- scripts/jenkins/gcc-tests-large.groovy
- scripts/jenkins/gcc.groovy
- Regular gcc job uses Eigen 3.2.8 (downloaded locally)
- [tests-large gcc job](https://jenkins.opengeosys.org/job/OGS-6/job/gcc-tests-large/) uses Eigen 3.3 (system installed package, job runs nightly)
> Tests large and Eigen 3.3

- ProcessLib/HT/CreatePorousMediaProperties.cpp
The vector 'material_ids' was not created properly which caused a crash
> [PL/HT] Fix bug in createPorousMediaProperties.

- Applications/FileIO/FEFLOW/FEFLOWMeshInterface.cpp
- Applications/FileIO/Gmsh/GMSHAdaptiveMeshDensity.cpp
- NumLib/TimeStepping/Algorithms/FixedTimeStepping.cpp
- ProcessLib/TES/TESLocalAssemblerInner-impl.h
- Tests/NumLib/TestComponentNorms.cpp
Fixes #973 
Warnings as reported by [Jenkins](https://jenkins.opengeosys.org/job/ufz/job/ogs/job/master/lastSuccessfulBuild/parsed_console/) in the ogs code were resolved.
One warning about "C4180	qualifier applied to function type has no meaning; ignored (compiling source file C:\Projects\ogs\Tests\MathLib\TestNonlinear1D.cpp)" is incorrect in my opinion because the `Function` type could be a pointer which needs a const qualifier in this case.
> Fix Visual Studio warnings

- MeshLib/Location.cpp
- MeshLib/Location.h
- MeshLib/MeshGenerators/VtkMeshConverter.cpp
- MeshLib/Vtk/VtkMappedMeshSource.cpp
- MeshLib/Vtk/VtkMappedMeshSource.h
- Tests/MeshLib/MeshProperties.cpp
- Tests/MeshLib/TestVtkMappedMeshSource.cpp
This is a preparation to output of secondary variables, especially of integration-point-data and of internal material model states.
In general any data (available to the local assemblers) can be written as a MeshLib::Property on the new `MeshItemType` `IntegrationPoint`. (Maybe IntegrationPoint is not a good name though.)
The mesh properties stored as `IntegrationPoint` type are written to vtk's FieldData.
Tests for creating/reading the mesh property and a vtk import/export *i.e.* roundtrip are implemented.
> Add FieldData to mesh properties

- MathLib/LinAlg/Eigen/EigenMatrix.h
Under certain circumstances the sparsity pattern will be destroyed and
adding/setting values would then result in an expensive reallocation.
Assume that in the first global iteration only one half of the values is
set to non-zero. Before the linear solver is called the sparse matrix is
compressed thus reducing the allocated space in each row. In the
subsequent iterations, which might add or set the other half of the
matrix values reallocations would be necessary.
~~I'll update the PR with explicit performance measurements later today. For a specific test (phase-field) the speedup is around 6.5 times (for every time-step). Of course there is some overhead for other processes because of additional `coeffRef() = value` calls; I'll quantify that later today.~~
See detailed benchmark details …
> [MaL] EigenMatrix: set/add values even if 0.

- ProcessLib/BoundaryCondition/GenericNaturalBoundaryConditionLocalAssembler.h
- ProcessLib/BoundaryCondition/NeumannBoundaryConditionLocalAssembler.h
- ProcessLib/BoundaryCondition/RobinBoundaryConditionLocalAssembler.h
- ProcessLib/CalculateSurfaceFlux/CalculateSurfaceFluxLocalAssembler.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowFEM.h
- ProcessLib/HT/HTFEM.h
- ProcessLib/HeatConduction/HeatConductionFEM.h
- ProcessLib/HydroMechanics/HydroMechanicsFEM.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerFracture.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrix.h
- ProcessLib/LIE/SmallDeformation/LocalAssembler/SecondaryData.h
- ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerFracture.h
- ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerMatrix.h
- ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerMatrixNearFracture.h
- ProcessLib/LiquidFlow/LiquidFlowLocalAssembler.h
- ProcessLib/RichardsFlow/RichardsFlowFEM.h
- ProcessLib/SmallDeformation/SmallDeformationFEM.h
- ProcessLib/TES/TESLocalAssembler.h
- ProcessLib/TwoPhaseFlowWithPP/TwoPhaseFlowWithPPLocalAssembler.h
- ProcessLib/TwoPhaseFlowWithPrho/TwoPhaseFlowWithPrhoLocalAssembler.h
- ProcessLib/Utils/InitShapeMatrices.h
- Tests/NumLib/TestExtrapolation.cpp
- Tests/NumLib/TestFe.cpp
- conanfile.py
- scripts/cmake/ExternalProjectEigen.cmake
- scripts/cmake/ThirdPartyLibVersions.cmake
- scripts/env/envinf1/cli.sh
TODO: 
Starting with Eigen-3.3 the alignment issue came up again and is solved here.
Without the proper alignment in Release mode there are segv's and undefined memory usage problems.
I tried to minimize set of changes, so not every structure got a special new-operator (we might have to extend this if errors happen).
I have changed some of the tests (and found some errors there) to run successfully on my computer with Eigen-3.2.10 and Eigen-3.3.2 and LIS-1.7.24.
~~Lars will setup a test in Jenkins using eigen-3.3 in nearest future.~~ See https://github.com/ufz/ogs/pull/1687 for the eigen-3.3 changes.
One problem I could not solve is the failing LIS-BiCG solver for the `ogs-Mechanics_SDE_cube_1e0` benchmark. I changed the solver to CG, which is fine in this case because the matrices are …
> Fixing eigen alignment

- MaterialLib/Fluid/Density/LinearTemperatureDependentDensity.h
There is a bug in ``LinearTemperatureDependentDensity->getdValue(..)``, which does not consider the cases of the derivative of the density with a non-temperature variable.  This PR fixes this bug.
> [Bug] Set return 0. for not drho/dT in LinearTemperatureDependentDensity

- scripts/cmake/ThirdPartyLibVersions.cmake
Used http protocoll for downloading as some CMake installation may
not have curl with https support.
> [CMake] Moved external project downloads to Azure storage.

- Documentation/ProjectFile/prj/processes/process/LIQUID_FLOW/material_property/solid/i_solid.md
- Documentation/ProjectFile/prj/processes/process/LIQUID_FLOW/material_property/solid/t_biot_constant.md
- Documentation/ProjectFile/prj/processes/process/LIQUID_FLOW/material_property/solid/t_thermal_expansion.md
- ProcessLib/HeatConduction/HeatConductionFEM-impl.h
- ProcessLib/HeatConduction/HeatConductionFEM.h
- ProcessLib/HeatConduction/HeatConductionProcess.cpp
- ProcessLib/HeatConduction/HeatConductionProcess.h
- ProcessLib/LiquidFlow/CMakeLists.txt
- ProcessLib/LiquidFlow/CreateLiquidFlowMaterialProperties.cpp
- ProcessLib/LiquidFlow/CreateLiquidFlowMaterialProperties.h
- ProcessLib/LiquidFlow/LiquidFlowLocalAssembler-impl.h
- ProcessLib/LiquidFlow/LiquidFlowLocalAssembler.h
- ProcessLib/LiquidFlow/LiquidFlowMaterialProperties.cpp
- ProcessLib/LiquidFlow/LiquidFlowMaterialProperties.h
- ProcessLib/LiquidFlow/LiquidFlowProcess.cpp
- ProcessLib/LiquidFlow/LiquidFlowProcess.h
- Tests/ProcessLib/LiquidFlow/TestLiquidFlowMaterialProperties.cpp
This PR extends the merged implementation of the staggered scheme (PR: #1672) to  coupled thermal hydraulic processes.
A test is provided for verification of the implemation. The test have been verify with OGS5. There is a slightly difference between the solution values by ogs6 and OGS5. The difference is caused by the different calculation approaches of thermal expansion coefficient of fluid. With the same linear temperature dependent fluid density model of the test, OGS5 uses the thermal expansion constant directly, while in ogs6,  the  thermal expansion coefficient is calculated by drho_w/dT/rho_w. 
Follow up PR: coupling term in the calculation of the secondary variables. 
Closes https://github.com/ufz/ogs/issues/1709
> First application of the staggered scheme: coupled thermal hydraulic processes

- Documentation/ProjectFile/material/solid/constitutive_relation/Ehlers/damage_properties/i_damage_properties.md
- Documentation/ProjectFile/material/solid/constitutive_relation/Ehlers/damage_properties/t_alpha_d.md
- Documentation/ProjectFile/material/solid/constitutive_relation/Ehlers/damage_properties/t_beta_d.md
- Documentation/ProjectFile/material/solid/constitutive_relation/Ehlers/damage_properties/t_h_d.md
- Documentation/bibliography.bib
- MaterialLib/SolidModels/CreateEhlers.h
- MaterialLib/SolidModels/Ehlers-impl.h
- MaterialLib/SolidModels/Ehlers.h
- MaterialLib/SolidModels/KelvinVector-impl.h
- ProcessLib/SmallDeformation/CMakeLists.txt
- web/content/docs/benchmarks/EhlersDamage/EhlersDamage.md
An isotropic damage model has been coupled to the classical Ehlers plastic yield surface. For further references, see the implementation manual.
Closes: https://github.com/ufz/ogs/issues/1645
TODO:
> Local isotropic damage coupled to Ehlers plasticity

- Jenkinsfile
It tried to set the commit status on GitHub on a non-existing commit as it falsely used the commit hash from the current Jenkins pipeline library ...?...
[This is a Jenkins bug](https://issues.jenkins-ci.org/browse/JENKINS-40150?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20github-plugin).
EDIT: Simply removing it seems to solve the problem as it then takes the status setter from the GitHub Branch Source plugin automatically which should be better suited.
> [Jenkins] Fix git commit status setter.

- GeoLib/IO/Legacy/OGSIOVer4.cpp
This fixes a problem with loading multiple TIN-files referenced in a GLI when the path or the filename contain a hash-character ("#").
> [Fix] issue with loading tin-files with hash in path

- Jenkinsfile
- conanfile.py
The Qt package was rebuild and misses some symlinks inside its
*.framework/-directories which leads to an error in copying these
files. Temporary disable copying.
> [Conan] Temporary fix mac conan issues related to Qt package.

- Applications/Utils/ModelPreparation/PartitionMesh/NodeWiseMeshPartitioner.cpp
- Applications/Utils/ModelPreparation/PartitionMesh/NodeWiseMeshPartitioner.h
- MeshLib/IO/MPI_IO/NodePartitionedMeshReader.cpp
- MeshLib/IO/MPI_IO/NodePartitionedMeshReader.h
- MeshLib/IO/MPI_IO/PropertyVectorMetaData.h
The PR adds the partitioning computed by metis also to the `PropertVector`s in the mesh and stores the meta data as well as the property values in separate binary files. The current PR contains the partitioning only for `PropertyVector`'s assigned to mesh nodes. The PR also includes the reading of the `PropertyVector`'s into a parallel running ogs.
> [HPC] Partition PropertyVectors and read partitioned PropertyVectors

- MaterialLib/SolidModels/Ehlers-impl.h
- MaterialLib/SolidModels/Ehlers.cpp
Small bug fix for a problem showing up since aligned Eigen matrices are used. The previous implementation would write behind the allocated space in 2D cases.
The 3D case code is just moved. The 2D case code is new.
> [MatL] Correct s_odot_s() product for 2D cases.

- scripts/cmake/Find.cmake
- scripts/cmake/packaging/PackagingLinux.cmake
- scripts/cmake/packaging/module.in
- scripts/env/envinf1/cli.sh
- scripts/jenkins/gcc-dynamic.groovy
```bash
export MODULEPATH=$MODULEPATH:/global/apps/modulefiles
module load ogs            # Loads head/standard
module load ogs/head/petsc # Loads head petsc config
module load ogs/6.0.9      # Loads version 6.0.9 standard config, not released yet
```
Tested on frontend1, frontend2 and envinf1.
| node | proc | `-march` gcc < 4.9 | `-march` gcc >= 4.9 |
| ----- | ---- | ------------------ | ------------------- |
frontend1 | `E5-2670 v2` | `core-avx-i` | `ivybridge`
frontend2 | `E5-2690 v4` | `core-avx2` | `broadwell `
envinf1 | `E5-2680 v2` | `core-avx-i` | `ivybridge`
frontend1 and envinf1 have the same architecture?
> Eve module

- Documentation/ProjectFile/prj/time_loop/output/t_compress_output.md
- MeshLib/IO/VtkIO/VtuInterface-impl.h
- ProcessLib/Output.cpp
- ProcessLib/Output.h
- ProcessLib/ProcessOutput.cpp
- ProcessLib/ProcessOutput.h
The default value is to compress the vtu output, but for a lot of output in production code the compression takes around 1/6th of each timestep (with output). The optional `<compress_output>` option allows switching off the compression.
Some results for the GWF/cube_1e6.prj:
File size increases a lot, almost five-fold:
-rw-r--r-- 1 naumov users   179 597 443   Mar 27 23:37 cube_1e6_pcs_0_ts_1_t_1.000000.vtu
-rw-r--r-- 1 naumov users   36 323 990   Mar 28 00:45 cube_1e6_pcs_0_ts_1_t_1.000000.vtu
But the time goes down
from 28.086064819 seconds ( +-  0.88% )
to 23.330982410 seconds ( +-  1.07% ),
which is 83% of the original runtime ;) (It would be more efficient for a transient simulation even...)
> Add output compression to project configuration.

- Applications/ApplicationsLib/ProjectData.cpp
- Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/porous_medium/porous_medium/relative_permeability/i_relative_permeability.md
- Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/porous_medium/porous_medium/relative_permeability/relative_permeability/a_id.md
- Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/porous_medium/porous_medium/relative_permeability/relative_permeability/i_relative_permeability.md
- Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/porous_medium/porous_medium/t_capillary_pressure.md
- Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/t_gas_density.md
- Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/t_gas_viscosity.md
- Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/t_liquid_density.md
- Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/t_liquid_viscosity.md
- Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/t_mass_lumping.md
- Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/t_specific_body_force.md
- Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/t_temperature.md
- MathLib/InterpolationAlgorithms/PiecewiseLinearInterpolation.cpp
- ProcessLib/TwoPhaseFlowWithPP/CMakeLists.txt
- ProcessLib/TwoPhaseFlowWithPP/CreateTwoPhaseFlowWithPPMaterialProperties.cpp
- ProcessLib/TwoPhaseFlowWithPP/CreateTwoPhaseFlowWithPPMaterialProperties.h
- ProcessLib/TwoPhaseFlowWithPP/CreateTwoPhaseFlowWithPPProcess.cpp
- ProcessLib/TwoPhaseFlowWithPP/CreateTwoPhaseFlowWithPPProcess.h
- ProcessLib/TwoPhaseFlowWithPP/TwoPhaseFlowWithPPLocalAssembler-impl.h
- ProcessLib/TwoPhaseFlowWithPP/TwoPhaseFlowWithPPLocalAssembler.h
- ProcessLib/TwoPhaseFlowWithPP/TwoPhaseFlowWithPPMaterialProperties.cpp
- ProcessLib/TwoPhaseFlowWithPP/TwoPhaseFlowWithPPMaterialProperties.h
- ProcessLib/TwoPhaseFlowWithPP/TwoPhaseFlowWithPPProcess.cpp
- ProcessLib/TwoPhaseFlowWithPP/TwoPhaseFlowWithPPProcess.h
- ProcessLib/TwoPhaseFlowWithPP/TwoPhaseFlowWithPPProcessData.h
- Tests/MathLib/TestPiecewiseLinearInterpolation.cpp
As titled, update the two-phase flow with PP-model based on fluid and porous media properties, and update the Test/data accordingly.
Here, the results of ctest are updated due to the BrookCorey type relative permeability model is applied instead of the previous curve type by following the original benchmark setting.  
The results are compared with ogs5 results.
> Add material properties in two-phase flow with PP model

- Applications/DataExplorer/DataExplorer.cmake
- Applications/DataExplorer/DataView/CMakeLists.txt
- Applications/DataExplorer/VtkVis/CMakeLists.txt
- Applications/Utils/OGSFileConverter/CMakeLists.txt
- Jenkinsfile
Updated pipeline lib to [1.0.4](https://gitlab.opengeosys.org/bilke/jenkins-library/tags/1.0.4)
This uses VS 2017 as default. After installing VS 2017 on win1 VS 2015 was broken :rage2: . I was able to restore VS 2015 compilation but without Ninja only which increased built times extraordinary.. :rage4:  So as a pragmatic solution I switched to VS 2017.
The only good thing here is that VS 2017 (finally) is binary compatible with VS 2015 so we can reuse Conan packages originally built with VS 2015..
Note to self: Checkout and maybe implement CMake [transitive dependencies](https://cmake.org/cmake/help/v3.8/manual/cmake-buildsystem.7.html#transitive-usage-requirements)..
> [Jenkins] Use Visual Studio 2017 as default

- ProcessLib/SmallDeformation/SmallDeformationFEM.h
- ProcessLib/SmallDeformation/SmallDeformationProcess.h
Go commit-wise.
Some fixes are applied to style (`_`), some to better code (`integration_weight`), some to wrong coding (`eps_xz/yz`), some extend the output (`eps_xz/yz`)
If you copied this process, please check if the wrong lines creeped into your copy too...
> SmallDeformation process fixes (and updates)

- Applications/FileIO/CMakeLists.txt
- Applications/FileIO/FEFLOW/FEFLOWGeoInterface.cpp
- Documentation/README.txt.in
- Jenkinsfile
- conanfile.py
- scripts/cmake/packaging/Pack.cmake
- scripts/cmake/packaging/PackagingLinux.cmake
- scripts/jenkins/gcc-conan.groovy
- scripts/jenkins/msvc.groovy
- scripts/jenkins/msvc32.groovy
- Fixed Conan QtXml package linking with PCH on macOS
- added conditional Conan install option `-o gui=True` -> CLI devs do not need to download large Qt anymore, added instructions to [the docs](https://docs.opengeosys.org/docs/devguide/getting-started/build-configuration)
- Added a README.txt to the redistributable packages with usage instructions
> Conan Mac Qt PCH fix

- MeshLib/Elements/FaceRule.cpp
- MeshLib/Elements/FaceRule.h
- ProcessLib/LIE/Common/FractureProperty.h
- ProcessLib/LIE/Common/Utils.cpp
- ProcessLib/LIE/Common/Utils.h
- Tests/ProcessLib/TestLIE.cpp
Used in the LIE process and needed for its 3D extension.
Optionally we could move some dealing with normals _etc._ code from LIE/Common.h to MeshLib.
> Face rule normals and vectors

- MeshLib/Properties.cpp
- MeshLib/Properties.h
With the additional parameter 't' the returned names can be filtered by mesh item type of the `PropertyVector`.
> [MeL] Another Properties::getPropertyVectorNames().

- NumLib/DOF/LocalToGlobalIndexMap.cpp
- NumLib/DOF/LocalToGlobalIndexMap.h
- NumLib/DOF/MeshComponentMap.cpp
- NumLib/DOF/MeshComponentMap.h
- ProcessLib/BoundaryCondition/GenericNaturalBoundaryCondition-impl.h
- ProcessLib/CalculateSurfaceFlux/CalculateSurfaceFlux.cpp
- ProcessLib/HydroMechanics/HydroMechanicsProcess.h
- ProcessLib/LIE/BoundaryCondition/GenericNaturalBoundaryCondition-impl.h
- ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.cpp
- ProcessLib/LIE/SmallDeformation/SmallDeformationProcess.cpp
- ProcessLib/Process.cpp
- ProcessLib/SmallDeformation/SmallDeformationProcess.h
- Tests/NumLib/LocalToGlobalIndexMap.cpp
- Tests/NumLib/LocalToGlobalIndexMapMultiComponent.cpp
- Tests/NumLib/TestComponentNorms.cpp
- Tests/NumLib/TestExtrapolation.cpp
- Tests/NumLib/TestMeshComponentMap.cpp
- Tests/NumLib/TestSerialLinearSolver.cpp
- Tests/NumLib/TestSparsityPattern.cpp
The main change is in the LocalToGlobalIndexMap, all other changes are "just" fixing the compilation errors. In the processes not all of the unique_ptr's are removed, since somebody has to be responsible for the MeshSubset.
> [NL] Remove vector<unique_ptr> from DOF table.

- Applications/DataExplorer/DataView/GeoTreeView.cpp
- Applications/FileIO/SWMM/SWMMInterface.cpp
- Applications/Utils/MeshEdit/CreateBoundaryConditionsAlongPolylines.cpp
- BaseLib/TemplateLogogFormatterSuppressedGCC-impl.h
- GeoLib/GEOObjects.cpp
- GeoLib/GEOObjects.h
- GeoLib/IO/Legacy/OGSIOVer4.cpp
- GeoLib/IO/XmlIO/Boost/BoostXmlGmlInterface.cpp
- GeoLib/IO/XmlIO/Qt/XmlGmlInterface.cpp
- GeoLib/IO/XmlIO/Qt/XmlGmlInterface.h
- GeoLib/PointVec.cpp
- GeoLib/PointVec.h
- GeoLib/StationBorehole.cpp
- GeoLib/TemplateVec.h
- MeshLib/MeshEditing/AddLayerToMesh.cpp
- MeshLib/MeshEditing/FlipElements.cpp
- Tests/FileIO/TestGmlInterface.h
- Tests/GeoLib/TestGEOObjectsMerge.cpp
Main interface change in TemplateVec is the usage of unique pointer for the name-id map.
The potential memory leakage is reported by clang's static code analyzer (clang-tidy clang-analyzer-cplusplus.NewDeleteLeaks).
I suggest commit-wise review.
> Potential memory leaks

- Jenkinsfile
Adds push notification via [Pushover](https://pushover.net/) on failed builds in ufz/master. This is more for myself but feel free to [subscribe](https://pushover.net/subscribe/jenkins-6uzd4c6ajcegzis) too. Pushover offers apps for iOS, Android and Desktop browser (around 5 Euro each, one-time).
> [Jenkins] Added build failure notifications for ufz/master.

- Applications/Utils/MeshEdit/swapNodeCoordinateAxes.cpp
fix a bug in swapNodeCoordinateAxes tool reported by Mohammad Islam. Reordering of the coordinate values was not correctly implemented.
> [A/P/ME] bugfix in swapNodeCoordinateAxes

- Applications/Utils/MeshEdit/CMakeLists.txt
- Applications/Utils/MeshEdit/UnityPreprocessing.cpp
- MeshLib/IO/VtkIO/VtuInterface-impl.h
* removes line elements if mesh isn't line-mesh (skipped if not applicable)
* splits element nodes and transforms all cell arrays into node array (skipped if not applicable)
* if cell arrays are present, arrays with more than one component are removed
> Tool for preparing ogs-meshes for unity

- MaterialLib/SolidModels/CreateEhlers.h
- MaterialLib/SolidModels/CreateLubby2.h
- MaterialLib/SolidModels/Ehlers-impl.h
- MaterialLib/SolidModels/Ehlers.h
- MaterialLib/SolidModels/LinearElasticIsotropic.h
- MaterialLib/SolidModels/Lubby2-impl.h
- MaterialLib/SolidModels/Lubby2.h
- MaterialLib/SolidModels/MechanicsBase.h
- ProcessLib/HydroMechanics/HydroMechanicsFEM.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrix-impl.h
- ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerMatrix-impl.h
- ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerMatrixNearFracture-impl.h
- ProcessLib/SmallDeformation/SmallDeformationFEM.h
Rewrite solid material models such that the internal material state variables are not modified but new values are returned. This simplifies introduction of finite difference scheme.
Behaviour w.r.t. the ctests has not changed.
> Rewrite solid material models

- scripts/cmake/SubmoduleSetup.cmake
This fixes submodule checkout errors when the submodules URL changed like this:
```
-- Updating submodule ThirdParty/cmake-modules
error: no such remote ref af334f92548b7349a1bb038d56ce91fc7b3d3d00
Fetched in submodule path 'ThirdParty/cmake-modules', but it did not contain af334f92548b7349a1bb038d56ce91fc7b3d3d00. Direct fetching of that commit failed.
```
Fixed also a CMake error when CVODE_KLU variable was not defined:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CVODE_KLU
linked by target "MathLib" in directory /home/naumov/w/ogs/s/MathLib
-- Configuring incomplete, errors occurred!
```
See #1827.
> [CMake] Run git submodule sync in CMake

- Documentation/ProjectFile/prj/processes/process/HT/fluid/i_fluid.md
- Documentation/ProjectFile/prj/processes/process/HT/fluid/t_density.md
- Documentation/ProjectFile/prj/processes/process/HT/fluid/t_viscosity.md
- Documentation/ProjectFile/prj/processes/process/HT/t_specific_heat_capacity_fluid.md
- MaterialLib/Fluid/SpecificHeatCapacity/CreateSpecificFluidHeatCapacityModel.cpp
- ProcessLib/HT/CreateHTProcess.cpp
- ProcessLib/HT/HTFEM.h
- ProcessLib/HT/HTProcess.cpp
- ProcessLib/HT/HTProcess.h
- ProcessLib/HT/HTProcessData.h
Also included:
- Use `FluidProperties` and `createFluidProperties` for handling of fluid density, viscosity and specific heat capacity.
- Improvements of readability.
- Small optimizations.
ToDo:
> Fix secondary variable computation in HT process

- ProcessLib/Deformation/LinearBMatrix.h
- ProcessLib/HydroMechanics/HydroMechanicsFEM.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerFracture-impl.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerInterface.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrix-impl.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/IntegrationPointDataMatrix.h
- ProcessLib/LIE/SmallDeformation/LocalAssembler/IntegrationPointDataMatrix.h
- ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerMatrix-impl.h
- ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerMatrix.h
- ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerMatrixNearFracture-impl.h
- ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerMatrixNearFracture.h
- ProcessLib/SmallDeformation/SmallDeformationFEM.h
- ProcessLib/SmallDeformationCommon/Common.h
This results in significantly lower memory usage (e.g. 16.8MiB now vs. 22MiB before for SmallDeformation process on cube_1e3 mesh). The run-time is not different or maybe a little higher now, but I didn't measure very carefully.
> Compute b matrices on the fly

- GeoLib/IO/Legacy/OGSIOVer4.cpp
This crashed the convertGEO utility. Thanks to JM for reporting!
This bug was introduced with a6ff2c7a.
> [GL] Fixed variable initialized with null instead of map.

- Applications/DataExplorer/CMakeLists.txt
- Applications/DataExplorer/DataExplorer.cmake
- Applications/DataExplorer/DataView/GeoTreeModel.h
- Applications/DataExplorer/DataView/GeoTreeView.h
- Applications/DataExplorer/DataView/LineEditDialog.h
- Applications/DataExplorer/DataView/MeshQualitySelectionDialog.h
- Applications/DataExplorer/DataView/ModelTreeItem.h
- Applications/DataExplorer/DataView/MshView.h
- Applications/DataExplorer/DataView/SetNameDialog.h
- Applications/DataExplorer/DataView/StationTreeModel.h
- Applications/DataExplorer/DataView/StationTreeView.h
- Applications/DataExplorer/VtkVis/VisPrefsDialog.h
- Applications/DataExplorer/VtkVis/VtkStationSource.h
- Applications/DataExplorer/VtkVis/VtkVisPipeline.h
- Applications/DataExplorer/VtkVis/VtkVisPipelineItem.cpp
- Applications/DataExplorer/VtkVis/VtkVisPipelineItem.h
- Applications/DataExplorer/main.cpp
- Applications/DataExplorer/mainwindow.cpp
- Applications/FileIO/CMakeLists.txt
- Applications/FileIO/SWMM/SWMMInterface.cpp
- Applications/Utils/OGSFileConverter/OGSFileConverter.cpp
The ProcessLib was coupled through the ApplicationsLib, and the latter is not used in the DataExplorer.
Remove some of the default include dirs (as in the rest of the project) but internal DataExplorer dirs.
Reorder includes in files, which were changed, with clang-format.
> Decouple ProcessLib from DataExplorer

- Applications/Utils/ModelPreparation/PartitionMesh/NodeWiseMeshPartitioner.cpp
- Applications/Utils/ModelPreparation/PartitionMesh/NodeWiseMeshPartitioner.h
- MeshLib/IO/MPI_IO/NodePartitionedMeshReader.cpp
- MeshLib/IO/MPI_IO/NodePartitionedMeshReader.h
- MeshLib/IO/MPI_IO/PropertyVectorMetaData.h
- Implementation the partition of cell properties in util partmesh (class `NodeWiseMeshPartitioner`)
- Implementation of functionality to read the parallelized cell properties in `NodePartitionedMeshReader`.
> [PETSc/MPI] Handle parallel cell properties

- NumLib/ODESolver/NonlinearSolver.cpp
One test needs to change file names.
The failing of another test is caused by allowing setting nonzero  initial guess for ksp solve.
> Fix two parallel tests

- BaseLib/ConfigTree.h
- MaterialLib/Fluid/FluidProperties/FluidProperties.h
- MaterialLib/SolidModels/Ehlers-impl.h
- ProcessLib/HydroMechanics/HydroMechanicsFEM.h
- ProcessLib/LIE/SmallDeformation/LocalAssembler/IntegrationPointDataMatrix.h
- ProcessLib/SmallDeformation/SmallDeformationFEM.h
- ProcessLib/ThermoMechanics/ThermoMechanicsFEM.h
Just looking if the `#ifdefs` for old VisualStudio can be removed.
> Remove MSVC ifdefs for version less than 19.00 = VisualStudio2015

- MaterialLib/SolidModels/CreateEhlers.h
- MaterialLib/SolidModels/Ehlers.cpp
- MaterialLib/SolidModels/Ehlers.h
- MaterialLib/SolidModels/LinearElasticIsotropic-impl.h
- MaterialLib/SolidModels/LinearElasticIsotropic.cpp
- MaterialLib/SolidModels/LinearElasticIsotropic.h
- MaterialLib/SolidModels/Lubby2.cpp
- MaterialLib/SolidModels/Lubby2.h
- Move template function definitions to `-impl.h` for LinearElastic (other models already have this done)
- Add explicit instantiation declaration in the `.h` file
- Include the definitions (the `-impl.h`) in the `.cpp`, where the templates are explicitly instantiated (do not include the `-impl.h` any longer in `.h`)
This saves a dozen or so of instantiations (for each mechanics process for the 2 and 3d cases).
For me ff8da7c compiles in about 1200s, while ufz/master (f14c072) compiles in 1240s. Not much difference, but still.
> Restructure solid materials

- NumLib/ODESolver/TimeDiscretization.h
- NumLib/TimeStepping/Algorithms/EvolutionaryPIDcontroller.cpp
- ProcessLib/LiquidFlow/Tests.cmake
- ProcessLib/RichardsFlow/Tests.cmake
- ProcessLib/UncoupledProcessesTimeLoop.cpp
- ProcessLib/UncoupledProcessesTimeLoop.h
This PR contains updates or bugfixing for the adaptive time stepping implementation:
- stop program when a rejected time step gets an unchanged  new step size if the previous step is also rejected.
- reset the initial guess of global x vector to its old value if a time step is rejected. Actually only the Picard  nonlinear solver needs  this computation.
- only display the accepted time step number as step number.
Besides, a test for the case of Richards flow with adaptive time stepping is also included in this PR.
> Patches for adaptive time stepping

- ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.cpp
- ProcessLib/LIE/HydroMechanics/HydroMechanicsProcessData.h
This PR extends LIE/HM so that it can output nodal values of fracture relative displacement in local coordinates (w) and fracture aperture (b).
> [PCS/LIE/HM] add output of nodal w and aperture

- scripts/cmake/test/Test.cmake
- scripts/jenkins/gcc-tests-large.groovy
- Do not run in parallel with unit tests
- ctest-large target run tests sequentially
> [Jenkins] Run ctest-large sequentially.

- scripts/cmake/test/AddTestTester.cmake
- scripts/cmake/test/AddTestWrapper.cmake
By this change it becomes easier to start a debugger for a specific invocation of ogs if some ctest fails, because now one can just copy & paste the specific command line from ctest's output.
Possible Output (the lines starting with, e.g., "136: --" are new):
```
$ ctest -R ogs-1D_HeatConduction_dirichlet -V
[...]
test 136
Start 136: ogs-1D_HeatConduction_dirichlet
136: Test command: /usr/bin/cmake "-DEXECUTABLE=/home/lehmannc/prog/ogs6/github-chleh-PRs/build-release-eigenlis/bin/ogs" "-DEXECUTABLE_ARGS=-o;/home/lehmannc/prog/ogs6/github-chleh-PRs/build-release-eigenlis/Tests/Data/Parabolic/T/1D_dirichlet;line_60_heat.prj" "-Dcase_path=/home/lehmannc/prog/ogs6/github-chleh-PRs/src/Tests/Data/Parabolic/T/1D_dirichlet" "-DBINARY_PATH=/home/lehmannc/prog/ogs6/github-chleh-PRs/build-release-ei …
```
> [cmake] print test commands before run

- Applications/FileIO/SWMM/SWMMInterface.cpp
- Applications/FileIO/SWMM/SWMMInterface.h
- Applications/Utils/SWMMConverter/SWMMConverter.cpp
This makes the SWMM converter slightly more usable for non-programmers. By default *all* node and link data is written into vtu-files (one for every timestep) and *all* subcatchment and system data is written into csv-files (one for every subcatchment/system)
For selective conversion of the data (only certain time steps, specific nodes/links/etc., assessment of pollutants, ...) it'd still be necessary to either adjust the source code or write a comprehensive user interface that accounts for such things.
> Writing SWMM data categories

- ProcessLib/LiquidFlow/Tests.cmake
- ProcessLib/RichardsFlow/Tests.cmake
- ProcessLib/UncoupledProcessesTimeLoop.cpp
The  step size estimation after a diverged non-linear solver is now integrated into the time stepping function. This resolves 
1) the problem that time stepping goes endless rejected steps after non-linear solver fails,
2) the rejected time step after a diverged non-linear solver restarts with the solution of the previous non-linear step but not with the solution of the previous time step.
With the changes, the time step size after a diverged nonlinear solver is computed in time stepper with the in-converged solution of the non-linear solver.
> Fixed a bug in time stepper when non-linear solver diverges

- MaterialLib/SolidModels/Ehlers-impl.h
- MaterialLib/SolidModels/Lubby2.h
- NumLib/Fem/CoordinatesMapping/ShapeMatrices.h
- ProcessLib/ComponentTransport/ComponentTransportFEM.h
- ProcessLib/HT/HTFEM.h
- ProcessLib/HydroMechanics/HydroMechanicsProcessData.h
- ProcessLib/LIE/BoundaryCondition/NeumannBoundaryConditionLocalAssembler.h
- ProcessLib/LIE/HydroMechanics/HydroMechanicsProcessData.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/IntegrationPointDataFracture.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/IntegrationPointDataMatrix.h
- ProcessLib/LIE/SmallDeformation/LocalAssembler/IntegrationPointDataFracture.h
- ProcessLib/LIE/SmallDeformation/LocalAssembler/IntegrationPointDataMatrix.h
- ProcessLib/RichardsFlow/RichardsFlowFEM.h
- ProcessLib/SmallDeformation/SmallDeformationFEM.h
- ProcessLib/ThermalTwoPhaseFlowWithPP/ThermalTwoPhaseFlowWithPPLocalAssembler.h
- ProcessLib/ThermoMechanics/ThermoMechanicsFEM.h
- ProcessLib/ThermoMechanics/ThermoMechanicsProcessData.h
- ProcessLib/TwoPhaseFlowWithPrho/TwoPhaseFlowWithPrhoLocalAssembler.h
- Tests/NumLib/SteadyDiffusion2DExample1.h
Adding Eigen's operator new to classes using any (fixed size) Eigen::Matrix as members.
Continuation of #1897.
Relates to  #1881 #1323
clang's matcher:
```
recordDecl(
hasDescendant(fieldDecl(hasType(cxxRecordDecl(hasName("Eigen::Matrix"))))),
unless(hasDescendant(typedefDecl(hasName("eigen_aligned_operator_new_marker_type")))),
unless(isExpansionInSystemHeader()))
```
This can be refined not to match dynamic matrices...
> Eigen alignment

- MaterialLib/SolidModels/Ehlers-impl.h
- MaterialLib/SolidModels/Ehlers.h
- MaterialLib/SolidModels/MechanicsBase.h
- ProcessLib/SmallDeformation/LocalAssemblerInterface.h
- ProcessLib/SmallDeformation/SmallDeformationFEM.h
- ProcessLib/SmallDeformation/SmallDeformationProcess-impl.h
- ProcessLib/SmallDeformation/SmallDeformationProcess.h
... for SmallDeformation process with Ehlers/Damage model.
follow-up of #1874.
This PR implements nodal output of material-model-defined internal variables at the example of the SD process.
I do not plan to implement more such output functionality now. Instead this PR can serve as a starting point for others.
TODO:
It would be nice if somebody could help me with the TODOs above, since SmallDeformation is not my main business.
> Internal variables output

- Applications/CLI/ogs.cpp
- NumLib/ODESolver/ConvergenceCriterionPerComponentDeltaX.cpp
NaN were introduced https://github.com/ufz/ogs/pull/1847/commits/0498c773278ec81c49b02261f8bb6f00a90aa73b here and are used by default in debug compilations.
> Floating point exceptions for debugging.

- Documentation/ProjectFile/prj/process_variables/process_variable/boundary_conditions/boundary_condition/NonuniformNeumann/c_NonuniformNeumann.md
- Documentation/ProjectFile/prj/process_variables/process_variable/boundary_conditions/boundary_condition/NonuniformNeumann/t_field_name.md
- Documentation/ProjectFile/prj/process_variables/process_variable/boundary_conditions/boundary_condition/NonuniformNeumann/t_mesh.md
- MeshLib/IO/VtkIO/VtuInterface.cpp
- MeshLib/Mesh.h
- ProcessLib/BoundaryCondition/BoundaryCondition.cpp
- ProcessLib/BoundaryCondition/BoundaryCondition.h
- ProcessLib/BoundaryCondition/DirichletBoundaryCondition.h
- ProcessLib/BoundaryCondition/GenericNaturalBoundaryCondition-impl.h
- ProcessLib/BoundaryCondition/GenericNonuniformNaturalBoundaryCondition-impl.h
- ProcessLib/BoundaryCondition/GenericNonuniformNaturalBoundaryCondition.h
- ProcessLib/BoundaryCondition/GenericNonuniformNaturalBoundaryConditionLocalAssembler.h
- ProcessLib/BoundaryCondition/NonuniformNeumannBoundaryCondition.cpp
- ProcessLib/BoundaryCondition/NonuniformNeumannBoundaryCondition.h
- ProcessLib/BoundaryCondition/NonuniformNeumannBoundaryConditionLocalAssembler.h
- ProcessLib/GroundwaterFlow/Tests.cmake
The structure is to a large extent copied from the current uniform natural BC implementation.
Todo:
* Not this PR: test with multi-component process, LIE, partitioned nonuniform BCs (PETSc)
In order to see what changed from the previous implementation:
https://github.com/chleh/ogs6/compare/f47cb8f4a0a5847929aa67a2c3d7462139af6ae9...chleh:nonuniform-neumann-bc
> Nonuniform Neumann BCs

- NumLib/TimeStepping/Algorithms/EvolutionaryPIDcontroller.cpp
- NumLib/TimeStepping/Algorithms/EvolutionaryPIDcontroller.h
- NumLib/TimeStepping/Algorithms/TimeStepAlgorithm.h
- ProcessLib/LiquidFlow/Tests.cmake
- ProcessLib/TwoPhaseFlowWithPrho/Tests.cmake
- ProcessLib/UncoupledProcessesTimeLoop.cpp
Improved the time stepper of EvolutionaryPIDcontroller for two phase flow. In case of non-linear solver diverged, the step size change is forced to decrease in the code improvement. A ctest about a two phase flow scheme, which uses  overall mass density as one of two primary variables, is added. In addition, a test that is influenced by the  improvement is updated as well.
> Improved the time stepper of EvolutionaryPIDcontroller for two phase flow

- scripts/cmake/CompilerSetup.cmake
This adds the flags setup in `CompilerSetup.cmake` for C libraries such `metis` too. Tom needed this to add cpu arch flags when compiling on cluster systems.
> [CMake] Copy CXX to C flags.

- CMakeLists.txt
- NumLib/ODESolver/ConvergenceCriterionPerComponentResidual.cpp
- NumLib/ODESolver/ConvergenceCriterionResidual.cpp
- ProcessLib/PhaseField/CreatePhaseFieldProcess.cpp
- ProcessLib/PhaseField/PhaseFieldProcessData.h
Defaults to ON.
~~Set EIGEN_NO_AUTOMATIC_RESIZING macro as well.~~
See https://eigen.tuxfamily.org/dox/TopicPreprocessorDirectives.html.
Related to #1909.
> [CMake] Added option OGS_EIGEN_INITIALIZE_MATRICES_BY_NAN.

- CMakeLists.txt
- ProcessLib/HydroMechanics/Tests.cmake
- Tests/NumLib/TestComponentNorms.cpp
This needs testing on local machines ( @chleh @fparisio ).
Hopefully
fixes #1881
> Disable eigen vectorization by default.

- ProcessLib/HT/HTFEM.h
If all components of the gravitational vector equals to zero in the project file the gravitational term will not be initialized. Anyway, it was used and caused a crash. This PR fixes the wrong behaviour.
> [HT] Fix handling of special gravitional vector.

- Tests/NumLib/TestComponentNorms.cpp
This has repeatedly failed in unrelated builds _e.g._ #1932
> [T] NL: Relax MultiComponentNorm2 test.

- MeshGeoToolsLib/BoundaryElementsAtPoint.cpp
The BoundaryElementsAtPoint algorithm expects the given
point to be found in the mesh. If this fails the preconditions
for the algorithm are not fulfilled.
Closes https://github.com/ufz/ogs/issues/1926
> [MGTL] BoundaryElems; Change assertion to error.

- .hooks/pre-commit
Added git pre-commit hook in .hooks-subdirectory.
Hook checks for correctly committing files tracked by git lfs.
Activate via the following setting in `.git/config`
```
[core]
hooksPath = .hooks
```
**Or** by copying this file to `.git/hooks/pre-commit`
Closes #1924.
> pre-commit hook for checking git lfs

- .lfsconfig
GitHub has some serious limitations on git lfs usage (storage and bandwidth). After merging #1982 we hit the quota in a few hours which resulted in GitHub disabling lfs in our account.
As a quickfix I moved our lfs files to our own GitLab instance where we have lots of more storage and bandwidth available. The new `.lfsconfig`-file should be enough to switch to the other lfs location. 
- Cloning and pulling simply works
- For pushing new lfs files you need to have an account on our GitLab instance and need to have write rights to the [ogs repo](https://gitlab.opengeosys.org/ogs/ogs). You also need a [personal access token](https://gitlab.opengeosys.org/profile/personal_access_tokens). On pushing please provide your GitLab username (should be the same as your GitHub user name) and your …
> Switch to GitLab for lfs

- .lfsconfig
The previous one is specific for the named remote.
> Use generalized lfs server access.

- MeshLib/MeshGenerators/QuadraticMeshGenerator.cpp
- Tests/MeshLib/TestQuadraticMesh.cpp
For the review I suggest to look on the new version of the [QuadraticMeshGenerator.cpp](https://github.com/endJunction/ogs/blob/5cc974165f3447ca3b4793a3b0a25ad767529ebb/MeshLib/MeshGenerators/QuadraticMeshGenerator.cpp)---it's a complete rewrite---and compare the tests.
The only unfortunate thing about the new code are the scattered `new`/`delete` operations on nodes---I don't have a good idea on how to replace them.
The runtime for conversion of a 1e6 linear quad elements mesh in the original version is more than 15 minutes (aborted then).
```
➜  ogs/r time bin/createQuadraticMesh -i quad1e6.vtu -o o.vtu
info: Create a quadratic order mesh
info: Found 2002000 edges in the mesh
^C
bin/createQuadraticMesh -i quad1e6.vtu -o o.vtu  944.93s user 0.27s system 100% cpu 15:45.19 total
```
The …
> Rewrite quadratic mesh generator

- NumLib/ODESolver/ODESystem.h
- NumLib/ODESolver/TimeDiscretizedODESystem.cpp
- ProcessLib/LocalAssemblerInterface.h
- ProcessLib/Process.cpp
- ProcessLib/Process.h
- ProcessLib/VectorMatrixAssembler.cpp
- ProcessLib/VectorMatrixAssembler.h
- Tests/NumLib/ODEs.h
In some processes (using non-local methods, for example (upcoming SmallDeformationNonlocal PR)) the assembly is split in two parts: computation of local quantities and actual (non-local) assembly (integration) into the local matrices.
This enhances the interface by a `preAssemble()` function.
> Add ode system preAssemble() call.

- Jenkinsfile
Added warnings logger for GCC, MSVC and Clang (only on master). Warnings are shown on the "classic" Jenkins UI only, e.g. [here](https://jenkins.opengeosys.org/job/ufz/job/ogs/job/PR-2006/2/). There are both links on the left navigation list and on the build summary page.
Also it should mark builds as unstable when there are new warnings introduced, but we have to check after merge if this really works.
> [Jenkins] Added warnings parser

- MaterialLib/SolidModels/KelvinVector-impl.h
The trace of deviatoric tensor must be zero but is
linearly scaling with the tensor's norm.
> [MatL] KelvinVector: Use vector norm in assertion.

- Documentation/ProjectFile/prj/nonlinear_solvers/nonlinear_solver/t_damping.md
- NumLib/ODESolver/NonlinearSolver.cpp
- NumLib/ODESolver/NonlinearSolver.h
This adds damping factor to the global newton to the constructor and the prj file parser.
Is it OK to have this one to have a default value 1.0? Or shell I add `<damping>1<\damping>` to all projects?
> [NL] Add damping factor to global Newton.

- ProcessLib/LIE/Common/FractureProperty.h
- ProcessLib/LIE/Common/PostUtils.h
- ProcessLib/LIE/HydroMechanics/CreateHydroMechanicsProcess.cpp
- ProcessLib/LIE/HydroMechanics/HydroMechanicsProcessData.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerFracture-impl.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrixNearFracture-impl.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/IntegrationPointDataFracture.h
- ProcessLib/LIE/HydroMechanics/Tests.cmake
Few renames and simplifications for the upcoming PRs for fracture permeability models (https://github.com/ufz/ogs/pull/2014) and pressure interpolation (https://github.com/ufz/ogs/pull/2015).
One small logic change is the separation of FracturePropertyHM class from FractureProperty. [[PL] LIE/HM: Separate FractureProperty for HM.](https://github.com/ufz/ogs/commit/a36d5f7ea3f1c7b55865b8b58ada3c17d4c106d7)
> Lie preparations

- BaseLib/ConfigTree.h
- BaseLib/Error.h
Unfortunately the Visual Studio 2015 does not support
the platform independent style for the function attributes.
Although it is a c++11 standard.
Closes https://github.com/ufz/ogs/issues/2024
> [BL] Use implementation specific [[noreturn]].

- MeshGeoToolsLib/MeshNodeSearcher.cpp
- MeshGeoToolsLib/MeshNodesAlongSurface.h
- MeshLib/Elements/HexRule20.cpp
- MeshLib/MeshSearch/ElementSearch.cpp
- Tests/MeshLib/TestBoundaryElementSearch.cpp
The second face (`face 1`) of a hex 20 was wrong; should contain node 16, not 11. This is fixed in the first commit and is the actual bugfix. A test is added.
Other small things (comments and makeVectorUnique) popped up during debugging session.
Thanks to Peter for reporting and to Tom for debug session. :1st_place_medal:
> Fix boundary element search hex20 bug

- BaseLib/LogogCustomCout.h
- scripts/cmake/ConanSetup.cmake
As requested by Keita. Not officially supported but works on macOS:
```bash
brew install open-mpi # (MPI installed via Homebrew is required)
...
CC=mpicc CXX=mpic++ cmake ../ogs -DCMAKE_BUILD_TYPE=Release -DOGS_USE_PETSC=ON -DOGS_USE_CONAN=ON
[builds VTK Conan package with MPI support locally]
[builds Petsc Conan package locally]
make ctest
```
> Conan PETSc

- ProcessLib/Output.cpp
- ProcessLib/ProcessOutput.cpp
- ProcessLib/ProcessOutput.h
This PR fixes #2040. It
1. separates the processing of output data and the data output by splitting  function ``doProcessOutput`` (in ProcessOutput.h) into two functions as  ``processOutputData`` and ``makeOutput``, respectively.
2. removes several  if-condtions that distinguish the data processing and the data output from  `Output::doOutputAlways` and `doOutputNonlinearIteration`.
> [Output] Cleanup of the output logic

- ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.cpp
- ProcessLib/LIE/HydroMechanics/Tests.cmake
- Tests/Data/LIE/HydroMechanics/expected_TaskB_pcs_0_ts_4_t_18.000000.vtu
- Tests/Data/LIE/HydroMechanics/expected_single_fracture_3D_pcs_0_ts_10_t_100.000000.vtu
- Tests/Data/LIE/HydroMechanics/expected_single_fracture_pcs_0_ts_10_t_100.000000.vtu
The first commit contains a bug fix for wrong global index access.
Small improvement in a vector access and updating the expected results.
> LIE_HM fix nodal aperture output

- Documentation/ProjectFile/prj/process_variables/process_variable/source_terms/source_term/Nodal/t_parameter.md
- Documentation/ProjectFile/prj/process_variables/process_variable/source_terms/source_term/Nodal/t_value.md
- ProcessLib/Process.cpp
- ProcessLib/Process.h
- ProcessLib/ProcessVariable.cpp
- ProcessLib/ProcessVariable.h
- ProcessLib/SourceTerms/CreateNodalSourceTerm.cpp
- ProcessLib/SourceTerms/CreateNodalSourceTerm.h
- ProcessLib/SourceTerms/NodalSourceTerm.cpp
- ProcessLib/SourceTerms/NodalSourceTerm.h
- ProcessLib/SourceTerms/SourceTermBuilder.cpp
- ProcessLib/SourceTerms/SourceTermBuilder.h
- ProcessLib/SourceTerms/SourceTermCollection.cpp
- ProcessLib/SourceTerms/SourceTermCollection.h
- Tests/Data/Elliptic/circle_radius_1/circle_1e1_axi.prj
- Tests/Data/Elliptic/circle_radius_1/circle_1e2_axi.prj
- Tests/Data/Elliptic/circle_radius_1/circle_1e3_axi.prj
- Tests/Data/Elliptic/circle_radius_1/circle_1e4_axi.prj
- Tests/Data/Elliptic/circle_radius_1/circle_1e5_axi.prj
- Tests/Data/Elliptic/circle_radius_1/circle_1e6_axi.prj
- Tests/Data/Elliptic/square_1x1_GroundWaterFlow/square_1e6_with_nodal_sources.prj
> [PL] Use parameter for defining source terms.

- MathLib/KelvinVector.cpp
- MathLib/KelvinVector.h
- Tests/MathLib/KelvinVector.cpp
Follow up of #2060 with fixes to the symmetric tensor to/from Kelvin vector conversion, now tested.
This came up during [Integration point data to VTK's field data output PR](https://github.com/ufz/ogs/pull/2071).
> Kelvin vector symmetric tensor conversion

- MathLib/KelvinVector-impl.h
- MathLib/KelvinVector.h
Used diagonal of tensor and fixed norm
> changed deviator trace assertion

- MathLib/LinAlg/LinAlg.cpp
- MathLib/LinAlg/LinAlg.h
- NumLib/Extrapolation/LocalLinearLeastSquaresExtrapolator.cpp
- ProcessLib/Output/CachedSecondaryVariable.cpp
- ProcessLib/Output/ProcessOutput.cpp
Although the extrapolation is not correct for partitioned domains, it is correct for non-partitioned projects and some people are using PETSc for its linear solvers in single threaded setup.
> Enable extrapolation in PETSc

- NumLib/TimeStepping/Algorithms/CreateFixedTimeStepping.cpp
- NumLib/TimeStepping/Algorithms/TimeStepAlgorithm.h
Improves error finding.
Removing the vector allocation would be better, but needs more time.
> bad_alloc catch in time loop creation

- ProcessLib/HT/HTFEM.h
This issue was recently raised by Boyan when he was testing his Koeln case study using the HT process. 
As can be seen in the following file HTFEM.h, the code is trying to calculate thermal_dispersivity value using the velocity vector and the velocity_magnitude. In case an inexperienced user sets an initial condition with uniform pressure values in the domain (I sometimes do it as well), the uniform pressure will lead to zero velocity values and hence exact zero for the velocity_magnitude. When left un-checked and passed on to the calculation of thermal_dispersivity, the "(thermal_dispersivity_longitudinal -           thermal_dispersivity_transversal) / velocity_magnitude" operation will deliver a "NAN" into the LHS matrix, and the linear solver will crash accordingly. For an …
> Fix NAN bug in the HT process

- Applications/Utils/FileConverter/CMakeLists.txt
- Applications/Utils/FileConverter/TecPlotTools.cpp
Currently can
* split TecPlot files containing multiple "zones" (i.e. timesteps, subdomains, etc.) into seperate tecplot files
* convert TecPlot files representing raster data into ogs-meshes (one file per zone, containing all variables as scalar arrays)
> TecPlot utility

- Applications/DataExplorer/DataView/MeshElementRemoval.ui
- Applications/DataExplorer/DataView/MeshElementRemovalDialog.cpp
- Applications/DataExplorer/DataView/MeshElementRemovalDialog.h
- Applications/Utils/MeshEdit/removeMeshElements.cpp
- MeshLib/MeshGenerators/RasterToMesh.cpp
- MeshLib/MeshSearch/ElementSearch.h
* works with arbitrary scalar arrays now (currently limited to int + double)
* allows inclusion and exclusion of value ranges
> Extension of element removal

- Applications/DataExplorer/VtkVis/CMakeLists.txt
- Applications/DataExplorer/VtkVis/VtkCompositeImageToPointCloudFilter.cpp
- Applications/DataExplorer/VtkVis/VtkCompositeImageToPointCloudFilter.h
- Applications/DataExplorer/VtkVis/VtkCompositeImageToSurfacePointsFilter.cpp
- Applications/DataExplorer/VtkVis/VtkCompositeImageToSurfacePointsFilter.h
- Applications/DataExplorer/VtkVis/VtkFilterFactory.cpp
- Applications/DataExplorer/VtkVis/VtkImageDataToPointCloudFilter.cpp
- Applications/DataExplorer/VtkVis/VtkImageDataToPointCloudFilter.h
- Applications/DataExplorer/VtkVis/VtkImageDataToSurfacePointsFilter.cpp
- Applications/DataExplorer/VtkVis/VtkImageDataToSurfacePointsFilter.h
Two VTK filters to represent raster data as point clouds + integration into Data Explorer
1. Varying desity based on pixel value
2. Representing pixel values as surface
> Raster to Point Cloud Filters

- BaseLib/quicksort.h
- MeshGeoToolsLib/BoundaryElementsAlongPolyline.cpp
- MeshGeoToolsLib/BoundaryElementsAlongPolyline.h
- MeshGeoToolsLib/BoundaryElementsAtPoint.cpp
- MeshGeoToolsLib/BoundaryElementsAtPoint.h
- MeshGeoToolsLib/BoundaryElementsOnSurface.cpp
- MeshGeoToolsLib/BoundaryElementsOnSurface.h
- MeshGeoToolsLib/BoundaryElementsSearcher.cpp
- MeshGeoToolsLib/BoundaryElementsSearcher.h
Preparation PR for the constraint boundary condition PR that will be created soon.
> BoundaryElementSearch: Return bulk element id and bulk element face id.

- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.h
- ProcessLib/HydroMechanics/HydroMechanicsProcess.cpp
- ProcessLib/HydroMechanics/HydroMechanicsProcess.h
- ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.h
- ProcessLib/LIE/SmallDeformation/SmallDeformationProcess.cpp
- ProcessLib/LIE/SmallDeformation/SmallDeformationProcess.h
- ProcessLib/PhaseField/PhaseFieldProcess.cpp
- ProcessLib/PhaseField/PhaseFieldProcess.h
- ProcessLib/RichardsFlow/RichardsFlowProcess.h
- ProcessLib/SmallDeformation/SmallDeformationProcess.cpp
- ProcessLib/SmallDeformation/SmallDeformationProcess.h
- ProcessLib/ThermoMechanicalPhaseField/ThermoMechanicalPhaseFieldProcess-impl.h
- ProcessLib/ThermoMechanicalPhaseField/ThermoMechanicalPhaseFieldProcess.h
- ProcessLib/ThermoMechanics/ThermoMechanicsProcess.cpp
- ProcessLib/ThermoMechanics/ThermoMechanicsProcess.h
Was probably needed when `Process` was a template. Obsolete now.
> Remove unneeded Base ns specifier

- GeoLib/GEOObjects.h
- MeshGeoToolsLib/BoundaryElementsAtPoint.cpp
- MeshLib/Elements/EdgeReturn.cpp
- MeshLib/Elements/HexRule20.cpp
- MeshLib/Elements/HexRule8.cpp
- MeshLib/Elements/PrismRule15.cpp
- MeshLib/Elements/PrismRule6.cpp
- MeshLib/Elements/PyramidRule13.cpp
- MeshLib/Elements/PyramidRule5.cpp
- MeshLib/Elements/TetRule10.cpp
- MeshLib/Elements/TetRule4.cpp
- MeshLib/MeshEditing/DuplicateMeshComponents.cpp
- MeshLib/MeshEditing/DuplicateMeshComponents.h
- MeshLib/MeshSubset.h
- NumLib/DOF/ComponentGlobalIndexDict.h
- NumLib/DOF/MeshComponentMap.cpp
- NumLib/DOF/MeshComponentMap.h
- ProcessLib/BoundaryCondition/BoundaryCondition.cpp
- ProcessLib/BoundaryCondition/BoundaryCondition.h
- ProcessLib/LIE/BoundaryCondition/BoundaryConditionBuilder.cpp
- Tests/NumLib/TestMeshComponentMap.cpp
A set of basic changes required for the actual "Move BC meshes #2141" PR.
> Move BC meshes; preparations

- Applications/Utils/MeshGeoTools/CMakeLists.txt
- Applications/Utils/MeshGeoTools/ConstructMeshesFromGeometry.cpp
- netlify.toml
- web/config.toml
- web/content/docs/tools/model-preparation/constructMeshesFromGeometry/index.pandoc
- web/content/docs/tools/model-preparation/constructMeshesFromGeometry/single_fracture_3D_geometries.png
Command line interface to the MeshGeoToolsLib's construct meshes from geometries function.
Needed for automated conversion when multiple meshes will be supported by the project files.
Also good for checking your geometrical input!
> [A/U] Add CLI to construct meshes from geometries.

- .appveyor.yml
VTK 8.1 binary packages are built for 2017 only.
> [appveyor] Bumped Visual Studio to 2017, never build Conan packages.

- Documentation/ProjectFile/prj/processes/process/THERMO_MECHANICS/t_reference_temperature.md
- ProcessLib/ThermoMechanics/CreateThermoMechanicsProcess.cpp
- ProcessLib/ThermoMechanics/Tests.cmake
- ProcessLib/ThermoMechanics/ThermoMechanicsFEM.h
- ProcessLib/ThermoMechanics/ThermoMechanicsProcessData.h
- Tests/Data/ThermoMechanics/CreepBGRa/SimpleAxisymmetricCreep/SimpleAxisymmetricCreep.prj
- Tests/Data/ThermoMechanics/CreepBGRa/SimpleAxisymmetricCreep/SimpleAxisymmetricCreepWithAnalyticSolution.prj
- Tests/Data/ThermoMechanics/cube_1e3.prj
- Tests/Data/ThermoMechanics/iglu_axisymmetric_plane_strain.prj
- Tests/Data/ThermoMechanics/iglu_axisymmetric_plane_strain_quad.prj
- Tests/Data/ThermoMechanics/iglu_quarter_plane_strain.prj
- Tests/Data/ThermoMechanics/iglu_quarter_plane_strain_quad.prj
Use the temperature increment dT instead of the global temperature change T-T_0 in the thermal strain calculation. Also this PR corrects the thermal strain calculation with initial temperature.
In the current master, the thermal strain increment is calculated by 
Such calculation is simplified in  this PR as
and the parameter of reference_temperature is dropped.
Note: In the current repository, the calculation of total strain increment takes the same calculation approach as that for thermal strain increment, which uses extra more memory by storing vectors of eps_prev and eps_m at each Gauss point. This will be improved later for all mechanics related processes.
> Improve TM process

- MeshLib/MeshGenerators/VtkMeshConverter.cpp
- MeshLib/MeshGenerators/VtkMeshConverter.h
- MeshLib/VtkOGSEnum.cpp
Add missing conversions and forbid default case in the first commit.
clang-format is necessary, because the rest of the switch-cases is out of alignment otherwise.
> MeshLib point vertex VTK conversion

- Applications/DataExplorer/DataView/DiagramView/CMakeLists.txt
- Applications/DataExplorer/DataView/DiagramView/DiagramList.cpp
- Applications/DataExplorer/DataView/DiagramView/DiagramList.h
- Applications/DataExplorer/DataView/DiagramView/DiagramPrefs.ui
- Applications/DataExplorer/DataView/DiagramView/DiagramPrefsDialog.cpp
- Applications/DataExplorer/DataView/DiagramView/DiagramScene.cpp
- Applications/DataExplorer/DataView/DiagramView/DiagramScene.h
- Applications/DataExplorer/DataView/DiagramView/GetDateTime.h
- Applications/DataExplorer/DataView/DiagramView/QArrow.cpp
- Applications/DataExplorer/DataView/DiagramView/QArrow.h
When visualising a time series as a diagram, limiting the time range works as intended now.
Also fixed a number of implicit data type conversion warnings.
> Fixed issue with limiting the date range on time series data

- MaterialLib/SolidModels/CreateCreepBGRa.cpp
- MaterialLib/SolidModels/CreepBGRa.cpp
- MaterialLib/SolidModels/CreepBGRa.h
- Tests/Data/ThermoMechanics/CreepBGRa/CreepAfterExcavation/CreepAfterExcavation.prj
- Tests/Data/ThermoMechanics/CreepBGRa/CreepAfterExcavation/ExpectedCreepAfterExcavation_pcs_0_ts_61_t_4320000.000000.vtu
- Tests/Data/ThermoMechanics/CreepBGRa/CreepAfterExcavation/mesh.vtu
- Tests/Data/ThermoMechanics/CreepBGRa/SimpleAxisymmetricCreep/SimpleAxisymmetricCreep.prj
- Tests/Data/ThermoMechanics/CreepBGRa/SimpleAxisymmetricCreep/SimpleAxisymmetricCreepWithAnalyticSolution.prj
- web/content/docs/benchmarks/creep-after-excavation-bgra/CreepAfterExcavation.md
- web/content/docs/benchmarks/creep-after-excavation-bgra/strain.png
- web/content/docs/benchmarks/creep-after-excavation-bgra/stress_xx_yy_110.png
- web/content/docs/benchmarks/creep-after-excavation-bgra/stress_xx_yy_20.png
- web/content/docs/benchmarks/creep-after-excavation-bgra/stress_xx_yy_50.png
- web/content/docs/benchmarks/creepbgra/CreepBRGa.md
The member type is changed from double to Parameter. One test of BGRa is changed to use different parameters of BGRa creep model with the new source code change.
> Changed the type of paramter members of  CreepBGRa

- Applications/Utils/ModelPreparation/PartitionMesh/NodeWiseMeshPartitioner.cpp
- Applications/Utils/ModelPreparation/PartitionMesh/NodeWiseMeshPartitioner.h
- Applications/Utils/ModelPreparation/PartitionMesh/PartitionMesh.cpp
- Applications/Utils/Tests.cmake
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_EAST.vtu
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_EAST_partitioned_msh_cfg3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_EAST_partitioned_msh_ele3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_EAST_partitioned_msh_ele_g3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_EAST_partitioned_msh_nod3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_NORTH.vtu
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_NORTH_partitioned_msh_cfg3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_NORTH_partitioned_msh_ele3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_NORTH_partitioned_msh_nod3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_SOUTH.vtu
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_SOUTH_partitioned_msh_cfg3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_SOUTH_partitioned_msh_ele3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_SOUTH_partitioned_msh_nod3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_WEST.vtu
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_WEST_partitioned_msh_cfg3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_WEST_partitioned_msh_ele3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_WEST_partitioned_msh_ele_g3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_PLY_WEST_partitioned_msh_nod3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_POINT4.vtu
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_POINT4_partitioned_msh_cfg3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_POINT4_partitioned_msh_ele3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_POINT4_partitioned_msh_nod3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_POINT5.vtu
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_POINT5_partitioned_msh_cfg3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_POINT5_partitioned_msh_ele3.bin
- Tests/Data/NodePartitionedMesh/partmesh_2Dmesh_3partitions/2Dmesh_POINT5_partitioned_msh_nod3.bin
Follow up of #2177 (MeshLib vertex point vtk conversion).
Further refactorings (mainly free-functions) to the NodeWiseMeshPartitioner.
Extension of the partmesh tool to partition boundary meshes (with ctests).
> Partition boundary meshes

- Applications/DataExplorer/DataView/DiagramView/DiagramList.cpp
- Applications/DataExplorer/DataView/DiagramView/DiagramList.h
- Applications/DataExplorer/DataView/FemConditionModel.h
- Applications/DataExplorer/mainwindow.cpp
- Applications/FileIO/FEFLOW/FEFLOWMeshInterface.cpp
- Applications/FileIO/XmlIO/Qt/XmlPrjInterface.cpp
- Applications/Utils/GeoTools/MoveGeometry.cpp
- Applications/Utils/GeoTools/TriangulatePolyline.cpp
- Applications/Utils/OGSFileConverter/OGSFileConverter.cpp
- GeoLib/IO/XmlIO/Boost/BoostXmlGmlInterface.cpp
- GeoLib/IO/XmlIO/Qt/XmlGmlInterface.cpp
- scripts/cmake/CompilerSetup.cmake
As titled. If the DataExplorer reads an erroneous file an exception is thrown within the XML GML Qt interface. ~~For a robust DataExplorer the exception shall be caught, but isn't yet. @rinkk This is for discussion.~~
Fixes the issue #2182 .
Update: Catched exceptions.
> Small improvements and bug fix in XML GML part

- MaterialLib/PorousMedium/UnsaturatedProperty/CapillaryPressure/BrooksCoreyCapillaryPressureSaturation.h
- MaterialLib/PorousMedium/UnsaturatedProperty/CapillaryPressure/CapillaryPressureSaturation.h
- MaterialLib/PorousMedium/UnsaturatedProperty/CapillaryPressure/CapillaryPressureSaturationCurve.h
- MaterialLib/PorousMedium/UnsaturatedProperty/CapillaryPressure/VanGenuchtenCapillaryPressureSaturation.cpp
- MaterialLib/PorousMedium/UnsaturatedProperty/CapillaryPressure/VanGenuchtenCapillaryPressureSaturation.h
- MathLib/Curve/PiecewiseLinearMonotonicCurve.cpp
- MathLib/Curve/PiecewiseLinearMonotonicCurve.h
- ProcessLib/RichardsFlow/RichardsFlowFEM.h
- ProcessLib/RichardsFlow/RichardsFlowMaterialProperties.cpp
- ProcessLib/RichardsFlow/RichardsFlowMaterialProperties.h
- Tests/MathLib/TestPiecewiseLinearCurve.cpp
- scripts/cmake/ClangSanitizer.cmake
A set of smaller fixes and extension of the unsaturated material model by permeability derivative and second derivative of capillary pressure wrt saturation. The derivatives are used in the RichardsMechanics process implementation in the following PR.
> Richards and material models

- scripts/cmake/ClangSanitizer.cmake
- scripts/cmake/CompilerSetup.cmake
Lists in cmake are separated with semicolon contrary to the environment variables.
If you know other places with same pattern, feel free to push to this branch...
> cmake; Separate compile flags with ; not with ' '.

- MeshLib/Mesh.cpp
Since (most) parts of the Mesh are not dependent on this property, this is merely a warning.
It would be better, though, to run this check only for algorithms relying on this property. Does anybody knows such algorithms? @rinkk , @TomFischer ?
There, the check must be a hard error, not just a warning.
Related to https://github.com/ufz/ogs/pull/1495
> [MeL] Change checkNonlinearNodeId msg to warning.

- MaterialLib/SolidModels/CreepBGRa.cpp
> [BGRa] A bug fixing: return try stress if the norm of its deviator is zero

- CMakeLists.txt
- Jenkinsfile
- scripts/cmake/ConanSetup.cmake
- web/content/docs/devguide/advanced/conan-package-manager.pandoc
- web/content/docs/devguide/getting-started/build-configuration.pandoc
- web/content/docs/devguide/troubleshooting/conan.pandoc
Use Conan as default when its executable is found. Developer having Conan installed typically also want to use it for third-party library handling. This avoids strange things happening when switching Conan to ON from the CMake GUI.
If you don't want to use Conan:
- Do not have `conan` in your `PATH`, **OR**
- Set `OGS_USE_CONAN=OFF`
@HaibingShao With this merged you can again use the CMake GUI for the initial CMake run if you like...
> Use Conan per default when available

- Applications/CLI/ogs.cpp
- Applications/CLI/ogs_embedded_python.cpp
- Applications/DataExplorer/DataView/MeshElementRemovalDialog.cpp
- Applications/DataExplorer/VtkVis/VisualizationWidget.cpp
- Applications/DataExplorer/VtkVis/VtkImageDataToSurfacePointsFilter.cpp
- Applications/FileIO/CMakeLists.txt
- GeoLib/IO/XmlIO/Qt/XmlGmlInterface.cpp
- Jenkinsfile
- ProcessLib/BoundaryCondition/CreateBoundaryCondition.cpp
- ProcessLib/BoundaryCondition/NonuniformDirichletBoundaryCondition.cpp
- ProcessLib/BoundaryCondition/NonuniformDirichletBoundaryCondition.h
- Tests/FileIO_Qt/TestQtPrjInterface.cpp
- scripts/cmake/CompilerSetup.cmake
See https://jenkins.io/blog/2018/09/11/speaker-blog-warnings-plugin/
Provides a better overview over warnings. I suggest to
> [Jenkins] New warnings publisher syntax

- web/content/docs/benchmarks/creep-after-excavation-bgra/CreepAfterExcavation.pandoc
- web/content/docs/benchmarks/creepbgra/CreepBRGa.pandoc
1. CreepBRGa.pandoc:  $\mathbf{C}: = \lambda  \mathcal{J} + 2G \mathbf I \otimes \mathbf I$ cannot be displayed after recent commits. Change it to $\mathbf{C} = \lambda  \mathcal{J} + 2G \mathbf I \otimes \mathbf I$
2. CreepAfterExcavation.pandoc: the table of material properties.
> [web/BGRa] Recovered the display of the formula of the elastic tensor and a table

- scripts/cmake/ConanSetup.cmake
- scripts/cmake/packaging/Pack.cmake
As reported by @KeitaYoshioka:
- `conan_add_remote()` in `ConanSetup.cmake` requires Conan 1.3.0
- On macOS on Debug build with PETSc there are directories containing `.dylib` which throw an error when trying to install as files
> CMake fixes

- Applications/Utils/MeshGeoTools/CMakeLists.txt
- Applications/Utils/MeshGeoTools/IdentifySubdomains.cpp
- Applications/Utils/Tests.cmake
- Jenkinsfile
- MeshGeoToolsLib/IdentifySubdomainMesh.cpp
- MeshGeoToolsLib/IdentifySubdomainMesh.h
- MeshGeoToolsLib/MeshNodeSearcher.cpp
- MeshGeoToolsLib/MeshNodeSearcher.h
- Tests/Data/MeshGeoToolsLib/IdentifySubdomains/2D_mesh.vtu
- Tests/Data/MeshGeoToolsLib/IdentifySubdomains/2D_mesh_bottom.vtu
- Tests/Data/MeshGeoToolsLib/IdentifySubdomains/2D_mesh_bottom_boundary.vtu
- Tests/Data/MeshGeoToolsLib/IdentifySubdomains/2D_mesh_top.vtu
- Tests/Data/MeshGeoToolsLib/IdentifySubdomains/2D_mesh_top_boundary.vtu
- web/content/docs/tools/model-preparation/identifySubdomains/disc_with_hole_and_bondary.png
- web/content/docs/tools/model-preparation/identifySubdomains/index.pandoc
- web/content/docs/tools/model-preparation/identifySubdomains/new_quater_circle.vtu
- web/content/docs/tools/model-preparation/identifySubdomains/quater_circle.vtu
Creates/updates/verifies bulk_node_ids and bulk_element_ids in subdomain meshes.
Test and docu included.
> Identify subdomains tool.

- CMakeLists.txt
- web/content/docs/devguide/advanced/configuration-options.pandoc
`;`-separated list of processes to build, e.g.:
```
cmake . -DOGS_BUILD_PROCESSES="HT;LIE"
```
As requested by @OlafKolditz.
Bumped CMake version to 3.3 (from 2015-07) because of `if(X IN_LIST Y)`-syntax.
> [CMake] Added option OGS_BUILD_PROCESSES.

- Applications/Utils/ModelPreparation/PartitionMesh/CMakeLists.txt
> [CMake] Do not build partmesh on gcc 5.4.

- Documentation/ProjectFile/prj/processes/process/jacobian_assembler/CentralDifferences/c_CentralDifferences.md
- Documentation/ProjectFile/prj/processes/process/jacobian_assembler/CentralDifferences/t_component_magnitudes.md
- Documentation/ProjectFile/prj/processes/process/jacobian_assembler/CentralDifferences/t_relative_epsilons.md
- Documentation/ProjectFile/prj/processes/process/jacobian_assembler/CompareJacobians/c_CompareJacobians.md
- Documentation/ProjectFile/prj/processes/process/jacobian_assembler/CompareJacobians/t_abs_tol.md
- Documentation/ProjectFile/prj/processes/process/jacobian_assembler/CompareJacobians/t_fail_on_error.md
- Documentation/ProjectFile/prj/processes/process/jacobian_assembler/CompareJacobians/t_jacobian_assembler.md
- Documentation/ProjectFile/prj/processes/process/jacobian_assembler/CompareJacobians/t_log_file.md
- Documentation/ProjectFile/prj/processes/process/jacobian_assembler/CompareJacobians/t_reference_jacobian_assembler.md
- Documentation/ProjectFile/prj/processes/process/jacobian_assembler/CompareJacobians/t_rel_tol.md
- Documentation/ProjectFile/prj/processes/process/jacobian_assembler/i_jacobian_assembler.md
- Documentation/ProjectFile/prj/processes/process/jacobian_assembler/t_component_magnitudes.md
- Documentation/ProjectFile/prj/processes/process/jacobian_assembler/t_relative_epsilons.md
- Documentation/ProjectFile/prj/processes/process/jacobian_assembler/t_type.md
- ProcessLib/AbstractJacobianAssembler.h
- ProcessLib/CentralDifferencesJacobianAssembler.cpp
- ProcessLib/CentralDifferencesJacobianAssembler.h
- ProcessLib/CompareJacobiansJacobianAssembler.cpp
- ProcessLib/CompareJacobiansJacobianAssembler.h
- ProcessLib/CreateJacobianAssembler.cpp
As requested, here comes a simple implementation of the Jacobian tester.
Configuration in the `prj` file:
```xml
<OpenGeoSysProject>
<processes>
<process>
<jacobian_assembler>
<type>CompareJacobians</type>
<jacobian_assembler>
<type>CentralDifferences</type>
<component_magnitudes>1 1</component_magnitudes>
<relative_epsilons>1e-8 1e-8</relative_epsilons>
</jacobian_assembler>
<reference_jacobian_assembler>
<type>CentralDifferences</type>
<component_magnitudes>1 1</component_magnitudes>
<relative_epsilons>1e-6 1e-6</relative_epsilons>
</reference_jacobian_assembler>
<abs_tol>1e-18</abs_tol>
<rel_tol>1e-7</rel_tol>
<fail_on_error>true</fail_on_error>
<log_file>/tmp/test.log</log_file>
</jacobian_assembler>
```
<details>
<summary>Sample (Python) log file (Click to expand)</summary>
```python …
```
> Jacobian tester for local assemblers.

- ProcessLib/LiquidFlow/LiquidFlowLocalAssembler-impl.h
- ProcessLib/LiquidFlow/LiquidFlowLocalAssembler.h
Use IntegrationPointData to accelerate the assembly. This saves ~ 3 % of the total run time for the two large benchmark cases.
> Liquid flow improvements

- web/content/docs/benchmarks/creepbgra/CreepBRGa.pandoc
as titled. Thanks  @KeitaYoshioka for pointing out these.
> [web/BGRa] Corrected two typos and made a consistency of one symbol within the context

- Applications/Utils/MeshGeoTools/IdentifySubdomains.cpp
- Applications/Utils/Tests.cmake
- MeshGeoToolsLib/IdentifySubdomainMesh.cpp
- Tests/Data/MeshGeoToolsLib/IdentifySubdomains/river_bc.vtu
- Tests/Data/MeshGeoToolsLib/IdentifySubdomains/river_bc_prism.vtu
- Tests/Data/MeshGeoToolsLib/IdentifySubdomains/river_bc_triangle.vtu
- Tests/Data/MeshGeoToolsLib/IdentifySubdomains/river_domain_prism.vtu
- Tests/Data/MeshGeoToolsLib/IdentifySubdomains/river_domain_triangle.vtu
Upon request for Dirichlet BCs inside of the domain defined along lines.
@Thomas-TK Could you provide an example?
> [MGTL] Allow multiple bulk element ids in identify

- Applications/ApplicationsLib/ProjectData.cpp
When the python modules are not in the current working directory but
in the projects directory, the user modules would not be found.
Adding project's directory to the python's module path allows to run ogs
from a different directory than the project file.
The error occurs, for example, if running the python piston  benchmark from the build directory like
```sh
bin/ogs ../ogs_source_dir/Tests/Data/Mechanics/Linear/PythonPiston/piston.prj
```
It would fail to load the `chamber` module from the [project directory](https://github.com/ufz/ogs/tree/master/Tests/Data/Mechanics/Linear/PythonPiston).
> [App] Add project dir to python module path.

- Applications/DataExplorer/DataView/DirectConditionGenerator.cpp
- Applications/DataExplorer/DataView/ElementTreeModel.cpp
- Applications/Utils/FileConverter/generateMatPropsFromMatID.cpp
- Applications/Utils/MeshEdit/queryMesh.cpp
- Applications/Utils/ModelPreparation/PartitionMesh/NodeWiseMeshPartitioner.cpp
- Applications/Utils/ModelPreparation/PartitionMesh/PartitionMesh.cpp
- Applications/Utils/ModelPreparation/createNeumannBc.cpp
- MaterialLib/PorousMedium/CreatePorousMediaProperties.cpp
- MeshGeoToolsLib/AppendLinesAlongPolyline.cpp
- MeshGeoToolsLib/IdentifySubdomainMesh.cpp
- MeshLib/Mesh.cpp
- MeshLib/MeshEditing/ElementValueModification.cpp
- MeshLib/MeshSearch/ElementSearch.h
- MeshLib/Properties-impl.h
- MeshLib/Properties.h
- NumLib/DOF/MeshComponentMap.cpp
- ProcessLib/BoundaryCondition/ConstraintDirichletBoundaryCondition.cpp
- ProcessLib/BoundaryCondition/NonuniformDirichletBoundaryCondition.cpp
- ProcessLib/BoundaryCondition/Python/PythonBoundaryCondition.cpp
- ProcessLib/BoundaryCondition/Python/PythonBoundaryConditionLocalAssembler.h
- ProcessLib/LIE/Common/MeshUtils.cpp
- ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.cpp
- ProcessLib/LiquidFlow/CreateLiquidFlowProcess.cpp
- ProcessLib/RichardsFlow/CreateRichardsFlowProcess.cpp
- ProcessLib/SurfaceFlux/SurfaceFlux.cpp
- ProcessLib/TwoPhaseFlowWithPP/CreateTwoPhaseFlowWithPPProcess.cpp
Using the new overloaded `Properties::getPropertyVector()`  the user can specify additionally to the data type and the name also the `MeshItemType` and the number of components.  These features don't need to be tested later in the user code.
> Use new overloaded getPropertyVector

- Documentation/ProjectFile/prj/processes/process/HEAT_TRANSPORT_BHE/borehole_heat_exchangers/borehole_heat_exchanger/pipes/inlet/t_diameter.md
- Documentation/ProjectFile/prj/processes/process/HEAT_TRANSPORT_BHE/borehole_heat_exchangers/borehole_heat_exchanger/pipes/inlet/t_radius.md
- ProcessLib/HeatTransportBHE/BHE/BHE_1U.cpp
- ProcessLib/HeatTransportBHE/BHE/BHE_1U.h
- ProcessLib/HeatTransportBHE/BHE/Physics.h
- ProcessLib/HeatTransportBHE/BHE/Pipe.cpp
- ProcessLib/HeatTransportBHE/BHE/Pipe.h
- ProcessLib/HeatTransportBHE/BHE/ThermoMechanicalFlowProperties.h
- Tests/Data/Parabolic/T/3D_Beier_sandbox/beier_sandbox.prj
- Tests/Data/Parabolic/T/3D_Beier_sandbox/fixed_power_constant_flow.prj
Use already extracted code. This prevents code duplication for 2U and the CXA/CXC implementations.
@ChaofanChen Could you please review this?
> BHE_1U flow properties update and bugfixes.

- ProcessLib/HeatTransportBHE/BHE/CreateFlowAndTemperatureControl.cpp
- ProcessLib/HeatTransportBHE/BHE/CreateFlowAndTemperatureControl.h
When adding cases of the CXA/CXC or 2U BHE, we also need to call the function named "createFlowAndTemperatureControl", and this will cause an error that multiple inclusion of the same definition in header file when compiling. Besides, we also need to enrich flow and temperature boundary conditions including the BHE coupled with heat pump.
> BHE; Move the function body in "CreateFlowAndTemperatureControl.h" to cpp file.

- BaseLib/Algorithm.h
- ProcessLib/LIE/Common/BranchProperty.h
- ProcessLib/LIE/Common/FractureProperty.h
- ProcessLib/LIE/Common/HMatrixUtils.h
- ProcessLib/LIE/Common/JunctionProperty.h
- ProcessLib/LIE/Common/LevelSetFunction.cpp
- ProcessLib/LIE/Common/LevelSetFunction.h
- ProcessLib/LIE/Common/PostUtils.cpp
- ProcessLib/LIE/Common/Utils.h
- ProcessLib/LIE/HydroMechanics/CreateHydroMechanicsProcess.cpp
- ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.cpp
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerFracture-impl.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerFracture.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerInterface.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrix-impl.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrix.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrixNearFracture-impl.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/LocalDataInitializer.h
- ProcessLib/LIE/SmallDeformation/CreateSmallDeformationProcess.cpp
- ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerFracture-impl.h
- ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerInterface.h
- ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerMatrixNearFracture-impl.h
- ProcessLib/LIE/SmallDeformation/SmallDeformationProcess.cpp
- ProcessLib/LIE/SmallDeformation/SmallDeformationProcessData.h
#2235 continued, especially addressing issues pointed out by @wenqing.
- Several renames
- Move some (generalized) algorithms to BaseLib (and fix msvc warnings)
- Use values where it is not necessary to pointers
- clang-format
- add braces around statements
> LIE intersect (continued).

- Applications/ApplicationsLib/ProjectData.cpp
- Documentation/ProjectFile/prj/time_loop/output/meshes/i_meshes.md
- Documentation/ProjectFile/prj/time_loop/output/meshes/t_mesh.md
- Documentation/ProjectFile/prj/time_loop/output/t_output_extrapolation_residuals.md
- Documentation/ProjectFile/prj/time_loop/processes/process/t_output.md
- ProcessLib/ComponentTransport/Tests.cmake
- ProcessLib/CreateProcessData.cpp
- ProcessLib/GroundwaterFlow/CreateGroundwaterFlowProcess.cpp
- ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.cpp
- ProcessLib/Output/CreateOutput.cpp
- ProcessLib/Output/CreateOutput.h
- ProcessLib/Output/Output.cpp
- ProcessLib/Output/Output.h
- ProcessLib/Output/ProcessOutput.cpp
- ProcessLib/Output/ProcessOutput.h
- ProcessLib/Output/SecondaryVariable.cpp
- ProcessLib/Output/SecondaryVariable.h
- ProcessLib/ProcessVariable.cpp
- ProcessLib/ProcessVariable.h
- ProcessLib/UncoupledProcessesTimeLoop.cpp
- ProcessLib/UncoupledProcessesTimeLoop.h
- Tests/Data/Parabolic/ComponentTransport/SimpleSynthetics/cube_1x1x1_hex_1e3_left_pcs_0_ts_0_t_0.000000.vtu
- Tests/Data/Parabolic/ComponentTransport/SimpleSynthetics/cube_1x1x1_hex_1e3_left_pcs_0_ts_1_t_1.000000.vtu
- Tests/Data/Parabolic/ComponentTransport/SimpleSynthetics/cube_1x1x1_hex_1e3_right_pcs_0_ts_0_t_0.000000.vtu
- Tests/Data/Parabolic/ComponentTransport/SimpleSynthetics/cube_1x1x1_hex_1e3_right_pcs_0_ts_1_t_1.000000.vtu
- Tests/Data/Parabolic/ComponentTransport/SimpleSynthetics/surfaceflux_component-transport_cube_1e3.prj
> Output primary variables on arbitrary meshes.

- ProcessLib/Process.cpp
The call was simply missing in the assembleWithJacobian().
Fixes #2317
> [PL] Fix source term integrate() call.

- ProcessLib/ThermoMechanics/LocalAssemblerInterface.h
- ProcessLib/ThermoMechanics/ThermoMechanicsFEM.h
- ProcessLib/ThermoMechanics/ThermoMechanicsProcess.cpp
- ProcessLib/ThermoMechanics/ThermoMechanicsProcess.h
These changes support reloading of strains from previous simulation results. Reloading of stress is already implemented.
> [ThermoMechanics] support reloading of strains in restart

- Applications/ApplicationsLib/ProjectData.cpp
- Documentation/ProjectFile/prj/processes/process/ComponentTransport/t_molecular_diffusion_coefficient.md
- Documentation/ProjectFile/prj/processes/process/ComponentTransport/t_solute_dispersivity_longitudinal.md
- Documentation/ProjectFile/prj/processes/process/ComponentTransport/t_solute_dispersivity_transverse.md
- MaterialLib/MPL/PropertyType.h
- ProcessLib/ComponentTransport/ComponentTransportFEM.h
- ProcessLib/ComponentTransport/ComponentTransportProcess.cpp
- ProcessLib/ComponentTransport/ComponentTransportProcessData.h
- ProcessLib/ComponentTransport/CreateComponentTransportProcess.cpp
- ProcessLib/ComponentTransport/CreateComponentTransportProcess.h
- ProcessLib/ComponentTransport/Tests.cmake
- ProcessLib/Utils/ProcessUtils.cpp
- ProcessLib/Utils/ProcessUtils.h
- Tests/Data/Elliptic/square_100x100_ComponentTransport/square_1e4_heterogeneity.prj
- Tests/Data/Parabolic/ComponentTransport/SimpleSynthetics/ConcentrationDiffusionAndStorage.prj
- Tests/Data/Parabolic/ComponentTransport/SimpleSynthetics/ConcentrationDiffusionOnly.prj
- Tests/Data/Parabolic/ComponentTransport/SimpleSynthetics/ConcentrationDiffusionOnly_3Components.prj
- Tests/Data/Parabolic/ComponentTransport/SimpleSynthetics/DiffusionAndStorageAndAdvection.prj
- Tests/Data/Parabolic/ComponentTransport/SimpleSynthetics/DiffusionAndStorageAndAdvectionAndDecay.prj
- Tests/Data/Parabolic/ComponentTransport/SimpleSynthetics/DiffusionAndStorageAndAdvectionAndDispersion.prj
- Tests/Data/Parabolic/ComponentTransport/SimpleSynthetics/DiffusionAndStorageAndAdvectionAndDispersionHalf.prj
- Tests/Data/Parabolic/ComponentTransport/SimpleSynthetics/DiffusionAndStorageAndGravityAndDispersionHalf.prj
- Tests/Data/Parabolic/ComponentTransport/SimpleSynthetics/surfaceflux_component-transport_cube_1e3.prj
- Tests/Data/Parabolic/ComponentTransport/VariableNeumannBoundary/vdbc_input.prj
- Tests/Data/Parabolic/ComponentTransport/elder/elder-python.prj
- Tests/Data/Parabolic/ComponentTransport/elder/elder.prj
- Tests/Data/Parabolic/ComponentTransport/goswami/goswami_input.prj
- Tests/Data/Parabolic/ComponentTransport/heterogeneous/ogs5_H_2D/ogs5_H_2d.prj
This pull request aims at extending the functionality of component transport process which now can be applicable for multiple component migration. Note that, this work is done using the newly developed multi-phase/-component library (#2303).
> [PL] Multi-component transport process

- ProcessLib/LocalAssemblerInterface.cpp
- ProcessLib/LocalAssemblerInterface.h
- ProcessLib/Process.cpp
- ProcessLib/Process.h
Some processes might require setup of the initial conditions dependent variables in local assemblers.
The new interface allows such implementations.
See https://github.com/endJunction/ogs/tree/RMSaturation branch changes of RichardsFlow process for usage.
> [PL] Infrastructure for setInitialConditions().

- .gitmodules
- CMakeLists.txt
- Documentation/ProjectFile/prj/parameters/parameter/Function/c_Function.md
- Documentation/ProjectFile/prj/parameters/parameter/Function/t_expression.md
- ProcessLib/Parameter/FunctionParameter.cpp
- ProcessLib/Parameter/FunctionParameter.h
- ProcessLib/Parameter/Parameter.cpp
- ThirdParty/ReadMe.md
- scripts/cmake/SubmoduleSetup.cmake
as titled. The implementation is based on exprtk (http://www.partow.net/programming/exprtk/index.html).
So far I named the new parameter type as "Function", but you might have better idea about the naming. let me know...
Remarks
- Currently "x", "y", "z" are supported as variables.
- Example of input files is
```
<parameter>
<name>initial_pressure</name>
<type>Function</type>
<expression>1000.0*9.81*(-z)</expression>
</parameter>
```
- For non-scalar parameters, `<expression>` definition should be given for each component. The number of parameter components is set by the number of given `<expression>`.
> support mathematical expressions in Parameter

- ProcessLib/BoundaryCondition/GenericNaturalBoundaryConditionLocalAssembler.h
- ProcessLib/BoundaryCondition/NeumannBoundaryConditionLocalAssembler.h
as titled. The change is needed to use `FunctionParameter`  to evaluate values for Neumann BC.
> [PL] support xyz-dependent parameters in Neumann bc

- Jenkinsfile
- ProcessLib/ComponentTransport/Tests.cmake
- ProcessLib/GroundwaterFlow/Tests.cmake
- ProcessLib/HT/Tests.cmake
- ProcessLib/HeatConduction/Tests.cmake
- ProcessLib/HeatTransportBHE/Tests.cmake
- ProcessLib/LIE/HydroMechanics/Tests.cmake
- ProcessLib/LiquidFlow/Tests.cmake
- ProcessLib/PhaseField/Tests.cmake
- ProcessLib/RichardsFlow/Tests.cmake
- ProcessLib/ThermalTwoPhaseFlowWithPP/Tests.cmake
- ProcessLib/ThermoMechanicalPhaseField/Tests.cmake
- ProcessLib/ThermoMechanics/Tests.cmake
- ProcessLib/TwoPhaseFlowWithPrho/Tests.cmake
- Tests/Data/Mechanics/EhlersDamageNonLocal/bar/fine/bar.prj
- Tests/Data/Mechanics/EhlersDamageNonLocal/bar/veryfine/bar.prj
- Tests/Data/PhaseField/square_line_h_400.prj
- Tests/Data/PhaseField/square_line_h_400_pcs_0_ts_2000_t_0.200000.vtu
- Tests/Data/PhaseField/square_shear_h_400.prj
- Tests/Data/PhaseField/square_shear_h_400_pcs_0_ts_4000_t_400.000000.vtu
- Tests/Data/ThermoMechanicalPhaseField/slab_5.prj
- Tests/Data/ThermoMechanicalPhaseField/tes_hx3_iglu.prj
- scripts/cmake/test/AddTestTester.cmake
- scripts/cmake/test/AddTestWrapper.cmake
- scripts/cmake/test/Test.cmake
WIP!
Idea: Move large tests into main Jenkinsfile and test if ufz/master runs. Then it is possible to check if all benchmarks added in CMake files with `Add_Test()` are really tested. This will not increase the overall run time of the Jenkins job as the large tests are conducted on another machine (@endJunction I plan to setup another spare PC here to relieve your machine..).
Related: #2053, #2054, #2055.
> Move large tests into main Jenkinsfile

- scripts/cmake/ConanSetup.cmake
Fixes mac jobs.
lzma dependency comes from:
```
boost_iostreams/1.66.0@bincrafters/stable
boost_level11group/1.66.0@bincrafters/stable
```
> [Conan] Explicitly use lzma/5.2.4@bincrafters/stable

- .lfsconfig
- web/content/docs/devguide/advanced/gitlab.pandoc
- web/content/docs/devguide/advanced/working-on-envinf1.pandoc
Our Artifactory at https://ogs.jfrog.io/ allows non-authenticated pushes for git lfs files in contrast to GitLab where user always needed to authenticate which was quite uncomfortable especially for new contributors.
We have no size limit on Artifactory so we should be safe for the future.
Related to #2347.
TODO after merge:
> Migrate LFS from GitLab to Artifactory

- Jenkinsfile
- web/content/docs/devguide/testing/jenkins.pandoc
When a commit message contains `[ci skip]` the Jenkins build will be skipped. Can be useful to not overload our CI system when testing is not necessary.
> [Jenkins] Added [ci skip] functionality.

- Applications/FileIO/FEFLOW/FEFLOWMeshInterface.cpp
- MeshLib/Elements/Element.cpp
- MeshLib/Elements/Element.h
- MeshLib/Mesh.cpp
- MeshLib/Mesh.h
- MeshLib/MeshGenerators/VtkMeshConverter.cpp
For the vtk meshes, where the node and element ids are already set (starting from 0, no gaps, etc) it is better to keep the original numbering. This comes in handy for pre- and post-processing, and sparse matrix bandwidth reduction.
> Don't reset node element ids always.

- ProcessLib/HydroMechanics/Tests.cmake
- ProcessLib/UncoupledProcessesTimeLoop.cpp
As titled. Getting all the solutions of previous time step has to be done before looping over coupled processes, because in some coupled problems all the PDEs have the coupling terms.
> [PL] Move solution assignment of previous time step forward

- ProcessLib/RichardsMechanics/Tests.cmake
- Tests/Data/RichardsMechanics/RichardsFlow_2d_small.prj
- Tests/Data/RichardsMechanics/Richards_2d.gml
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_0_t_0.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_104_t_2000.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_19_t_318.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_1_t_1.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_29_t_518.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_2_t_3.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_39_t_718.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_3_t_8.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_49_t_918.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_4_t_18.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_59_t_1118.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_5_t_38.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_69_t_1318.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_6_t_58.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_79_t_1518.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_7_t_78.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_89_t_1718.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_8_t_98.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_99_t_1918.000000.vtu
- Tests/Data/RichardsMechanics/Richards_2d_geometry_OBSERVATION_POINT_pcs_0_ts_9_t_118.000000.vtu
Just an example of a subdomain output and also just checking the combination of geometry input and multiple meshes output.
> Observation point output

- Applications/FileIO/Legacy/createSurface.cpp
The PR add testing of the return value of gmsh, which was silently omitted before. The check is related to the warnings about a return value of std::system call not being used.
No test case present. Needs checking by hand from data explorer.
> [App/IO] Check gmsh return value.

- Applications/DataExplorer/DataView/GeoTreeView.cpp
- Applications/DataExplorer/DataView/GeoTreeView.h
- Applications/DataExplorer/mainwindow.cpp
- Applications/DataExplorer/mainwindow.h
- GeoLib/GEOObjects.cpp
- GeoLib/GEOObjects.h
- Tests/Data/MeshGeoToolsLib/Hamburg/BrunnenGOK_Outline_ModellHH.gml
- Tests/GeoLib/TestPointToStationConversion.cpp
Converts geometry points into station objects.
A flag signals if all points should be converted or just the ones not used in any polyline or surface.
> Geo-point to station conversion

- BaseLib/ConfigTree.h
- BaseLib/Error.h
- BaseLib/RunTime.h
- NumLib/Assembler/SerialExecutor.h
- Tests/GeoLib/TestLineSegmentIntersect2d.cpp
- Tests/GeoLib/TestSortSegments.cpp
Some older VisualStudio compilers are no longer supported anyway.
> Cleanup _MSC_VER uses.

- Applications/Utils/Tests.cmake
- MeshLib/MeshSurfaceExtraction.cpp
- Tests/Data/MeshLib/Back.vtu
- Tests/Data/MeshLib/Front.vtu
- Tests/Data/MeshLib/Left.vtu
- Tests/Data/MeshLib/Right.vtu
- Tests/Data/MeshLib/cube_1x1x1_hex_1e3_layers_10.vtu
- web/content/docs/tools/meshing/extract-surface/CubeFrontRightBackLeft.png
- web/content/docs/tools/meshing/extract-surface/index.pandoc
Add the subsurface MaterialIDs to the extracted surface. This information can be further be used for setting the boundary conditions.
> Extend ExtractSurface tool

- Jenkinsfile
- scripts/cmake/packaging/Pack.cmake
Packaged OGS build with `OGS_USE_PYTHON=ON` has a dependency on the Python distribution (Python system modules) it was built with.
This PR adds the used Python version as a string to the package name and adds Windows packages without Python for easy distribution.
> Package non python

- Applications/Utils/FileConverter/MeshToRaster.cpp
- Applications/Utils/MeshEdit/moveMeshNodes.cpp
- MeshLib/MeshEditing/ProjectPointOnMesh.cpp
- MeshLib/MeshEditing/ProjectPointOnMesh.h
Adjusts the mesh on mesh mapping tool to use the functionality introduced in #2367
> Mesh on mesh mapping fix

- CMakeLists.txt
The list of libraries which are to be included or excluded
from the conan's list of required libraries must preceed
the conan include(ConanSetup) line. Otherwise the selection
does not have any effects.
> Fix conan (Default) vs System library selection

- CHANGELOG.md
- Documentation/ProjectFile/properties/property/LinearProperty/c_LinearProperty.md
- Documentation/ProjectFile/properties/property/LinearProperty/independent_variable/t_slope.md
- MaterialLib/MPL/Properties/LinearProperty.cpp
- Tests/MaterialLib/TestMPLLinearProperty.cpp
Changing from y_ref + m (p - p_ref) to y_ref (1 + m (p - p_ref)).
> [MPL] Change implementation of LinearProperty

- Applications/DataExplorer/Base/ImportFileTypes.h
- Applications/DataExplorer/CMakeLists.txt
- Applications/DataExplorer/DataExplorer.cmake
- Applications/DataExplorer/VtkVis/CMakeLists.txt
- Applications/DataExplorer/VtkVis/VtkCompositeTextureOnSurfaceFilter.cpp
- Applications/DataExplorer/mainwindow.cpp
- CMakeLists.txt
Adds an `OGS_USE_NETCDF` option with default being ON => no changes to current setup.
The NetCDF related code is wrapped in if conditions.
Background: The NetCDF library interface provided by paraview/vtk is used now, not the actual netcdf-cxx library. On some systems paraview/vtk installation does not provide the header files for the internally used interface. This leads to compilation problems of the DE. On the long run the netcdf-cxx library should be used directly, not the paraview/vtk interface to that library.
Closes https://github.com/ufz/ogs/issues/2379
> Make NetCDF optional.

- MathLib/CMakeLists.txt
Is required when CVode is installed in a non-standard location.
> [CMake] Added CVODE_INCLUDE_DIRS to MathLib.

- Applications/FileIO/SHPInterface.cpp
- Applications/FileIO/SHPInterface.h
* works only for 2D meshes
* works only for int/double arrays
* works only for cell-arrays (because the shape format can only assign value to shape-entities, i.e. polygons but not points ... this can be easily fixed via VTK point 2 cell, though)
> Expanded shape output to write scalar arrays to shape attribute table

- Applications/DataExplorer/VtkVis/VisualizationWidget.cpp
- Applications/DataExplorer/mainwindow.cpp
Probably since switching to the new QVTKWidget (#2432) the 3D view was not updated automatically upon item removal (e.g. mesh removal). I added a new signal/slot connect to fix this. I have not investigated why it worked before...
> [DE] Fixed 3D update on item removal

- Applications/DataExplorer/DataView/MeshElementRemovalDialog.cpp
- Applications/DataExplorer/NetCdfDialog/NetCdfConfigureDialog.cpp
- Applications/DataExplorer/VtkVis/VtkColorByHeightFilter.cpp
- Applications/DataExplorer/VtkVis/VtkColorLookupTable.cpp
- Applications/DataExplorer/VtkVis/VtkCompositeFilter.cpp
- Applications/DataExplorer/VtkVis/VtkCompositeFilter.h
- Applications/DataExplorer/VtkVis/VtkCompositeGeoObjectFilter.cpp
- Applications/DataExplorer/VtkVis/VtkImageDataToLinePolyDataFilter.cpp
- Applications/DataExplorer/VtkVis/VtkImageDataToPointCloudFilter.cpp
- Applications/DataExplorer/VtkVis/VtkRaster.cpp
- Applications/DataExplorer/VtkVis/VtkSurfacesSource.cpp
- Applications/FileIO/XmlIO/Qt/XmlNumInterface.cpp
- Applications/Utils/ModelPreparation/PartitionMesh/NodeWiseMeshPartitioner.cpp
- MeshLib/MeshGenerators/RasterToMesh.cpp
- scripts/cmake/CompilerSetup.cmake
The CMake change supresses the display of lots of warnings from external libraries (Qt/VTK) when using Visual Studio.
Also fixing a few conversion warnings in our code.
> Fixing warnings

- Applications/DataExplorer/Base/StrictDoubleValidator.h
- Applications/DataExplorer/DataView/GMSHPrefs.ui
- Applications/DataExplorer/DataView/GMSHPrefsDialog.cpp
Previous implementation didn't work with small value ranges for some reason (such as GMSH preferences where some params need to be in [0;1]).
This fixes an issue with unchangable parameter values in the GMSH dialog.
Also adjusts the minimum default value for parameters to something more reasonable.
(No entry to the changelog because this was supposed to work anyway. I *think* it *did* work in the past, possibly something was changed in QDoubleValidator?)
> [DE] Re-implementing strict double validation

- Applications/DataExplorer/Base/TreeModelIterator.cpp
Fixes issue where first index would be pushed to the stack twice, causing the iterator to traverse the tree again after finishing.
> [DE] Fixes index-stack-error in TreeModelIterator

- ProcessLib/ComponentTransport/Tests.cmake
The name in Ctest file was wrong causing test failure.
Fixes #2477
> [T] Reference concentration array name changend

- ProcessLib/ComponentTransport/ComponentTransportFEM.h
Extracted from https://github.com/ufz/ogs/pull/2466, because unrelated to BC changes.
Already reviewed; can be merged when tests pass.
> HC surface flux now calculates mass flux

- Documentation/ProjectFile/prj/time_loop/output/meshes/i_meshes.md
- ProcessLib/Output/Output.cpp
- ProcessLib/Output/Output.h
- ProcessLib/Output/ProcessOutput.cpp
- ProcessLib/Output/ProcessOutput.h
- ProcessLib/Output/SecondaryVariable.h
Replacing the previous attempt https://github.com/ufz/ogs/pull/2471.
Only if the output meshes list is empty, write it.
As requested by @ErikNixdorf
Some refactorings included avoiding code duplication.
The bulk mesh output and the observation meshes outputs are identical now but for the pvd files. The pvd files need some refactorings before => another PR.
> Output only explicitly given meshes

- Applications/ApplicationsLib/ProjectData.cpp
- Applications/Utils/FileConverter/GocadSGridReaderMain.cpp
- Applications/Utils/MeshEdit/ExtractSurface.cpp
- Applications/Utils/MeshEdit/ResetPropertiesInPolygonalRegion.cpp
- Applications/Utils/MeshGeoTools/constructMeshesFromGeometry.cpp
- Applications/Utils/MeshGeoTools/identifySubdomains.cpp
- MeshGeoToolsLib/BoundaryElementsAtPoint.cpp
- MeshGeoToolsLib/BoundaryElementsAtPoint.h
- MeshGeoToolsLib/BoundaryElementsSearcher.cpp
- MeshGeoToolsLib/BoundaryElementsSearcher.h
- MeshGeoToolsLib/ConstructMeshesFromGeometries.cpp
- MeshGeoToolsLib/ConstructMeshesFromGeometries.h
- MeshGeoToolsLib/MeshNodeSearcher.cpp
- MeshGeoToolsLib/MeshNodesOnPoint.cpp
- MeshGeoToolsLib/MeshNodesOnPoint.h
- Tests/GeoLib/CreateTestPoints.cpp
- Tests/GeoLib/CreateTestPoints.h
- Tests/GeoLib/TestGEOObjectsMerge.cpp
- Tests/MeshGeoToolsLib/TestConstructAdditionalMeshesFromGeoObjects.cpp
- Tests/MeshLib/TestBoundaryElementSearch.cpp
- Tests/NumLib/LocalToGlobalIndexMapMultiComponent.cpp
Some users (@Thomas-TK , @ErikNixdorf  and Janine) need a more robust constructMeshesFromGeometry tool. This PR allows to give a larger search radius eps to the tool such that several mesh nodes are located in the eps-ball. Then the mesh node with the smallest distance to the given point is choosen.
> Improve constructMeshFromGeometry

- scripts/cmake/CCacheSetup.cmake
ccache --print-config is not a valid option since
ccache 3.7. Using specific config access.
> [cmake] Use ccache --get-config for sloppiness.

- Applications/Utils/Tests.cmake
- scripts/cmake/test/MeshTest.cmake
- scripts/cmake/test/Test.cmake
testing the corresponding submodule PR (https://github.com/ufz/vtkdiff/pull/11).
> Vtkdiff; Mesh comparison option.

- ProcessLib/HT/CreateHTProcess.cpp
- ProcessLib/HT/HTFEM.h
- ProcessLib/HT/HTMaterialProperties.h
- ProcessLib/HT/MonolithicHTFEM.h
- ProcessLib/HT/StaggeredHTFEM-impl.h
- ProcessLib/HT/Tests.cmake
- Tests/Data/Parabolic/HT/ConstViscosity/square_5500x5500.prj
- Tests/Data/Parabolic/HT/FaultedCube/Ra_795_fault_bcgs_jacobi.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/CoupledPressureParabolicTemperatureParabolic.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/CoupledPressureParabolicTemperatureParabolicStaggered.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/IsothermalFluidFlow.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/IsothermalFluidFlowStaggered.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/IsothermalFluidFlowWithGravity.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/IsothermalFluidFlowWithGravityStaggered.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/PressureDiffusionTemperatureDiffusion.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/PressureDiffusionTemperatureDiffusionStaggered.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/PressureParabolicTemperatureParabolic.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/PressureParabolicTemperatureParabolicStaggered.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/calculatesurfaceflux_ht_cube_1e3.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/calculatesurfaceflux_ht_cube_1e4.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/constraint_bc_1e3.prj
- Tests/Data/Parabolic/HT/StaggeredCoupling/ConstViscosity/square_5500x5500_staggered_scheme.prj
- Tests/Data/Parabolic/HT/StaggeredCoupling/ConstViscosity/square_5500x5500_staggered_scheme_adaptive_dt.prj
Using MPL for solid phase properties needs also changes in the project files. For the benchmarks this is done in this PR.
2. [x] All HT-Tests were changed, except the decovalex test since these tests use mesh parameters that are not implemented yet in the MPL. As soon as we can use a parameter as MPL::Property we can reenable the tests.
> [HT] Use MPL for solid phase properties.

- ProcessLib/HT/MonolithicHTFEM.h
- ProcessLib/HT/StaggeredHTFEM-impl.h
- scripts/docker/Dockerfile.clang.full
- scripts/docker/Dockerfile.gcc.full
- scripts/docker/Dockerfile.gcc.gui
Update servers for 17.10 were not available anymore.
Fixes Jenkins job errors in Docker-GUI.
> [Jenkins] Update docker base image to Ubuntu 18.04

- Jenkinsfile
- MaterialLib/SolidModels/Lubby2.h
- scripts/docker/Dockerfile.gcc.full
- scripts/docker/Dockerfile.gcc.gui
Corresponding change: https://github.com/ufz/ogs-container-maker/commit/79241adda9744ae4ee12ef88417a249807620599.
Merge when green.
> [Docker] Use default gcc (7.3) on Ubuntu.

- NumLib/TimeStepping/Algorithms/IterationNumberBasedTimeStepping.cpp
- NumLib/TimeStepping/Algorithms/IterationNumberBasedTimeStepping.h
- ProcessLib/UncoupledProcessesTimeLoop.cpp
- Tests/NumLib/TestTimeSteppingFixed.cpp
- Tests/NumLib/TestTimeSteppingIterationNumber.cpp
Introduced information flow whether the timestep was accepted or not.
This prevents the times in the timestepper and the external loop to diverge
which causes two issues otherwise:
1.) Endless loop at t --> t_end, if max_iter > largest multiplier
2.) Endless loop at t --> t_end, if nonlinear solver fails during
execution
> Fix on IterationNumberBasedTimeStepping

- MeshLib/MeshSurfaceExtraction.cpp
- MeshLib/MeshSurfaceExtraction.h
- Tests/Data/MeshLib/Back.vtu
- Tests/Data/MeshLib/Front.vtu
- Tests/Data/MeshLib/Left.vtu
- Tests/Data/MeshLib/Right.vtu
- Tests/Data/MeshLib/cube_1x1x1_hex_1e3_layers_10.vtu
Extended mesh surface extraction for both DataExplorer + CL-tool to also copy scalar arrays (both point- and cell-based). Currently only int and double arrays are transferred and tuple sizes > 1 are ignored.
1. [ x] Feature description was added to the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.2.1)
2. [ x] Tests covering your feature were added?
> Extract surface with scalar arrays

- BaseLib/FileFinder.h
- BaseLib/IO/XmlIO/Qt/XMLQtInterface.h
- GeoLib/IO/XmlIO/Qt/XmlGmlInterface.h
- GeoLib/IO/XmlIO/Qt/XmlStnInterface.h
- MathLib/LinAlg/Lis/LisOption.h
- MeshLib/IO/MPI_IO/NodePartitionedMeshReader.h
- NumLib/NamedFunctionCaller.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcessData.h
As reported by cppcheck, single argument ctors should be marked explicit.
Additionally add final specifier to the modified classes (where applicable).
Remove one defaulted dtor.
> Explicit constructors

- Applications/DataExplorer/DataView/ElementTreeModel.cpp
- Applications/Utils/MeshEdit/checkMesh.cpp
- MeshLib/MeshInformation.cpp
- MeshLib/MeshInformation.h
- MeshLib/convertMeshToGeo.cpp
- MeshLib/convertMeshToGeo.h
- ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.cpp
- Tests/FileIO/TestGmsInterface.cpp
- Tests/FileIO/TestTetGenInterface.cpp
- Tests/FileIO_SWMM/TestSwmmInterface.cpp
- Tests/MeshLib/TestRasterToMesh.cpp
Avoids variable shadowing of `vec_bounds` in two cases.
Adds stricter error checking.
Avoids use of sentinel values, which could be part of the input.
> Refactor mesh information value bounds

- web/content/docs/devguide/getting-started/build-configuration.pandoc
- web/content/docs/devguide/getting-started/build.pandoc
- web/content/docs/devguide/getting-started/get-the-source-code.pandoc
- web/content/docs/devguide/testing/unit-testing.pandoc
- web/layouts/shortcodes/asciinema.html
> [web] Embedded screen recordings with Asciinema

- ProcessLib/HT/HTFEM.h
- ProcessLib/HT/MonolithicHTFEM.h
The PR makes the code more readable.
> [HT] Use const vars for sizes and indexes in local assembly.

- ChemistryLib/CreatePhreeqcIO.cpp
- ChemistryLib/Output.cpp
- ChemistryLib/Output.h
- ChemistryLib/PhreeqcIO.cpp
- ChemistryLib/PhreeqcIO.h
- ChemistryLib/PhreeqcIOData/AqueousSolution.cpp
- ChemistryLib/PhreeqcIOData/AqueousSolution.h
- ChemistryLib/PhreeqcIOData/EquilibriumPhase.cpp
- ChemistryLib/PhreeqcIOData/EquilibriumPhase.h
- ChemistryLib/PhreeqcIOData/KineticReactant.cpp
- ChemistryLib/PhreeqcIOData/KineticReactant.h
- ChemistryLib/PhreeqcIOData/ReactionRate.cpp
- ChemistryLib/PhreeqcIOData/ReactionRate.h
- Use base class `ostream` for output; 
- Operator overloading on class templates;
> [CL] Improve data structure of Phreeqc Interface

- MeshLib/MeshEditing/ConvertToLinearMesh.cpp
- MeshLib/MeshEditing/ConvertToLinearMesh.h
- Tests/MeshLib/ConvertToLinearMesh.cpp
Current conversion routine relies on the numbering of the nodes, but this is not necessary.
A test and a proposed change are included.
3. [x] Any new feature or behavior change was documented? (no new features)
> Convert to linear mesh tests

- ProcessLib/BoundaryCondition/NeumannBoundaryConditionLocalAssembler.h
- ProcessLib/BoundaryCondition/RobinBoundaryConditionLocalAssembler.h
- ProcessLib/BoundaryCondition/VariableDependentNeumannBoundaryConditionLocalAssembler.h
In cases when the underlying element is quadratic but the shape function
is of linear order, there is a dimension mismatch between the
`NodalVectorType` and the return value of the `getNodalValuesOnElement`.
Taking the first rows of the return matrix ensures correct dimensions.
Changing only for BC's which use the `getNodalValuesOnElement` and
are used by processes like HM/RM etc. where one of the process
variables is of lower order.
The error is present already in the master for quite some time and only shows
up when compiling with fixed size matrices in debug mode.
> [PL] BC; Fix lower order element values access.

- MaterialLib/SolidModels/Ehlers.h
- MaterialLib/SolidModels/LinearElasticIsotropic.cpp
- MaterialLib/SolidModels/LinearElasticIsotropic.h
- MaterialLib/SolidModels/LinearElasticOrthotropic.cpp
- MaterialLib/SolidModels/LinearElasticOrthotropic.h
- MaterialLib/SolidModels/Lubby2.h
- MaterialLib/SolidModels/MechanicsBase.h
Originally pointed out by cppcheck about some assignment operator not being marked with 'override', but resulted in the following refactoring.
> Cleanup MaterialStateVariables in solid models

- Documentation/ProjectFile/material/fracture_properties/i_fracture_properties.md
- Documentation/ProjectFile/material/fracture_properties/permeability_model/CubicLaw/c_CubicLaw.md
- Documentation/ProjectFile/material/fracture_properties/permeability_model/i_permeability_model.md
- Documentation/ProjectFile/material/fracture_properties/permeability_model/t_type.md
- Documentation/ProjectFile/prj/processes/process/HYDRO_MECHANICS_WITH_LIE/fracture_properties/permeability_model
- MaterialLib/CMakeLists.txt
- MaterialLib/FractureModels/Permeability/CreateCubicLaw.cpp
- MaterialLib/FractureModels/Permeability/CreateCubicLaw.h
- MaterialLib/FractureModels/Permeability/CreatePermeabilityModel.cpp
- MaterialLib/FractureModels/Permeability/CreatePermeabilityModel.h
- MaterialLib/FractureModels/Permeability/CubicLaw.cpp
- MaterialLib/FractureModels/Permeability/CubicLaw.h
- MaterialLib/FractureModels/Permeability/Permeability.h
- MaterialLib/PorousMedium/Permeability/Permeability.h
- ProcessLib/LIE/Common/FractureProperty.h
- ProcessLib/LIE/HydroMechanics/CreateHydroMechanicsProcess.cpp
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerFracture-impl.h
- ProcessLib/LIE/HydroMechanics/LocalAssembler/IntegrationPointDataFracture.h
- Tests/Data/LIE/HydroMechanics/TaskB.prj
- Tests/Data/LIE/HydroMechanics/single_fracture.prj
- Tests/Data/LIE/HydroMechanics/single_fracture_3D.prj
- Tests/Data/LIE/HydroMechanics/single_fracture_3compartments_flow.prj
- Tests/Data/LIE/HydroMechanics/single_fracture_3compartments_flow_linear_aperture0.prj
- Tests/Data/LIE/HydroMechanics/single_fracture_3compartments_flow_linear_aperture0_e.prj
Based on #2541.
Generalizes the permeability computation in the fracture. Adding infrastructure and the currently only used cubic law.
2. [x] Tests covering your feature were added? Project files updated, no changes to references.
> LIE/HM fracture permeability models; CubicLaw

- NumLib/ODESolver/ConvergenceCriterionPerComponentDeltaX.cpp
Output of Convergence Criteria showed wrong Component Number 
and wrong dx because they were swapped. Now it is fixed.
> Fix Convergence Output

- Applications/ApplicationsLib/ProjectData.cpp
- ChemistryLib/CreatePhreeqcIO.cpp
- ChemistryLib/CreatePhreeqcIO.h
- ChemistryLib/PhreeqcIO.cpp
- ChemistryLib/PhreeqcIO.h
- ChemistryLib/PhreeqcIOData/CreateEquilibriumPhase.cpp
- ChemistryLib/PhreeqcIOData/CreateEquilibriumPhase.h
- ChemistryLib/PhreeqcIOData/CreateKineticReactant.cpp
- ChemistryLib/PhreeqcIOData/CreateKineticReactant.h
- ChemistryLib/PhreeqcIOData/EquilibriumPhase.cpp
- ChemistryLib/PhreeqcIOData/EquilibriumPhase.h
- ChemistryLib/PhreeqcIOData/KineticReactant.cpp
- ChemistryLib/PhreeqcIOData/KineticReactant.h
- ProcessLib/ComponentTransport/Tests.cmake
- Tests/Data/Parabolic/ComponentTransport/ReactiveTransport/KineticReactant/1d_isofrac_pcs_3_ts_126_t_12600.000000_expected.vtu
- Tests/Data/Parabolic/ComponentTransport/ReactiveTransport/KineticReactant/1d_isofrac_pcs_3_ts_168_t_16800.000000_expected.vtu
- Tests/Data/Parabolic/ComponentTransport/ReactiveTransport/KineticReactant/1d_isofrac_pcs_3_ts_210_t_21000.000000_expected.vtu
- Tests/Data/Parabolic/ComponentTransport/ReactiveTransport/KineticReactant/1d_isofrac_pcs_3_ts_42_t_4200.000000_expected.vtu
- Tests/Data/Parabolic/ComponentTransport/ReactiveTransport/KineticReactant/1d_isofrac_pcs_3_ts_84_t_8400.000000_expected.vtu
As titled. The solutions of immobile phases defined in the chemical system, i.e., equilibrium phases and kinetic reactants, will be automatically written into the result files. Defining additional transport processes for outputting the solutions of immobile phases is not needed any more.
> [CL] Output Solutions of Immobile Phases

- Jenkinsfile
- scripts/cmake/ConanSetup.cmake
Added CMake option `OGS_CONAN_BUILD_TYPE` to overwrite Conan build type
Can be useful to build / pull Conan release packages when building OGS in debug mode:
```bash
cmake ../ogs -DCMAKE_BUILD_TYPE=Debug -DOGS_CONAN_BUILD_TYPE=Release
```
1. [ ] Feature description was added to the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.2.1)
> Overwrite Conan build type

- MaterialLib/CMakeLists.txt
- MaterialLib/MPL/Utils/FormEffectiveThermalConductivity.cpp
- MaterialLib/MPL/Utils/FormEffectiveThermalConductivity.h
- MaterialLib/MPL/Utils/FormEigenTensor.cpp
- MaterialLib/MPL/Utils/FormEigenTensor.h
- ProcessLib/HT/HTFEM.h
- ProcessLib/HT/MonolithicHTFEM.h
- ProcessLib/HT/StaggeredHTFEM-impl.h
~1. Renamed thermal_expansivity as thermal_expansion~
2. Moved ProcessLib::HT::intrisincPermeabilty to a new file in MPL, and renamed the function to localTensor for general purpose.
3. Added a common function of effectiveThermalConductivity.
> Three updates in MPL

- ProcessLib/PhaseField/PhaseFieldProcess.cpp
- ProcessLib/Process.cpp
- ProcessLib/Process.h
- ProcessLib/ThermoMechanicalPhaseField/ThermoMechanicalPhaseFieldProcess.cpp
- ProcessLib/ThermoMechanics/ThermoMechanicsProcess.cpp
- made constructDofTable of the base class, Process,  more general.
- replaced the repeated part in constructDofTable() of ThermoMechanicsProcess, ThermoMechanicalPhaseField and PhaseFieldProcess with the calling of Process::constructDofTable.
Note:
1. The condensed part in this PR will be further improved when the staggered scheme is refactored.
2. constructDofTable() of HydroMechanicsProcess and RichardsMechanicsProcess, which use the Talyor-Hood element, are identical and will be improved in the future in the work of unify the common part of mechanics related processes.
3. This PR contains a commit of #2581: [ThermoMechanicalPhaseFieldProcess] Removed an unnecessary file.
> Condensed constructDofTable() of some process classes

- scripts/cmake/CCacheSetup.cmake
> [cmake] no check of pch_defines if ccache < 3.2.5

- Applications/DataExplorer/mainwindow.cpp
- Applications/FileIO/GocadIO/GocadAsciiReader.cpp
- Applications/FileIO/GocadIO/GocadAsciiReader.h
- Applications/FileIO/GocadIO/GocadEnums.cpp
- Applications/FileIO/GocadIO/GocadEnums.h
- Applications/Utils/FileConverter/GocadTSurfaceReader.cpp
Can now also parse GoCAD PLine data.
Also added a check if multiple data sets in the same file have the same name and if so append a UID, so files don't get overwritten on export.
> Expansion of GoCAD interface

- MaterialLib/SolidModels/Lubby2.cpp
This is a minor change to Lubby2 switching from rate form to incremental form. Preparation for an upcoming model comparison.
> Lubby2 incremental form

- MaterialLib/MPL/Component.cpp
- MaterialLib/MPL/Phase.cpp
- MaterialLib/MPL/Properties/Constant.cpp
- MaterialLib/MPL/Properties/ExponentialProperty.cpp
- MaterialLib/MPL/Properties/LinearProperty.cpp
- MaterialLib/MPL/Property.h
- MaterialLib/MPL/Utils/FormEigenTensor.cpp
- MaterialLib/MPL/VariableType.h
- ProcessLib/HeatTransportBHE/BHE/BHECommonCoaxial.cpp
- ProcessLib/HeatTransportBHE/BHE/BHETypes.h
- ProcessLib/HeatTransportBHE/BHE/BHE_1U.cpp
- ProcessLib/HeatTransportBHE/BHE/BHE_CXA.h
- ProcessLib/HeatTransportBHE/BHE/BHE_CXC.h
- ProcessLib/HeatTransportBHE/BHE/FlowAndTemperatureControl.h
- ProcessLib/HeatTransportBHE/HeatTransportBHEProcess.cpp
- ProcessLib/HeatTransportBHE/LocalAssemblers/LocalDataInitializer.h
- Tests/MaterialLib/TestMPLExponentialProperty.cpp
- Tests/MaterialLib/TestMPLLinearProperty.cpp
- Tests/MeshLib/ConvertToLinearMesh.cpp
Replaces boost::variant.
Fixes #2611
> Use std::variant instead of boost::variant.

- ProcessLib/ComponentTransport/ComponentTransportProcessData.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcessData.h
- ProcessLib/HeatConduction/HeatConductionProcessData.h
- ProcessLib/HeatTransportBHE/HeatTransportBHEProcessData.h
- ProcessLib/HydroMechanics/HydroMechanicsProcessData.h
- ProcessLib/PhaseField/PhaseFieldProcessData.h
- ProcessLib/RichardsComponentTransport/RichardsComponentTransportProcessData.h
- ProcessLib/RichardsFlow/RichardsFlowProcessData.h
- ProcessLib/RichardsMechanics/RichardsMechanicsProcessData.h
- ProcessLib/SmallDeformation/CreateSmallDeformationProcess.cpp
- ProcessLib/SmallDeformation/SmallDeformationProcessData.h
- ProcessLib/SmallDeformationNonlocal/CreateSmallDeformationNonlocalProcess.cpp
- ProcessLib/SmallDeformationNonlocal/SmallDeformationNonlocalProcessData.h
- ProcessLib/ThermalTwoPhaseFlowWithPP/ThermalTwoPhaseFlowWithPPProcessData.h
- ProcessLib/ThermoHydroMechanics/ThermoHydroMechanicsProcessData.h
- ProcessLib/ThermoMechanicalPhaseField/CreateThermoMechanicalPhaseFieldProcess.cpp
- ProcessLib/ThermoMechanicalPhaseField/ThermoMechanicalPhaseFieldProcessData.h
- ProcessLib/ThermoMechanics/ThermoMechanicsProcessData.h
- ProcessLib/TwoPhaseFlowWithPP/TwoPhaseFlowWithPPProcessData.h
- ProcessLib/TwoPhaseFlowWithPrho/TwoPhaseFlowWithPrhoProcessData.h
All of the special functions are not needed. Smaller reorderings to ensure the same initialization order.
Stricter default initializations, especially using NaN for doubles.
> Simplify *ProcessData classes

- ProcessLib/HydroMechanics/HydroMechanicsFEM.h
- ProcessLib/HydroMechanics/HydroMechanicsProcess.cpp
- ProcessLib/LocalAssemblerInterface.cpp
- ProcessLib/LocalAssemblerInterface.h
- ProcessLib/PhaseField/PhaseFieldFEM.h
- ProcessLib/PhaseField/PhaseFieldProcess.cpp
- ProcessLib/RichardsMechanics/RichardsMechanicsFEM.h
- ProcessLib/RichardsMechanics/RichardsMechanicsProcess.cpp
- ProcessLib/SmallDeformation/SmallDeformationFEM.h
- ProcessLib/SmallDeformation/SmallDeformationProcess.cpp
- ProcessLib/SmallDeformationNonlocal/SmallDeformationNonlocalFEM.h
- ProcessLib/SmallDeformationNonlocal/SmallDeformationNonlocalProcess.cpp
- ProcessLib/SmallDeformationNonlocal/SmallDeformationNonlocalProcess.h
- ProcessLib/ThermoHydroMechanics/ThermoHydroMechanicsFEM.h
- ProcessLib/ThermoHydroMechanics/ThermoHydroMechanicsProcess.cpp
- ProcessLib/ThermoMechanicalPhaseField/ThermoMechanicalPhaseFieldFEM.h
- ProcessLib/ThermoMechanicalPhaseField/ThermoMechanicalPhaseFieldProcess.cpp
- ProcessLib/ThermoMechanics/ThermoMechanicsFEM.h
- ProcessLib/ThermoMechanics/ThermoMechanicsProcess.cpp
In case when a time step is repeated `preTimestep` is called again. The `pushBackState` call must be executed only after successful time step, *i.e.* in `postTimestep`. Then an additional call in the initialization is needed; therefore a new interface function in local assemblers: `initialize`.
The first `pushBackState` call must be executed after the secondary variables are set, therefore a new function is needed. If you have better ideas, w/o adding a new interface function, I'd be happy to implement those.
Didn't apply the changes to LIE.
2. [x] Tests covering your feature were added? (Covered by current ctests)
3. [ ] Any new feature or behavior change was documented? Will not …
> Split pushBackState between init and post- timestep

- MaterialLib/SolidModels/Ehlers.h
- MaterialLib/SolidModels/LinearElasticIsotropic.h
- MaterialLib/SolidModels/Lubby2.h
- MaterialLib/SolidModels/MechanicsBase.h
Allows to fetch the bulk modulus inside a process without specifying a material model.
Solid Materials without own implementation will cause an OGS_FATAL.
> [ML/SM] extended interface to get bulk modulus

- Applications/FileIO/GocadIO/GocadAsciiReader.cpp
Set the node type so that VRTX and PVRTX definitions cannot mix
> [Fix] setting Gocad node type

- MaterialLib/SolidModels/LinearElasticOrthotropic.cpp
- MaterialLib/SolidModels/LinearElasticOrthotropic.h
- MathLib/KelvinVector.cpp
- MathLib/KelvinVector.h
Previously only used in the linear elastic orthotropic
model, but the transformation itself is more general
and is being used in other (not yet available) code
parts.
> [MaL] Extract fourth order rotation to KelvinVector

- ProcessLib/TimeLoop.cpp
For very small dt other checks fail.
> [PL] TL; Explicitly check for t == end time.

- MaterialLib/MPL/Component.cpp
- MaterialLib/MPL/Components/Water.cpp
- MaterialLib/MPL/Medium.cpp
- MaterialLib/MPL/Phase.cpp
- MaterialLib/MPL/Property.h
properties are now equipped with a pointer to their parent material scale (medium, phase, or component)
> MPL; Parent material scale pointers

- MaterialLib/MPL/CreateProperty.cpp
- MaterialLib/MPL/Properties/IdealGasLaw.cpp
- MaterialLib/MPL/Properties/IdealGasLaw.h
- MaterialLib/MPL/Properties/Properties.h
- Tests/MaterialLib/TestMPLIdealGasLaw.cpp
Implementation for entire phases, an expansion for multiple components is coming soon.
> Ideal Gas Law property for generalized material property lib

- MaterialLib/MPL/CreateProperty.cpp
- MaterialLib/MPL/Properties/CreateConstant.cpp
- MaterialLib/MPL/Properties/CreateConstant.h
- MaterialLib/MPL/Properties/CreateExponentialProperty.cpp
- MaterialLib/MPL/Properties/CreateExponentialProperty.h
- MaterialLib/MPL/Properties/CreateIdealGasLaw.cpp
- MaterialLib/MPL/Properties/CreateIdealGasLaw.h
- MaterialLib/MPL/Properties/CreateLinearProperty.cpp
- MaterialLib/MPL/Properties/CreateLinearProperty.h
- MaterialLib/MPL/Properties/CreateParameterProperty.cpp
- MaterialLib/MPL/Properties/CreateParameterProperty.h
- MaterialLib/MPL/Properties/CreateProperties.h
- MaterialLib/MPL/Properties/IdealGasLaw.h
- MaterialLib/MPL/Properties/ParameterProperty.h
- Tests/MaterialLib/TestMPLIdealGasLaw.cpp
All MPL Properties are now constructed via a new create method. Parsing the parameter type is done by peeking the config object rather than reading it. The actual check is done in the individual create methods. 
1. [ ] Feature description was added to the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.2.2)
> Create Methods for MPL Properties

- MaterialLib/SolidModels/MFront/MFront.cpp
- Tests/Data/Mechanics/MohrCoulombAbboSloan/load_test_mc.prj
Until now the models didn't use `sigma_prev` and `eps_prev`.
> MFront state initialization with sigma_prev and eps_prev.

- ChemistryLib/CreateOutput.cpp
- ChemistryLib/PhreeqcIOData/CreateKineticReactant.cpp
- ChemistryLib/PhreeqcIOData/KineticReactant.h
- Documentation/ProjectFile/prj/chemical_system/kinetic_reactants/kinetic_reactant/t_fix_amount.md
- ProcessLib/ComponentTransport/Tests.cmake
- Tests/Data/Parabolic/ComponentTransport/ReactiveTransport/Wetland/Wetland_1d.gml
- Tests/Data/Parabolic/ComponentTransport/ReactiveTransport/Wetland/Wetland_1d.prj
- Tests/Data/Parabolic/ComponentTransport/ReactiveTransport/Wetland/Wetland_1d.vtu
- Tests/Data/Parabolic/ComponentTransport/ReactiveTransport/Wetland/Wetland_1d_pcs_11_ts_4_t_28800.000000_expected.vtu
- Tests/Data/Parabolic/ComponentTransport/ReactiveTransport/Wetland/cwm1.dat
- web/content/docs/benchmarks/reactive-transport/wetland/Wetland.pandoc
- web/content/docs/benchmarks/reactive-transport/wetland/Wetland_1d.gif
- web/content/docs/benchmarks/reactive-transport/wetland/Wetland_cwm1.png
- web/content/docs/benchmarks/reactive-transport/wetland/Wetland_domain.png
This pull request adds an option to fix the *amount* of a defined *kinetic_reactant* to its *initial_amount*. Subsequently the change of  the *amount* of a *kinetic_reactant* in time step i does not affect the *amount* in subsequent time steps. 
This is necessary when using a *kinetic_reactant* as reaction rate that only transfers mass between different reactants but does not represent a reactive species itself. 
1. [ ] Feature description was added to the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.2.2)
3. [x ] Any new feature or behavior change was documented?
> [CL] Option to fix amount of kinetic reactant

- Applications/Utils/MeshGeoTools/createIntermediateRasters.cpp
Adjusted the tool to number the created layers from top to bottom in accordance with how geological data is usually ordered.
> [Fix] createIntermediateRasters-tool layer numbering

- Applications/CLI/ogs.cpp
- ProcessLib/TimeLoop.cpp
- ProcessLib/TimeLoop.h
Moving and extracting functions.
One behavioural change is that now the `postTimestep` calls for monolithic processes happen in a batch after solve for all process as it is done in the staggered scheme.
> Time loop refactorings

- NumLib/ODESolver/NonlinearSolverStatus.h
- ProcessLib/TimeLoop.cpp
Extract `preTimestep` and `postTimestep` calls into individual functions merging the monolithic and staggered implementations.
No behavioural change for the staggered scheme.
For the monolithic scheme the `preTimestep` calls are now executed separately in the beginning.
> Time loop refactorings; Extract pre and post.

- Applications/ApplicationsLib/ProjectData.cpp
- Documentation/ProjectFile/prj/processes/process/HEAT_TRANSPORT_BHE/t_density_fluid.md
- Documentation/ProjectFile/prj/processes/process/HEAT_TRANSPORT_BHE/t_density_gas.md
- Documentation/ProjectFile/prj/processes/process/HEAT_TRANSPORT_BHE/t_density_solid.md
- Documentation/ProjectFile/prj/processes/process/HEAT_TRANSPORT_BHE/t_heat_capacity_fluid.md
- Documentation/ProjectFile/prj/processes/process/HEAT_TRANSPORT_BHE/t_heat_capacity_gas.md
- Documentation/ProjectFile/prj/processes/process/HEAT_TRANSPORT_BHE/t_heat_capacity_solid.md
- Documentation/ProjectFile/prj/processes/process/HEAT_TRANSPORT_BHE/t_thermal_conductivity_fluid.md
- Documentation/ProjectFile/prj/processes/process/HEAT_TRANSPORT_BHE/t_thermal_conductivity_gas.md
- Documentation/ProjectFile/prj/processes/process/HEAT_TRANSPORT_BHE/t_thermal_conductivity_solid.md
- MaterialLib/MPL/CreateMaterialSpatialDistributionMap.cpp
- ProcessLib/HeatTransportBHE/CreateHeatTransportBHEProcess.cpp
- ProcessLib/HeatTransportBHE/CreateHeatTransportBHEProcess.h
- ProcessLib/HeatTransportBHE/HeatTransportBHEProcessData.h
- ProcessLib/HeatTransportBHE/LocalAssemblers/HeatTransportBHELocalAssemblerSoil-impl.h
- Tests/Data/Parabolic/T/3D_2U_BHE/3D_2U_BHE.prj
- Tests/Data/Parabolic/T/3D_Beier_sandbox/beier_sandbox.prj
- Tests/Data/Parabolic/T/3D_Beier_sandbox/fixed_power_constant_flow.prj
- Tests/Data/Parabolic/T/3D_deep_BHE/3D_deep_BHE_CXA.prj
- Tests/Data/Parabolic/T/3D_deep_BHE/3D_deep_BHE_CXC.prj
In this PR, the source code and input files related to HEAT_TRANSPORT_BHE process were changed in order to use the MPL data structure for reading in soil parameters such as thermal conductivity and heat capacity. 
1. The MPL data structure was used when assembling the local matrix for soil part. 
2. All test files have been updated accordingly. 
3. When checking the number of material groups, the original FATAL error was replaced by a WARNING, as the BHEs are additional material groups than the number of medias defined.
> Using MPL in Heat_Transport_BHE process

- ProcessLib/HT/HTFEM.h
- ProcessLib/HT/MonolithicHTFEM.h
- ProcessLib/HT/StaggeredHTFEM-impl.h
- Tests/Data/Parabolic/HT/ConstViscosity/square_5500x5500.prj
- Tests/Data/Parabolic/HT/FaultedCube/Ra_795_fault_bcgs_jacobi.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/CoupledPressureParabolicTemperatureParabolic.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/CoupledPressureParabolicTemperatureParabolicStaggered.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/IsothermalFluidFlow.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/IsothermalFluidFlowStaggered.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/IsothermalFluidFlowWithGravity.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/IsothermalFluidFlowWithGravityStaggered.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/PressureDiffusionTemperatureDiffusion.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/PressureDiffusionTemperatureDiffusionStaggered.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/PressureParabolicTemperatureParabolic.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/PressureParabolicTemperatureParabolicStaggered.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/calculatesurfaceflux_ht_cube_1e3.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/calculatesurfaceflux_ht_cube_1e4.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/constraint_bc_1e3.prj
- Tests/Data/Parabolic/HT/StaggeredCoupling/ADecovalexTHMCBasedHTExample/th_decovalex.prj
- Tests/Data/Parabolic/HT/StaggeredCoupling/ConstViscosity/square_5500x5500_staggered_scheme.prj
- Tests/Data/Parabolic/HT/StaggeredCoupling/ConstViscosity/square_5500x5500_staggered_scheme_adaptive_dt.prj
Used the following bash script for changing project files:
```
#!/usr/bin/env bash
number_of_medium_tags=`xmlstarlet sel -t -v "count(///*/medium)" $1`
number_of_medium_tags=$(($number_of_medium_tags - 1))
xmlstarlet ed --move "//OpenGeoSysProject/media/medium[@id=0]/phases/phase/properties/property[name='permeability']" "//OpenGeoSysProject/media/medium[@id=0]/properties" $1 > /tmp/t0.prj
for i in `seq 1 ${number_of_medium_tags}`;
do
i_m_e=$(($i-1))
#echo "${i}, ${i_m_e}"
path="//OpenGeoSysProject/media/medium[@id="${i}"]"
xmlstarlet ed --move "$path/phases/phase/properties/property[name='permeability']" "$path/properties" /tmp/t$i_m_e.prj > /tmp/t${i}.prj
done
#format the result file
xmlstarlet fo -s 4 /tmp/t${number_of_medium_tags}.prj > ${1}
```
> [PL/HT] Move the permeability specification from solid phase to medium scale.

- ProcessLib/HT/MonolithicHTFEM.h
- ProcessLib/HT/StaggeredHTFEM-impl.h
- Tests/Data/Parabolic/HT/ConstViscosity/square_5500x5500.prj
- Tests/Data/Parabolic/HT/FaultedCube/Ra_795_fault_bcgs_jacobi.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/CoupledPressureParabolicTemperatureParabolic.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/CoupledPressureParabolicTemperatureParabolicStaggered.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/IsothermalFluidFlow.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/IsothermalFluidFlowStaggered.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/IsothermalFluidFlowWithGravity.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/IsothermalFluidFlowWithGravityStaggered.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/PressureDiffusionTemperatureDiffusion.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/PressureDiffusionTemperatureDiffusionStaggered.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/PressureParabolicTemperatureParabolic.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/PressureParabolicTemperatureParabolicStaggered.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/calculatesurfaceflux_ht_cube_1e3.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/calculatesurfaceflux_ht_cube_1e4.prj
- Tests/Data/Parabolic/HT/SimpleSynthetics/constraint_bc_1e3.prj
- Tests/Data/Parabolic/HT/StaggeredCoupling/ADecovalexTHMCBasedHTExample/th_decovalex.prj
- Tests/Data/Parabolic/HT/StaggeredCoupling/ConstViscosity/square_5500x5500_staggered_scheme.prj
- Tests/Data/Parabolic/HT/StaggeredCoupling/ConstViscosity/square_5500x5500_staggered_scheme_adaptive_dt.prj
For changes in the project files the following script was used:
```
#!/usr/bin/env bash
number_of_medium_tags=`xmlstarlet sel -t -v "count(///*/medium)" $1`
number_of_medium_tags=$(($number_of_medium_tags - 1))
xmlstarlet ed --move "//OpenGeoSysProject/media/medium[@id=0]/phases/phase/properties/property[name='porosity']" "//OpenGeoSysProject/media/medium[@id=0]/properties" $1 > /tmp/t0.prj
for i in `seq 1 ${number_of_medium_tags}`;
do
i_m_e=$(($i-1))
#echo "${i}, ${i_m_e}"
path="//OpenGeoSysProject/media/medium[@id="${i}"]"
xmlstarlet ed --move "$path/phases/phase/properties/property[name='porosity']" "$path/properties" /tmp/t$i_m_e.prj > /tmp/t${i}.prj
done
#format the result file
xmlstarlet fo -s 4 /tmp/t${number_of_medium_tags}.prj > ${1}
```
> [PL/HT] Move the porosity specification from solid phase to medium scale.

- ProcessLib/CoupledSolutionsForStaggeredScheme.cpp
- ProcessLib/CoupledSolutionsForStaggeredScheme.h
- ProcessLib/PhaseField/PhaseFieldProcess.cpp
- ProcessLib/TimeLoop.cpp
- ProcessLib/TimeLoop.h
~Follow up of #2679.~ (rebased)
Remove coupled solutions references in `TimeLoop`. The pointers are stored in the same object, `_process_solutions`, which is reused.
> Remove coupled solutions references

- ProcessLib/ComponentTransport/ComponentTransportFEM.h
- ProcessLib/ComponentTransport/ComponentTransportProcess.cpp
- ProcessLib/CoupledSolutionsForStaggeredScheme.cpp
- ProcessLib/CoupledSolutionsForStaggeredScheme.h
- ProcessLib/HT/HTFEM.h
- ProcessLib/HT/MonolithicHTFEM.h
- ProcessLib/HT/StaggeredHTFEM-impl.h
- ProcessLib/HT/StaggeredHTFEM.h
- ProcessLib/HydroMechanics/HydroMechanicsFEM-impl.h
- ProcessLib/PhaseField/PhaseFieldFEM-impl.h
- ProcessLib/PhaseField/PhaseFieldFEM.h
- ProcessLib/ThermoMechanicalPhaseField/ThermoMechanicalPhaseFieldFEM-impl.h
- ProcessLib/ThermoMechanicalPhaseField/ThermoMechanicalPhaseFieldFEM.h
- ProcessLib/ThermoMechanics/ThermoMechanicsFEM-impl.h
- ProcessLib/VectorMatrixAssembler.cpp
Yet another staggered coupling refactoring.
Instead of passing a vector of a vector with data, pass a flat vector of (local) solutions ordered the same as the processes.
Review commit-wise.
> Flatten local coupled solutions vector.

- ParameterLib/CoordinateSystem.cpp
- ParameterLib/CoordinateSystem.h
Moving the code into cpp.
This saves repeated instantiations of the same template. Almost 300 instatitations.
> [PaL] Explicitly instantiate rotate*() templates.

- ProcessLib/BoundaryCondition/BoundaryCondition.h
- ProcessLib/BoundaryCondition/BoundaryConditionCollection.cpp
- ProcessLib/BoundaryCondition/BoundaryConditionCollection.h
- ProcessLib/BoundaryCondition/ConstraintDirichletBoundaryCondition.cpp
- ProcessLib/BoundaryCondition/ConstraintDirichletBoundaryCondition.h
- ProcessLib/BoundaryCondition/ConstraintDirichletBoundaryConditionLocalAssembler.h
- ProcessLib/BoundaryCondition/GenericNaturalBoundaryCondition-impl.h
- ProcessLib/BoundaryCondition/GenericNaturalBoundaryCondition.h
- ProcessLib/BoundaryCondition/GenericNaturalBoundaryConditionLocalAssembler.h
- ProcessLib/BoundaryCondition/HCNonAdvectiveFreeComponentFlowBoundaryConditionLocalAssembler.h
- ProcessLib/BoundaryCondition/NeumannBoundaryConditionLocalAssembler.h
- ProcessLib/BoundaryCondition/NormalTractionBoundaryCondition-impl.h
- ProcessLib/BoundaryCondition/NormalTractionBoundaryCondition.h
- ProcessLib/BoundaryCondition/NormalTractionBoundaryConditionLocalAssembler.h
- ProcessLib/BoundaryCondition/Python/PythonBoundaryCondition.cpp
- ProcessLib/BoundaryCondition/Python/PythonBoundaryCondition.h
- ProcessLib/BoundaryCondition/Python/PythonBoundaryConditionLocalAssembler.h
- ProcessLib/BoundaryCondition/RobinBoundaryConditionLocalAssembler.h
- ProcessLib/BoundaryCondition/VariableDependentNeumannBoundaryConditionLocalAssembler.h
- ProcessLib/ComponentTransport/ComponentTransportProcess.cpp
- ProcessLib/ComponentTransport/ComponentTransportProcess.h
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.h
- ProcessLib/HT/HTProcess.cpp
- ProcessLib/HT/HTProcess.h
- ProcessLib/Process.cpp
- ProcessLib/Process.h
- ProcessLib/SurfaceFlux/SurfaceFlux.cpp
- ProcessLib/SurfaceFlux/SurfaceFlux.h
- ProcessLib/SurfaceFlux/SurfaceFluxData.h
- ProcessLib/SurfaceFlux/SurfaceFluxLocalAssembler.h
Main reason for modification is the getFlux function, which for
particular processes (ComponentTransport) relies on all solutions being
available.
This modification ripples through all of the code, especially through
the boundary conditions.
Modified `applyNaturalBC`, ~`preTimestep`~, `integrate`, and `assemble`
functions.
The `preTimestep` is now decoupled from the secondary vars/BCs since #2697
> Pass current solutions to BC's

- ProcessLib/HT/MonolithicHTFEM.h
The PR fixes the issue that the calculation of the specific storage uses the array `vars` before it was initialized.
> [PL/HT] Mv calc. of specific storage after filling vars array.

- web/content/docs/benchmarks/small-deformations/lubby2.pdf
Correct Lubby2 eq 6, eq8 and eq 9:
1. [ ] Eq6: switch the \eta_M and G_M
2. [ ] Eq9: add an identity tensor symbol
> Correct Lubby2 equations in the pdf file in web content folder

- ProcessLib/HeatTransportBHE/LocalAssemblers/HeatTransportBHELocalAssemblerSoil-impl.h
In the original PR#2711, when running in debug mode, there will be assertion failures since Eigen::Map performs an internal check of the row and cols. Now they are corrected as the same with Vector3d.
> Fix bug in groundwater advection feature of HeatTransportBHE process

- MeshGeoToolsLib/MeshNodeSearcher.cpp
- MeshGeoToolsLib/MeshNodeSearcher.h
It is expected that exactly one MeshLib::Node has to be found. In the case more than one MeshLib::Node is found, the coordinates and the distances of the corresponding nodes  are written as output.
> Improve error message in MeshNodeSearcher

- MaterialLib/SolidModels/MFront/MohrCoulombAbboSloan.mfront
- Tests/Data/Mechanics/MohrCoulombAbboSloan/load_test_mc.prj
Minor change in the Mohr-Coulomb Abbo-Sloan model for non-associated flow with apex smoothing.
> Matched non-associated tension cut-off in MCAS.

- ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.cpp
- ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrix-impl.h
- ProcessLib/LIE/SmallDeformation/SmallDeformationProcess.cpp
- Tests/Data/LIE/HydroMechanics/expected_single_fracture_3compartments_flow_linear_aperture0_e_pcs_0_ts_1108_t_10000.000000.vtu
- Tests/Data/LIE/HydroMechanics/expected_single_fracture_3compartments_flow_linear_aperture0_pcs_0_ts_1108_t_10000.000000.vtu
- Tests/Data/LIE/HydroMechanics/expected_single_fracture_3compartments_flow_pcs_0_ts_1108_t_10000.000000.vtu
- Tests/Data/LIE/HydroMechanics/single_fracture_3compartments_flow.prj
- Tests/Data/LIE/HydroMechanics/single_fracture_3compartments_flow_linear_aperture0.prj
- Tests/Data/LIE/HydroMechanics/single_fracture_3compartments_flow_linear_aperture0_e.prj
When flow is only in the fracture, p is still set in the adjacent matrix elements to avoid leak-off. This pressure had an impact mechanically which is now deactivated.
Secondly, some test cases had a missing boundary condition on the displacement jump which has now been added.
> Biot effect LIE/HM

- Applications/Utils/MeshEdit/CMakeLists.txt
- Applications/Utils/MeshEdit/Vtu2Grid.cpp
- Applications/Utils/Tests.cmake
- Tests/Data/FileIO/AmmerSubsurfaceGrid.vtu
- web/content/docs/tools/meshing/vtu2grid/index.pandoc
- web/content/docs/tools/meshing/vtu2grid/vtu2grid-100.png
- web/content/docs/tools/meshing/vtu2grid/vtu2grid-200.png
- web/content/docs/tools/meshing/vtu2grid/vtu2grid-50.png
- web/content/docs/tools/meshing/vtu2grid/vtu2grid-50x50x10.png
- web/content/docs/tools/meshing/vtu2grid/vtu2grid-orig.png
Samples a 3D mesh into a hex-grid of userdefined resolution.
> 3D mesh to grid conversion

- MaterialLib/SolidModels/MFront/MFront.cpp
- NumLib/Exceptions.h
- NumLib/ODESolver/NonlinearSolver.cpp
- NumLib/ODESolver/TimeDiscretizedODESystem.cpp
- ProcessLib/SmallDeformation/Tests.cmake
- Tests/Data/Mechanics/MohrCoulombAbboSloan/oedometer.gml
- Tests/Data/Mechanics/MohrCoulombAbboSloan/oedometer.prj
- Tests/Data/Mechanics/MohrCoulombAbboSloan/oedometer.vtu
- Tests/Data/Mechanics/MohrCoulombAbboSloan/oedometer_bottom.vtu
- Tests/Data/Mechanics/MohrCoulombAbboSloan/oedometer_fixed_timestepping.prj
- Tests/Data/Mechanics/MohrCoulombAbboSloan/oedometer_left.vtu
- Tests/Data/Mechanics/MohrCoulombAbboSloan/oedometer_pcs_0_ts_376_t_240000.000000.vtu
- Tests/Data/Mechanics/MohrCoulombAbboSloan/oedometer_pcs_0_ts_5_t_79811.437500.vtu
- Tests/Data/Mechanics/MohrCoulombAbboSloan/oedometer_right.vtu
- Tests/Data/Mechanics/MohrCoulombAbboSloan/oedometer_top.vtu
Introduce explicit exception handling in the time loop/nonlinear-solver for failed assembly. In case of exception the time step will be repeated (if adaptive time stepping is used) with smaller time step size.
The exception is thrown in MFront material model when local integration fails.
3. [x] Any new feature or behavior change was documented? Not needed.
> Repeat time step on assembly error

- ProcessLib/HydroMechanics/HydroMechanicsFEM-impl.h
- ProcessLib/HydroMechanics/HydroMechanicsFEM.h
- ProcessLib/HydroMechanics/HydroMechanicsProcess.cpp
- ProcessLib/HydroMechanics/HydroMechanicsProcess.h
- ProcessLib/HydroMechanics/LocalAssemblerInterface.h
- ProcessLib/RichardsMechanics/LocalAssemblerInterface.h
- ProcessLib/RichardsMechanics/RichardsMechanicsFEM-impl.h
- ProcessLib/RichardsMechanics/RichardsMechanicsFEM.h
- ProcessLib/RichardsMechanics/RichardsMechanicsProcess.cpp
- ProcessLib/RichardsMechanics/RichardsMechanicsProcess.h
- ProcessLib/ThermoMechanics/LocalAssemblerInterface.h
- ProcessLib/ThermoMechanics/ThermoMechanicsFEM-impl.h
- ProcessLib/ThermoMechanics/ThermoMechanicsFEM.h
- ProcessLib/ThermoMechanics/ThermoMechanicsProcess.cpp
- ProcessLib/ThermoMechanics/ThermoMechanicsProcess.h
Adds possibility (as it already exists in SD) of internal state variables output to TM/RM/HM processes.
2. [ ] Tests covering your feature were added? Uses same code as SD, so hopefully it just works ;)
> Internal variables for TM/RM/HM

- ProcessLib/RichardsMechanics/RichardsMechanicsProcess.cpp
- ProcessLib/RichardsMechanics/RichardsMechanicsProcess.h
Probably forgotten when splitting the preTS in init and postTS.
> [PL] RM; Fix the postTimestep, which is preTS.

- .gitattributes
- Applications/DataExplorer/NetCdfDialog/CMakeLists.txt
- Applications/DataExplorer/NetCdfDialog/NetCdfConfigure.ui
- Applications/DataExplorer/NetCdfDialog/NetCdfConfigureDialog.cpp
- Applications/DataExplorer/NetCdfDialog/NetCdfConfigureDialog.h
- Applications/Utils/FileConverter/CMakeLists.txt
- Applications/Utils/FileConverter/NetCdfConverter.cpp
- Applications/Utils/Tests.cmake
- Jenkinsfile
- Tests/Data/FileConverter/slim_100897_198.nc
- Tests/Data/FileConverter/slim_100897_198.vtu
- Tests/Data/FileConverter/sresa1b_ncar_ccsm3-example.nc
- Tests/Data/FileConverter/sresa1b_ncar_ccsm3-example.vtu
- scripts/cmake/ConanSetup.cmake
- scripts/cmake/Find.cmake
- scripts/docker/Dockerfile.clang.full
- scripts/docker/Dockerfile.gcc.full
- scripts/docker/Dockerfile.gcc.gui
Command line utility to conver netCDF-files into OGS meshes. Works for both 2d and 3d meshes + time. Multiple time steps can be saved as seperate meshes or as one mesh with one scalar array per time step.
(A follow-up PR will move all non-ui functionality into FileIO and adjust the DataExplorer interface to use that as well.)
**Please note:**
- Conan minimum version was bumped to `1.20`, do `pip install --upgrade conan`!
- Updated Conan Qt package to 5.13.2
> [utils] netCDF converter

- NumLib/TimeStepping/Algorithms/EvolutionaryPIDcontroller.cpp
- NumLib/TimeStepping/Algorithms/EvolutionaryPIDcontroller.h
- NumLib/TimeStepping/Algorithms/IterationNumberBasedTimeStepping.cpp
- NumLib/TimeStepping/Algorithms/IterationNumberBasedTimeStepping.h
- NumLib/TimeStepping/Algorithms/TimeStepAlgorithm.h
- ProcessLib/TimeLoop.cpp
Iteration number based time stepping scheme ended in an infinite loop when the minimum time step size was reached.
- Add a new function (similar to `isSolutionErrorComputationNeeded`) but with different logic for the adaptive timesteppers, `canReduceTimestepSize()`.
- Update (generalize) error message.
> Time stepping infinite loop fix

- CMakeLists.txt
- web/content/docs/devguide/advanced/configuration-options.pandoc
This disables building of all processes, e.g. if you want to just
build the utils.
Setting `OGS_BUILD_CLI=OFF` also disables all processes.
> [CMake] Added option to set OGS_BUILD_PROCESSES=OFF.

- NumLib/Assembler/SerialExecutor.h
As titled.
Coincidentally, in the benchmark of Mechanics/Linear/square_with_deactivated_hole.prj, the elements in the deactivated domain are stored in the last section of the element vector, and it passed the ctest.
> [SerialExcutor] Fixed a bug in the loop for the element deactivatíon.

- Applications/ApplicationsLib/ProjectData.cpp
- ProcessLib/LiquidFlow/CreateLiquidFlowProcess.cpp
- ProcessLib/LiquidFlow/CreateLiquidFlowProcess.h
- ProcessLib/LiquidFlow/LiquidFlowLocalAssembler-impl.h
- ProcessLib/LiquidFlow/LiquidFlowLocalAssembler.h
- ProcessLib/LiquidFlow/LiquidFlowProcess.cpp
- ProcessLib/LiquidFlow/LiquidFlowProcess.h
- ProcessLib/LiquidFlow/Tests.cmake
- ProcessLib/SurfaceFlux/SurfaceFluxLocalAssembler.h
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/LF_square_1e1_surfaceflux_pcs_0_ts_1_t_0.432000_expected.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/LF_square_1e1_surfaceflux_pcs_0_ts_2_t_0.864000_expected.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/square_1e1_calculatesurfaceflux.prj
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/square_1x1_quad_1e1.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/square_1x1_quad_1e1_complete_surface.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/square_1x1_quad_1e1_complete_surface_left_right_dirichlet_specific_flux_t_0.432000_expected.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/square_1x1_quad_1e1_complete_surface_left_right_dirichlet_specific_flux_t_0.864000_expected.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/square_1x1_quad_1e1_left.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/square_1x1_quad_1e1_right.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/LF_cube_1e3_calculatesurfaceflux_pcs_0_ts_0_t_0.000000_expected.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/LF_cube_1e3_calculatesurfaceflux_pcs_0_ts_1_t_0.432000_expected.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/LF_cube_1e3_calculatesurfaceflux_pcs_0_ts_2_t_0.864000_expected.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/cube_1e3_calculatesurfaceflux.prj
- Tests/Data/Parabolic/LiquidFlow/Flux/cube_1x1x1_hex_1e3.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/cube_1x1x1_hex_1e3_complete_surface.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/cube_1x1x1_hex_1e3_complete_surface_left_right_dirichlet_specific_flux_t_0.432000_expected.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/cube_1x1x1_hex_1e3_complete_surface_left_right_dirichlet_specific_flux_t_0.864000_expected.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/cube_1x1x1_hex_1e3_left.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/cube_1x1x1_hex_1e3_right.vtu
3. [x] Any new feature or behavior change was documented?:
The flux calculation is now available for the LiquidFlow process. This works analogously to the other implementations in the HT-Process, HC-Process and groundwater flow process. Documentation already exists for this.
> Add output of fluxes to LiquidFlow process

- MaterialLib/MPL/PropertyType.h
- Tests/MaterialLib/TestMPLConvertProperties.cpp
- A missing property string was added to the *property_enum_to_string*-array
- A test that verifies the correct conversion from *PropertyType* enum to string and back was added
> Convert properties test

- ProcessLib/HT/HTProcess.cpp
A more elegant way (IMHO) to verify the correct configuration of material properties. No new features, and in this process there is actually the same number of code lines, but it will be very useful in complex processes such as th2m where 18+ properties have to be checked.
> refactoring the MPL verification of HT process

- Applications/Utils/MeshEdit/CMakeLists.txt
- Applications/Utils/MeshEdit/ExtractBoundary.cpp
- Applications/Utils/Tests.cmake
- MeshLib/Elements/Element.h
- MeshLib/Elements/QuadRule4.cpp
- MeshLib/Elements/TemplateElement.h
- MeshLib/MeshEditing/DuplicateMeshComponents.cpp
- MeshLib/MeshEditing/DuplicateMeshComponents.h
- MeshLib/MeshQuality/MeshValidation.cpp
- MeshLib/MeshSurfaceExtraction.cpp
- MeshLib/MeshSurfaceExtraction.h
- Tests/Data/FileIO/square_1x1_quad_boundary.vtu
- Tests/Data/FileIO/square_1x1_tri_boundary.vtu
- Tests/MeshLib/TestBoundaryElementSearch.cpp
- Tests/MeshLib/TestPntInElement.cpp
- web/content/docs/tools/meshing-submeshes/extract-boundary/ExtractBoundary_square_1x1_quad_border.png
- web/content/docs/tools/meshing-submeshes/extract-boundary/ExtractBoundary_square_1x1_tri_border.png
- web/content/docs/tools/meshing-submeshes/extract-boundary/index.pandoc
[Documentation preview](https://deploy-preview-2764--ogs.netlify.com/docs/tools/meshing-submeshes/extract-entire-surface/)
> Tool ExtractEntireSurface

- web/content/docs/devguide/getting-started/prerequisites.pandoc
> [docs] Migrated Linux CMake installation to apt.kitware.com

- ProcessLib/RichardsMechanics/RichardsMechanicsFEM-impl.h
- ProcessLib/RichardsMechanics/RichardsMechanicsProcess.cpp
- ProcessLib/RichardsMechanics/RichardsMechanicsProcessData.h
Added additional output of averaged integration point stresses for each cell similar to existing saturation output.
Allows to visualize stress values on tri-meshes.
- Hard coded for RichardsM process and not configurable in project file.
> RichardsM: Add element averaged stress output

- Applications/ApplicationsLib/ProjectData.cpp
- Applications/ApplicationsLib/ProjectData.h
- MaterialLib/MPL/CreateMaterialSpatialDistributionMap.cpp
- MaterialLib/MPL/CreateMaterialSpatialDistributionMap.h
- MaterialLib/MPL/MaterialSpatialDistributionMap.h
- ProcessLib/ComponentTransport/CreateComponentTransportProcess.cpp
- ProcessLib/ComponentTransport/CreateComponentTransportProcess.h
- ProcessLib/HT/CreateHTProcess.cpp
- ProcessLib/HT/CreateHTProcess.h
- ProcessLib/HeatTransportBHE/CreateHeatTransportBHEProcess.cpp
- ProcessLib/HeatTransportBHE/CreateHeatTransportBHEProcess.h
- ProcessLib/HydroMechanics/CreateHydroMechanicsProcess.cpp
- ProcessLib/HydroMechanics/CreateHydroMechanicsProcess.h
- ProcessLib/ThermoHydroMechanics/CreateThermoHydroMechanicsProcess.cpp
- ProcessLib/ThermoHydroMechanics/CreateThermoHydroMechanicsProcess.h
- ProcessLib/TwoPhaseFlowWithPP/CreateTwoPhaseFlowWithPPProcess.cpp
- ProcessLib/TwoPhaseFlowWithPP/CreateTwoPhaseFlowWithPPProcess.h
Changed the media map definition to shared_pointer, so that one medium definition can be assigned to multiple material ID's. This can be useful when a mesh has multiple material ID's defined, but they have the same properties. Or if they only differ in one property, this can be easier written by refering this property to a Group-Parameter.
PR #2779 will contain a benchmark benefitting from this.
This is how a .prj-file would look like, which benefits from it: 
[hm1_3Dgravity.prj.txt](https://github.com/ufz/ogs/files/4152636/hm1_3Dgravity.prj.txt)
> [MPL] Shared Media

- MaterialLib/MPL/Component.cpp
- MaterialLib/MPL/Component.h
- MaterialLib/MPL/Components/Water.cpp
- MaterialLib/MPL/CreateComponent.cpp
- MaterialLib/MPL/CreatePhase.cpp
- MaterialLib/MPL/Medium.cpp
- MaterialLib/MPL/Phase.cpp
- MaterialLib/MPL/Phase.h
- MaterialLib/MPL/Properties/CreateConstant.cpp
- MaterialLib/MPL/Properties/ParameterProperty.cpp
- MaterialLib/MPL/Properties/RelPermBrooksCorey.cpp
- MaterialLib/MPL/Properties/RelPermLiakopoulos.cpp
- MaterialLib/MPL/Property.cpp
- MaterialLib/MPL/Property.h
- MaterialLib/MPL/Utils/FormEigenTensor.cpp
- ProcessLib/HeatTransportBHE/LocalAssemblers/HeatTransportBHELocalAssemblerSoil-impl.h
- ProcessLib/ThermoHydroMechanics/ThermoHydroMechanicsFEM-impl.h
- ProcessLib/TwoPhaseFlowWithPP/TwoPhaseFlowWithPPLocalAssembler-impl.h
- Tests/MaterialLib/TestMPLParseMaterial.cpp
- Tests/MaterialLib/TestMPLRelPermBrooksCorey.cpp
- Tests/MaterialLib/TestMPLRelPermLiakopoulos.cpp
Replaces `std::array` types avoiding few conversions.
2. [x] Tests covering your feature were added? Existing tests should cover the changes.
3. [x] Any new feature or behavior change was documented? No project file or material model changes.
> Use Eigen in MPL.

- scripts/env/eve/cli.sh
Newer Boost module does not depend on deprecated modules.
> Updated eve modules

- ProcessLib/TimeLoop.cpp
In the current ogs,  if a rejected step gives no change in the step size, the time loop becomes  infinite. This PR fixes this issue.
> Avoided the infinite time loop when a rejected step gives no change in the step size

- Documentation/ProjectFile/properties/property/PorosityFromMassBalance/t_maximal_porosity.md
- Documentation/ProjectFile/properties/property/PorosityFromMassBalance/t_minimal_porosity.md
- MaterialLib/MPL/Properties/CreatePorosityFromMassBalance.cpp
- MaterialLib/MPL/Properties/PorosityFromMassBalance.cpp
- MaterialLib/MPL/Properties/PorosityFromMassBalance.h
- Tests/Data/RichardsMechanics/deformation_dependent_porosity.prj
- Tests/Data/RichardsMechanics/orthotropic_power_law_permeability_xyz.prj
Currently the limits are hard coded to be 0 and 1.
In some cases these values could be higher and lower,
respectively.
2. [x] Tests covering your feature were added? Existing one is updated.
> [MPL] User-provided limits for porosity.

- NumLib/TimeStepping/Algorithms/IterationNumberBasedTimeStepping.cpp
Forces the multiplier to use the minimum value of the multipliers, if the solver
fails in an iteration step where it would otherwise be larger than 1.
It is not checked, that the minimum value is less than 1, but if that's the case, 
then this shouldn't make it worse.
> IterationBasedTimeStepping fix FindMultiplier

- Documentation/ProjectFile/prj/processes/process/HYDRO_MECHANICS/t_mass_lumping.md
- ProcessLib/HydroMechanics/CreateHydroMechanicsProcess.cpp
- ProcessLib/HydroMechanics/HydroMechanicsFEM-impl.h
- ProcessLib/HydroMechanics/HydroMechanicsProcessData.h
Gives the option to use mass lumping in HM which can help with oscillation problems
> [HM] enable mass lumping

- ProcessLib/RichardsMechanics/RichardsMechanicsFEM-impl.h
- scripts/cmake/ConanSetup.cmake
Disabled geotiff when `OGS_USE_CONAN=ON` and `OGS_BUILD_GUI=ON`.
> Fix conan gui builds

- Applications/ApplicationsLib/LinearSolverLibrarySetup.h
- MeshLib/Vtk/VtkMappedMeshSource.cpp
Two corrections:
1. DBUG message (`*name->c_str()`) in `VtkMappedMeshSource::RequestData`,
2. Enabled MPI to work with `std::runtime_error` properly.
> Two corrections in MPI and vtk stuffs.

- MaterialLib/MPL/Utils/GetSymmetricTensor.cpp
- MaterialLib/MPL/Utils/GetSymmetricTensor.h
- MaterialLib/MPL/VariableType.h
- ProcessLib/HydroMechanics/HydroMechanicsFEM-impl.h
- ProcessLib/HydroMechanics/HydroMechanicsProcess.cpp
- ProcessLib/HydroMechanics/HydroMechanicsProcessData.h
Made the permeability in HM a tensor which will be needed to use certain permeability models.
To analyze the results of the permeability models the k-output was added.
Therefore, the variant visitor was implemented.
> HM permeability output

- MaterialLib/MPL/CheckMaterialSpatialDistributionMap.h
- ProcessLib/ComponentTransport/ComponentTransportProcess.cpp
- ProcessLib/ComponentTransport/CreateComponentTransportProcess.cpp
- ProcessLib/GroundwaterFlow/CreateGroundwaterFlowProcess.cpp
- ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.cpp
- ProcessLib/HT/CreateHTProcess.cpp
- ProcessLib/HT/HTProcess.cpp
- ProcessLib/LiquidFlow/CreateLiquidFlowProcess.cpp
- ProcessLib/LiquidFlow/LiquidFlowProcess.cpp
- ProcessLib/RichardsFlow/CreateRichardsFlowProcess.cpp
- ProcessLib/RichardsMechanics/CreateRichardsMechanicsProcess.cpp
This PR
- moves the function `checkMPLProperties` from the respective processes to the corresponding CreateProcess implementations and 
- uses a newly implemented function `checkMaterialSpatialDistributionMap` in the respective function `checkMPLProperties`.
> Improve checkMPLProperties

- MeshLib/IO/MPI_IO/NodePartitionedMeshReader.cpp
- MeshLib/Vtk/VtkMappedMeshSource.cpp
Removed vtkGhostType due to issue #2866. The overlapping in pvtu will be avoided by using computations together with MPI communications, or by other decent method (see my comment in  # #2868).
> [pvtu] Removed vtkGhostType

- Applications/Utils/CMakeLists.txt
- ProcessLib/ComponentTransport/CMakeLists.txt
- ProcessLib/GroundwaterFlow/CMakeLists.txt
- ProcessLib/HT/CMakeLists.txt
- ProcessLib/HeatConduction/CMakeLists.txt
- ProcessLib/HeatTransportBHE/CMakeLists.txt
- ProcessLib/HydroMechanics/CMakeLists.txt
- ProcessLib/LiquidFlow/CMakeLists.txt
- ProcessLib/PhaseField/CMakeLists.txt
- ProcessLib/RichardsComponentTransport/CMakeLists.txt
- ProcessLib/RichardsFlow/CMakeLists.txt
- ProcessLib/RichardsMechanics/CMakeLists.txt
- ProcessLib/SmallDeformation/CMakeLists.txt
- ProcessLib/SmallDeformationNonlocal/CMakeLists.txt
- ProcessLib/TES/CMakeLists.txt
- ProcessLib/ThermalTwoPhaseFlowWithPP/CMakeLists.txt
- ProcessLib/ThermoHydroMechanics/CMakeLists.txt
- ProcessLib/ThermoMechanicalPhaseField/CMakeLists.txt
- ProcessLib/ThermoMechanics/CMakeLists.txt
- ProcessLib/TwoPhaseFlowWithPP/CMakeLists.txt
- ProcessLib/TwoPhaseFlowWithPrho/CMakeLists.txt
- scripts/cmake/test/AddTest.cmake
- scripts/cmake/test/OgsTest.cmake
The condition for adding a ctest is moved out of the `AddTest` and `OgsTest` cmake macros.
Small bugfix as reported by @ThieJan for the `ogs-Mechanics_slope_stability_mfront` test, which has a special conditions. Error happens with `BUILD_TESTING=OFF` configuration.
```
CMake Error at ProcessLib/SmallDeformation/Tests.cmake:121 (set_tests_properties):
> set_tests_properties Can not find test to add properties to:
> ogs-Mechanics_slope_stability_mfront
```
> [cmake] Move BUILD_TESTING condition up.

- CMakeLists.txt
As titled. 
In order to fix the issue mentioned in #2861,  the syntax `add_subdirectory(ThirdParty)` is reverted back to the place where it was.
> [CMake] Fix segmentation fault in ThirdParty/IPhreeqc

- CMakeLists.txt
- web/content/docs/devguide/advanced/configuration-options.pandoc
- web/content/docs/devguide/advanced/log-and-debug-output.pandoc
the log level can be adjusted in preprocessor. The default values are "debug" for all builds.
If someone actively uses/relies on this feature, now is good point to tell it ;)
This feature is removed in this pull request.
Reducing complexity a little.
Part of #2875
> Remove compile time log level

- Applications/Utils/FileConverter/GMSH2OGS.cpp
- Applications/Utils/MeshEdit/checkMesh.cpp
- MeshLib/MeshInformation.cpp
- MeshLib/MeshInformation.h
Perform additional mesh checks (e.g. for element type) while converting.
This should facilitate troubleshooting as GMSH meshes nomally don't work out of the box.
Fixes #2841
1. [ ] Feature description was added to the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.3.1)
> GMSH2OGS: check mesh integration

- Applications/DataExplorer/DataView/ElementTreeModel.cpp
- Applications/FileIO/TetGenInterface.cpp
- Applications/Utils/MeshEdit/UnityPreprocessing.cpp
- MeshLib/MeshInformation.cpp
- MeshLib/MeshInformation.h
- Tests/FileIO/TestGmsInterface.cpp
- Tests/FileIO_SWMM/TestSwmmInterface.cpp
- Tests/MeshLib/TestAddLayerToMesh.cpp
- Tests/MeshLib/TestRasterToMesh.cpp
Substitute getNumberOfElementTypes() array by std::map to avoid multiple different element type mappings.
I'm not able to check the output of the DataExplorer right now as the binary makes some throws some OpenGL/QT errors on my machine. But at least it compiles.
> Elemtypes map

- Documentation/ProjectFile/properties/property/SaturationVanGenuchten/t_entry_pressure.md
- Documentation/ProjectFile/properties/property/SaturationVanGenuchten/t_p_b.md
- Documentation/bibliography.bib
- MaterialLib/MPL/Properties/CapillaryPressureSaturation/CreateSaturationVanGenuchten.cpp
- MaterialLib/MPL/Properties/CapillaryPressureSaturation/SaturationVanGenuchten.cpp
- MaterialLib/MPL/Properties/CapillaryPressureSaturation/SaturationVanGenuchten.h
- Tests/Data/RichardsMechanics/RichardsFlow_2d_quasinewton.prj
- Tests/Data/RichardsMechanics/RichardsFlow_2d_richardsflow.prj
- Tests/Data/RichardsMechanics/RichardsFlow_2d_small.prj
- Tests/Data/RichardsMechanics/RichardsFlow_2d_small_masslumping.prj
- Tests/Data/RichardsMechanics/bishops_effective_stress_power_law.prj
- Tests/Data/RichardsMechanics/bishops_effective_stress_saturation_cutoff.prj
- Tests/Data/RichardsMechanics/deformation_dependent_porosity_swelling.prj
- Tests/Data/RichardsMechanics/gravity.prj
- Tests/Data/RichardsMechanics/orthotropic_swelling_xy.prj
- Tests/Data/RichardsMechanics/orthotropic_swelling_xyz.prj
- Tests/MaterialLib/TestMPLSaturationVanGenuchten.cpp
Mainly fixing the documentation. See individual commits for details.
Change input parameter `<entry_pressure>` to `<p_b>` and `<exponent>` to `<m>`.
> Van Genuchten capillary pressure saturation

- Jenkinsfile
- MeshLib/Elements/MapBulkElementPoint.cpp
- MeshLib/Elements/MapBulkElementPoint.h
- ProcessLib/ComponentTransport/Tests.cmake
- ProcessLib/LiquidFlow/Tests.cmake
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/LF_square_1x1_tri_1.8e1_surfaceflux_pcs_0_ts_1_t_0.432000_expected.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/LF_square_1x1_tri_1.8e1_surfaceflux_pcs_0_ts_2_t_0.864000_expected.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/square_1.8e1_calculatesurfaceflux.prj
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/square_1x1_tri_1.8e1.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/square_1x1_tri_1.8e1_complete_boundary.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/square_1x1_tri_1.8e1_complete_boundary_left_right_dirichlet_specific_flux_t_0.432000_expected.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/square_1x1_tri_1.8e1_complete_boundary_left_right_dirichlet_specific_flux_t_0.864000_expected.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/square_1x1_tri_1.8e1_left.vtu
- Tests/Data/Parabolic/LiquidFlow/Flux/2D/square_1x1_tri_1.8e1_right.vtu
- web/static/pdf/BulkElementMappings.pdf
Yes, I created a pdf. The question is where to put the sketches?
> Add bulk element mappings for triangles.

- Applications/Utils/SimpleMeshCreation/generateStructuredMesh.cpp
- MeshLib/MeshEnums.cpp
- MeshLib/MeshGenerators/MeshGenerator.h
This allows to generate tests for the prism element.
The feature is tested already in `Tests/MeshLib/TestMeshGenerator.cpp`
Command line help is updated.
> Add prism element type to structure mesh generator tool.

- Applications/CLI/CMakeLists.txt
- Applications/DataExplorer/DataExplorer.cmake
- Applications/DataExplorer/DataView/DiagramView/GetDateTime.h
- CMakeLists.txt
- Jenkinsfile
- MathLib/KelvinVector-impl.h
- Tests/BaseLib/TestFilePathStringManipulation.cpp
- Tests/CMakeLists.txt
- Tests/MathLib/TestODESolver.cpp
- Tests/NumLib/TestODEInt.cpp
- azure-pipelines.yml
- scripts/cmake/CCacheSetup.cmake
- scripts/cmake/CompilerSetup.cmake
- scripts/cmake/Functions.cmake
- scripts/cmake/UnityBuildSettings.cmake
- scripts/docker/Dockerfile.clang.full
- scripts/docker/Dockerfile.gcc.full
- scripts/docker/Dockerfile.gcc.gui
- web/content/docs/devguide/troubleshooting/build.pandoc
Introduces CMake-option `OGS_USE_UNITY_BUILDS` to enable [unity builds](https://onqtam.com/programming/2019-12-20-pch-unity-cmake-3-16/) to speed up compilation significantly (defaults to `ON`).
Compilation tests show speed-ups for different targets between 25 % and 75 %.
When using at least CMake 3.16 then `OGS_USE_UNITY_BUILDS` is set to `ON` (requires CMake 3.16, as a soft dependency) and all libs added with `ogs_add_library()` will build as Unity builds.
Removed CMake-option `OGS_USE_PCH`.
Also introduced CMake-variable `OGS_DISABLE_CCACHE`.
TODO:
> [CMake] Unity builds

- Documentation/ProjectFile/prj/linear_solvers/linear_solver/eigen/t_restart.md
- MathLib/LinAlg/Eigen/EigenLinearSolver.cpp
- MathLib/LinAlg/Eigen/EigenLinearSolver.h
- MathLib/LinAlg/Eigen/EigenOption.cpp
- MathLib/LinAlg/Eigen/EigenOption.h
add restart option for the GMRES solver (Eigen-unsupported). 
It sets the number of iterations before a restart is conducted. It can improve the convergence behavior. However, increasing the value comes with a tradeoff in time and memory. First tests suggest that the default value (30) is already quite optimal in most cases.
> add GMRES restart option

- Documentation/ProjectFile/properties/property/CapillaryPressureVanGenuchten/c_CapillaryPressureVanGenuchten.md
- Documentation/ProjectFile/properties/property/CapillaryPressureVanGenuchten/t_exponent.md
- Documentation/ProjectFile/properties/property/CapillaryPressureVanGenuchten/t_maximum_capillary_pressure.md
- Documentation/ProjectFile/properties/property/CapillaryPressureVanGenuchten/t_maximum_liquid_saturation.md
- Documentation/ProjectFile/properties/property/CapillaryPressureVanGenuchten/t_p_b.md
- Documentation/ProjectFile/properties/property/CapillaryPressureVanGenuchten/t_residual_gas_saturation.md
- Documentation/ProjectFile/properties/property/CapillaryPressureVanGenuchten/t_residual_liquid_saturation.md
- MaterialLib/MPL/CreateProperty.cpp
- MaterialLib/MPL/Properties/CapillaryPressureSaturation/CapillaryPressureVanGenuchten.cpp
- MaterialLib/MPL/Properties/CapillaryPressureSaturation/CapillaryPressureVanGenuchten.h
- MaterialLib/MPL/Properties/CapillaryPressureSaturation/CreateCapillaryPressureVanGenuchten.cpp
- MaterialLib/MPL/Properties/CapillaryPressureSaturation/CreateCapillaryPressureVanGenuchten.h
- MaterialLib/MPL/Properties/CreateProperties.h
- MaterialLib/MPL/PropertyType.h
- Tests/MaterialLib/TestMPLCapillaryPressureVanGenuchten.cpp
An implementation of capillary pressure calculation from liquid saturation. This is not an inverse of the
SaturationVanGenuchten model, because the resulting capillary pressure is cut off at some maximum value.
1. [ ] Feature description was added to the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.3.1)
> Capillary pressure - van Genuchten model.

- Applications/DataExplorer/VtkVis/NetCdfConfigureDialog.cpp
- Applications/DataExplorer/VtkVis/VtkCompositeTextureOnSurfaceFilter.cpp
- Applications/DataExplorer/VtkVis/VtkGeoImageSource.cpp
- Applications/DataExplorer/VtkVis/VtkGeoImageSource.h
- Applications/DataExplorer/VtkVis/VtkRaster.cpp
- Applications/DataExplorer/VtkVis/VtkRaster.h
- Applications/DataExplorer/VtkVis/VtkTextureOnSurfaceFilter.cpp
- Applications/DataExplorer/VtkVis/VtkTextureOnSurfaceFilter.h
- Applications/DataExplorer/mainwindow.cpp
- Tests/FileIO_Qt/TestVtkRaster.cpp
- Tests/MeshLib/TestRasterToMesh.cpp
Small changes regarding positioning raster data in geographic context.
Previously, position data had been sometimes pulled from image algorithm object and sometimes been given explicitely via parameters. Now it's *always* within the image algorithm, making the interface slimmer and reducing the number of ambiguous cases.
(I cannot currently test this for GeoTIFFs. It *should* work but I'm not 100% sure.)
> [DE] Raster translation fix

- Applications/Utils/MeshEdit/NodeReordering.cpp
Pyramid elements with incorrect node ordering can reordered now correctly. This works at least for one test mesh. More meshes to test are welcome.
1. [ ] Feature description was added to the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.3.1)
> [A/U/ME] Change reordering for pyramid elements.

- MaterialLib/SolidModels/MFront/CMakeLists.txt
- MaterialLib/SolidModels/MFront/MohrCoulombAbboSloan.mfront
- MaterialLib/SolidModels/MFront/MohrCoulombAbboSloanAniso.mfront
- MaterialLib/SolidModels/MFront/MohrCoulombAbboSloanOrtho.mfront
- MaterialLib/SolidModels/MFront/MohrCoulombAbboSloanUBI.mfront
- MaterialLib/SolidModels/MFront/MohrCoulombAbboSloanUBI.mtest
- MaterialLib/SolidModels/MFront/MohrCoulombAbboSloanUBIOrtho.mfront
- ProcessLib/SmallDeformation/Tests.cmake
- Tests/Data/Mechanics/MohrCoulombAbboSloanAnisotropic/run_script.py
- Tests/Data/Mechanics/MohrCoulombAbboSloanAnisotropic/square_1x1.gml
- Tests/Data/Mechanics/MohrCoulombAbboSloanAnisotropic/square_1x1_quad_1e0.vtu
- Tests/Data/Mechanics/MohrCoulombAbboSloanAnisotropic/triax_1e0_47.prj
- Tests/Data/Mechanics/MohrCoulombAbboSloanAnisotropic/triax_47_pcs_0_ts_200_t_2.000000.vtu
- Tests/Data/Mechanics/MohrCoulombAbboSloanAnisotropic/triax_ORTHO_original.prj
- Tests/Data/Mechanics/MohrCoulombAbboSloanAnisotropic/triax_aniso_1e0_47.prj
- Tests/Data/Mechanics/MohrCoulombAbboSloanAnisotropic/triax_aniso_47_pcs_0_ts_200_t_2.000000.vtu
- Tests/Data/Mechanics/MohrCoulombAbboSloanAnisotropic/triax_aniso_original.prj
- Tests/Data/Mechanics/MohrCoulombAbboSloanAnisotropic/triax_original.prj
- Tests/Data/Mechanics/MohrCoulombAbboSloanAnisotropic/triax_ortho_1e0_47.prj
- Tests/Data/Mechanics/MohrCoulombAbboSloanAnisotropic/triax_ortho_47_pcs_0_ts_200_t_2.000000.vtu
Inclusion of several new MFront material models:
-- anisotropic Mohr Coulomb (reference included in mfront file)
-- Mohr Coulomb with embedded Coulomb weakness plane (standard model).
Jupyter Notebook script that runs about 90 tests on literature parameter sets (references in script).
> Weak plane

- Applications/FileIO/Legacy/createSurface.cpp
Fixes an issue with calling GMSH if the path includes whitespaces.
(This was fixed before for creating meshes but apparently not when meshing geometric surfaces.)
> fixing command line in case of whitespaces in path

- ProcessLib/HydroMechanics/HydroMechanicsFEM-impl.h
- ProcessLib/PhaseField/PhaseFieldFEM.h
- ProcessLib/RichardsMechanics/RichardsMechanicsFEM-impl.h
- ProcessLib/RichardsMechanics/RichardsMechanicsFEM.h
- ProcessLib/SmallDeformation/SmallDeformationFEM.h
- ProcessLib/SmallDeformationNonlocal/SmallDeformationNonlocalFEM.h
- ProcessLib/ThermoHydroMechanics/ThermoHydroMechanicsFEM.h
- ProcessLib/ThermoMechanicalPhaseField/ThermoMechanicalPhaseFieldFEM.h
- ProcessLib/ThermoMechanics/ThermoMechanicsFEM-impl.h
- ProcessLib/ThermoMechanics/ThermoMechanicsFEM.h
- ProcessLib/Utils/SetOrGetIntegrationPointData.h
As titled.
The introduced common functions are included in a new file: 
`ProcessLib/Utils/SetOrGetIntegrationPointData.h`.
> Introduced common functions to remove code duplication in mechanics related processes

- Documentation/ProjectFile/properties/property/CapillaryPressureRegularizedVanGenuchten/c_CapillaryPressureRegularizedVanGenuchten.md
- Documentation/ProjectFile/properties/property/CapillaryPressureRegularizedVanGenuchten/t_exponent.md
- Documentation/ProjectFile/properties/property/CapillaryPressureRegularizedVanGenuchten/t_p_b.md
- Documentation/ProjectFile/properties/property/CapillaryPressureRegularizedVanGenuchten/t_residual_gas_saturation.md
- Documentation/ProjectFile/properties/property/CapillaryPressureRegularizedVanGenuchten/t_residual_liquid_saturation.md
- Documentation/bibliography.bib
- MaterialLib/MPL/CreateProperty.cpp
- MaterialLib/MPL/Properties/CapillaryPressureSaturation/CapillaryPressureRegularizedVanGenuchten.cpp
- MaterialLib/MPL/Properties/CapillaryPressureSaturation/CapillaryPressureRegularizedVanGenuchten.h
- MaterialLib/MPL/Properties/CapillaryPressureSaturation/CreateCapillaryPressureRegularizedVanGenuchten.cpp
- MaterialLib/MPL/Properties/CapillaryPressureSaturation/CreateCapillaryPressureRegularizedVanGenuchten.h
- MaterialLib/MPL/Properties/CreateProperties.h
- MaterialLib/MPL/Utils/CheckVanGenuchtenExponentRange.cpp
- MaterialLib/MPL/Utils/CheckVanGenuchtenExponentRange.h
- Tests/MaterialLib/TestMPLCapillaryPressureRegularizedVanGenuchten.cpp
as titled.
In the old  old implementation, pc of  S  in [Smax, 1] is wrong, which should be zero. 
2. [x] Tests covering your feature were added? Yes.
The following figure shows the curve of the regularized pc(S) in the test:
3. [x] Any new feature or behavior change was documented? Yes
> Copy the old implementation regularized van Genuchten to MPL with some improvements

- GeoLib/DuplicateGeometry.cpp
Previously, names of objects were ignored. Now they're copied along with the geometric information.
> [geolib] copy geometrical object names when duplicating geometries

- MaterialLib/MPL/Component.cpp
- MaterialLib/MPL/Component.h
- MaterialLib/MPL/Medium.cpp
- MaterialLib/MPL/Medium.h
- MaterialLib/MPL/Phase.cpp
- MaterialLib/MPL/Phase.h
- MaterialLib/MPL/Property.cpp
- MaterialLib/MPL/Property.h
Improves error handling upon access of wrong type.
For the extra information on the medium/phase/component the definition scale was moved to the property.
Closes #2933 
Review commit-wise.
TODO:
> Improve error handling in MPL

- Applications/Utils/FileConverter/NetCdfConverter.cpp
- Tests/Data/FileConverter/slim_100897_198.vtu
Allows to manually set the no data value when converting netCDF data.
It's not straightforward to automatically extract this from the file, so this allows to handle the issue in the rare cases when not the default value is used.
> [netcdf] allow explicitly setting no data value

- MaterialLib/SolidModels/CreepBGRa.h
- MaterialLib/SolidModels/LinearElasticOrthotropic.h
So far, these two models did not have expressions to compute bulk moduli of the porous matrix. This PR adds this functionality which is required when using these models with HM or RM processes to compute intrinsic solid compressibility.
> Added bulk moduli computation to CreepBGRa and LinearElasticOrthotropic.

- Applications/ApplicationsLib/ProjectData.cpp
- MaterialLib/MPL/CreateComponent.cpp
- MaterialLib/MPL/CreateComponent.h
- MaterialLib/MPL/CreateMedium.cpp
- MaterialLib/MPL/CreateMedium.h
- MaterialLib/MPL/CreatePhase.cpp
- MaterialLib/MPL/CreatePhase.h
- MaterialLib/MPL/CreateProperty.cpp
- MaterialLib/MPL/CreateProperty.h
- Tests/MaterialLib/TestMPL.cpp
- Tests/MaterialLib/TestMPL.h
As titled,  `ProjectData::_mesh_vec[0]->getDimension()` is passed into the functions for creating properties.
There exists a  property creation function, 
[CreatePermeabilityOrthotropicPowerLaw.cpp](https://github.com/ufz/ogs/blob/master/MaterialLib/MPL/Properties/CreatePermeabilityOrthotropicPowerLaw.cpp#L64-L82), 
which use the size of the input parameter as the geometry dimension. For properties that such parameter size may not be identical to the the geometry dimension, such consideration is invalid. Besides, the input info should be made as unique as possible. Therefore, the changes in this PR were made.
> Pass the geometry dimension to functions for creating properties

- Tests/MeshLib/TestRasterToMesh.cpp
Triggered by fixing a warning of uninitialized spacing variable.
> [T] RasterToMesh: Const, auto, unused uninit vars.

- Applications/DataExplorer/DataView/MeshView.cpp
- Applications/Utils/MeshEdit/AddTopLayer.cpp
- MeshLib/MeshEditing/AddLayerToMesh.cpp
- MeshLib/MeshEditing/AddLayerToMesh.h
- MeshLib/MeshGenerators/MeshGenerator.cpp
- Tests/MeshLib/TestAddLayerToMesh.cpp
In some applications it is practical to adopt the material ID of the underlying layer.
> Add switch to function addLayerToMesh to copy the MaterialID.

- NumLib/TimeStepping/Algorithms/CreateEvolutionaryPIDcontroller.cpp
- NumLib/TimeStepping/Algorithms/CreateIterationNumberBasedTimeStepping.cpp
- NumLib/TimeStepping/Algorithms/EvolutionaryPIDcontroller.cpp
- NumLib/TimeStepping/Algorithms/IterationNumberBasedTimeStepping.cpp
- ProcessLib/Output/CreateOutput.cpp
- ProcessLib/Output/Output.cpp
- ProcessLib/Output/Output.h
Fixes missed output in case of repeated time step.
> Dont skip output of repeated fixed time step

- MaterialLib/FractureModels/Coulomb.cpp
Throwing an exception, which can be caught and lead to rejection of the time step.
> [MatL] Fracture/Coulomb. Throw on error.

- Documentation/ProjectFile/properties/property/Exponential/c_Exponential.md
- Documentation/ProjectFile/properties/property/Exponential/exponent/t_factor.md
- Documentation/ProjectFile/properties/property/Exponential/exponent/t_reference_condition.md
- Documentation/ProjectFile/properties/property/Exponential/exponent/t_variable_name.md
- Documentation/ProjectFile/properties/property/Exponential/t_offset.md
- MaterialLib/MPL/Properties/CreateExponential.cpp
- MaterialLib/MPL/Properties/Exponential.cpp
- MaterialLib/MPL/Properties/Exponential.h
- Tests/Data/Parabolic/HT/FaultedCube/Ra_795_fault_bcgs_jacobi.prj
- Tests/Data/RichardsMechanics/deformation_dependent_porosity_swelling.prj
- Tests/MaterialLib/TestMPLExponential.cpp
A small generalization.
Can be used for exponential saturation-head relation as described by Tracy2006 paper for analytical solutions of Richards equation. [https://doi.org/10.1029/2005WR004638]
1. [ ] Feature description was added to the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.3.1)
> MPL exponenential property additive offset
