ufz/ogs

Tests/MeshLib/MeshProperties.cpp

[T] Fix compile issue: Added include for mac and windows.

---

Applications/Utils/MeshEdit/CMakeLists.txt
Applications/Utils/MeshEdit/editMaterialID.cpp
Applications/Utils/MeshEdit/reviseMesh.cpp
FileIO/CMakeLists.txt
FileIO/writeMeshToFile.cpp
FileIO/writeMeshToFile.h
MeshLib/MeshEditing/ElementValueModification.cpp
MeshLib/MeshEditing/ElementValueModification.h
MeshLib/MeshEnums.cpp
MeshLib/MeshEnums.h

This PR introduces
- a new tool reviseMesh based on MeshRevision class
- supporting element type to modify material IDs

Add reviseMesh tool and modify editMaterialID tool

---

Applications/DataExplorer/main.cpp
Applications/DataExplorer/mainwindow.cpp
Applications/DataExplorer/mainwindow.h

as titled. this is my first try and any suggestions are welcome.

[DataExplorer] automatically load a file given as a command line argument

---

.travis.yml

- apt-get install outputs errors only
- install CMake 3.1.1 system-wide
- install VTK system-wide

Some travis script improvements

---

Applications/Utils/CMakeLists.txt
Applications/Utils/GeoTools/CMakeLists.txt
Applications/Utils/GeoTools/TriangulatePolyline.cpp
GeoLib/Polyline.cpp
GeoLib/Polyline.h

this is a request by @waltherm
a command line tool for specifying a polyline that should be triangulated into a surface.
tests if line is closed and coplaner, if not closed user can specify if line should be closed prior to triangulating.

Cmdline tool for triangulating polylines

---

FileIO/readMeshFromFile.cpp

As the title.
The first commit is PR #577.

Added reading partitioned mesh to readMeshFromFile

---

Tests/MeshLib/TestMeshValidation.cpp

I forgot to switch on the utils before merging the original branch. Here small changes, no logic changes.

Mesh hole detection fixes

---

Applications/DataExplorer/mainwindow.cpp
FileIO/GMSHInterface.cpp
FileIO/GMSHInterface.h

* moved gmsh-geo-export to GMSHInterface
* fixed issue where geo export would fail if only one geometry was loaded
* output of correct error messages in data explorer

[Fix] Several issues with GMSH geo file export

---

.editorconfig

This PR adds a configuration file which configures your IDE to use consistent file formatting. Have a look at the config file to see the used settings. Although you need a IDE-specific plugin to make this happen. There are plugins for Visual Studio, Vim, Sublime Text and more.
See http://editorconfig.org for more info.

Use editorconfig

---

Tests/CMakeLists.txt

Fixed the problem reported in #606.

[CM] Fixed MPITest on travis.

---

FileIO/XmlIO/Boost/BoostXmlGmlInterface.cpp
FileIO/XmlIO/Qt/XmlGmlInterface.cpp
GeoLib/TemplateVec.h

[GeoLib] Output warning in case a polyline-name already exists

---

Applications/DataExplorer/DataView/CMakeLists.txt
Applications/DataExplorer/DataView/MergeGeometriesDialog.cpp
Applications/DataExplorer/DataView/MergeGeometriesDialog.h
Applications/DataExplorer/DataView/MeshQualitySelection.ui
Applications/DataExplorer/DataView/MeshQualitySelectionDialog.cpp
Applications/DataExplorer/DataView/MeshQualitySelectionDialog.h
Applications/DataExplorer/DataView/SetNameDialog.cpp
Applications/DataExplorer/DataView/SetNameDialog.h
Applications/DataExplorer/VtkVis/VtkVisPipeline.h
Applications/DataExplorer/mainwindow.cpp
GeoLib/GEOObjects.cpp
GeoLib/GEOObjects.h

Changed a few dialogue calls such that dialogues get only the information they absolutely need.

Data explorer dialog calls

---

GeoLib/MinimalBoundingSphere.cpp
GeoLib/MinimalBoundingSphere.h
scripts/cmake/CompilerSetup.cmake

This enables assertions in the STL code in the glibcxx.
Also fix a discovered bug in minimum bounding box algorithm.

Enable STL assertions for Debug builds with gcc/clang.

---

Applications/DataExplorer/VtkVis/VtkGeoImageSource.cpp
Applications/DataExplorer/VtkVis/VtkGeoImageSource.h
Applications/DataExplorer/VtkVis/VtkRaster.cpp
Applications/DataExplorer/mainwindow.cpp
FileIO/AsciiRasterInterface.cpp

* added error handling if file cannot be read
* added alternative tags supported by new arcgis version

[Fix] handling errors when reading raster files

---

.travis.yml

as titled related to issue #625

Use a new PPA for PETSc

---

.travis.yml
Applications/CLI/CMakeLists.txt
Tests/AssemblerLib/TestSerialVectorMatrixBuilder.cpp
Tests/CMakeLists.txt

Three commits unrelated to each other:
Adding one test. Change configuration of petsc/mpi tests.

Petsc/mpi tests.

---

MeshLib/MeshEditing/MeshRevision.cpp
MeshLib/MeshEditing/MeshRevision.h

Only critical part of this PR are commit  2d89f5d and  bf41054. All other commits are reformating things.

Cleanup mesh editing

---

MeshGeoToolsLib/GeoMapper.cpp
MeshGeoToolsLib/GeoMapper.h
MeshLib/MeshEditing/projectMeshOntoPlane.h
MeshLib/Node.h
Tests/MeshLib/TestProjectMeshOnPlane.cpp

A small method that projects a mesh to an arbitrary plane defined by point of origin + normal vector.

Project mesh to plane

---

Applications/Utils/MeshEdit/ResetPropertiesInPolygonalRegion.cpp

As titled. Also added/updated [documentation](http://docs.opengeosys.org/docs/tools/meshing/set-properties-in-polygonal-region)

Using new data structures of Mesh to reset property values.

---

GeoLib/AnalyticalGeometry.cpp
Tests/GeoLib/TestComputeRotationMatrix.cpp

As titled. Also added a simple test.

Fix bug in GeoLib::computeRotationMatrixToXY

---

FileIO/Legacy/MeshIO.cpp

fix a bug in reading legacy Mesh file

---

Applications/DataExplorer/mainwindow.cpp
Applications/Utils/MeshEdit/CMakeLists.txt
Applications/Utils/MeshEdit/MapGeometryToMeshSurface.cpp
MeshGeoToolsLib/GeoMapper.cpp
MeshGeoToolsLib/GeoMapper.h

as titled.
I am also open for suggestions to improve the [documentation](http://docs.opengeosys.org/docs/tools/meshing/map-geometric-object-to-the-surface-of-a-mesh) of the tool.

Command line tool for mapping geometry to the surface of a mesh

---

MeshLib/MeshEditing/MeshRevision.cpp
MeshLib/MeshEditing/MeshRevision.h

- Main changes in MeshLib/MeshEditing/MeshRevision.

Using new interface of Mesh to access Properties and PropertyVector in class MeshRevision

---

MeshLib/MeshSubset.h
ProcessLib/GroundwaterFlowProcess.h
Tests/AssemblerLib/LocalToGlobalIndexMap.cpp
Tests/AssemblerLib/TestMeshComponentMap.cpp
Tests/AssemblerLib/TestSerialLinearSolver.cpp
Tests/AssemblerLib/TestSerialVectorMatrixBuilder.cpp
Tests/MeshLib/MeshSubsets.cpp

Remove a memory leak in MeshSubset. Documentation.

MeshSubset cleanup

---

NumLib/Fem/ShapeFunction/ShapePrism15-impl.h

fix compiling errors

---

Applications/Utils/GeoTools/CMakeLists.txt
Applications/Utils/MeshEdit/CMakeLists.txt
Applications/Utils/SimpleMeshCreation/CMakeLists.txt

Utilities will later on be available as binary downloads on ogs.org.

CMake instructions for installing utilities

---

MeshLib/VtkOGSEnum.cpp
Tests/MeshLib/MeshProperties.cpp

... using MS Visual Studio.
Note: A few warnings are left in the ```CoordinateSystem``` class because I don't know how to handle them. I already dropped Nori an e-mail.

Fixing warnings

---

GeoLib/Raster.cpp

This solves issues #677 and #678
Edit: For easier reviewing, actual changes are only present in lines 137, 151-156 and 173.
Everything else is just indentation changes.

[Fix] Solving several issues concerned with mesh mapping using raster files

---

Applications/Utils/MeshEdit/AddTopLayer.cpp

Corrected node sequence for Prisms.

Very small bug fix in AddTopLayer util

---

InSituLib/VtkMappedMeshSource.cpp
InSituLib/VtkMappedMeshSource.h
MeshLib/MeshGenerators/VtkMeshConverter.cpp
MeshLib/MeshGenerators/VtkMeshConverter.h
Tests/InSituLib/TestVtkMappedMeshSource.cpp
Tests/InSituLib/TestVtkMappedPropertyVector.cpp
Tests/MeshLib/TestVtkMeshConverter.cpp

- Added mapped unsigned properties
- Added explicit conversion for unsigned MaterialIDs to int

Unsigned properties and MaterialIDs conversion

---

MathLib/LinAlg/Dense/DenseVector.h

a template type was not used in some places in DenseVector

---

NumLib/Fem/CoordinatesMapping/NaturalCoordinatesMapping-impl.h
NumLib/Fem/ShapeMatrixPolicy.h
Tests/NumLib/FeTestData/TestFeLINE2Y.h
Tests/NumLib/TestFe.cpp

This PR fixes the issue reported in #723 together with a test

fix Eigen issue with auto keyword in NaturalCoordinatesMapping

---

Applications/CLI/CMakeLists.txt
MathLib/Nonlinear/NewtonRaphson-impl.h
MathLib/Nonlinear/NewtonRaphson.h
MathLib/Nonlinear/Picard-impl.h
MathLib/Nonlinear/Picard.h
NumLib/Fem/Integration/GaussIntegrationPolicy.h
NumLib/TimeStepping/Algorithms/ITimeStepAlgorithm.h

This PR provides corrections of includes in some files, changes of debug macro, and linking NumLib to ogs.

Minor fixes

---

NumLib/Fem/CoordinatesMapping/ShapeMatrices-impl.h
NumLib/Fem/CoordinatesMapping/ShapeMatrices.h

as titled. new reset() takes golobal dim

[NUM] add another version of  reset() in ShapeMatrices 

---

NumLib/Fem/CoordinatesMapping/ShapeMatrices.h

See http://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html for details.

[NL] Fix possible alignment issues with eigen.

---

FileIO/Legacy/OGSIOVer4.cpp
Tests/GeoLib/TestPolygon.cpp
Tests/GeoLib/TestPolyline.cpp
Tests/GeoLib/TestSimplePolygonTree.cpp

Should fix windows builds on Jenkins.

Removed using namespace GeoLib.

---

AssemblerLib/CMakeLists.txt
MeshGeoToolsLib/CMakeLists.txt
MeshLib/CMakeLists.txt
Tests/MeshLib/TestUniqueMeshId.cpp

I encountered some linking errors with the latest maser and fixed them with this PR. However, travis and Jenkins are actually working fine. so it could be specific to my environment.

fix linking errors

---

MathLib/CMakeLists.txt

Cleanup MathLib/CMake

---

MeshLib/MeshGenerators/MeshGenerator.cpp
MeshLib/MeshGenerators/MeshGenerator.h

This PR is a preparation for another PR that will improve the search for points/nodes along surfaces.

Add another function for construction of a surface mesh approximating a function.

---

Applications/DataExplorer/DataView/GEOModels.cpp
Applications/DataExplorer/DataView/GeoTreeModel.cpp
Applications/DataExplorer/VtkVis/VtkSurfacesSource.cpp
Applications/Utils/FileConverter/generateBCandGLI.cpp
FileIO/TINInterface.cpp
FileIO/TetGenInterface.cpp
FileIO/XmlIO/Qt/XmlGmlInterface.cpp
GeoLib/GEOObjects.cpp
GeoLib/Raster.cpp
GeoLib/Surface.cpp
GeoLib/Surface.h
MeshLib/convertMeshToGeo.cpp
Tests/FileIO/TestXmlGmlReader.cpp

- Added forward declaration of class `Triangle` in class `Surface`.
- Fixed include issue with class `Color`.

[GeoLib] Another forward declaration.

---

FileIO/CMakeLists.txt
MathLib/CMakeLists.txt

Should also fix the Mac-PR build in #789

Added dependency on Eigen for FileIO and MathLib

---

Applications/DataExplorer/VtkVis/VtkMeshSource.cpp
Applications/DataExplorer/VtkVis/VtkMeshSource.h
Applications/DataExplorer/VtkVis/VtkVisPipelineItem.cpp
Applications/DataExplorer/VtkVis/VtkVisPipelineView.cpp
Applications/DataExplorer/VtkVis/VtkVisPointSetItem.cpp
InSituLib/VtkMappedMeshSource.cpp
MeshLib/MeshGenerators/VtkMeshConverter.cpp

Several Data Explorer fixes

---

Applications/DataExplorer/VtkVis/VtkPolylinesSource.cpp
Tests/GeoLib/TestPointVec.cpp

Remove mem leaks

---

GeoLib/Grid.h

This PR extracts some changes in #789 which are moving definitions of Grid functions (no changes in algorithms).

rework of Grid

---

MathLib/LinAlg/Eigen/EigenMatrix.h
MathLib/LinAlg/EigenLis/EigenLisLinearSolver.cpp
MathLib/LinAlg/Lis/LisLinearSolver.cpp

This PR includes several improvements in MathLib/LinAlg
- LisLinearSolver: call lis_solver_set_optionC() to configure Lis solver with command line arguments
- EigenLisLinearSolver: improve efficiency in solve()
- EigenMatrix: improve efficiency in setZero()

some improvements in MathLib/LinAlg

---

MathLib/LinAlg/MatrixTools.h
NumLib/Fem/CoordinatesMapping/NaturalCoordinatesMapping-impl.h
NumLib/Fem/CoordinatesMapping/ShapeMatrices-impl.h
Tests/MathLib/TestLocalMatrixFunctions.cpp
Tests/NumLib/FeTestData/MatrixTools.h

as titled. `setZeo()`, `inverse()`, `determinant()` in Eigen::Matrix can be slow (at least with dynamic matrix).

Repleacement of some Eigen functions with own implementations in shape stuff

---

MeshLib/Mesh.cpp

bugfix in Mesh::calcNodeDistanceRange()

---

GeoLib/AnalyticalGeometry-impl.h
GeoLib/AnalyticalGeometry.cpp
GeoLib/AnalyticalGeometry.h
NumLib/Function/LinearInterpolationOnSurface.cpp

fix a bug that an interpolation point was not rotated to XY plane

bugfix in LinearInterpolationOnSurface

---

FileIO/FEFLOWInterface.cpp

as titled. reported by @fabienma

bugfix in reading quad elements in FEFLOW files.

---

BaseLib/LogogCustomCout.h

added `std::flush` in `LogogCustomCout` to get real time log output from applications.

flush logog message

---

Applications/Utils/SimpleMeshCreation/createMeshElemPropertiesFromASCRaster.cpp
BaseLib/quicksort.h
GeoLib/Polygon.cpp
MathLib/InterpolationAlgorithms/PiecewiseLinearInterpolation.cpp
MathLib/LinAlg/Sparse/NestedDissectionPermutation/AdjMat.cpp
MeshGeoToolsLib/MeshNodesAlongPolyline.cpp
Tests/BaseLib/TestQuicksort.cpp

The PR substitutes divers implemented versions of the quicksort algorithm using stl functions.

Substituting Quicksort algorithms

---

GeoLib/Grid.h
MeshGeoToolsLib/MeshNodeSearcher.cpp
MeshGeoToolsLib/MeshNodeSearcher.h
MeshGeoToolsLib/MeshNodesOnPoint.cpp
MeshGeoToolsLib/MeshNodesOnPoint.h
MeshGeoToolsLib/SearchLength.h
MeshLib/MeshEditing/MeshRevision.cpp
Tests/MeshLib/TestBoundaryElementSearch.cpp
Tests/MeshLib/TestMeshNodeSearch.cpp

This PR is a collaboration of @norihiro-w and me. It contains:
- rework of class Grid,
- new method `Grid::getPointsInEpsilonEnvironment()`,
- new class `MeshNodesOnPoint`
This is an updated version of PR https://github.com/ufz/ogs/pull/796.

Grid extension for MeshNodeSearch

---

GeoLib/GEOObjects.cpp

This reduces noise on the console.
Someone more knowledgable about the GEOObjects might have a look if the messages are needed at all.

Replace GEOObjects info/err msg with DBUG.

---

Applications/ApplicationsLib/ProjectData.cpp
Applications/ApplicationsLib/ProjectData.h
Applications/CLI/ogs.cpp
MathLib/LinAlg/Eigen/EigenMatrix.h
MathLib/LinAlg/Eigen/EigenTools.cpp
MathLib/LinAlg/Eigen/EigenVector.h
MathLib/Nonlinear/Picard-impl.h
MathLib/Nonlinear/Picard.cpp
ProcessLib/ProcessVariable.cpp
ProcessLib/ProcessVariable.h

This PR contains only changes to some small issues, most notably:
* XML Parser now trims whitespace
* changed ICs and BCs in ProcessVariable to unique_ptr

Small issues

---

NumLib/Fem/CoordinatesMapping/NaturalCoordinatesMapping-impl.h
ProcessLib/GroundwaterFlowFEM.h

- Avoid some implicit type conversions.
- Reuse existing type definitons.

Small cleanup

---

FileIO/SHPInterface.cpp
FileIO/SHPInterface.h

The PR is based on PR https://github.com/ufz/ogs/pull/817 and must not be merged before. It contains the removal of some methods not used anymore and fixes a mem leak.

Shape interface improvements

---

Applications/CLI/ogs.cpp

This is a split-off from ufz/ogs#580.
When we add some more init/finalize stuff using preprocessor here it will be a preprocessor-jungle.
Any ideas how to avoid these ifdef's? Feel free to merge otherwise.

[CLI] Added PETSc and MPI stuffs in main function of CLI.

---

MeshLib/NodePartitionedMesh.h

This is a split-off from ufz/ogs#580
Both new functions are indeed used in the above mentioned PR.
Unfortunatly jenkins went down some time ago and I can only hope for correct compilation on other platforms but linux.
@wenqing Please confirm this code is working for you, then someone merge it.

Node partitioned mesh

---

FileIO/readMeshFromFile.cpp

Corrected a value to a function argument.

Corrected an error in PR #834

---

MeshGeoToolsLib/GeoMapper.cpp
MeshGeoToolsLib/GeoMapper.h

[MGT] Fix bug in GeoMapper::mapOnMesh().

---

BaseLib/quicksort.h
Tests/BaseLib/TestQuicksort.cpp
Tests/MathLib/AutoCheckTools.h
scripts/cmake/Find.cmake

[BL] Quicksort: Fix miscalculated second limit.

---

GeoLib/Grid.h
GeoLib/PointVec.cpp
GeoLib/Triangle.cpp
MeshLib/convertMeshToGeo.cpp

Some small changes to the code while preparation for major changes in TemplateVec, which otherwise will be difficult to untangle if presented together.
No logic changes.

unique_ptr TemplateVec preparations

---

Applications/DataExplorer/DataView/NetCdfConfigureDialog.cpp
Applications/DataExplorer/DataView/NetCdfConfigureDialog.h
Applications/Utils/MeshEdit/CreateBoundaryConditionsAlongPolylines.cpp
GeoLib/GEOObjects.cpp
MeshLib/Elements/Element.h
MeshLib/MeshGenerators/MeshGenerator.cpp

- `GEOObjects`: Omit crash in adding an empty vector of points.
-  `createSurfaceMesh`: Fix a logical bug. Mesh size is as expected now.
- `NetCdfConfigureDialog`: Fix a mem leak and const correctness.

Small bug fixes

---

Applications/CLI/ogs.cpp
MeshGeoToolsLib/GeoMapper.cpp
ProcessLib/ProcessVariable.cpp

proposed under the slogan "Don't pollute you PR!"

Various cleanups.

---

MathLib/LinAlg/Eigen/EigenTools.cpp

The provided implementation of `applyKnownSolution()` transposes the matrix and thereby avoids expensive searching for the right column.
This drastically increases perfomance for big matrices.

[MaL] faster applyKnownSolution

---

AssemblerLib/ComputeSparsityPattern.cpp
AssemblerLib/ComputeSparsityPattern.h
AssemblerLib/LocalToGlobalIndexMap.h
MathLib/LinAlg/Eigen/EigenMatrix.h
MathLib/LinAlg/Lis/LisMatrix.h
MeshLib/NodeAdjacencyTable.h
ProcessLib/GroundwaterFlowProcess.h

This PR provides a multi-component aware implementation for setting matrix sparsities.

Multi-component sparsity pattern

---

MathLib/LinAlg/Lis/LisTools.cpp
MathLib/LinAlg/Lis/LisTools.h
MathLib/LinAlg/Sparse/CRSTools-impl.h
MathLib/LinAlg/Sparse/CRSTools.h

- Integration of boundary conditions of first-type into the system of linear equations using the `CRSMatrix` as system matrix
- Converter to use this integration together with the LIS data structures

Integration of boundary conditions of first-type

---

.idea/codeStyleSettings.xml
.idea/encodings.xml
.idea/misc.xml

Especially `SMART_TABS` is important because this is for "indent with tabs, align with spaces".

Updated CLion project files

---

Applications/Utils/MeshEdit/CreateBoundaryConditionsAlongPolylines.cpp

also updated the [docu](http://docs.opengeosys.org/docs/tools/meshing/create-boundary-conditions-along-a-polyline)

Cleanup in CreateBoundaryConditionsAlongPolyline.

---

Applications/DataExplorer/DataView/MshModel.cpp
Applications/DataExplorer/VtkVis/VtkCompositeThresholdFilter.cpp
Applications/DataExplorer/VtkVis/VtkVisPipeline.cpp
Applications/DataExplorer/VtkVis/VtkVisTabWidget.cpp
Applications/DataExplorer/mainwindow.cpp
MeshLib/MeshGenerators/VtkMeshConverter.cpp

Fixes for AlgorithmProperties and small bug fixes.

---

CMakeLists.txt
NumLib/Fem/CoordinatesMapping/ShapeMatrices.h
ProcessLib/NeumannBcAssembler.h
Tests/NumLib/TestCoordinatesMapping.cpp
Tests/NumLib/TestFe.cpp
Tests/NumLib/TestShapeMatrices.cpp

Fixes https://github.com/ufz/ogs/issues/881
Along enabling the Eigen assertions fix some bugs in the code and in the testing code.

Enable Eigen assertions by default

---

Applications/DataExplorer/DataView/ElementTreeModel.cpp
Applications/DataExplorer/DataView/MeshElementRemovalDialog.cpp
MeshLib/Elements/Element.cpp
MeshLib/Elements/Element.h

MeshProperties DataExplorer

---

Applications/Utils/FileConverter/generateMatPropsFromMatID.cpp
Applications/Utils/MeshEdit/queryMesh.cpp
Applications/Utils/SimpleMeshCreation/createMeshElemPropertiesFromASCRaster.cpp

Extract from https://github.com/ufz/ogs/pull/897

Fixes for AlgorithmProperties and get- / setValue()-removal: Utils

---

Applications/DataExplorer/DataView/MeshLayerEditDialog.cpp
Applications/Utils/MeshEdit/appendLinesAlongPolyline.cpp
MeshGeoToolsLib/AppendLinesAlongPolyline.cpp
MeshGeoToolsLib/AppendLinesAlongPolyline.h
MeshGeoToolsLib/BoundaryElementsAtPoint.cpp
MeshLib/ElementStatus.cpp
MeshLib/Elements/TemplateElement-impl.h
MeshLib/Elements/TemplateElement.h
MeshLib/MeshEditing/DuplicateMeshComponents.cpp
MeshLib/MeshEditing/Mesh2MeshPropertyInterpolation.cpp
MeshLib/MeshGenerators/ConvertRasterToMesh.cpp
MeshLib/MeshGenerators/LayeredMeshGenerator.cpp
MeshLib/MeshGenerators/LayeredMeshGenerator.h
MeshLib/MeshGenerators/LayeredVolume.cpp
MeshLib/MeshGenerators/MeshLayerMapper.cpp
MeshLib/MeshGenerators/VtkMeshConverter.cpp
MeshLib/MeshInformation.cpp
MeshLib/MeshInformation.h
MeshLib/convertMeshToGeo.cpp
Tests/MeshLib/TestElementStatus.cpp
Tests/MeshLib/TestVtkMeshConverter.cpp
Tests/NumLib/TestFunctionInterpolation.cpp

Extracted / merged / rebase commits from PR #897.

Using MeshProperties in the complete MeshLib

---

FileIO/FEFLOWInterface.cpp
FileIO/FEFLOWInterface.h
FileIO/GMSInterface.cpp
FileIO/SHPInterface.cpp
FileIO/TetGenInterface.cpp
FileIO/TetGenInterface.h

Extracted from https://github.com/ufz/ogs/pull/897
TODO:

Fixes for AlgorithmProperties and get- / setValue()-removal; FileIO

---

CHANGELOG.md

[CHLog] Updated the changlog for v6.0.4

---

Tests/GeoLib/TestDividedByPlane.cpp
Tests/GeoLib/TestGEOObjectsMerge.cpp
Tests/GeoLib/TestGrid.cpp
Tests/GeoLib/TestPolyline.cpp

Cleanup GeoLib Tests

---

CHANGELOG.md
MathLib/LinAlg/Lis/LisTools.cpp

Moved the transformation "crs matrix" to "lis matrix" to a separate function.

Lis tools refactorization

---

MeshGeoToolsLib/GeoMapper.cpp

[MGTL] GeoMapper: allocate mem before using it.

Fix a memory bug in GeoMapper implementation.

---

Applications/DataExplorer/VtkVis/VtkColorLookupTable.cpp
Applications/DataExplorer/VtkVis/VtkColorLookupTable.h
InSituLib/VtkMappedMeshSource.cpp
InSituLib/VtkMappedMeshSource.h
MathLib/LinAlg/Sparse/CRSMatrix.h
MathLib/LinAlg/Sparse/CRSTools-impl.h
MeshLib/ElementStatus.cpp
MeshLib/ElementStatus.h
Tests/AssemblerLib/LocalToGlobalIndexMapMultiComponent.cpp
Tests/MeshLib/TestElementStatus.cpp
Tests/NumLib/TestFunctionInterpolation.cpp

Warnings gathered around from different compilers mainly clang and msvc.

Warnings cleanup

---

Applications/Utils/FileConverter/generateMatPropsFromMatID.cpp
Applications/Utils/MeshEdit/queryMesh.cpp
Applications/Utils/SimpleMeshCreation/createMeshElemPropertiesFromASCRaster.cpp
Applications/Utils/SimpleMeshCreation/generateStructuredMesh.cpp

- Use `FileIO::writeGeometryToFile()`
- Use `LogogSetup`
- Use `std::unique_ptr`

Cleanup in utils

---

scripts/cmake/CompilerSetup.cmake
scripts/cmake/Find.cmake

See [devguide](http://docs.opengeosys.org/docs/devguide/advanced/using-ccache) for usage instructions.

Enable ccache

---

Applications/Utils/MeshGeoTools/CMakeLists.txt
BaseLib/CMakeLists.txt
BaseLib/ConfigTree.cpp
BaseLib/ConfigTree.h
BaseLib/FileTools.cpp
CMakeLists.txt
Tests/FileIO/TestCsvReader.cpp
Tests/FileIO/TestGLIReader.cpp
Tests/FileIO/TestXmlGmlReader.cpp
scripts/cmake/ExternalProjectBoost.cmake

Header-only Boost

---

FileIO/VtkIO/VtuInterface.cpp

FileIO add error message in VtuInterface

---

GeoLib/CMakeLists.txt
scripts/cmake/SubmoduleSetup.cmake

The predicates will be used for a robust line segment intersection algorithm. This algorithm will be used in the reimplementation of the surface mapping algorithm, see issue #944.

[GL] Make tetgen predicates in OGS available.

---

Applications/Utils/MeshEdit/NodeReordering.cpp

Cleanup node reordering

---

Applications/DataExplorer/mainwindow.cpp

Bug reported by Jing. Fixed with the help of @bilke .

[DE] Fix bug in graphical user interface.

---

ProcessLib/DirichletBc.h
ProcessLib/GroundwaterFlowProcess.h
ProcessLib/ProcessVariable.cpp
ProcessLib/ProcessVariable.h
ProcessLib/UniformDirichletBoundaryCondition.h

This is a preparation PR before moving all of the boundary conditions to Process class (from the GroundwaterFlowProcess).
Also see https://github.com/ufz/ogs/issues/949

Extract Dirichlet type boundary conditions from GWF process.

---

Applications/DataExplorer/DataView/MeshAnalysisDialog.cpp
MeshLib/MeshQuality/MeshValidation.cpp
MeshLib/MeshQuality/MeshValidation.h

fixed two issues with analysis dialog

MeshAnalysisDialog fix

---

Applications/DataExplorer/DataView/AddLayerToMesh.ui
Applications/DataExplorer/DataView/AddLayerToMeshDialog.cpp
Applications/DataExplorer/DataView/AddLayerToMeshDialog.h
Applications/DataExplorer/DataView/CMakeLists.txt
Applications/DataExplorer/DataView/MshView.cpp
Applications/DataExplorer/DataView/MshView.h
Applications/Utils/MeshEdit/AddTopLayer.cpp
MeshLib/MeshEditing/AddLayerToMesh.cpp
MeshLib/MeshEditing/AddLayerToMesh.h

added the functionality of @TomFischer 's AddTopLayer tool to "normal" OGS/GUI
layers can now also be added at bottom of mesh

Add top layer for gui

---

Applications/DataExplorer/DataView/MeshAnalysisDialog.cpp
Applications/Utils/GeoTools/TriangulatePolyline.cpp
Applications/Utils/MeshEdit/NodeReordering.cpp
AssemblerLib/SerialExecutor.h
BaseLib/ConfigTreeNew.h
Documentation/Doxyfile.in
GeoLib/AnalyticalGeometry.h
GeoLib/MinimalBoundingSphere.cpp
GeoLib/MinimalBoundingSphere.h
MathLib/LinAlg/Dense/DenseMatrix-impl.h
MathLib/LinAlg/Dense/GlobalDenseMatrix-impl.h
MathLib/LinAlg/PETSc/PETScMatrix.h
MathLib/LinAlg/PETSc/PETScVector.h
MeshLib/Elements/PrismRule6.h
MeshLib/Elements/PyramidRule5.h
MeshLib/Elements/QuadRule8.h
MeshLib/Elements/QuadRule9.h
MeshLib/Elements/TetRule4.h
MeshLib/Elements/TriRule6.h
MeshLib/MeshEditing/projectMeshOntoPlane.h
MeshLib/MeshInformation.h
MeshLib/MeshQuality/MeshValidation.h
MeshLib/PropertyVector.h

* add auto brief for Qt-style (`//!`) comments
* remove those doxygen warnings that are not related to undocumented/renamed parameters

Remove some doxygen warnings

---

MathLib/Vector3.h

added check for normalising 0-vector

---

Applications/DataExplorer/VtkVis/CMakeLists.txt
Applications/Utils/SimpleMeshCreation/createMeshElemPropertiesFromASCRaster.cpp
FileIO/CMakeLists.txt
SimpleTests/MatrixTests/CMakeLists.txt
SimpleTests/MeshTests/CMakeLists.txt
SimpleTests/SolverTests/CMakeLists.txt

In preparation for building on a new Jenkins Docker slave (will be available after some WKDV-work).

Fixes for Windows cross-compilation

---

MeshLib/MeshEditing/AddLayerToMesh.cpp
MeshLib/MeshEditing/FlipElements.cpp
MeshLib/MeshEditing/FlipElements.h
Tests/MeshLib/TestFlipElements.cpp

adds a function to flip elements (i.e. reverse direction of 1d elems, change sign of normals for 2d elements). this solves #983.

Element flipping

---

ProcessLib/GroundwaterFlowProcess.h
ProcessLib/Process.h

No real code changes here, just moving of the output.
_Next steps:_ I'll introduce number of components in the ProcessVariable and extend the output to all of the process variables available in the Process.

[PL] Move up process' output. Split post and out.

---

.travis.yml
CMakeLists.txt
NumLib/Fem/ShapeMatrixPolicy.h

Added CMake option OGS_EIGEN_DYNAMIC for using dynamically allocated eigen matrices

---

Applications/DataExplorer/VtkVis/MeshFromRaster.ui
Applications/DataExplorer/VtkVis/MeshFromRasterDialog.cpp
Applications/DataExplorer/VtkVis/MeshFromRasterDialog.h
Applications/DataExplorer/VtkVis/VtkRaster.cpp
Applications/DataExplorer/VtkVis/VtkVisPipelineView.cpp
Applications/DataExplorer/VtkVis/VtkVisPipelineView.h
MeshLib/MeshEnums.h
MeshLib/MeshGenerators/VtkMeshConverter.cpp
MeshLib/MeshGenerators/VtkMeshConverter.h

this got a little out of hand. i basically rewrote the VtkMeshConverter parts for converting images to meshes. with the tiny addition that you can now choose if pixel values should be interpreted as mat ids or double arrays.
there will be at least two follow-up PRs on this but i guess this one is already long enough.

Raster values to mesh scalars

---

scripts/cmake/test/Test.cmake

Removed another data-target dependency

---

Applications/DataExplorer/VtkVis/VtkVisPipelineView.cpp
MeshLib/MeshGenerators/RasterToMesh.cpp
MeshLib/MeshGenerators/RasterToMesh.h
Tests/GeoLib/AutoCheckGenerators.h

See commit messages.
For the removed calls I assumed there are no side-effects.

Warnigs cleanup

---

Applications/Utils/MeshEdit/AddTopLayer.cpp
Applications/Utils/MeshEdit/CreateBoundaryConditionsAlongPolylines.cpp
Applications/Utils/MeshEdit/MapGeometryToMeshSurface.cpp
Applications/Utils/MeshEdit/ResetPropertiesInPolygonalRegion.cpp
Applications/Utils/MeshGeoTools/ComputeSurfaceNodeIDsInPolygonalRegion.cpp
Applications/Utils/SimpleMeshCreation/generateStructuredMesh.cpp

added urls of util documentation to -h output

---

Applications/DataExplorer/DataView/ElementTreeModel.cpp
Applications/DataExplorer/DataView/ElementTreeModel.h
Applications/DataExplorer/DataView/MshView.cpp
Applications/DataExplorer/DataView/MshView.h
Applications/DataExplorer/mainwindow.cpp
Applications/Utils/MeshEdit/checkMesh.cpp
MeshLib/MeshInformation.cpp
MeshLib/MeshInformation.h
MeshLib/convertMeshToGeo.cpp

generalised the methods for retrieving and displaying value bounds for all scalar arrays in a mesh

Property info display

---

Applications/DataExplorer/DataView/NetCdfConfigure.ui
Applications/DataExplorer/DataView/NetCdfConfigureDialog.cpp
Applications/DataExplorer/VtkVis/MeshFromRasterDialog.cpp
Applications/DataExplorer/VtkVis/MeshFromRasterDialog.h
Applications/DataExplorer/VtkVis/VtkVisPipelineView.cpp
Applications/DataExplorer/VtkVis/VtkVisPipelineView.h
MeshLib/MeshGenerators/RasterToMesh.cpp
MeshLib/MeshGenerators/RasterToMesh.h

names of data vecs can now be set from gui when converting a raster-/netcdf-file into a mesh.

Raster vector name

---

Tests/NumLib/TestFe.cpp

Fixes https://github.com/ufz/ogs/issues/1029

[T] Add all shapefunction/matrix-policy comb.

---

Applications/ApplicationsLib/ProjectData.h
AssemblerLib/ComputeSparsityPattern.h
ProcessLib/GroundwaterFlowProcess.h
ProcessLib/Process.cpp
ProcessLib/Process.h

Review commit-wise. There should be no behavioural changes.
~~@chleh Needs discussion on what is going into the base Process class...~~
Update: Extract common functions for

Separate GroundwaterFlow process parser from its ctor.

---

Applications/DataExplorer/DataView/AddLayerToMesh.ui
Applications/DataExplorer/DataView/CondFromRaster.ui
Applications/DataExplorer/DataView/DataExplorerSettings.ui
Applications/DataExplorer/DataView/GMSHPrefs.ui
Applications/DataExplorer/DataView/GeoOnMeshMapping.ui
Applications/DataExplorer/DataView/License.ui
Applications/DataExplorer/DataView/LineEdit.ui
Applications/DataExplorer/DataView/MergeGeometries.ui
Applications/DataExplorer/DataView/MeshAnalysis.ui
Applications/DataExplorer/DataView/MeshElementRemoval.ui
Applications/DataExplorer/DataView/MeshQualitySelection.ui
Applications/DataExplorer/DataView/MeshValueEdit.ui
Applications/DataExplorer/DataView/NetCdfConfigure.ui
Applications/DataExplorer/DataView/NetCdfConfigureDialog.cpp
Applications/DataExplorer/DataView/SaveMesh.ui
Applications/DataExplorer/DataView/SurfaceExtraction.ui
Applications/DataExplorer/VtkVis/VisPrefs.ui
Applications/DataExplorer/VtkVis/VtkAddFilterDialogBase.ui
Applications/DataExplorer/mainwindow.ui

I don't think there is much need for a review here. This PR contains only cosmetic changes (size constraints, fixing typos, fixing dialog logic).

Various small dialog fixes

---

Applications/Utils/MeshEdit/CMakeLists.txt
Applications/Utils/MeshEdit/createLayeredMeshFromRasters.cpp
GeoLib/AnalyticalGeometry.cpp
GeoLib/AnalyticalGeometry.h
MeshGeoToolsLib/GeoMapper.cpp
MeshLib/CMakeLists.txt
MeshLib/MeshGenerators/LayeredMeshGenerator.cpp
MeshLib/MeshGenerators/MeshLayerMapper.cpp

Command line tool for creating layered meshes from raster files

---

Tests/MathLib/AutoCheckTools.h
Tests/MeshLib/TestAddLayerToMesh.cpp
Tests/MeshLib/TestFlipElements.cpp

fixed warnings + memleak

---

MeshLib/MeshGenerators/MeshGenerator.cpp

@endJunction : can you pls check if this resolves the issue?

fixing memleak when generating regular prism mesh

---

scripts/cmake/test/AddTest.cmake
scripts/cmake/test/AddTestWrapper.cmake
scripts/cmake/test/Test.cmake

Remove ctest output files

---

BaseLib/FileTools.cpp
MeshLib/MeshEditing/MeshRevision.cpp
Tests/InSituLib/TestVtkMappedPropertyVector.cpp

Fix (potential) errors found by clang sanitizer.

---

GeoLib/SurfaceGrid.cpp

[GL] Make SurfaceGrid non verbose in release mode.

---

BaseLib/FileTools.cpp
MeshGeoToolsLib/BoundaryElementsSearcher.cpp

As titled. For details see commit messages.

Fix clang sanitizer issues

---

FileIO/TetGenInterface.cpp
MeshLib/MeshEditing/MeshRevision.cpp

- Fix clang sanitizer errors in TetGen interface
- Make code readable in MeshRevision

Two small improvements/fixes

---

BaseLib/StringTools.cpp
BaseLib/StringTools.h
BaseLib/uniqueInsert.h
CMakeLists.txt
FileIO/XmlIO/Boost/BoostXmlGmlInterface.cpp
NumLib/Fem/ShapeFunction/ShapeStaticConsts.cpp
NumLib/Fem/ShapeMatrixPolicy.h

Those parts have been extracted from #1050. This PR is a prerequisite of #1050!

Small fixes

---

Tests/AssemblerLib/TestSerialLinearSolver.cpp

Fixed a memory leak in a test

---

Applications/DataExplorer/DataView/CMakeLists.txt
Applications/DataExplorer/DataView/MeshLayerEditDialog.cpp
Applications/DataExplorer/DataView/MeshLayerEditDialog.h
Applications/DataExplorer/DataView/MeshMapping2D.ui
Applications/DataExplorer/DataView/MeshMapping2DDialog.cpp
Applications/DataExplorer/DataView/MeshMapping2DDialog.h
Applications/DataExplorer/DataView/MshView.cpp
Applications/DataExplorer/DataView/MshView.h
MeshLib/MeshGenerators/MeshLayerMapper.cpp
MeshLib/MeshGenerators/MeshLayerMapper.h

This is mostly restructuring + usability changes.
I am in the process of decoupling mesh mapping and adding layers. As a first change, this adds a new dialog for mapping 2d meshes. As a tiny addition it is now possible to map all mesh nodes to a constant value.

Mesh Mapping in Data Explorer

---

Applications/DataExplorer/DataView/MeshElementRemovalDialog.cpp
Applications/Utils/MeshEdit/removeMeshElements.cpp
MeshLib/MeshSearch/ElementSearch.cpp
MeshLib/MeshSearch/ElementSearch.h

As titled. For details see commit messages.

Generalized removeMeshElements tool.

---

Applications/DataExplorer/VtkVis/VisPrefsDialog.cpp
Applications/DataExplorer/VtkVis/VisPrefsDialog.h
Applications/DataExplorer/VtkVis/VtkAddFilterDialog.cpp
Applications/DataExplorer/VtkVis/VtkAddFilterDialog.h
Applications/DataExplorer/main.cpp
Applications/DataExplorer/mainwindow.cpp
Applications/DataExplorer/mainwindow.h

* fixing a few mem-leaks
* using a few unique pointers
* dereferencing a few pointers for dialog

DataExplorer MainWindow clean up

---

Applications/DataExplorer/VtkAct/VtkCustomInteractorStyle.cpp
Applications/DataExplorer/VtkAct/VtkCustomInteractorStyle.h
Applications/DataExplorer/VtkVis/VisualizationWidget.cpp
Applications/DataExplorer/VtkVis/VisualizationWidget.h
GeoLib/SensorData.cpp

this should fix the remaining leaks after PR #1091 on DataExplorer startup.

Fixing Mem-leaks in DataExplorer

---

AssemblerLib/VectorMatrixAssembler.h

* renamed the standalone method
* added a method doing essentially the same as a member to the class
I use this method in the TES process to check if the primary variables are within given bounds, i.e., if they are positive.

[AsmL] extended VectorMatrixAssembler

---

ProcessLib/GroundwaterFlowFEM.h
ProcessLib/ProcessUtil.h

[PL] shape matrices created in separate function

---

MathLib/LinAlg/PETSc/PETScVector.cpp
MathLib/LinAlg/PETSc/PETScVector.h
NumLib/ODESolver/MatrixTranslator.h
NumLib/ODESolver/TimeLoopSingleODE.h

* fixes copy ctor and makes it explicit
* adds move ctor

Fix PETScVector

---

FileIO/GMSHInterface.cpp
FileIO/GMSHInterface.h
FileIO/GmshIO/GMSHPolygonTree.cpp
FileIO/GmshIO/GMSHPolygonTree.h
GeoLib/QuadTree.h
GeoLib/SimplePolygonTree.cpp
GeoLib/SimplePolygonTree.h
Tests/GeoLib/TestSimplePolygonTree.cpp

[GeoLib]
- QuadTree: correction of destructor fixes mem leaks  
[FileIO]
- Initial implementation of destructor for
* GMSHInterface
* GMSHPolygonTree

Cleanup and mem leak fixing

---

Applications/DataExplorer/DataView/MshModel.cpp
Applications/DataExplorer/DataView/MshModel.h

This saves ~10% memory when loading a mesh.

Static string references for MshModel

---

Applications/DataExplorer/Base/Color.cpp
Applications/DataExplorer/Base/Color.h
Applications/DataExplorer/DataView/DiagramView/DetailWindow.cpp
Applications/DataExplorer/DataView/StationTreeView.cpp
Applications/DataExplorer/DataView/StratView/StratBar.cpp
Applications/DataExplorer/DataView/StratView/StratBar.h
Applications/DataExplorer/DataView/StratView/StratScene.cpp
Applications/DataExplorer/DataView/StratView/StratScene.h
Applications/DataExplorer/DataView/StratView/StratView.cpp
Applications/DataExplorer/DataView/StratView/StratView.h
Applications/DataExplorer/DataView/StratView/StratWindow.cpp
Applications/DataExplorer/DataView/StratView/StratWindow.h
Applications/DataExplorer/VtkVis/VtkPointsSource.cpp
Applications/DataExplorer/VtkVis/VtkPolylinesSource.cpp
Applications/DataExplorer/VtkVis/VtkStationSource.cpp
Applications/DataExplorer/VtkVis/VtkStationSource.h
Applications/DataExplorer/VtkVis/VtkSurfacesSource.cpp
Applications/DataExplorer/VtkVis/VtkVisPipeline.cpp

95% of this PR is just swapping pointers to ```Color```s for actual values or references.

Fix color and import leaks

---

CHANGELOG.md

Changelog for preparation of version 6.0.5

---

Applications/ApplicationsLib/UncoupledProcessesTimeLoop.h
NumLib/TimeStepping/Algorithms/FixedTimeStepping.cpp
NumLib/TimeStepping/Algorithms/FixedTimeStepping.h

This is a follow-up PR of #1105. Only the last four commits matter.
* Extends FixedTimeStepper builder to support different timestep sizes.
* Uses FixedTimeStepper in the time loop

Using existing FixedTimeStepper in time loop

---

ProcessLib/GroundwaterFlowFEM.h

Follow-up of #1123.
In #1123 I claimed that the changes there will lead to better const-correctness and less heap allocations. So, here's the proof.
Only the last commit matters for this PR.
Note: () vs. {} is not consistent at one point, because there are narrowing conversions involved.

Changed GWFlowFEM Constructor

---

AssemblerLib/GlobalSetup.h
AssemblerLib/LocalDataInitializer.h
AssemblerLib/SerialExecutor.h
AssemblerLib/VectorMatrixAssembler.h
ProcessLib/GroundwaterFlowProcess.h
ProcessLib/NeumannBc.h
Tests/AssemblerLib/TestSerialLinearSolver.cpp

Follow-up of #1123.
This PR is meant to promote the use of C++11 memory management.

Local assemblers stored as unique_ptr's

---

MathLib/CMakeLists.txt
MathLib/LinAlg/Solvers/BiCGStab.cpp
MathLib/LinAlg/Solvers/BiCGStab.h

This is a split-off from https://github.com/ufz/ogs/pull/1133 having only the MathLib  and metis changes.
This has been reviewed and all changes are included. Look at it as a small MathLib cleanup.

Fix math lib metis linking

---

GeoLib/GeoObject.h
GeoLib/Polyline.cpp
MathLib/TemplatePoint.h
MathLib/Vector3.h
MeshGeoToolsLib/SearchLength.h
MeshLib/MeshQuality/ElementErrorCode.h

While searching a bug I raised the warning level of the compiler. PR tries to fix some warnings.

Cleanup and remove warnings

---

Applications/Utils/MeshEdit/removeMeshElements.cpp
Applications/Utils/ModelPreparation/ComputeNodeAreasFromSurfaceMesh.cpp

Tiny fixes in  tools.

---

NumLib/Extrapolation/Extrapolator.h
NumLib/Extrapolation/LocalLinearLeastSquaresExtrapolator.h

Extrapolator releases global vectors again

---

scripts/jenkins/gcc.groovy

@ufz/developer 
Please rebase your PRs to get green Jenkins docker runs.

[Jenkins] Changed ccache path in docker jobs.

---

conanfile.txt

- Fixes QVTK compilation error on MSVC
- Added libgeotiff dependency
TODO:

Conan fixes

---

.travis.yml

[Travis] Cache ccache.

---

MathLib/LinAlg/VectorNorms.h
NumLib/Fem/Integration/IntegrationGaussPrism.h
NumLib/Fem/Integration/IntegrationGaussPyramid.h
NumLib/Fem/Integration/IntegrationGaussTet.h
NumLib/Fem/Integration/IntegrationGaussTri.h
NumLib/Fem/Integration/IntegrationPoint.h
NumLib/ODESolver/MatrixTranslator.h

Mainly correct variable names in the documentation.
Remove some documentation for non-existing parameters.

Fix some of doxygen warnings.

---

Applications/Utils/FileConverter/ConvertSHPToGLI.cpp
Applications/Utils/FileConverter/FEFLOW2OGS.cpp
Applications/Utils/FileConverter/GMSH2OGS.cpp
Applications/Utils/FileConverter/OGS2VTK.cpp
Applications/Utils/FileConverter/TIN2VTK.cpp
Applications/Utils/FileConverter/VTK2OGS.cpp
Applications/Utils/FileConverter/VTK2TIN.cpp
Applications/Utils/FileConverter/generateMatPropsFromMatID.cpp
Applications/Utils/GeoTools/MoveGeometry.cpp
Applications/Utils/GeoTools/TriangulatePolyline.cpp
Applications/Utils/MeshEdit/AddTopLayer.cpp
Applications/Utils/MeshEdit/CreateBoundaryConditionsAlongPolylines.cpp
Applications/Utils/MeshEdit/ExtractSurface.cpp
Applications/Utils/MeshEdit/MapGeometryToMeshSurface.cpp
Applications/Utils/MeshEdit/MoveMesh.cpp
Applications/Utils/MeshEdit/NodeReordering.cpp
Applications/Utils/MeshEdit/ResetPropertiesInPolygonalRegion.cpp
Applications/Utils/MeshEdit/appendLinesAlongPolyline.cpp
Applications/Utils/MeshEdit/checkMesh.cpp
Applications/Utils/MeshEdit/createLayeredMeshFromRasters.cpp
Applications/Utils/MeshEdit/editMaterialID.cpp
Applications/Utils/MeshEdit/moveMeshNodes.cpp
Applications/Utils/MeshEdit/queryMesh.cpp
Applications/Utils/MeshEdit/removeMeshElements.cpp
Applications/Utils/MeshEdit/reviseMesh.cpp
Applications/Utils/MeshGeoTools/ComputeSurfaceNodeIDsInPolygonalRegion.cpp
Applications/Utils/ModelPreparation/ComputeNodeAreasFromSurfaceMesh.cpp
Applications/Utils/OGSFileConverter/main.cpp
Applications/Utils/SimpleMeshCreation/createMeshElemPropertiesFromASCRaster.cpp
Applications/Utils/SimpleMeshCreation/generateStructuredMesh.cpp

- Use Logog
- Use `unique_ptr` (fixes some mem leaks)
- Sort/cleanup includes

Cleanup in tools

---

Applications/ApplicationsLib/UncoupledProcessesTimeLoop.h
MathLib/LinAlg/BLAS.cpp
MathLib/LinAlg/BLAS.h
MathLib/LinAlg/Lis/LisOption.h
NumLib/Function/Interpolation.h
NumLib/ODESolver/NonlinearSolver-impl.h
ProcessLib/Process.h

This PR mainly adds some log output to the time integrator.
It also contains the proposed fix for #1180.

Misc changes

---

Documentation/Doxyfile.in

Update paths for generating documentation.

---

scripts/cmake/cmake/FindCVODE.cmake

This fixes linking errors with sundias libraries

fix FindCVODE.cmake 

---

GeoLib/AnalyticalGeometry.cpp
GeoLib/AnalyticalGeometry.h
GeoLib/IO/XmlIO/Qt/XmlGmlInterface.cpp
GeoLib/LineSegment.cpp
GeoLib/LineSegment.h
GeoLib/Polyline.cpp
GeoLib/Polyline.h
Tests/GeoLib/AutoCheckGenerators.cpp
Tests/GeoLib/AutoCheckGenerators.h
Tests/GeoLib/TestLineSegmentIntersect2d.cpp
Tests/GeoLib/TestSortSegments.cpp
ThirdParty/CMakeLists.txt

[GL] Changes in GeoLib needed for GeoMapper Refactorization.

---

.travis.yml
scripts/cmake/cmake/FindEigen3.cmake

Will find Eigen correctly on envinf1
Fixes #1073.
Disables check for new blank lines at end-of-file in `git diff --check`

Simplified FindEigen3.cmake.

---

MeshLib/MeshSearch/MeshElementGrid.cpp
MeshLib/MeshSearch/MeshElementGrid.h

[MeL] Changes in MeshLib used for GeoMapper refactorization.

---

Applications/DataExplorer/Base/CheckboxDelegate.cpp
Applications/DataExplorer/Base/QValueTooltipSlider.cpp
Applications/DataExplorer/DataView/GeoTreeView.cpp
Applications/DataExplorer/DataView/StationTreeView.cpp
Applications/DataExplorer/VtkVis/VtkRaster.cpp
Applications/Utils/FileConverter/ConvertSHPToGLI.cpp
Applications/Utils/FileConverter/ConvertVtkToOsg.cpp
Applications/Utils/MeshEdit/moveMeshNodes.cpp
AssemblerLib/ComponentGlobalIndexDict.h
BaseLib/DateTools.cpp
BaseLib/IO/Writer.cpp
BaseLib/MemWatch.cpp
GeoLib/IO/XmlIO/Rapid/RapidStnInterface.cpp
GeoLib/LineSegment.cpp
MathLib/LinAlg/Dense/DenseMatrix.h
MathLib/TemplatePoint.h
MeshLib/MeshEditing/Mesh2MeshPropertyInterpolation.cpp
MeshLib/MeshQuality/ElementQualityMetric.cpp
Tests/AssemblerLib/LocalToGlobalIndexMapMultiComponent.cpp
Tests/GeoLib/TestAABB.cpp
Tests/MathLib/TestEigenCSR.cpp
Tests/MeshLib/TestQuadMesh.cpp
Tests/MeshLib/TestTriLineMesh.cpp
Tests/NumLib/ODEs.h

Replace cout/cerr output with hopefully semantically equal logog calls.

Remove iostream include

---

Applications/Utils/FileConverter/CMakeLists.txt
Applications/Utils/FileConverter/GMSH2OGS.cpp
Applications/Utils/GeoTools/CMakeLists.txt
Applications/Utils/MeshEdit/CMakeLists.txt
Applications/Utils/SimpleMeshCreation/CMakeLists.txt

Remove setting include dirs in some CMake files

---

Applications/CLI/Tests.cmake
MathLib/ODE/CVodeSolver.cpp
scripts/cmake/test/AddTest.cmake

This PR
* provides tolerances for individual ctests
* extends tests s.t. vtkdiff can compare multiple files and multiple properties
* switches PETSc tests to vtkdiff.

Made tests more flexible

---

NumLib/ODESolver/TimeDiscretizedODESystem.h

[NL] Apply all Dirichlet BCs at once.

---

CMakeLists.txt
MathLib/LinAlg/GlobalMatrixVectorTypes.h
MathLib/LinAlg/LinearSolver.cpp
Tests/MathLib/TestGlobalMatrixInterface.cpp

Fix OGS_USE_LIS build

---

Applications/CLI/CMakeLists.txt
MeshGeoToolsLib/CMakeLists.txt

Remove FileIO from target_link_libraries list.

---

NumLib/Assembler/VectorMatrixAssembler.h
NumLib/DOF/LocalToGlobalIndexMap.cpp
NumLib/DOF/LocalToGlobalIndexMap.h
NumLib/Extrapolation/LocalLinearLeastSquaresExtrapolator.h
ProcessLib/NeumannBc.cpp
ProcessLib/TES/TESProcess.cpp
ProcessLib/Utils/LocalDataInitializer.h
Tests/NumLib/LocalToGlobalIndexMapMultiComponent.cpp
Tests/NumLib/TestSerialLinearSolver.cpp

follow up of #1243 which I forgot renaming

rename LocalToGlobalIndexMap::getNumXXX() to getNumberOfXXX()

---

MathLib/LinAlg/Eigen/EigenMatrix.h
NumLib/DOF/LocalToGlobalIndexMap.cpp
ProcessLib/NeumannBc.cpp

fix some warnings

---

Applications/ApplicationsLib/ProjectData.cpp
Applications/ApplicationsLib/ProjectData.h
Applications/ApplicationsLib/UncoupledProcessesTimeLoop.cpp
Applications/ApplicationsLib/UncoupledProcessesTimeLoop.h
NumLib/Extrapolation/LocalLinearLeastSquaresExtrapolator.h
NumLib/ODESolver/EquationSystem.h
NumLib/ODESolver/MatrixTranslator.cpp
NumLib/ODESolver/MatrixTranslator.h
NumLib/ODESolver/NonlinearSolver-impl.h
NumLib/ODESolver/NonlinearSolver.cpp
NumLib/ODESolver/NonlinearSolver.h
NumLib/ODESolver/NonlinearSystem.h
NumLib/ODESolver/ODESystem.h
NumLib/ODESolver/TimeDiscretization.h
NumLib/ODESolver/TimeDiscretizationBuilder.cpp
NumLib/ODESolver/TimeDiscretizationBuilder.h
NumLib/ODESolver/TimeDiscretizedODESystem.cpp
NumLib/ODESolver/TimeDiscretizedODESystem.h
NumLib/ODESolver/TimeLoopSingleODE.h
ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.cpp
ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.h
ProcessLib/Process.cpp
ProcessLib/Process.h
ProcessLib/TES/TESProcess.cpp
ProcessLib/TES/TESProcess.h
Tests/NumLib/ODEs.h
Tests/NumLib/TestODEInt.cpp

Remove Mat/Vec template parameters #2

---

NumLib/ODESolver/EquationSystem.h
NumLib/ODESolver/NonlinearSolver.h
NumLib/ODESolver/NonlinearSystem.h
NumLib/ODESolver/ODESystem.h
NumLib/ODESolver/TimeDiscretizedODESystem.h
NumLib/ODESolver/TimeLoopSingleODE.h

remove doxygen commments for removed template Mat/Vec parameters

---

Applications/DataExplorer/DataView/CreateStructuredGridDialog.cpp
Applications/DataExplorer/DataView/StationTreeModel.cpp
Applications/DataExplorer/DataView/StationTreeModel.h
GeoLib/Surface.cpp
MeshLib/MeshEditing/MeshRevision.cpp
MeshLib/MeshQuality/MeshValidation.cpp

For details see commit messages.

Small improvements.

---

MathLib/LinAlg/LinAlg.cpp
MathLib/LinAlg/MatrixVectorTraits.cpp
MathLib/LinAlg/MatrixVectorTraits.h
MathLib/LinAlg/UnifiedMatrixSetters.cpp
MathLib/LinAlg/UnifiedMatrixSetters.h

remove support of EigenXd as global matrix and vector types

---

Jenkinsfile
scripts/jenkins/gcc.groovy
scripts/jenkins/msvc-log-parser.rules
scripts/jenkins/msvc.groovy

Builds existing Linux (gcc in Docker) build in parallel with new Windows build.
The new Windows build is a replacement for these legacy jobs which can be removed when the new job is working properly:
- OGS-6/Win
- OGS-6/Win-PRs
- OGS-6/Win_Utils
- OGS-6/Gui/Win
- OGS-6/Gui/Win-PRs

[Jenkins] Windows Pipeline job

---

NumLib/ODESolver/TimeDiscretizedODESystem.cpp

Now more similar to the Picard implementation doing all the boundaries at once.
See https://github.com/ufz/ogs/pull/1248 for the Picard part.

[NL] Update apply known solutions for Newton.

---

Applications/DataExplorer/VtkVis/VtkCompositeColorByHeightFilter.cpp
Applications/DataExplorer/VtkVis/VtkCompositeElementSelectionFilter.cpp
Applications/DataHolderLib/ColorLookupTable.cpp

As titled. For details see commit messages.

Fix warnings

---

Applications/ApplicationsLib/UncoupledProcessesTimeLoop.cpp
Applications/CLI/ogs.cpp
BaseLib/DateTools.cpp
BaseLib/DateTools.h
NumLib/ODESolver/NonlinearSolver.cpp
ProcessLib/Output.cpp

Sorry @wenqing that we did not respond to your time measurement PR #863. But I think time measurement is important, so here is my attempt on it.
This PR provides wall-time measurement of assembly, linear solvers, nonlinear iterations, dirchlet BCs timesteps, output, and overall runtime.
The time is measured for individual "events" and not accumulated over timesteps.

Added time measurement output

---

MathLib/LinAlg/EigenLis/EigenLisLinearSolver.cpp
MathLib/LinAlg/Lis/LisLinearSolver.cpp

Made LIS linear solver return if it succeeded.

---

Applications/FileIO/CsvInterface.cpp
Applications/FileIO/CsvInterface.h
Tests/FileIO/TestCsvWriter.cpp

Vectors are added to object and then written to the file in the sequence they have been added in.
Currently only double/int/string vectors are supported.

Functionality for writing CSV files

---

ProcessLib/GroundwaterFlow/GroundwaterFlowFEM.h

[GW] Corrected the sign of the groundwater flow velocity

---

Applications/CLI/Tests.cmake

* File IO errors detected earlier
* Some more information printed
* Rel/abs tol fixed.

Updated vtkdiff

---

Applications/CLI/Tests.cmake
MathLib/LinAlg/Eigen/EigenLinearSolver.cpp
MathLib/LinAlg/Eigen/EigenOption.cpp
MathLib/LinAlg/Eigen/EigenOption.h
NumLib/NamedFunctionCaller.cpp

Until now the setting in the prj file was not strictly parsed and ignored later on.

Enabled Eigen preconditioner configuration

---

Documentation/ProjectFile/prj/curves/curve/i_curve.md
Documentation/ProjectFile/prj/curves/curve/t_coords.md
Documentation/ProjectFile/prj/curves/curve/t_name.md
Documentation/ProjectFile/prj/curves/curve/t_values.md
Documentation/ProjectFile/prj/curves/i_curves.md
Documentation/ProjectFile/prj/process_variables/i_process_variables.md
Documentation/ProjectFile/prj/process_variables/process_variable/boundary_conditions/i_boundary_conditions.md
Documentation/ProjectFile/prj/process_variables/process_variable/boundary_conditions/t_boundary_condition.md
Documentation/ProjectFile/prj/process_variables/process_variable/i_process_variable.md
Documentation/ProjectFile/prj/process_variables/process_variable/t_components.md
Documentation/ProjectFile/prj/process_variables/process_variable/t_initial_condition.md
Documentation/ProjectFile/prj/process_variables/process_variable/t_name.md
Documentation/ProjectFile/process/secondary_variables/i_secondary_variables.md
Documentation/ProjectFile/process/secondary_variables/secondary_variable/a_internal_name.md
Documentation/ProjectFile/process/secondary_variables/secondary_variable/a_output_name.md
Documentation/ProjectFile/process/secondary_variables/secondary_variable/a_sink_arg.md
Documentation/ProjectFile/process/secondary_variables/secondary_variable/a_source_fct.md
Documentation/ProjectFile/process/secondary_variables/secondary_variable/a_type.md
Documentation/ProjectFile/process/secondary_variables/secondary_variable/i_secondary_variable.md
Documentation/ProjectFile/process/secondary_variables/secondary_variable/plug/a_sink_arg.md
Documentation/ProjectFile/process/secondary_variables/secondary_variable/plug/a_source_fct.md
Documentation/ProjectFile/process/secondary_variables/secondary_variable/plug/i_plug.md
Documentation/ProjectFile/process/secondary_variables/secondary_variable/t_plug.md
ProcessLib/Utils/ParseSecondaryVariables.cpp

Documented
* curves
* process variables
* secondary variables

Docu part 3

---

Documentation/ProjectFile/linear_solver/c_linear_solver.md
Documentation/ProjectFile/linear_solver/eigen/i_eigen.md
Documentation/ProjectFile/linear_solver/eigen/t_error_tolerance.md
Documentation/ProjectFile/linear_solver/eigen/t_max_iteration_step.md
Documentation/ProjectFile/linear_solver/eigen/t_precon_type.md
Documentation/ProjectFile/linear_solver/eigen/t_solver_type.md
Documentation/ProjectFile/linear_solver/petsc/i_petsc.md
Documentation/ProjectFile/linear_solver/petsc/t_parameters.md
Documentation/ProjectFile/linear_solver/petsc/t_prefix.md
Documentation/ProjectFile/linear_solver/t_lis.md
Documentation/ProjectFile/linear_solver/t_name.md
Documentation/ProjectFile/ode_solver/CVODE/c_CVODE.md
Documentation/ProjectFile/ode_solver/CVODE/t_linear_multistep_method.md
Documentation/ProjectFile/ode_solver/CVODE/t_nonlinear_solver_iteration.md
Documentation/ProjectFile/ode_solver/c_ode_solver.md
Documentation/ProjectFile/prj/linear_solvers/i_linear_solvers.md
Documentation/ProjectFile/prj/linear_solvers/linear_solver/i_linear_solver.md
Documentation/ProjectFile/prj/nonlinear_solvers/i_nonlinear_solvers.md
Documentation/ProjectFile/prj/nonlinear_solvers/nonlinear_solver/Picard/c_Picard.md
Documentation/ProjectFile/prj/nonlinear_solvers/nonlinear_solver/i_nonlinear_solver.md
Documentation/ProjectFile/prj/nonlinear_solvers/nonlinear_solver/t_linear_solver.md
Documentation/ProjectFile/prj/nonlinear_solvers/nonlinear_solver/t_max_iter.md
Documentation/ProjectFile/prj/nonlinear_solvers/nonlinear_solver/t_name.md
Documentation/ProjectFile/prj/nonlinear_solvers/nonlinear_solver/t_type.md
MathLib/LinAlg/Lis/LisOption.h
NumLib/ODESolver/NonlinearSolver.cpp
scripts/doc/linked-xml-file.py

Follow-up of #1370.
I also noticed that our LIS default options are erroneous.
Contains docu for
* linear solvers
* nonlinear solvers
* ODE solver

Wrote some more docu

---

Applications/Utils/Tests.cmake

This are Bode and Naegelstedt tests taking much more
time then other non-LARGE tests.
The tests will be executed every night by Jenkins, not every build (or PR).

[T] Mark two MapGeometryToMeshSurf tests as LARGE.

---

GeoLib/GEOObjects.h
MeshLib/MeshGenerators/LayeredMeshGenerator.h
NumLib/ODESolver/ConvergenceCriterion.h

...as reported by compiler.
Prevents memory leaks.

Add virtual to dtors of polymorphic classes.

---

Jenkinsfile
scripts/jenkins/clang.groovy
scripts/jenkins/coverage.groovy
scripts/jenkins/deploy-post.groovy
scripts/jenkins/deploy.groovy
scripts/jenkins/gcc.groovy
scripts/jenkins/msvc.groovy
scripts/jenkins/msvc32.groovy

- Is now a [separate job](https://svn.ufz.de:8443/job/OGS-6/job/Deploy/)
- Which triggers a [post job](https://svn.ufz.de:8443/job/OGS-6/job/Deploy-Post/) which uploads an [info file](https://opengeosys.s3.amazonaws.com/lastSuccessfulArtifacts.json) to S3 as well which is used by the web site to determine the specific URLs to the latest binaries, e.g.:
- https://opengeosys.s3.amazonaws.com/jobs/OGS-6/Deploy/2/ogs-6.0.6-506-g84f9db9-Windows-6.1.7601-x64-de-utils.zip

Upload binaries to S3

---

Applications/DataExplorer/DataView/DirectConditionGenerator.cpp

Fix usage of optional<T const&>.

---

.travis.yml

sorry my previous PR was not enough to run tests for GUI builds

[travis] fix test with GUI builds

---

Applications/Utils/CMakeLists.txt
CMakeLists.txt
Jenkinsfile
scripts/cmake/SubmoduleSetup.cmake
scripts/jenkins/gcc.groovy
scripts/jenkins/mac.groovy
scripts/jenkins/msvc.groovy
scripts/jenkins/msvc32.groovy

Enable swmm interface compilation on Jenkins

---

scripts/jenkins/gcc.groovy
scripts/jenkins/mac.groovy
scripts/jenkins/msvc.groovy
scripts/jenkins/msvc32.groovy

Should fix errors on unstashing, see
https://groups.google.com/forum/#!topicsearchin/jenkinsci-users/pipeline/jenkinsci-users/xj-yAIPjAFI

[Jenkins] Explicitly allocate workspace before unstashing.

---

Applications/FileIO/SWMM/SWMMInterface.cpp
Tests/CMakeLists.txt
Tests/FileIO_SWMM/TestSwmmInterface.cpp

* fixed issue where non-unique points would cause problems during conversion
* added test for reading input files

SWMM interface update

---

Jenkinsfile
scripts/jenkins/gcc.groovy
scripts/jenkins/mac.groovy
scripts/jenkins/msvc.groovy
scripts/jenkins/msvc32.groovy

Unfortunately unstashing sometimes fails and I cannot reproduce it so I am reverting this.

[Jenkins] Fix unstash

---

ProcessLib/SmallDeformation/CreateSmallDeformationProcess.cpp
ProcessLib/SmallDeformation/CreateSmallDeformationProcess.h

This PR is for speeding up build times and following the way of other processes

move definitions of createSmallDeformationProcess() to cpp file

---

Applications/CLI/Tests.cmake
Documentation/ProjectFile/process/SMALL_DEFORMATION/constitutive_relation/Lubby2/c_Lubby2.md
Documentation/ProjectFile/process/SMALL_DEFORMATION/constitutive_relation/Lubby2/t_dependency_parameter_mk.md
Documentation/ProjectFile/process/SMALL_DEFORMATION/constitutive_relation/Lubby2/t_dependency_parameter_mvk.md
Documentation/ProjectFile/process/SMALL_DEFORMATION/constitutive_relation/Lubby2/t_dependency_parameter_mvm.md
Documentation/ProjectFile/process/SMALL_DEFORMATION/constitutive_relation/Lubby2/t_kelvin_shear_modulus.md
Documentation/ProjectFile/process/SMALL_DEFORMATION/constitutive_relation/Lubby2/t_kelvin_viscosity.md
Documentation/ProjectFile/process/SMALL_DEFORMATION/constitutive_relation/Lubby2/t_maxwell_bulk_modulus.md
Documentation/ProjectFile/process/SMALL_DEFORMATION/constitutive_relation/Lubby2/t_maxwell_shear_modulus.md
Documentation/ProjectFile/process/SMALL_DEFORMATION/constitutive_relation/Lubby2/t_maxwell_viscosity.md
Documentation/bibliography.bib
MaterialLib/SolidModels/CreateLinearElasticIsotropic.h
MaterialLib/SolidModels/CreateLubby2.h
MaterialLib/SolidModels/LinearElasticIsotropic.cpp
MaterialLib/SolidModels/LinearElasticIsotropic.h
MaterialLib/SolidModels/Lubby2-impl.h
MaterialLib/SolidModels/Lubby2.cpp
MaterialLib/SolidModels/Lubby2.h
MaterialLib/SolidModels/MechanicsBase.h
ProcessLib/SmallDeformation/CreateSmallDeformationProcess.cpp
ProcessLib/SmallDeformation/CreateSmallDeformationProcess.h
ProcessLib/SmallDeformation/SmallDeformationFEM.h
ProcessLib/SmallDeformation/SmallDeformationProcessData.h

Copy of the OGS5 implementation in general. So while mathematically same, technically different.
There are two larger commented code blocks, testing parameter validity and another with linear solver choices---ignore them for now. They will be either deleted or commented as explicitly needed.
Newton method extracted in #1393, so this is a follow-up

Burgers material model.

---

MeshLib/ElementCoordinatesMappingLocal.cpp

[MeL] clang format ElementCoordinatesMappingLocal.

---

NumLib/DOF/DOFTableUtil.cpp
NumLib/DOF/DOFTableUtil.h
ProcessLib/TES/TESProcess.cpp

Move dof table functionality

---

MaterialLib/CMakeLists.txt
MaterialLib/Fluid/Viscosity/LinearPressureDependentViscosity.h
MaterialLib/Fluid/Viscosity/TemperatureDependentViscosity.h
MaterialLib/Fluid/Viscosity/VogelsLiquidDynamicViscosity.h
MaterialLib/Fluid/Viscosity/createViscosityModel.cpp
MaterialLib/Fluid/Viscosity/createViscosityModel.h
Tests/MaterialLib/TestFluidViscosity.cpp

A family of classes for fluid viscosity, which are derived from class FluidProperty (in PR #1398 ).

Fluid viscosity

---

Applications/FileIO/SWMM/SWMMInterface.cpp

fixed issue with non-unique points at beginning and end of polyline

SwmmInterface BugFix

---

Applications/CLI/Tests.cmake

[CTest] Move SmallDeformation_ring_plane_strain_axi to Large tests.

---

MathLib/InterpolationAlgorithms/PiecewiseLinearInterpolation.cpp
MathLib/InterpolationAlgorithms/PiecewiseLinearInterpolation.h
Tests/GeoLib/TestLineSegmentIntersect2d.cpp
Tests/GeoLib/TestSortSegments.cpp
Tests/MathLib/TestPiecewiseLinearInterpolation.cpp

This PR includes
1) add GetCurveDerivative function in order to get the curve slope
2) update the getValue functions
3) add g-test for test these functions
4) fix some settings in order to run testrunner in VS2015/windows

Update PiecewiseLinearInterpolation functions

---

MeshLib/MeshSearch/NodeSearch.cpp
MeshLib/MeshSearch/NodeSearch.h
Tests/MeshLib/TestNodeSearch.cpp

[Mesh] searche boundary nodes in NodeSearch

---

ProcessLib/SmallDeformation/SmallDeformationFEM.h
ProcessLib/SmallDeformation/SmallDeformationProcess.h

Just a typo (with little consequences so far :)

[PL] SmallDeformation: Fix sigma_xy output.

---

MathLib/LinAlg/Eigen/EigenMapTools.h
NumLib/Extrapolation/LocalLinearLeastSquaresExtrapolator.cpp
NumLib/Extrapolation/LocalLinearLeastSquaresExtrapolator.h
ProcessLib/BoundaryCondition/BoundaryCondition.cpp
ProcessLib/BoundaryCondition/BoundaryCondition.h
ProcessLib/CMakeLists.txt
ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.h
ProcessLib/HeatConduction/HeatConductionProcess.h
ProcessLib/SmallDeformation/SmallDeformationFEM.h
ProcessLib/SmallDeformation/SmallDeformationProcess.h
ProcessLib/SmallDeformationWithLIE/BoundaryCondition/BoundaryConditionBuilder.cpp
ProcessLib/SmallDeformationWithLIE/BoundaryCondition/BoundaryConditionBuilder.h
ProcessLib/SmallDeformationWithLIE/BoundaryCondition/GenericNaturalBoundaryCondition-impl.h
ProcessLib/SmallDeformationWithLIE/BoundaryCondition/GenericNaturalBoundaryCondition.h
ProcessLib/SmallDeformationWithLIE/BoundaryCondition/NeumannBoundaryCondition.cpp
ProcessLib/SmallDeformationWithLIE/BoundaryCondition/NeumannBoundaryCondition.h
ProcessLib/SmallDeformationWithLIE/BoundaryCondition/NeumannBoundaryConditionLocalAssembler.h
Tests/NumLib/TestExtrapolation.cpp

I created this branch from c50dad011bcb21ab7d32742925b591952973a9b1, which was still accessible on github.
I suggest that force-pushing to ogs/master be disabled. It can be handy from time to time, but that can be explicitly enabled in those rare cases, and disabled again afterwards.

Does that restore the lost pull requests?

---

ProcessLib/RichardsFlow/RichardsFlowFEM.h
ProcessLib/SmallDeformationWithLIE/LocalAssembler/SmallDeformationLocalAssemblerInterface.h

It fixes
- warning in Richards flow process
- errors in LIE part with Dima's recent version of clang

Fix compiling issues

---

Applications/CLI/Tests.cmake
ProcessLib/CalculateSurfaceFlux/MapBulkElementPoint.cpp
ProcessLib/CalculateSurfaceFlux/MapBulkElementPoint.h

PR provides the mapping and tests for each face of a prism element.

Mapping for calculation of surface flux through prism elements

---

MathLib/LinAlg/Eigen/EigenLinearSolver.cpp

[Math/EigenLS] output iterations and residual even when it failed

---

Documentation/DocsetFeed.xml.in
Jenkinsfile
scripts/jenkins/docset.groovy
scripts/jenkins/gcc-tests-large.groovy

- Docset-job will be run as part of the main Jenkins job but only if commit is a tag
- tests large job will be run nightly as a [separate job](https://jenkins.opengeosys.org/job/OGS-6/job/gcc-tests-large/)

[Jenkins] Docset and tests large jobs

---

Applications/CLI/CMakeLists.txt
Applications/DataExplorer/DataExplorer.cmake
Jenkinsfile
scripts/cmake/packaging/GetDependencies.cmake
scripts/cmake/packaging/InstallDependencies.cmake
scripts/jenkins/gcc-dynamic.groovy
scripts/jenkins/gcc-tests-large.groovy
scripts/jenkins/gcc.groovy

- Fixed installation of shared libraries / DLLs
- INSTALL_COMPONENT was not defined and therefore the shared libraries were not installed.
- Use Release config in gcc jobs
- Added gcc-dynamic job

[CMake,Jenkins] Various fixes

---

MathLib/LinAlg/Eigen/EigenLinearSolver.cpp
MathLib/LinAlg/Eigen/EigenMatrix.h
MathLib/LinAlg/Eigen/EigenOption.cpp
MathLib/LinAlg/Eigen/EigenOption.h
ProcessLib/BoundaryCondition/BoundaryCondition.cpp
ProcessLib/BoundaryCondition/GenericNaturalBoundaryCondition-impl.h
ProcessLib/LIE/BoundaryCondition/GenericNaturalBoundaryCondition-impl.h

please have a look at each commit

add diagnostic outputs

---

MeshLib/Properties.cpp
ProcessLib/UncoupledProcessesTimeLoop.cpp

For details see commit messages.

Tiny fixes.

---

scripts/cmake/cmake/FindMKL.cmake

this avoid an unnecessary dialog in ccmake.

[CMake] fix the message to status in FindMKL

---

scripts/jenkins/gcc.groovy
scripts/jenkins/mac.groovy
scripts/jenkins/msvc.groovy

This enables downloading of binaries on each Pull Request.
As requested by @norihiro-w.

[Jenkins] Always archive build artifacts

---

Tests/NumLib/TestSparsityPattern.cpp

as titled. this fixes the Jenkins error

disable testing sparsity pattern in PETSc builds

---

ProcessLib/LIE/HydroMechanics/LocalAssembler/CreateLocalAssemblers.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/LocalDataInitializer.h

a part of #1535, depends on #1539 
This PR adds creation and initialization of the local assemblers

LIE/HM part 4: Local assembler creation

---

MathLib/InterpolationAlgorithms/PiecewiseLinearInterpolation.cpp
ProcessLib/RichardsFlow/CreateRichardsFlowProcess.cpp
ProcessLib/RichardsFlow/RichardsFlowFEM.h
ProcessLib/RichardsFlow/RichardsFlowProcessData.h

A forgotten branch with small improvements.

Richards flow optimizations

---

BaseLib/Histogram.h
BaseLib/StringTools.h
GeoLib/Point.h
MaterialLib/Adsorption/Adsorption.h
MaterialLib/Fluid/Density/IdealGasLaw.h
MeshLib/Elements/HexRule8.cpp
MeshLib/Elements/HexRule8.h
MeshLib/Elements/LineRule2.cpp
MeshLib/Elements/LineRule2.h
MeshLib/Elements/PointRule1.cpp
MeshLib/Elements/PointRule1.h
MeshLib/Elements/PrismRule6.cpp
MeshLib/Elements/PrismRule6.h
MeshLib/Elements/PyramidRule5.cpp
MeshLib/Elements/PyramidRule5.h
MeshLib/Elements/QuadRule4.cpp
MeshLib/Elements/QuadRule4.h
MeshLib/Elements/TemplateElement.h
MeshLib/Elements/TetRule4.cpp
MeshLib/Elements/TetRule4.h
MeshLib/Elements/TriRule3.cpp
MeshLib/Elements/TriRule3.h
MeshLib/Mesh.h
MeshLib/MeshEditing/MeshRevision.h
MeshLib/MeshGenerators/MeshGenerator.h
MeshLib/MeshGenerators/RasterToMesh.h
MeshLib/Vtk/VtkMappedMesh.h
MeshLib/Vtk/VtkMappedMeshSource.h
MeshLib/Vtk/VtkMappedPropertyVectorTemplate.h
MeshLib/Vtk/VtkMeshNodalCoordinatesTemplate.h

Few changes reducing some of the Doxygen warnings.

Doxygen documentation

---

MaterialLib/Fluid/Density/createFluidDensityModel.cpp
MaterialLib/Fluid/Density/createFluidDensityModel.h
MaterialLib/Fluid/Viscosity/createViscosityModel.cpp
MaterialLib/Fluid/Viscosity/createViscosityModel.h

[DOCFL] Removed doxygen warnings in the documentation of fluid classes

---

MaterialLib/FractureModels/FractureModelBase.h
MaterialLib/FractureModels/LinearElasticIsotropic.cpp
MaterialLib/FractureModels/LinearElasticIsotropic.h
MaterialLib/FractureModels/MohrCoulomb.cpp
MaterialLib/FractureModels/MohrCoulomb.h
ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.cpp
ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.h
ProcessLib/LIE/HydroMechanics/HydroMechanicsProcessData.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerFracture-impl.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerFracture.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerInterface.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrix-impl.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrix.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrixNearFracture-impl.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrixNearFracture.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/IntegrationPointDataFracture.h
ProcessLib/LIE/SmallDeformation/LocalAssembler/IntegrationPointDataFracture.h
ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerFracture-impl.h
Tests/MaterialLib/TestFractureModels.cpp

Changes in this PR is aimed at saving some internal variables (e.g. fracture force vector, fracture model state) in LIE/HM process into result VTU files. 
The last commit is formatting. I suggest reviewing commit wise

[LIE/HM] compute & output second varaibles

---

Applications/CLI/Tests.cmake
Documentation/bibliography.bib
MaterialLib/SolidModels/CreateEhlers.h
MaterialLib/SolidModels/Ehlers-impl.h
MaterialLib/SolidModels/Ehlers.cpp
MaterialLib/SolidModels/Ehlers.h
ProcessLib/SmallDeformation/CreateSmallDeformationProcess.cpp
ProcessLib/SmallDeformation/SmallDeformationFEM.h
ProcessLib/SmallDeformation/SmallDeformationProcess.h

Initial copy from OGS-5 by Xing-Yuan Miao @xingyuanmiao.

Ehlers Single surface yield function material model.

---

Applications/CLI/Tests.cmake
MeshLib/ElementStatus.cpp
MeshLib/ElementStatus.h
ProcessLib/LIE/HydroMechanics/CreateHydroMechanicsProcess.cpp
ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.cpp
ProcessLib/LIE/HydroMechanics/HydroMechanicsProcessData.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerFracture-impl.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrix-impl.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrix.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrixNearFracture-impl.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/LocalDataInitializer.h

[LIE/HM] Supporting deactivation by material IDs

---

Documentation/ProjectFile/curve/i_curve.md
Documentation/ProjectFile/curve/t_coords.md
Documentation/ProjectFile/curve/t_values.md
MathLib/Curve/CreatePiecewiseLinearCurve.h

Corrected the documentation for doxygen and added documentation for curve keywords

---

Documentation/ProjectFile/process/HT/c_HT.md
Documentation/ProjectFile/process/HT/t_density_fluid.md
MaterialLib/Fluid/Density/LiquidDensity.h
MaterialLib/Fluid/Viscosity/LinearPressureDependentViscosity.h
MaterialLib/Fluid/Viscosity/TemperatureDependentViscosity.h
MaterialLib/Fluid/Viscosity/VogelsLiquidDynamicViscosity.h
MaterialLib/PorousMedium/UnsaturatedProperty/CapillaryPressure/BrookCoreyCapillaryPressureSaturation.h
MaterialLib/PorousMedium/UnsaturatedProperty/CapillaryPressure/VanGenuchtenCapillaryPressureSaturation.h
MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/NonWettingPhaseBrookCoreyOilGas.h
MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/NonWettingPhaseVanGenuchten.h
MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/WettingPhaseBrookCoreyOilGas.h
MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/WettingPhaseVanGenuchten.h
ProcessLib/HT/HTProcess.h
README.md

Fixes also some mistakes.
This PR is only to inform you that I'm working on the documentation. Do not review until WIP label is removed.
**Update** WIP label is removed.

Documentation of HT process

---

Documentation/ProjectFile/material/porous_medium/capillary_pressure/BrookCorey/c_BrookCorey.md
Documentation/ProjectFile/material/porous_medium/capillary_pressure/BrookCorey/t_m.md
Documentation/ProjectFile/material/porous_medium/capillary_pressure/BrookCorey/t_pc_max.md
Documentation/ProjectFile/material/porous_medium/capillary_pressure/BrookCorey/t_pd.md
Documentation/ProjectFile/material/porous_medium/capillary_pressure/BrookCorey/t_smax.md
Documentation/ProjectFile/material/porous_medium/capillary_pressure/BrookCorey/t_sr.md
Documentation/ProjectFile/material/porous_medium/capillary_pressure/Curve/c_Curve.md
Documentation/ProjectFile/material/porous_medium/capillary_pressure/Curve/t_curve.md
Documentation/ProjectFile/material/porous_medium/capillary_pressure/t_type.md
Documentation/ProjectFile/material/porous_medium/capillary_pressure/vanGenuchten/i_vanGenuchten.md
Documentation/ProjectFile/material/porous_medium/capillary_pressure/vanGenuchten/t_m.md
Documentation/ProjectFile/material/porous_medium/capillary_pressure/vanGenuchten/t_pc_max.md
Documentation/ProjectFile/material/porous_medium/capillary_pressure/vanGenuchten/t_pd.md
Documentation/ProjectFile/material/porous_medium/capillary_pressure/vanGenuchten/t_smax.md
Documentation/ProjectFile/material/porous_medium/capillary_pressure/vanGenuchten/t_sr.md

Added documentations for the input keywords of capillary pressure saturation models

---

MaterialLib/SolidModels/Ehlers.h
Tests/CMakeLists.txt
scripts/cmake/Find.cmake

Some Windows fixes

---

Applications/Utils/MeshEdit/ExtractSurface.cpp

Add link to docs.opengeosys.org documentation.

---

Documentation/ProjectFile/prj/processes/process/LIQUID_FLOW/material_property/fluid/i_fluid.md
Documentation/ProjectFile/prj/processes/process/LIQUID_FLOW/material_property/porous_medium/porous_medium/a_id.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/c_TWOPHASE_FLOW_PP.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/fluid/i_fluid.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/fluid/t_gas_density.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/fluid/t_gas_viscosity.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/fluid/t_liquid_density.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/fluid/t_liquid_viscosity.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/i_material_property.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/porous_medium/i_porous_medium.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/porous_medium/porous_medium/a_id.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/porous_medium/porous_medium/i_porous_medium.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/porous_medium/porous_medium/t_permeability.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/porous_medium/porous_medium/t_porosity.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/material_property/porous_medium/porous_medium/t_storage.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/process_variables/i_process_variables.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/process_variables/t_capillary_pressure.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/process_variables/t_gas_pressure.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/process_variables/t_process_variable.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/t_mass_lumping.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/t_material_property.md
Documentation/ProjectFile/prj/processes/process/TWOPHASE_FLOW_PP/t_specific_body_force.md
MaterialLib/TwoPhaseModels/CreateTwoPhaseFlowMaterialProperties.cpp
ProcessLib/TwoPhaseFlowWithPP/CreateTwoPhaseFlowWithPPProcess.cpp
ProcessLib/TwoPhaseFlowWithPP/TwoPhaseFlowWithPPProcess.h
ProcessLib/TwoPhaseFlowWithPP/TwoPhaseFlowWithPPProcessData.h

A joint venture with @Yonghui56 
Spell check and additional information is welcome.
porous_media tag docu taken from @wenqing's LiquidFlow.

Document two-phase flow input parameters.

---

CHANGELOG.md

As titled, the two phase flow process with PP model and Richards flow process are involved.

Update the changelog file

---

Documentation/ProjectFile/material/fluid/density/t_type.md
Documentation/ProjectFile/material/fluid/viscosity/t_type.md

Corrected the documentations for the fluid viscosity

---

Jenkinsfile
MeshLib/Mesh.cpp
MeshLib/MeshSearch/NodeSearch.cpp
MeshLib/MeshSurfaceExtraction.cpp
Tests/ProcessLib/TestLIE.cpp
scripts/cmake/cmake/FindEigen3.cmake
scripts/env/envinf1/cli.sh
scripts/env/envinf1/gui.sh
scripts/jenkins/clang.groovy
scripts/jenkins/docs.groovy
scripts/jenkins/gcc-dynamic.groovy
scripts/jenkins/gcc-tests-large.groovy
scripts/jenkins/gcc.groovy
scripts/jenkins/mac.groovy

Please see commit messages for details.
The loaded modules are also available on eve (in `/global/apps`).
I updated [the documentation](https://docs.opengeosys.org/docs/devguide/advanced/working-on-envinf1) to reflect these changes.
TODO once merged:

Envinf1 fixes and improvements

---

Applications/DataExplorer/VtkVis/QVtkDataSetMapper.h
Applications/DataExplorer/VtkVis/VtkAppendArrayFilter.h
Applications/DataExplorer/VtkVis/VtkColorByHeightFilter.h
Applications/DataExplorer/VtkVis/VtkConsoleOutputWindow.h
Applications/DataExplorer/VtkVis/VtkGeoImageSource.h
Applications/DataExplorer/VtkVis/VtkImageDataToLinePolyDataFilter.h
Applications/DataExplorer/VtkVis/VtkPointsSource.h
Applications/DataExplorer/VtkVis/VtkPolylinesSource.h
Applications/DataExplorer/VtkVis/VtkStationSource.h
Applications/DataExplorer/VtkVis/VtkSurfacesSource.h
Applications/DataExplorer/VtkVis/VtkTextureOnSurfaceFilter.h
MeshLib/Vtk/VtkMappedMesh.h
MeshLib/Vtk/VtkMappedMeshSource.h
MeshLib/Vtk/VtkMappedPropertyVectorTemplate-impl.h
MeshLib/Vtk/VtkMappedPropertyVectorTemplate.h
MeshLib/Vtk/VtkMeshNodalCoordinatesTemplate-impl.h
MeshLib/Vtk/VtkMeshNodalCoordinatesTemplate.h

~~Just checking for now.~~
OK. This is just working fine with the vtk-6.3.
Review commit-wise.
Todo

Update for vtk7.1

---

Documentation/ProjectFile/material/fluid/viscosity/t_type.md
MaterialLib/Fluid/FluidProperty.h
MaterialLib/Fluid/Viscosity/WaterViscosityIAPWS.cpp
MaterialLib/Fluid/Viscosity/WaterViscosityIAPWS.h
MaterialLib/Fluid/Viscosity/createViscosityModel.cpp
Tests/MaterialLib/TestFluidViscosity.cpp

as titled.  
Next:
- IAPWS density model of water
- class FluidProperties, which consists models of individual fluid properties and which only takes  primary variable as arguments to get property values.

IAPWS viscosity model of water

---

MaterialLib/Fluid/Viscosity/WaterViscosityIAPWS.cpp

[FL] Fixed two compilation warnings in WaterViscosityIAPWS.cpp

---

MaterialLib/Fluid/FluidProperties/FluidProperties.h
ProcessLib/LiquidFlow/CreateLiquidFlowMaterialProperties.cpp
ProcessLib/LiquidFlow/CreateLiquidFlowMaterialProperties.h
ProcessLib/LiquidFlow/LiquidFlowLocalAssembler-impl.h
ProcessLib/LiquidFlow/LiquidFlowLocalAssembler.h
ProcessLib/LiquidFlow/LiquidFlowMaterialProperties.cpp
ProcessLib/LiquidFlow/LiquidFlowMaterialProperties.h
ProcessLib/LiquidFlow/LiquidFlowProcess.cpp
ProcessLib/LiquidFlow/LiquidFlowProcess.h
Tests/MaterialLib/TestFluidProperties.cpp
Tests/ProcessLib/LiquidFlow/TestLiquidFlowMaterialProperties.cpp

- Apply FluidProperties class to LiquidFlow
- Added a creator for LiquidFlowMaterialProperties
Note: This is the 2nd PR for the staggered scheme implementation.

Apply FluidProperties class to LiquidFlow

---

ProcessLib/LiquidFlow/CreateLiquidFlowMaterialProperties.cpp

As titled.
*Lesson*: Check the parameter documentation again after running source code formatter.

[Doc] Moved the four parameter documentations to the right places

---

Documentation/ProjectFile/prj/processes/process/LIQUID_FLOW/material_property/fluid/i_fluid.md
Documentation/ProjectFile/prj/processes/process/LIQUID_FLOW/material_property/fluid/t_density.md
Documentation/ProjectFile/prj/processes/process/LIQUID_FLOW/material_property/fluid/t_viscosity.md

Removed two unused material parameter documentations, and corrected one  parameter documentation.

Removed two unused material parameter documentations

---

Tests/MaterialLib/TestCapillaryPressureSaturationModel.cpp

as titled. 
Yonghui pointed out this error. Thanks.

[gtest] Corrected a tag name in one unit test

---

Tests/NumLib/TestODEInt.cpp
Tests/NumLib/TimeLoopSingleODE.h

Moved TimeLoopSingleODE.h from NumLib to Tests/NumLib

---

MaterialLib/Fluid/Density/LinearTemperatureDependentDensity.h
MaterialLib/Fluid/FluidProperty.h
MaterialLib/Fluid/Viscosity/TemperatureDependentViscosity.h
MaterialLib/PorousMedium/Porosity/ConstantPorosity.h
MaterialLib/PorousMedium/Porosity/Porosity.h
Tests/MaterialLib/TestFluidDensity.cpp
Tests/MaterialLib/TestFluidProperties.cpp

This is a split of PR https://github.com/ufz/ogs/pull/1685

MaterialLib fixes

---

.travis.yml
scripts/cmake/ConanSetup.cmake

[CMake] Check for CMake 3.4 when using Conan.

---

CMakeLists.txt

[CMake] Added option BUILD_SHARED_LIBS, defaults to OFF.

---

Documentation/ProjectFile/prj/processes/process/HT/fluid/i_fluid.md
Documentation/ProjectFile/prj/processes/process/HT/fluid/t_density.md
Documentation/ProjectFile/prj/processes/process/HT/fluid/t_viscosity.md
Documentation/ProjectFile/prj/processes/process/HT/porous_medium/i_porous_medium.md
Documentation/ProjectFile/prj/processes/process/HT/porous_medium/porous_medium/a_id.md
Documentation/ProjectFile/prj/processes/process/HT/porous_medium/porous_medium/i_porous_medium.md
Documentation/ProjectFile/prj/processes/process/HT/porous_medium/porous_medium/t_permeability.md
Documentation/ProjectFile/prj/processes/process/HT/porous_medium/porous_medium/t_porosity.md
Documentation/ProjectFile/prj/processes/process/HT/porous_medium/porous_medium/t_storage.md
Documentation/ProjectFile/prj/processes/process/HT/t_density_fluid.md
Documentation/ProjectFile/prj/processes/process/HT/t_fluid_reference_density.md
Documentation/ProjectFile/prj/processes/process/HT/t_intrinsic_permeability.md
Documentation/ProjectFile/prj/processes/process/HT/t_porosity.md
Documentation/ProjectFile/prj/processes/process/HT/t_reference_temperature.md
Documentation/ProjectFile/prj/processes/process/HT/t_specific_storage.md
Documentation/ProjectFile/prj/processes/process/HT/t_thermal_expansion_coefficient_fluid.md
Documentation/ProjectFile/prj/processes/process/HT/t_viscosity.md
ProcessLib/HT/CreateHTProcess.cpp
ProcessLib/HT/CreatePorousMediaProperties.cpp
ProcessLib/HT/CreatePorousMediaProperties.h
ProcessLib/HT/HTFEM.h
ProcessLib/HT/HTProcessData.h
ProcessLib/HT/PorousMediaProperties.cpp
ProcessLib/HT/PorousMediaProperties.h

The following material properties are now configurable via the project file:
- fluid density
- viscosity
- porosity
- permeability
- storage
ToDo:

Add material laws to the HT process

---

ProcessLib/TwoPhaseFlowWithPrho/CreateTwoPhaseFlowWithPrhoProcess.cpp
ProcessLib/TwoPhaseFlowWithPrho/TwoPhaseFlowWithPrhoLocalAssembler.h
ProcessLib/TwoPhaseFlowWithPrho/TwoPhaseFlowWithPrhoProcess.cpp

This pr includes:
Move IntegrationPointData struct into namespace.
Fix a wrong debug message.

Fix error in TwoPhaseFlowWithPrho process

---

scripts/cmake/test/AddTest.cmake
scripts/travis/vtk.sh

CMake fix as reported by @waltherm .

Quick fixes

---

ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.cpp
ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.h
ProcessLib/HeatConduction/HeatConductionFEM-impl.h
ProcessLib/HeatConduction/HeatConductionFEM.h
ProcessLib/HeatConduction/HeatConductionProcess.cpp
ProcessLib/HeatConduction/HeatConductionProcess.h
ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.cpp
ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.h
ProcessLib/LiquidFlow/CMakeLists.txt
ProcessLib/LiquidFlow/LiquidFlowLocalAssembler-impl.h
ProcessLib/LiquidFlow/LiquidFlowLocalAssembler.h
ProcessLib/LiquidFlow/LiquidFlowProcess.cpp
ProcessLib/LiquidFlow/LiquidFlowProcess.h
ProcessLib/LocalAssemblerInterface.cpp
ProcessLib/LocalAssemblerInterface.h
ProcessLib/Process.cpp
ProcessLib/Process.h
ProcessLib/StaggeredCouplingTerm.cpp
ProcessLib/StaggeredCouplingTerm.h
ProcessLib/UncoupledProcessesTimeLoop.cpp
ProcessLib/VectorMatrixAssembler.cpp

as titled.
Besides, some member names are changed.

Calculation of the secondary variables with coupled term

---

ProcessLib/LiquidFlow/CreateLiquidFlowMaterialProperties.cpp

Corrected a documentation page reference

---

ProcessLib/TwoPhaseFlowWithPrho/CreateTwoPhaseFlowWithPrhoProcess.cpp

Fix parameter documentation in two phase flow with P-rho process

Fix document reference.

---

Documentation/ProjectFile/prj/processes/process/LIQUID_FLOW/t_reference_temperature.md
MaterialLib/Fluid/Density/CreateFluidDensityModel.cpp
MaterialLib/Fluid/Density/CreateFluidDensityModel.h
MaterialLib/Fluid/FluidPropertyHeaders.h
MaterialLib/Fluid/Viscosity/CreateViscosityModel.cpp
MaterialLib/Fluid/Viscosity/CreateViscosityModel.h
ProcessLib/HT/CreateHTProcess.cpp
ProcessLib/LiquidFlow/CreateLiquidFlowProcess.cpp
ProcessLib/LiquidFlow/LiquidFlowLocalAssembler-impl.h
ProcessLib/LiquidFlow/LiquidFlowLocalAssembler.h
ProcessLib/LiquidFlow/LiquidFlowProcess.cpp
ProcessLib/LiquidFlow/LiquidFlowProcess.h
Tests/MaterialLib/TestFluidDensity.cpp
Tests/MaterialLib/TestFluidViscosity.cpp

This PR contains:
Fluid property: Changed the first letter of four file names to capital letter.
Liquid flow: Added an optional input of reference temperature for LiquidFlow.

Added an optional input of reference temperature for LiquidFlow

---

MeshLib/Node.h

This is needed for the GMSH interface.

[MeL] Make Node::setID protected instead of privat.

---

ProcessLib/HydroMechanics/CMakeLists.txt
ProcessLib/HydroMechanics/CreateHydroMechanicsProcess.cpp
ProcessLib/HydroMechanics/CreateLocalAssemblers.h
ProcessLib/HydroMechanics/HydroMechanicsFEM.h
ProcessLib/HydroMechanics/HydroMechanicsProcess.cpp
ProcessLib/HydroMechanics/HydroMechanicsProcess.h
ProcessLib/HydroMechanics/LocalDataInitializer.h

Copied together from SmallDeformation and LiquidFlow processes.
The output of Darcy velocity needs validation.
@grubbymoon Would you please do this?

HM process; secondary variables extrapolation

---

MeshLib/Mesh.h
ProcessLib/ProcessOutput.cpp
ProcessLib/ProcessVariable.cpp

Generalization of common pattern.

Get or create mesh property

---

Applications/DataExplorer/DataView/MeshElementRemovalDialog.cpp
Applications/DataExplorer/DataView/MeshElementRemovalDialog.h
Applications/DataExplorer/DataView/MshModel.cpp
Applications/DataExplorer/DataView/MshModel.h
Applications/DataExplorer/VtkVis/VtkVisPipeline.cpp
Applications/DataExplorer/mainwindow.h
MaterialLib/FractureModels/MohrCoulomb.cpp
MathLib/MathTools.h
ProcessLib/LIE/Common/LevelSetFunction.cpp
ProcessLib/LIE/Common/Utils.cpp

If you are aware of more qt4 workarounds, this would be a good point to finish them off.

Remove some Qt4 related code.

---

CMakeLists.txt
scripts/cmake/CompilerSetup.cmake

[CMake] Added cpu arch flags for MSVC and option OGS_ENABLE_AVX2.

---

ProcessLib/SmallDeformation/CMakeLists.txt
ProcessLib/SmallDeformation/SmallDeformationFEM.h
ProcessLib/SmallDeformation/SmallDeformationProcess.h
ProcessLib/SmallDeformationCommon/Common.h

Output of so called nodal forces common for all mechanics processes.
TODO:

Nodal force output

---

Applications/ApplicationsLib/CMakeLists.txt
Applications/CLI/CMakeLists.txt
Applications/DataExplorer/Base/CMakeLists.txt
Applications/DataExplorer/DataExplorer.cmake
Applications/DataExplorer/DataView/CMakeLists.txt
Applications/DataExplorer/DataView/DiagramView/CMakeLists.txt
Applications/DataExplorer/DataView/StratView/CMakeLists.txt
Applications/DataExplorer/VtkAct/CMakeLists.txt
Applications/DataExplorer/VtkVis/CMakeLists.txt
Applications/DataHolderLib/CMakeLists.txt
Applications/FileIO/CMakeLists.txt
Applications/InSituLib/CMakeLists.txt
Applications/Utils/OGSFileConverter/CMakeLists.txt
BaseLib/CMakeLists.txt
CMakeLists.txt
GeoLib/CMakeLists.txt
MaterialLib/CMakeLists.txt
MathLib/CMakeLists.txt
MeshGeoToolsLib/CMakeLists.txt
MeshLib/CMakeLists.txt
NumLib/CMakeLists.txt
ProcessLib/CMakeLists.txt
Tests/CMakeLists.txt
scripts/cmake/CompilerSetup.cmake

Disabled PCH on Visual Studio 2015.

[CMake] Added option OGS_USE_PCH.

---

Applications/CLI/ogs.cpp
MeshLib/IO/VtkIO/VtuInterface-impl.h
MeshLib/IO/VtkIO/VtuInterface.cpp
MeshLib/IO/VtkIO/VtuInterface.h
scripts/cmake/VtkModules.cmake

With this changes the pvtu files in the parallel benchmarks are written correctly. This fixes one issue of the issues collection https://github.com/ufz/ogs/issues/1761.

Fix PVTU output

---

.travis.yml

Closes https://github.com/ufz/ogs/issues/1084

[Travis] gcc 4.9

---

NumLib/DOF/LocalToGlobalIndexMap.cpp
NumLib/DOF/LocalToGlobalIndexMap.h
NumLib/DOF/MeshComponentMap.cpp
NumLib/DOF/MeshComponentMap.h
ProcessLib/BoundaryCondition/GenericNaturalBoundaryCondition-impl.h
ProcessLib/LIE/BoundaryCondition/GenericNaturalBoundaryCondition-impl.h
Tests/NumLib/LocalToGlobalIndexMap.cpp
Tests/NumLib/LocalToGlobalIndexMapMultiComponent.cpp
Tests/NumLib/TestMeshComponentMap.cpp

Required in ["pressure" boundary condition](https://github.com/endJunction/ogs/tree/PressureBC)

Multicomponent DOF table upgrade.

---

Applications/Utils/ModelPreparation/PartitionMesh/PartitionMesh.cpp

Useful for debug purposes and scalability measurements.

[A/U/MP] 'Partition' mesh into one partition.

---

.appveyor.yml
.travis.yml
Applications/DataExplorer/CMakeLists.txt
Applications/DataExplorer/DataView/CMakeLists.txt
Applications/Utils/MeshEdit/CMakeLists.txt
Applications/Utils/OGSFileConverter/CMakeLists.txt
BaseLib/BuildInfo.h
BaseLib/CMakeLists.txt
BaseLib/Functional.h
MaterialLib/Adsorption/ReactionCaOH2.h
MaterialLib/CMakeLists.txt
MaterialLib/FractureModels/FractureIdentity2.h
MathLib/CMakeLists.txt
MathLib/Integration/GaussLegendre.h
MathLib/Integration/GaussLegendrePyramid.h
MathLib/Integration/GaussLegendreTet.h
MathLib/Integration/GaussLegendreTri.h
MathLib/Point3d.h
MathLib/TemplatePoint.h
MeshLib/CMakeLists.txt
NumLib/CMakeLists.txt
NumLib/DOF/GlobalMatrixProviders.h
NumLib/DOF/MeshComponentMap.h
scripts/cmake/CompilerSetup.cmake

As MSVC 2015 is not tested on our own hardware anymore this PR fills that gap. A new check is added on every PR. Also this PR enables shared linking on Windows with VS 2017.
This builds the CLI, runs unit and benchmark tests with standard config. Please note that this already takes 50 minutes. I can enable building the GUI but then it will build even longer..
*Edit:* Now the GUI is build too and it takes about 27 mins. Do not know why it took so long before.
Issues:

MSVC 2015 builds with Appveyor

---

ProcessLib/UncoupledProcessesTimeLoop.cpp

This fixes #https://github.com/ufz/ogs/issues/1799.
Kudos to @chleh!

[PL] Pass initial delta_t to time discretization.

---

Documentation/Doxyfile.in
scripts/jenkins/docs.groovy
scripts/jenkins/gcc.groovy
web/layouts/partials/header.html

If a build failed the report was not published before.

[Jenkins] Show Doxygen and web html reports for failing builds too

---

Applications/Utils/ModelPreparation/PartitionMesh/PartitionMesh.cpp
Applications/Utils/SimpleMeshCreation/generateStructuredMesh.cpp
BaseLib/Error.h
BaseLib/Subdivision.cpp
BaseLib/Subdivision.h
MaterialLib/Adsorption/ReactionInert.h
MaterialLib/PorousMedium/Permeability/createPermeabilityModel.cpp

* some arguments that are mutually exclusive are checked
* --mx now works together with --nx etc.
* the existing subdivision class now checks if (infinitely many) subdivisions can sum up to the total length.

Extended generateStructuredMesh

---

scripts/env/envinf1/petsc.sh

Updated petsc module, which enables external packages of mumps, superLU and hypre.

[envinf1] Updated petsc module

---

Applications/Utils/MeshEdit/editMaterialID.cpp
MaterialLib/Adsorption/Reaction.cpp
MaterialLib/Fluid/Density/CreateFluidDensityModel.cpp
MaterialLib/PorousMedium/UnsaturatedProperty/RelativePermeability/CreateRelativePermeabilityModel.cpp
MeshLib/MeshEditing/DuplicateMeshComponents.cpp
MeshLib/MeshEditing/MeshRevision.cpp
NumLib/ODESolver/TimeDiscretizationBuilder.cpp
ProcessLib/Parameter/Parameter.cpp

Just discovered that applying clang-tidy repeatedly is required to get all of the changes.
This is follow up of https://github.com/ufz/ogs/pull/1819

Do not use else after return. II

---

Applications/Utils/FileConverter/CMakeLists.txt

Thanks to J. Maßmann for reporting!

[CMake] convertGEO is not dependent on Qt.

---

MathLib/LinAlg/PETSc/PETScLinearSolver.cpp
MathLib/LinAlg/PETSc/PETScLinearSolver.h
MathLib/LinAlg/PETSc/PETScMatrix.cpp
MathLib/LinAlg/PETSc/PETScMatrix.h
MathLib/LinAlg/PETSc/PETScMatrixOption.h
MathLib/LinAlg/PETSc/PETScTools.cpp
MathLib/LinAlg/PETSc/PETScTools.h
MathLib/LinAlg/PETSc/PETScVector.cpp
MathLib/LinAlg/PETSc/PETScVector.h

Applied clang-format to all files in LinAlg/PETSc

---

ProcessLib/LIE/SmallDeformation/LocalAssembler/LocalDataInitializer.h
Tests/NumLib/TestODEInt.cpp
Tests/ProcessLib/TestLIE.cpp

Removed some compilation warnings

---

MathLib/LinAlg/PETSc/PETScVector.cpp
ProcessLib/HydroMechanics/HydroMechanicsFEM.h
Tests/NumLib/LocalToGlobalIndexMapMultiComponent.cpp

Removed three compilation warnings

---

NumLib/DOF/DOFTableUtil.cpp
NumLib/DOF/DOFTableUtil.h
NumLib/DOF/LocalToGlobalIndexMap.h
NumLib/DOF/MeshComponentMap.cpp
Tests/CMakeLists.txt
Tests/NumLib/TestComponentNorms.cpp
Tests/VectorUtils.h

Fix PETSc norm computation

---

.editorconfig

Removed root = true from .editorconfig to allow user settings.

---

ProcessLib/Output.cpp
ProcessLib/Output.h

fix a bug that a PVD file includes output directory in VTU paths

---

ProcessLib/UncoupledProcessesTimeLoop.cpp

Force the program abort when nonlinear solver fails during FixedTimeStepping

---

NumLib/TimeStepping/Algorithms/EvolutionaryPIDcontroller.cpp
ProcessLib/LiquidFlow/Tests.cmake
ProcessLib/RichardsFlow/Tests.cmake
ProcessLib/UncoupledProcessesTimeLoop.cpp
ProcessLib/UncoupledProcessesTimeLoop.h

as titled.
In addition, it includes several minor changes as
-  The commits in the closed PR of #1862 are merged to this PR
-  A new commit corrects the times of rejected steps and formats a warning message.

Improved the convergence control of the coupling iterations

---

MathLib/LinAlg/Eigen/EigenMatrix.h
MathLib/LinAlg/Eigen/EigenVector.h
MathLib/LinAlg/UnifiedMatrixSetters.cpp
ProcessLib/ProcessOutput.cpp
Tests/NumLib/TestSerialLinearSolver.cpp

... analogously to PETSc's index type in the PETSc classes.
Prerequisite to #1874.

Use Eigen's index type in EigenMatrix and EigenVector

---

MaterialLib/FractureModels/MohrCoulomb.cpp
Tests/MaterialLib/TestFractureModels.cpp

as titled, though LIE isn't supporting 3d yet.

[Mat/Fracture] support 3d in MC model

---

CMakeLists.txt
scripts/cmake/SubmoduleSetup.cmake

[CMake] Added option OGS_SYNC_SUBMODULES

---

ProcessLib/SmallDeformation/SmallDeformationFEM.h

Some recent PR of mine messed that up. @endJunction and @xingyuanmiao please have a look if the fix is correct. I apologize for any inconvenience cause by this bug.

[PL] corrected ordering of SD stress output

---

Applications/DataExplorer/mainwindow.cpp
Applications/FileIO/Gmsh/GMSHInterface.h
GeoLib/Polygon.cpp
GeoLib/Polygon.h

Details in the commit message.

Fix Gmsh Interface

---

ProcessLib/PhaseField/PhaseFieldFEM.h

Fixed a compilation warning

---

ProcessLib/Process.h

~Removed multiple private and protected in class Processs, and~ applied clang-format to Process.h.
This PR contains the firs two commits in PR #1920, and it is expected to be merged before  PR #1920.

Removed multiple private and protected in class Processs

---

Documentation/ProjectFile/prj/time_loop/output/t_data_mode.md
ProcessLib/Output.cpp
ProcessLib/Output.h
ProcessLib/ProcessOutput.cpp
ProcessLib/ProcessOutput.h

Closes https://github.com/ufz/ogs/issues/1839

 [PL] Add Ascii, Binary, and Appended output option

---

web/src/js/vis/index.js
web/webpack.config.js
web/yarn.lock

Changed lookup table in webgl visualisations to blue to red rainbow.
Fixes #1933.

[web] Updated dependencies and fixed webgl rendering.

---

ProcessLib/ComponentTransport/ComponentTransportFEM.h
ProcessLib/HydroMechanics/HydroMechanicsFEM.h
ProcessLib/HydroMechanics/HydroMechanicsProcess-impl.h
ProcessLib/HydroMechanics/LocalAssemblerInterface.h
ProcessLib/HydroMechanics/Tests.cmake
ProcessLib/LiquidFlow/LiquidFlowLocalAssembler-impl.h
ProcessLib/LiquidFlow/LiquidFlowLocalAssembler.h
ProcessLib/LiquidFlow/LiquidFlowProcess.cpp
ProcessLib/LiquidFlow/LiquidFlowProcess.h
ProcessLib/LiquidFlow/Tests.cmake
ProcessLib/Process.h
ProcessLib/RichardsFlow/RichardsFlowFEM.h
ProcessLib/RichardsFlow/RichardsFlowProcess.cpp
ProcessLib/RichardsFlow/RichardsFlowProcess.h
ProcessLib/UncoupledProcessesTimeLoop.cpp
ProcessLib/UncoupledProcessesTimeLoop.h

Continue on Christoph's implementation of vectorial extrapolation, this PR changes the velocity calculation in several other classes of processes. The changes are
1. CL:     CompontTransport, Hydromechnics, Richards.
2. WW:  Coupled term, LiquidFlow.

Vector extrapolation part2

---

MaterialLib/SolidModels/LinearElasticIsotropicPhaseField.h
MaterialLib/SolidModels/PhaseFieldExtension.h
ProcessLib/PhaseField/CreatePhaseFieldProcess.cpp
ProcessLib/PhaseField/CreatePhaseFieldProcess.h
ProcessLib/PhaseField/LocalAssemblerInterface.h
ProcessLib/PhaseField/PhaseFieldFEM.h
ProcessLib/PhaseField/PhaseFieldProcess-impl.h
ProcessLib/PhaseField/PhaseFieldProcess.cpp
ProcessLib/PhaseField/PhaseFieldProcess.h
ProcessLib/PhaseField/PhaseFieldProcessData.h

Same as #1877 and #1855 and https://github.com/ufz/ogs/pull/1937  to keep the processes similar.

Restructure PhaseField

---

Documentation/ProjectFile/prj/processes/process/SMALL_DEFORMATION/t_solid_density.md
Documentation/ProjectFile/prj/processes/process/SMALL_DEFORMATION/t_specific_body_force.md
ProcessLib/SmallDeformation/CreateSmallDeformationProcess.cpp
ProcessLib/SmallDeformation/SmallDeformationFEM.h
ProcessLib/SmallDeformation/SmallDeformationProcessData.h
ProcessLib/SmallDeformation/Tests.cmake

Closes https://github.com/ufz/ogs/issues/1945
This adds gravity to the small deformation process.
TODO:

SmallDeformation gravity.

---

Documentation/ProjectFile/prj/process_variables/process_variable/boundary_conditions/boundary_condition/NonuniformDirichlet/c_NonuniformDirichlet.md
Documentation/ProjectFile/prj/process_variables/process_variable/boundary_conditions/boundary_condition/NonuniformDirichlet/t_field_name.md
Documentation/ProjectFile/prj/process_variables/process_variable/boundary_conditions/boundary_condition/NonuniformDirichlet/t_mesh.md
ProcessLib/BoundaryCondition/BoundaryCondition.cpp
ProcessLib/BoundaryCondition/BoundaryCondition.h
ProcessLib/BoundaryCondition/BoundaryConditionCollection.cpp
ProcessLib/BoundaryCondition/BoundaryConditionCollection.h
ProcessLib/BoundaryCondition/DirichletBoundaryCondition.cpp
ProcessLib/BoundaryCondition/DirichletBoundaryCondition.h
ProcessLib/BoundaryCondition/NonuniformDirichletBoundaryCondition.cpp
ProcessLib/BoundaryCondition/NonuniformDirichletBoundaryCondition.h
ProcessLib/BoundaryCondition/NonuniformNeumannBoundaryCondition.cpp
ProcessLib/GroundwaterFlow/Tests.cmake
ProcessLib/Process.cpp

Mostly copied from nonuniform Neumann boundary condition and married to the existing Dirichlet boundary condition.
Next step would be to generalize the copy-paste parts and continue on the Robin BCs.

Nonuniform Dirichlet boundary conditions

---

Jenkinsfile

[Jenkins] Fix log parser publisher.

---

MaterialLib/FractureModels/CreateLinearElasticIsotropic.cpp
MaterialLib/FractureModels/CreateMohrCoulomb.cpp
MaterialLib/FractureModels/FractureModelBase.h
MaterialLib/FractureModels/LinearElasticIsotropic.cpp
MaterialLib/FractureModels/LinearElasticIsotropic.h
MaterialLib/FractureModels/LogPenalty.h
MaterialLib/FractureModels/MohrCoulomb.cpp
MaterialLib/FractureModels/MohrCoulomb.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerFracture-impl.h
ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerFracture-impl.h
ProcessLib/LIE/SmallDeformation/Tests.cmake
Tests/MaterialLib/TestFractureModels.cpp
web/content/docs/benchmarks/small-deformations/LIE_fracture_incompressibility.pdf
web/content/docs/benchmarks/small-deformations/lie-m-linear-single-fracture.md

Prevents negative apertures
Review can be done commit-wise.
TODO:

LIE compression

---

Applications/DataExplorer/VtkVis/VtkRaster.cpp
Applications/DataExplorer/mainwindow.cpp
Applications/FileIO/Legacy/createSurface.cpp
Applications/Utils/FileConverter/GMSH2OGS.cpp
Applications/Utils/MeshEdit/ResetPropertiesInPolygonalRegion.cpp
Applications/Utils/MeshEdit/checkMesh.cpp
Applications/Utils/MeshEdit/removeMeshElements.cpp
GeoLib/IO/XmlIO/Rapid/RapidStnInterface.cpp
MathLib/Integration/GaussLegendreTet.cpp
MathLib/LinAlg/Eigen/EigenVector.h
MeshLib/Mesh.h
NumLib/DOF/LocalToGlobalIndexMap.cpp
NumLib/DOF/LocalToGlobalIndexMap.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/LocalDataInitializer.h
ProcessLib/LIE/SmallDeformation/LocalAssembler/LocalDataInitializer.h
ProcessLib/ProcessOutput.cpp
Tests/FileIO/TestCsvWriter.cpp

After this the remaining warnings are only the `tmpnam` and some brace initialization in `NumLib::LocalLinearLeastSquaresExtrapolator::CachedData`.

Cleanup compiler warnings.

---

GeoLib/AABB.h
GeoLib/Surface.cpp
GeoLib/Surface.h
MeshGeoToolsLib/MeshNodesAlongSurface.cpp
MeshLib/MeshSearch/ElementSearch.cpp
NumLib/Function/LinearInterpolationOnSurface.cpp
Tests/GeoLib/TestAABB.cpp

[GL] Add eps to the bounding box search.

---

Applications/FileIO/Gmsh/GMSHInterface.cpp
Applications/FileIO/Gmsh/GMSHInterface.h
Applications/FileIO/Gmsh/GMSHPolygonTree.cpp
Applications/FileIO/Gmsh/GMSHPolygonTree.h
GeoLib/PointVec.h

Two comments by Tom, using unique_ptr in two occasions, better function parameter names.

Small GMSH improvements.

---

MaterialLib/SolidModels/Ehlers.h
MaterialLib/SolidModels/LinearElasticIsotropic.h
MaterialLib/SolidModels/LinearElasticIsotropicPhaseField.h
MaterialLib/SolidModels/Lubby2.h
MaterialLib/SolidModels/MechanicsBase.h
ProcessLib/Deformation/GMatrix.h
ProcessLib/Deformation/GMatrixPolicy.h
ProcessLib/Deformation/LinearBMatrix.h
ProcessLib/Deformation/MaterialForces.h
ProcessLib/SmallDeformation/LocalAssemblerInterface.h
ProcessLib/SmallDeformation/SmallDeformationFEM.h
ProcessLib/SmallDeformation/SmallDeformationProcess-impl.h
ProcessLib/SmallDeformation/SmallDeformationProcess.h
ProcessLib/SmallDeformation/Tests.cmake
Tests/lfs-data/Mechanics/Linear/MaterialForces/bar.gml
Tests/lfs-data/Mechanics/Linear/MaterialForces/bar.prj
Tests/lfs-data/Mechanics/Linear/MaterialForces/bar.vtu
Tests/lfs-data/Mechanics/Linear/MaterialForces/bar_3D.gml
Tests/lfs-data/Mechanics/Linear/MaterialForces/bar_3D.prj
Tests/lfs-data/Mechanics/Linear/MaterialForces/bar_3D.vtu
Tests/lfs-data/Mechanics/Linear/MaterialForces/expected_bar_3D_out_pcs_0_ts_2_t_1.000000.vtu
Tests/lfs-data/Mechanics/Linear/MaterialForces/expected_bar_out_pcs_0_ts_2_t_1.000000.vtu

Material forces

---

NumLib/DOF/LocalToGlobalIndexMap.h
ProcessLib/SourceTerms/NodalSourceTerm.cpp

One I forgot to update previously. Another is a new one.

Warning fix

---

MeshLib/MeshEditing/ConvertToLinearMesh.cpp
MeshLib/PropertyVector.h
NumLib/DOF/DOFTableUtil.cpp
NumLib/DOF/LocalToGlobalIndexMap.cpp
NumLib/DOF/LocalToGlobalIndexMap.h
NumLib/ODESolver/ConvergenceCriterionPerComponentDeltaX.cpp
NumLib/ODESolver/ConvergenceCriterionPerComponentResidual.cpp
ProcessLib/BoundaryCondition/GenericNonuniformNaturalBoundaryCondition-impl.h
ProcessLib/CalculateSurfaceFlux/CalculateSurfaceFluxLocalAssembler.h
ProcessLib/HydroMechanics/HydroMechanicsProcess-impl.h
ProcessLib/LIE/BoundaryCondition/GenericNaturalBoundaryCondition-impl.h
ProcessLib/LIE/Common/PostUtils.cpp
ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.cpp
ProcessLib/LIE/SmallDeformation/SmallDeformationProcess.cpp
ProcessLib/Parameter/ConstantParameter.h
ProcessLib/Parameter/CurveScaledParameter.h
ProcessLib/Parameter/GroupBasedParameter.h
ProcessLib/Parameter/MeshElementParameter.h
ProcessLib/Parameter/MeshNodeParameter.h
ProcessLib/Parameter/Parameter.h
ProcessLib/Process.cpp
ProcessLib/Utils/ProcessUtils.h
Tests/NumLib/LocalToGlobalIndexMap.cpp
Tests/NumLib/LocalToGlobalIndexMapMultiComponent.cpp

Update getNumberOfComponents to return an int.

---

Tests/lfs-data/Parabolic/LiquidFlow/GravityDriven3D/isotropic_gravity_driven3D.prj

Closes https://github.com/ufz/ogs/issues/2000

[Test] Corrected the new permeability input for one benchmark

---

Jenkinsfile

Runs on every master build. Works, see https://github.com/ufz/ogs-data/commit/64c7817ec058f7682771359bad2fbbc8a7ae0420.

Update ogs data

---

Documentation/ProjectFile/prj/processes/process/ComponentTransport/t_coupling_scheme.md
ProcessLib/ComponentTransport/CreateComponentTransportProcess.cpp
ProcessLib/HydroMechanics/CreateHydroMechanicsProcess.cpp
ProcessLib/LIE/HydroMechanics/CreateHydroMechanicsProcess.cpp
ProcessLib/PhaseField/CreatePhaseFieldProcess.cpp
ProcessLib/RichardsComponentTransport/CreateRichardsComponentTransportProcess.cpp
ProcessLib/ThermoMechanics/CreateThermoMechanicsProcess.cpp

Added a missed parameter documentation and ran clang-tidy for some files

---

ProcessLib/SmallDeformation/Tests.cmake
Tests/Data/HydroMechanics/Linear/Confined_Compression/cube_1e3.prj

See commit messages for explanations.
Reason for changes is that it is not passing on my computer.

Mechanics CTest updates

---

NumLib/Fem/CoordinatesMapping/NaturalCoordinatesMapping.cpp

The function gives more detailed message about the reason to failure.  Besides, the checking of the determinant of Jacobian  is moved to position before using the determinant.

[Num] Added a function in NaturalCoordinatesMapping.cpp to check the determinant of Jacobian.

---

Jenkinsfile
scripts/docker/Dockerfile.gcc.full

Added gcc.full Docker image definition which contains everything required for building Doxygen and benchmark docs.

[Jenkins] Restored web build.

---

NumLib/ODESolver/TimeDiscretizedODESystem.h
ProcessLib/Output/CreateProcessOutput.cpp
ProcessLib/UncoupledProcessesTimeLoop.cpp

See commit messages.
@bilke If you have time, please have a look on the jenkins' doxygen warning parser.

Fix doxygen docu

---

MaterialLib/PorousMedium/CreatePorousMediaProperties.cpp

Fixes https://github.com/ufz/ogs/issues/1998.

[Material] Fix bug matching MaterialIDs and corresponding porous media def.

---

MaterialLib/SolidModels/Ehlers-impl.h
MaterialLib/SolidModels/Ehlers.cpp
MaterialLib/SolidModels/Ehlers.h
MaterialLib/SolidModels/LinearElasticIsotropic.h
MaterialLib/SolidModels/LinearElasticIsotropicPhaseField.h
MaterialLib/SolidModels/Lubby2-impl.h
MaterialLib/SolidModels/Lubby2.h
MaterialLib/SolidModels/MechanicsBase.h
MaterialLib/SolidModels/PhaseFieldExtension.h
MathLib/KelvinVector-impl.h
MathLib/KelvinVector.cpp
MathLib/KelvinVector.h
ProcessLib/Deformation/BMatrixPolicy.h
ProcessLib/Deformation/LinearBMatrix.h
ProcessLib/HydroMechanics/HydroMechanicsFEM-impl.h
ProcessLib/HydroMechanics/HydroMechanicsFEM.h
ProcessLib/LIE/HydroMechanics/CreateHydroMechanicsProcess.cpp
ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrix-impl.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrix.h
ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerMatrix-impl.h
ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerMatrixNearFracture-impl.h
ProcessLib/PhaseField/PhaseFieldFEM.h
ProcessLib/SmallDeformation/SmallDeformationFEM.h
ProcessLib/SmallDeformation/SmallDeformationProcess-impl.h
ProcessLib/ThermoMechanics/ThermoMechanicsFEM.h
Tests/MaterialLib/KelvinVector.cpp

Commit-wise will be faster....
There are still many places having component-wise sigma/epsilon output, I'm aware of this, but it will take another five PRs to replace all of them. (Help is welcome;)

Collect Kelvin vector code and function in single place.

---

ProcessLib/CreateProcessData.cpp
ProcessLib/CreateProcessData.h
ProcessLib/Output/Output.cpp
ProcessLib/Output/Output.h
ProcessLib/ProcessData.h
ProcessLib/UncoupledProcessesTimeLoop.cpp
ProcessLib/UncoupledProcessesTimeLoop.h

Move SingleProcessData definition and creation in own files out of time loop code.
Then rename to ProcessData.
Commit-wise.

Separate ProcessData

---

Jenkinsfile

[Jenkins] Re-added git diff --check.

---

scripts/cmake/ConanSetup.cmake

Code looks a lot like CMake-fu... it has to be!
Will speed up CMake runs after the first run on each day.

[Conan] Check only once a day for new Conan packages.

---

ProcessLib/Output/ProcessOutput.cpp

This adds ogs version to all vtu output files.

[PL] Output; Add OGS_VERSION field data.

---

ProcessLib/CoupledSolutionsForStaggeredScheme.cpp
ProcessLib/UncoupledProcessesTimeLoop.cpp

... discovered during staggered PhaseField process implementation.

Small updates to coupled solutions

---

Jenkinsfile
web/content/books/models-of-thermochemical-heat-storage.pandoc

Checks git changesets for conditional pipeline execution:
- web can be built standalone
- web is always build on ufz/master
- changes in Jenkinsfile always trigger a full build
- the first build in a PR is always a full build as there are no changesets defined (technically, I know that one could derive them manually..)
Maybe we can introduce more conditions in the future..

[Jenkins] Conditional pipeline execution

---

GeoLib/Grid.h

Due to rounding errors the computed grid coordinates are in some cases to large which leads to memory errors.

[GL] Change Grid<POINT>::getGridCoords.

---

ProcessLib/UncoupledProcessesTimeLoop.cpp

Forbid output when a time step is rejected

---

ProcessLib/PhaseField/PhaseFieldFEM-impl.h
ProcessLib/PhaseField/PhaseFieldFEM.h
ProcessLib/PhaseField/PhaseFieldProcess.cpp

As described in the individual commits...

Phase field cleanup

---

MathLib/LinAlg/PETSc/PETScLinearSolver.cpp
MathLib/LinAlg/PETSc/PETScMatrix.h

In addition, apply clang-format to PETScLinearSolver.cpp.

A more detailed descritpion of PETScMatrix::add

---

web/content/docs/benchmarks/liquid-flow/liquid-flow-theis-problem.md
web/content/docs/benchmarks/liquid-flow/theis_comparison.png

[Web] Added a figure about the result comparison of Theis' test

---

ProcessLib/SmallDeformation/SmallDeformationProcess-impl.h
ProcessLib/SmallDeformation/SmallDeformationProcess.h

In the initial conditions output (time step 0) this vector does not exist and paraview has difficulties (error) plotting values over time.

[PL] SD: Create material forces at process start.

---

Documentation/ProjectFile/prj/processes/process/THERMO_MECHANICS/t_reference_solid_density.md
ProcessLib/ThermoMechanics/ThermoMechanicsFEM.h
Tests/Data/ThermoMechanics/expected_tm_a_pcs_0_ts_20_t_20000.000000.vtu
Tests/Data/ThermoMechanics/expected_tm_a_quad_pcs_0_ts_20_t_20000.000000.vtu

As titled. This correction has been done in thermo-mechanical phase-field process.

correction of density calculation in thermo-mechanics

---

MathLib/LinAlg/LinAlg.cpp
ProcessLib/HT/Tests.cmake
ProcessLib/LiquidFlow/LiquidFlowLocalAssembler-impl.h
ProcessLib/LiquidFlow/LiquidFlowLocalAssembler.h

Small changes

---

Applications/ApplicationsLib/ProjectData.cpp
Applications/DataExplorer/DataView/FemConditionView.cpp
Applications/DataExplorer/VtkVis/VtkImageDataToPointCloudFilter.cpp
Applications/DataExplorer/VtkVis/VtkImageDataToSurfacePointsFilter.cpp
BaseLib/ConfigTree-impl.h
BaseLib/ConfigTreeUtil.cpp
NumLib/Extrapolation/LocalLinearLeastSquaresExtrapolator.cpp
Tests/NumLib/NaturalNodeCoordinates.cpp

Removed two compilation warnings

 Removed two compilation warnings

---

web/content/images/xsd/OpenGeoSysCND.xsd
web/content/images/xsd/OpenGeoSysGLI.xsd
web/content/images/xsd/OpenGeoSysNum.xsd
web/content/images/xsd/OpenGeoSysProject.xsd
web/content/images/xsd/OpenGeoSysSTN.xsd

[web] Add xsd files into images/xsd.

---

ProcessLib/CalculateSurfaceFlux/CalculateSurfaceFlux.cpp
ProcessLib/CalculateSurfaceFlux/CalculateSurfaceFlux.h
ProcessLib/CalculateSurfaceFlux/CalculateSurfaceFluxLocalAssembler.h
ProcessLib/GroundwaterFlow/GroundwaterFlowProcess.h
ProcessLib/HT/HTProcess.cpp

[PL] Use std::function to give the flux calculation to CalculateSurfaceFlux.

---

NumLib/DOF/MeshComponentMap.cpp
ProcessLib/LocalAssemblerInterface.h

Fix warning and compilation error

---

Documentation/ProjectFile/prj/processes/process/HYDRO_MECHANICS/t_reference_temperature.md
Documentation/ProjectFile/prj/processes/process/HYDRO_MECHANICS_WITH_LIE/t_reference_temperature.md
Documentation/ProjectFile/prj/processes/process/SMALL_DEFORMATION/t_reference_temperature.md
Documentation/ProjectFile/prj/processes/process/SMALL_DEFORMATION_WITH_LIE/t_reference_temperature.md
MaterialLib/PhysicalConstant.h
MaterialLib/SolidModels/Ehlers.cpp
MaterialLib/SolidModels/Ehlers.h
MaterialLib/SolidModels/LinearElasticIsotropic.cpp
MaterialLib/SolidModels/LinearElasticIsotropic.h
MaterialLib/SolidModels/LinearElasticIsotropicPhaseField.h
MaterialLib/SolidModels/Lubby2.cpp
MaterialLib/SolidModels/Lubby2.h
MaterialLib/SolidModels/MechanicsBase.h
ProcessLib/HydroMechanics/CreateHydroMechanicsProcess.cpp
ProcessLib/HydroMechanics/HydroMechanicsFEM-impl.h
ProcessLib/HydroMechanics/HydroMechanicsFEM.h
ProcessLib/HydroMechanics/HydroMechanicsProcessData.h
ProcessLib/LIE/HydroMechanics/CreateHydroMechanicsProcess.cpp
ProcessLib/LIE/HydroMechanics/HydroMechanicsProcessData.h
ProcessLib/LIE/HydroMechanics/LocalAssembler/HydroMechanicsLocalAssemblerMatrix-impl.h
ProcessLib/LIE/SmallDeformation/CreateSmallDeformationProcess.cpp
ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerMatrix-impl.h
ProcessLib/LIE/SmallDeformation/LocalAssembler/SmallDeformationLocalAssemblerMatrixNearFracture-impl.h
ProcessLib/LIE/SmallDeformation/SmallDeformationProcessData.h
ProcessLib/SmallDeformation/CreateSmallDeformationProcess.cpp
ProcessLib/SmallDeformation/SmallDeformationFEM.h
ProcessLib/SmallDeformation/SmallDeformationProcessData.h
ProcessLib/ThermoMechanics/ThermoMechanicsFEM.h

[Solids] Added an arguments of T to the class member of integrateStress

---

MaterialLib/FractureModels/CohesiveZoneModeI.cpp
MaterialLib/SolidModels/CreepBGRa.h
ProcessLib/BoundaryCondition/ConstraintDirichletBoundaryConditionLocalAssembler.h

Fixed three warnings

---

web/content/docs/benchmarks/creep-after-excavation-bgra/CreepAfterExcavation.md

Corrected a number on the web documentation in #2179 .

[web] Corrected a number

---

MaterialLib/SolidModels/CreepBGRa.cpp
ProcessLib/ThermoMechanics/Tests.cmake

[CreepBGRa] Added a condition for the case of |s_try|=0

---

web/content/docs/benchmarks/creepbgra/CreepBRGa.md

[web/BGRa] Added another analytical solution formulus

---

Applications/FileIO/TetGenInterface.cpp
GeoLib/Polyline.cpp
MeshLib/MeshEditing/MeshRevision.cpp
MeshLib/MeshGenerators/MeshLayerMapper.cpp
ProcessLib/BoundaryCondition/NonuniformNeumannBoundaryCondition.cpp
Tests/GeoLib/TestGrid.cpp
Tests/GeoLib/TestPolygon.cpp
Tests/MeshLib/TestUniqueMeshId.cpp

Fixes for some of the warnings from a [static analyzer run](https://jenkins.opengeosys.org/job/ufz/job/ogs/job/master/702/clang/).
See commit messages for some explanations, so maybe review commit-wise is better.
I definitely changed the logic in most places, but not the end results (so far they are tested ;), so please check carefully.

Warning and error fixes

---

Jenkinsfile
web/content/docs/devguide/advanced/docker.pandoc

Pushes docker images used by Jenkins to [Docker Hub](https://hub.docker.com/u/ogs6).
More info on how this can be used later ..

[Jenkins] Push docker images

---

NumLib/Fem/ShapeFunction/ShapeTri3.h

remove non-Unicode characters in ShapeTri3.h

---

Jenkinsfile
scripts/cmake/ConanSetup.cmake

See
https://bugreports.qt.io/browse/QTBUG-71004?jql=project%20%3D%20QTBUG%20AND%20fixVersion%20%3D%205.11.2

[MSVC] Bump Conan Qt to 5.11.2.

---

Applications/Utils/Tests.cmake
MeshLib/Elements/LineRule3.cpp
MeshLib/Elements/LineRule3.h

Fixes https://github.com/ufz/ogs/issues/1845

[MeL] Fix edge_nodes table for Line3.

---

ProcessLib/ThermoMechanics/ThermoMechanicsFEM.h

The TM process passes the mechanical strain to the solid material model. So far this mechanical strain has been a mix of total strain and the thermal strain increment.
That worked until now for the OGS material models, because there this "mixture" cancelled out in the end. However, it won't cancel out if we use material models provided by MFront.
In this PR the mechanical strain is properly computed with the total strain increment and the thermal strain increment.
This solution has been proposed by @fparisio.
In the TM-Phasefield process no change seems to be necessary, because there no incremental thermal strains seem to be used. Maybe somebody (@KeitaYoshioka) could confirm this.

Prepare TM process for upcoming MFront integration.

---

MeshLib/MeshGenerators/VtkMeshConverter.cpp

Fixes https://github.com/ufz/ogs/issues/2273

[MeL] VTK mesh conversion; Improve failure message

---

NumLib/DOF/LocalToGlobalIndexMap.cpp
Tests/Data/HydroMechanics/Linear/Confined_Compression/square_1e2.prj

Fixes https://github.com/ufz/ogs/issues/2276
Maybe also related to the https://github.com/ufz/ogs/issues/2279.

Fix DOF table for lower order variables

---

ProcessLib/HeatConduction/HeatConductionProcess.cpp
ProcessLib/HeatConduction/HeatConductionProcess.h
ProcessLib/HeatTransportBHE/HeatTransportBHEProcess.cpp
ProcessLib/HeatTransportBHE/HeatTransportBHEProcess.h
ProcessLib/HydroMechanics/HydroMechanicsProcess.cpp
ProcessLib/HydroMechanics/HydroMechanicsProcess.h
ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.cpp
ProcessLib/LIE/HydroMechanics/HydroMechanicsProcess.h
ProcessLib/LIE/SmallDeformation/SmallDeformationProcess.cpp
ProcessLib/LIE/SmallDeformation/SmallDeformationProcess.h
ProcessLib/LiquidFlow/LiquidFlowProcess.cpp
ProcessLib/LiquidFlow/LiquidFlowProcess.h
ProcessLib/Process.cpp
ProcessLib/Process.h
ProcessLib/RichardsMechanics/RichardsMechanicsProcess.cpp
ProcessLib/RichardsMechanics/RichardsMechanicsProcess.h
ProcessLib/UncoupledProcessesTimeLoop.cpp

A problem discovered by @renchao-lu when running a staggered HM test with ogs build in debug mode.
The proposed change fixes the error.
@wenqing or @renchao-lu Please update other processes, which are using the staggered scheme, and push directly to this branch (if you can).

Secondary variables staggered fix

---

MeshLib/MeshEditing/ConvertToLinearMesh.cpp

[MSH] support tri6, tet10 in ConvertToLinearMesh

---

Applications/Utils/ModelPreparation/CMakeLists.txt
Applications/Utils/ModelPreparation/ConvertVtkDataArrayToVtkDataArray.cpp
MeshLib/MeshGenerators/VtkMeshConverter.cpp
MeshLib/Vtk/VtkMappedMeshSource.cpp
web/content/docs/tools/doubleValuedMaterialIDs.vtu
web/content/docs/tools/model-preparation/convert-data-array-to-data-array/index.pandoc

Needed sometimes for model preparation.

Convert double array to int array

---

Jenkinsfile

https://github.com/jenkinsci/warnings-ng-plugin/blob/master/doc/Documentation.md

[Jenkins] Use new syntax for warnings plugin.

---

ProcessLib/SurfaceFlux/SurfaceFlux.h

Fixed an argument documentation in the merged PR #2297.

[Doc] Fixed an argument documentation

---

CMakeLists.txt

Bump CMake minimum version to 3.8.

---

MathLib/Integration/GaussLegendreTet.cpp

[Math] fix warning C4819 (unsupported character in current code)

---

ProcessLib/HydroMechanics/HydroMechanicsProcess.cpp

Shear strains epsilon_xz and epsilon_yz added as secondary variables.

HM Add shear strains for output

---

Jenkinsfile

To be merged on 2019-02-18.
To be reverted on 2019-02-22.

[Jenkins] Disable envinf1 jobs due to eve downtime

---

Applications/DataExplorer/DataView/ElementTreeModel.cpp

Correct display of node coordinates in element view.

Node coordinate fix

---

Jenkinsfile

To be merged on 2019-02-**18**.
To be reverted on 2019-02-22.

[Jenkins] Disable envinf1 jobs.

---

GeoLib/AnalyticalGeometry.cpp
GeoLib/AnalyticalGeometry.h
GeoLib/Polygon.cpp

Review commit-wise possible.
Used in #2367 see https://github.com/endJunction/ogs/tree/master2raster branch with refactorings.

Use exact predicates for orient2d

---

Applications/Utils/FileConverter/TIN2VTK.cpp
GeoLib/GEOObjects.cpp
GeoLib/IO/TINInterface.cpp
MaterialLib/SolidModels/CreepBGRa.h

CppCheck fixes

---

ProcessLib/BoundaryCondition/Python/CMakeLists.txt
ThirdParty/CMakeLists.txt

Part of #2376 not related to that PR but needed due to previous changes of python installation.

Update python handling in CMake

---

ProcessLib/HT/CreateHTProcess.cpp
ProcessLib/HT/HTProcess.cpp
ProcessLib/HT/HTProcess.h

* Introduced two members of process IDs for the staggered scheme.
* Enabled more flexible process order within the staggered coupling.

Some improvements over the staggered scheme of TH

---

Applications/Utils/Tests.cmake
Jenkinsfile
scripts/env/envinf1/cli.sh
scripts/env/envinf1/mpi.sh
scripts/env/envinf1/petsc.sh
scripts/env/frontend1/cli.sh
scripts/env/frontend1/mpi.sh
scripts/env/frontend1/petsc.sh

Will re-enable envinf1 in this PR once it is back online.
Closes #2383.

[eve] Updates for CentOS 7

---

Applications/Utils/OGSFileConverter/CMakeLists.txt
Jenkinsfile
scripts/cmake/ConanSetup.cmake

Thanks to @waltherm for the report.

[CMake] Added missing Qt platform plugin to packages

---

CHANGELOG.md

A final review of the changelog, please.
Closes https://github.com/ufz/ogs/issues/2351

Update changelog for 6.2.0 release.

---

web/content/releases/6.1.0.pandoc
web/content/releases/6.2.0.pandoc
web/layouts/partials/releases-single.html
web/layouts/releases/single.html
web/layouts/section/releases.html

Preview is here: https://deploy-preview-2420--ogs.netlify.com/releases/

[web] Refactored releases page.

---

Applications/ApplicationsLib/ProjectData.cpp
Documentation/ProjectFile/prj/processes/process/HT/thermal_dispersivity/i_thermal_dispersivity.md
Documentation/ProjectFile/prj/processes/process/HT/thermal_dispersivity/t_longitudinal.md
Documentation/ProjectFile/prj/processes/process/HT/thermal_dispersivity/t_transversal.md
ProcessLib/HT/CreateHTProcess.cpp
ProcessLib/HT/CreateHTProcess.h
ProcessLib/HT/HTFEM.h
ProcessLib/HT/HTMaterialProperties.h
ProcessLib/HT/MonolithicHTFEM.h
ProcessLib/HT/StaggeredHTFEM-impl.h
Tests/Data/Parabolic/HT/ConstViscosity/square_5500x5500.prj
Tests/Data/Parabolic/HT/SimpleSynthetics/CoupledPressureParabolicTemperatureParabolic.prj
Tests/Data/Parabolic/HT/SimpleSynthetics/CoupledPressureParabolicTemperatureParabolicStaggered.prj
Tests/Data/Parabolic/HT/SimpleSynthetics/IsothermalFluidFlow.prj
Tests/Data/Parabolic/HT/SimpleSynthetics/IsothermalFluidFlowStaggered.prj
Tests/Data/Parabolic/HT/SimpleSynthetics/IsothermalFluidFlowWithGravity.prj
Tests/Data/Parabolic/HT/SimpleSynthetics/IsothermalFluidFlowWithGravityStaggered.prj
Tests/Data/Parabolic/HT/SimpleSynthetics/PressureDiffusionTemperatureDiffusion.prj
Tests/Data/Parabolic/HT/SimpleSynthetics/PressureDiffusionTemperatureDiffusionStaggered.prj
Tests/Data/Parabolic/HT/SimpleSynthetics/PressureParabolicTemperatureParabolic.prj
Tests/Data/Parabolic/HT/SimpleSynthetics/PressureParabolicTemperatureParabolicStaggered.prj
Tests/Data/Parabolic/HT/SimpleSynthetics/calculatesurfaceflux_ht_cube_1e3.prj
Tests/Data/Parabolic/HT/SimpleSynthetics/calculatesurfaceflux_ht_cube_1e4.prj
Tests/Data/Parabolic/HT/SimpleSynthetics/constraint_bc_1e3.prj
Tests/Data/Parabolic/HT/StaggeredCoupling/ADecovalexTHMCBasedHTExample/th_decovalex.prj
Tests/Data/Parabolic/HT/StaggeredCoupling/ConstViscosity/square_5500x5500_staggered_scheme.prj
Tests/Data/Parabolic/HT/StaggeredCoupling/ConstViscosity/square_5500x5500_staggered_scheme_adaptive_dt.prj

This PR is based on PR #2425.
Substituted properties are:
- fluid density
- viscosity
- thermal conductivity
- thermal dispersivity
- porosity
- storage
- permeability
There are still some properties open, but the PR is already large. The remaining properties will be changed in another PR later on.

[PL/HT] Use MPL in HT process.

---

Applications/DataExplorer/mainwindow.cpp
scripts/cmake/ProjectSetup.cmake

CMake variables `GIT_SHA1` and `GIT_SHA1_SHORT` were not defined..

[DE] Fix about window information

---

web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/01_load-tifs.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/02_merge-DEMs.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/03_create-shp-for-clipping.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/04_edit-save-new-polygon.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/05_clip.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/06_reproject-raster.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/07_reproject-vector-layers.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/08_vector-to-raster.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/09_bathymetry-depth-to-elev.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/10_save-asc.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/11_contour-for-coastline.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/12_select-non-coast.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/13_remove-non-coast.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/14_simplify-coast.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/15_delete-unnecessary-vertices.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/16_polygone-to-line.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/17_remove-all-fields.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/18_merge-vector-layers.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/19a_save-gmsh.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/19b_create-2d-mesh.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/19c_create-2d-mesh.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/19d_create-2d-mesh.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/20_create-3d-mesh.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/21_create-3d-mesh.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/22_save-3d-mesh.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/24_define-bc-values.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/25_simulation-result.png
web/content/docs/tools/workflows/Example-of-a-DGM-to-model-workflow/index.pandoc

This is a documentation for an exemplified workflow to use digital elevation model data to create a 3D groundwater flow model.
Proposed "Feature description" for "the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.2.1)": "Exemplified workflow to generate a 3D mesh from digital elevation model data." in "Testing and Documentation"

[Doc] Workflow 3d gw model from dgm

---

Jenkinsfile
web/assets/js/fancybox.js
web/assets/scss/main.scss
web/content/_index.pandoc
web/layouts/partials/components/feature.html
web/resources/_gen/assets/js/bundle.js_d11fe7b62c27961c87ecd0f2490357b9.content
web/resources/_gen/assets/js/bundle.js_d11fe7b62c27961c87ecd0f2490357b9.json
web/resources/_gen/assets/scss/scss/main.scss_4e7f57577ae5587f96f0311b7197bce0.content
web/resources/_gen/assets/scss/scss/main.scss_4e7f57577ae5587f96f0311b7197bce0.json
web/resources/_gen/assets/scss/scss/main.scss_fb23c2453b1d1395eb4b9e3814032563.content

Fixes  #2438:
See commit messages.
Please note: you can use markdown image captions (the part in square brackets `[...]`) to create styled and numbered captions like in [Example of a DGM-to-model-workflow](https://deploy-preview-2442--ogs.netlify.com/docs/tools/workflows/example-of-a-dgm-to-model-workflow/):
```
```

Web improvements

---

ProcessLib/ThermoMechanics/ThermoMechanicsProcess.cpp
ProcessLib/ThermoMechanics/ThermoMechanicsProcess.h

Almost verbatim copy from HydroMechanics.
If you have a better name for "thermal forces" I'd be happy to improve it.
Waiting for @fparisio for validation.

[PL] TM: Add NodalForces and HeatFlux.

---

web/content/docs/_index.pandoc
web/content/docs/tools/getting-started/overview.pandoc

Added GINA link

---

Applications/FileIO/CsvInterface.cpp
Applications/FileIO/CsvInterface.h
Tests/FileIO/TestCsvReader.cpp

Also added call to method in test so it doesn't get deleted again.

re-inserting previously deleted method

---

Documentation/ProjectFile/i_ProjectFile.md
web/content/docs/tools/getting-started/first_steps/index.pandoc
web/content/docs/userguide/basics/introduction.pandoc
web/content/docs/userguide/troubleshooting/general.md
web/content/docs/userguide/troubleshooting/project-file.pandoc

As requested by @ErikNixdorf.
I also found out that xmllint provides some schema checking with [RELAX NG](https://relaxng.org) schema. This maybe worth a look...

[web] Added instructions on prj-file checking with xmllint

---

Applications/Utils/FileConverter/OGS2VTK.cpp
Applications/Utils/MeshEdit/ExtractSurface.cpp
Applications/Utils/MeshEdit/createLayeredMeshFromRasters.cpp

Add ascii switch to VTK2OGS and createLayeredMeshFromRaster

---

web/content/docs/tools/workflows/create-a-simple-parallel-model/index.pandoc

[doc] Added some words about unsupported processes in "Create a simple parallel model"

---

Applications/DataExplorer/mainwindow.cpp

[DE] Adjusting names for bulk vtk export

---

netlify.toml
web/assets/js/discourse-news.js
web/layouts/index.html
web/layouts/partials/components/hero.html
web/layouts/partials/components/news.html
web/layouts/partials/components/quicklinks.html
web/layouts/partials/footer.html
web/resources/_gen/assets/js/js/discourse-news.js_d11fe7b62c27961c87ecd0f2490357b9.content
web/resources/_gen/assets/js/js/discourse-news.js_d11fe7b62c27961c87ecd0f2490357b9.json

Adds links to the 3 recent items in the announcements and the usability category on Discourse.
See the [preview here](https://deploy-preview-2456--ogs.netlify.com).
1. [ ] Feature description was added to the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.2.1)

[web] Added news links on front page.

---

Applications/DataExplorer/DataView/ElementTreeView.cpp
Applications/DataExplorer/DataView/GeoTreeView.cpp
Applications/DataExplorer/DataView/MeshView.cpp
Applications/DataExplorer/DataView/StationTreeView.cpp
Applications/DataExplorer/VtkVis/VtkVisPipelineView.cpp

[DE] Unifying column width for data views

---

Tests/MeshGeoToolsLib/TestConstructAdditionalMeshesFromGeoObjects.cpp

[T/MGTL] Reduce number of test points.

---

MeshLib/CMakeLists.txt
NumLib/TimeStepping/Algorithms/IterationNumberBasedTimeStepping.cpp
ProcessLib/HT/Tests.cmake
ProcessLib/HeatTransportBHE/Tests.cmake
ProcessLib/RichardsFlow/Tests.cmake
ProcessLib/SmallDeformation/SmallDeformationProcess.cpp
scripts/env/envinf1/cli.sh
scripts/env/frontend1/cli.sh

Some unrelated (to each other) smaller changes from WIP branches.

Random fixes

---

ProcessLib/ComponentTransport/Tests.cmake
Tests/Data/Parabolic/ComponentTransport/SimpleSynthetics/open_boundary_component-transport_cube_1e3.prj
Tests/Data/Parabolic/ComponentTransport/SimpleSynthetics/open_boundary_component-transport_cube_1e3_advective_form.prj

[T/HC] fix the race conditions in two benchmarks

---

Applications/ApplicationsLib/ProjectData.cpp
Applications/ApplicationsLib/ProjectData.h
Applications/CLI/ogs.cpp
ProcessLib/CreateTimeLoop.cpp
ProcessLib/CreateTimeLoop.h
ProcessLib/TimeLoop.cpp
ProcessLib/TimeLoop.h

Rename the time loop, extract the create method, rearrange private members.

Rename time loop

---

Applications/FileIO/SHPInterface.cpp
Applications/FileIO/SWMM/SWMMInterface.cpp
GeoLib/IO/XmlIO/Qt/XmlGmlInterface.cpp
GeoLib/Polygon.cpp
NumLib/DOF/LocalToGlobalIndexMap.cpp

Warning reported by cpp-check.

Fix unread variable warnings

---

netlify.toml

[web] Added netlify redirect from /papers to ufz.de pub list.

---

Jenkinsfile
scripts/docker/Dockerfile.clang.full
scripts/docker/Dockerfile.gcc.full
scripts/docker/Dockerfile.gcc.gui

[Jenkins] Update Conan to 1.16.0

---

Applications/ApplicationsLib/ProjectData.cpp

This pull request aims to fix the compiling error in parsing the subtree of chemical system when component transport process is switched off in Cmake.

Bugfix Parsing chemical system

---

ChemistryLib/CreateOutput.cpp
ChemistryLib/Output.h
ChemistryLib/PhreeqcIO.h
ChemistryLib/PhreeqcIOData/AqueousSolution.h
ChemistryLib/PhreeqcIOData/CreateReactionRate.cpp
ChemistryLib/PhreeqcIOData/EquilibriumPhase.h
ChemistryLib/PhreeqcIOData/KineticReactant.h

Fixed a few cppcheck/clang-tidy warnings in chemistry library

---

Jenkinsfile
scripts/cmake/CompilerSetup.cmake
scripts/cmake/Find.cmake
scripts/cmake/packaging/PackagingLinux.cmake
scripts/env/eve/cli.sh

Fixes eve modules deployment.
See https://www.opengeosys.org/docs/userguide/basics/envinf1 for usage.

Eve deploy fix

---

Applications/FileIO/Gmsh/GmshReader.cpp
Applications/FileIO/GocadIO/GocadSGridReader.cpp
Applications/FileIO/SWMM/SWMMInterface.cpp
Applications/Utils/FileConverter/ConvertSHPToGLI.cpp
Applications/Utils/FileConverter/MeshToRaster.cpp
Applications/Utils/MeshEdit/CreateBoundaryConditionsAlongPolylines.cpp
Applications/Utils/MeshEdit/NodeReordering.cpp
Applications/Utils/MeshEdit/UnityPreprocessing.cpp
Applications/Utils/ModelPreparation/PartitionMesh/NodeWiseMeshPartitioner.cpp
Applications/Utils/ModelPreparation/PartitionMesh/PartitionMesh.cpp
GeoLib/GEOObjects.cpp
MathLib/LinAlg/Lis/LisLinearSolver.cpp
MathLib/LinAlg/Lis/LisMatrix.cpp
MeshGeoToolsLib/GeoMapper.cpp
MeshLib/ElementStatus.cpp
MeshLib/MeshGenerators/VtkMeshConverter.cpp
MeshLib/MeshSearch/ElementSearch.cpp
NumLib/Fem/ShapeFunction/ShapeHex20-impl.h
ProcessLib/ComponentTransport/ComponentTransportFEM.h
ProcessLib/DeactivatedSubdomain.cpp
ProcessLib/LIE/Common/MeshUtils.cpp
ProcessLib/RichardsFlow/CreateRichardsFlowMaterialProperties.cpp
ProcessLib/SmallDeformation/SmallDeformationFEM.h
ProcessLib/SmallDeformationNonlocal/SmallDeformationNonlocalFEM.h
ProcessLib/ThermoHydroMechanics/ThermoHydroMechanicsFEM.h
ProcessLib/TimeLoop.cpp

Some more fixes. See corresponding commit messages.
Review commit-wise.

CPPCheck warning fixes

---

MaterialLib/MPL/CreateComponent.cpp
MaterialLib/MPL/CreatePhase.cpp

Prevent creation of temporary variables in checking the uniqueness.

[MatL/MPL] Check uniqueness of components and phases

---

ChemistryLib/PhreeqcIO.cpp
ChemistryLib/PhreeqcIO.h

With current commit changes, creation of phreeqc instance and database loading process will be executed only once in the ctor.

[CL] Move creation of Phreeqc instance in the ctor

---

Applications/DataHolderLib/Color.cpp
Applications/DataHolderLib/Color.h

Extracted from previous 'RandomFixes' PR.

Cleanup AppLib Color functions

---

web/content/docs/benchmarks/reactive-transport/ResultComparison.png
web/content/docs/benchmarks/reactive-transport/calcite.pandoc

[Web] Fixes on web documentation of equilibrium phase benchmark

---

Jenkinsfile

[Jenkins] master milestone

---

MeshLib/IO/VtkIO/PVDFile.cpp

Proposed by @zhangning737 in some other PR. This is extracted patch.
Fixes #2412 
1. [ ] Feature description was added to the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.2.1)

Fix problem #2412 of parallel output

---

ProcessLib/ThermoMechanics/ThermoMechanicsFEM-impl.h
ProcessLib/ThermoMechanics/ThermoMechanicsFEM.h

[TM] Moved the function definitions from ThermoMechanicsFEM.h to ThermoMechanicsFEM-impl.h

---

MaterialLib/SolidModels/Lubby2.cpp
MaterialLib/SolidModels/Lubby2.h
web/content/docs/benchmarks/small-deformations/lubby2.pdf

@nagelt changed Lubby2 to rate form, tested by sample shear benchmark.

Lubby2 rate form

---

NumLib/TimeStepping/Algorithms/IterationNumberBasedTimeStepping.cpp
ProcessLib/ProcessData.h
ProcessLib/TimeLoop.cpp

[NL] Store current dt in prev dt for next iteration.

---

web/content/docs/devguide/troubleshooting/conan.pandoc

as titled
Fixes # 
1. [ ] Feature description was added to the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.2.1)

fix the conan package name for vtk

---

scripts/cmake/CompilerSetup.cmake

[cmake] coloring compiler output

---

Applications/DataExplorer/DataView/DiagramView/DiagramList.cpp
Applications/Utils/ModelPreparation/PartitionMesh/PartitionMesh.cpp
Documentation/ProjectFile/prj/parameters/parameter/TimeDependentHeterogeneousParameter/c_TimeDependentHeterogeneousParameter.md
MaterialLib/MPL/Properties/ExponentialProperty.h
ParameterLib/Parameter.cpp
ParameterLib/TimeDependentHeterogeneousParameter.h
ProcessLib/Process.h
Tests/Data/Parabolic/LiquidFlow/TimeIntervalDirichletBC/TimeIntervalDirichletBC.prj
Tests/Data/Parabolic/LiquidFlow/TimeIntervalDirichletBC/bottom.vtu
Tests/Data/Parabolic/LiquidFlow/TimeIntervalDirichletBC/square.gml
Tests/Data/Parabolic/LiquidFlow/TimeIntervalDirichletBC/top.vtu

Cleanup and fixes in Documentation

---

ProcessLib/LIE/HydroMechanics/LocalAssembler/LocalDataInitializer.h
ProcessLib/LIE/SmallDeformation/LocalAssembler/LocalDataInitializer.h

fix a bug that Line3 element was disabled when OGS_MAX_ELEMENT_DIM=2

[LIE] bugfix. line3 should be included also in 2D

---

scripts/cmake/CheckHeaderCompilation.cmake

Fix check header

---

ProcessLib/HT/CreateHTProcess.cpp
ProcessLib/HT/HTFEM.h
ProcessLib/HT/HTMaterialProperties.h
ProcessLib/HT/HTProcess.cpp
ProcessLib/HT/HTProcess.h
ProcessLib/HT/HTProcessData.h
ProcessLib/HT/MonolithicHTFEM.h
ProcessLib/HT/StaggeredHTFEM-impl.h
ProcessLib/HT/StaggeredHTFEM.h

Only cleanup and renaming for consistency.

[PL/HT] Cleanup the code a bit.

---

Applications/Utils/FileConverter/CMakeLists.txt
Applications/Utils/FileConverter/Mesh2Shape.cpp

[utils] mesh to shape conversion

---

MaterialLib/TwoPhaseModels/TwoPhaseFlowWithPPMaterialProperties.h
ProcessLib/LiquidFlow/LiquidFlowMaterialProperties.h
ProcessLib/RichardsFlow/RichardsFlowMaterialProperties.h
ProcessLib/ThermalTwoPhaseFlowWithPP/ThermalTwoPhaseFlowWithPPMaterialProperties.h
ProcessLib/TimeLoop.cpp
ProcessLib/TwoPhaseFlowWithPP/TwoPhaseFlowWithPPMaterialProperties.h
ProcessLib/TwoPhaseFlowWithPrho/TwoPhaseFlowWithPrhoMaterialProperties.h

Various cleanups

---

Documentation/ProjectFile/prj/processes/process/HYDRO_MECHANICS/t_specific_storage.md
ProcessLib/HydroMechanics/CreateHydroMechanicsProcess.cpp

deleted unneeded docu file and fixed position of comment for docu-path

[HM] docu fix

---

ProcessLib/RichardsMechanics/RichardsMechanicsFEM.h

Was forgotten in the main PR #2635.

[PL] RM; Setting initial stress in FEM.

---

MaterialLib/MPL/Components/GetThermalExpansivity.cpp
MaterialLib/MPL/Properties/ExponentialProperty.cpp
MaterialLib/MPL/Properties/ExponentialProperty.h
MaterialLib/MPL/Properties/LinearProperty.cpp
MaterialLib/MPL/Properties/LinearProperty.h
MaterialLib/MPL/Properties/ParameterProperty.cpp
MaterialLib/MPL/Properties/ParameterProperty.h
MaterialLib/MPL/Property.cpp
MaterialLib/MPL/Property.h
ProcessLib/HT/StaggeredHTFEM-impl.h
Tests/MaterialLib/TestMPLExponentialProperty.cpp
Tests/MaterialLib/TestMPLLinearProperty.cpp

1. [ ] Feature description was added to the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.2.2)

Pass position and time parameters to derivatives and 2nd derivatives of property values

---

Documentation/bibliography.bib

add citation for documentation in bib-file

---

scripts/docker/Dockerfile.clang.full
scripts/docker/Dockerfile.gcc.full
scripts/docker/Dockerfile.gcc.gui

Related Conan issue: https://github.com/conan-io/conan/issues/5780
If you encounter this locally on your workstation upgrade Conan (to 1.18.5):
```
pip install --upgrade conan
```

Fix Conan Boost download

---

web/content/docs/benchmarks/thermo-hydro-mechanics/consolidation_pointheatsource.pandoc

THM benchmark doc: updating references + spell/grammar improvements

---

Jenkinsfile
scripts/docker/Dockerfile.clang.full
scripts/docker/Dockerfile.gcc.full
scripts/docker/Dockerfile.gcc.gui

Generated with https://github.com/ufz/ogs-container-maker/commit/9b0036a9c9816946d67248dfb61db3c4f334e645

Updated Dockerfiles to install clang-8

---

MaterialLib/MPL/Properties/ParameterProperty.cpp

[MatL/MPL] Return non-scalar values of a parameterized property.

---

ProcessLib/HydroMechanics/HydroMechanicsFEM-impl.h
ProcessLib/HydroMechanics/HydroMechanicsFEM.h
ProcessLib/HydroMechanics/HydroMechanicsProcess.cpp
ProcessLib/HydroMechanics/LocalAssemblerInterface.h

Outputs sigma and epsilon for all integration points.
Is identical to the implementation in ThermoMechanics.

[HM] output of sigma and epsilon per IP

---

ProcessLib/ComponentTransport/ComponentTransportFEM.h

There is another one, which is used.

[PL] CT; Remove unneeded getFlux implementation.

---

ChemistryLib/PhreeqcKernel.cpp
ChemistryLib/PhreeqcKernel.h
ChemistryLib/PhreeqcKernelData/AqueousSolution.h
Jenkinsfile
ProcessLib/HeatConduction/Tests.cmake
scripts/cmake/ConanSetup.cmake
scripts/docker/Dockerfile.clang.full
scripts/docker/Dockerfile.gcc.full
scripts/docker/Dockerfile.gcc.gui

**Important**: Update Conan to `1.19.2`!

Fix conan issues

---

web/content/docs/benchmarks/elliptic/elliptic-dirichlet-volumetric-source-term.pandoc
web/content/docs/benchmarks/elliptic/elliptic-dirichlet.pandoc
web/content/docs/benchmarks/elliptic/elliptic-neumann.pandoc
web/content/docs/benchmarks/elliptic/elliptic-pde-with-dirichlet-and-nodal-source-term.pandoc
web/content/docs/benchmarks/elliptic/elliptic-robin.pandoc
web/content/docs/benchmarks/elliptic/line_1e1_robin_left.png
web/content/docs/benchmarks/heatconduction/heatconduction-dirichlet.pandoc
web/content/docs/benchmarks/heatconduction/heatconduction-neumann.pandoc

Improve documentation

---

scripts/cmake/CompilerSetup.cmake
scripts/cmake/GCCSanitizer.cmake

[scripts] Options for enabling gcc sanitizer flags.

---

Applications/DataExplorer/mainwindow.cpp
Applications/FileIO/Legacy/createSurface.cpp
MeshLib/MeshEditing/RemoveMeshComponents.cpp
MeshLib/MeshEditing/RemoveMeshComponents.h

Cleanup / Fix warnings / Correct formatting

---

ProcessLib/ThermoHydroMechanics/ThermoHydroMechanicsFEM-impl.h

cleanup: removed unused variables

---

GeoLib/Polygon.cpp
MathLib/LinAlg/PETSc/PETScVector.cpp
MeshGeoToolsLib/MeshEditing/MarkNodesOutsideOfPolygon.h
MeshGeoToolsLib/MeshEditing/ResetMeshElementProperty.h
ProcessLib/LocalAssemblerTraits.h

Cleanup / fix spelling

---

CMakeLists.txt
ThirdParty/CMakeLists.txt

[cmake] Compile ChemistryLib only if there are mass transport related  processes

---

ProcessLib/CMakeLists.txt

ProcessLIb/CMakeLists.txt was not changed in #2722. This PR fixes that issue.

Amending #2722

---

ProcessLib/SourceTerms/CreateSourceTerm.cpp
ProcessLib/SourceTerms/Python/CreatePythonSourceTerm.cpp
ProcessLib/SourceTerms/Python/CreatePythonSourceTerm.h
ProcessLib/SourceTerms/Python/PythonSourceTerm.h
ProcessLib/SourceTerms/Python/PythonSourceTermLocalAssembler.h

@jbathmann If this works (I tested it with your example and it seems to work) for you, then it is a smaller bugfix, than in #2717.
Bugfix is only in the first commit. Second is cleanup.
#Closes #2717

Python source term DOF table fix.

---

MaterialLib/FractureModels/MohrCoulomb.cpp

Incremental formulation of the Mohr-Coulomb fracture model.
More or less covered by the existing `mohr_coulomb_load_path` ctest.

Fracture Mohr-Coulomb Incremental Form

---

ProcessLib/Deformation/SolidMaterialInternalToSecondaryVariables.h
ProcessLib/SmallDeformation/SmallDeformationProcess.cpp
ProcessLib/SmallDeformation/SmallDeformationProcess.h

Extract a function and do some cleanup in SDProcess.
Changes are covered by the `load_test_mc`.

SD; extract internal variables code

---

MeshLib/NodePartitionedMesh.h
NumLib/DOF/MeshComponentMap.cpp
NumLib/DOF/MeshComponentMap.h
ProcessLib/RichardsMechanics/Tests.cmake
Tests/Data/RichardsMechanics/RichardsFlow_2d_richardsflow.prj

As titled.
One benchmark is added for this bug fixing.

Fixed a bug in MeshComponentMap under PETSc with single thread

---

MaterialLib/SolidModels/CreepBGRa.cpp
MaterialLib/SolidModels/CreepBGRa.h
MaterialLib/SolidModels/Ehlers.cpp
MaterialLib/SolidModels/Ehlers.h
MaterialLib/SolidModels/LinearElasticIsotropic.cpp
MaterialLib/SolidModels/LinearElasticIsotropic.h
MaterialLib/SolidModels/LinearElasticOrthotropic.cpp
MaterialLib/SolidModels/LinearElasticOrthotropic.h
MaterialLib/SolidModels/Lubby2.cpp
MaterialLib/SolidModels/Lubby2.h
MaterialLib/SolidModels/MFront/MFront.cpp
MaterialLib/SolidModels/MFront/MFront.h
MaterialLib/SolidModels/MechanicsBase.h
Tests/MaterialLib/MFront.cpp

As titled.
Fixes https://github.com/ufz/ogs/issues/2738

[MatL] Use std::optional in SolidModels.

---

web/config.toml
web/content/docs/userguide/process-dependent-configuration/Heat_Transport_BHE.pandoc
web/content/docs/userguide/process-dependent-configuration/coaxial.png
web/content/docs/userguide/process-dependent-configuration/u_type.png

This is a pull request only for the documentation of the website.
The configuration tutorial for the HEAT_TRANSPORT_BHE process has been added. It will be listed in the process_dependent_configuration at User Guide.

Add configuration document of BHE process

---

scripts/cmake/ConanSetup.cmake
scripts/docker/Dockerfile.clang.full
scripts/docker/Dockerfile.gcc.full
scripts/docker/Dockerfile.gcc.gui

Bump Conan to 1.21.0

---

ProcessLib/AbstractJacobianAssembler.h
ProcessLib/AnalyticalJacobianAssembler.cpp
ProcessLib/AnalyticalJacobianAssembler.h
ProcessLib/ComponentTransport/ComponentTransportFEM.h
ProcessLib/CoupledSolutionsForStaggeredScheme.h
ProcessLib/HT/StaggeredHTFEM-impl.h
ProcessLib/HT/StaggeredHTFEM.h
ProcessLib/HydroMechanics/HydroMechanicsFEM-impl.h
ProcessLib/HydroMechanics/HydroMechanicsFEM.h
ProcessLib/LocalAssemblerInterface.cpp
ProcessLib/LocalAssemblerInterface.h
ProcessLib/PhaseField/PhaseFieldFEM-impl.h
ProcessLib/PhaseField/PhaseFieldFEM.h
ProcessLib/RichardsMechanics/RichardsMechanicsFEM-impl.h
ProcessLib/RichardsMechanics/RichardsMechanicsFEM.h
ProcessLib/ThermoMechanicalPhaseField/ThermoMechanicalPhaseFieldFEM-impl.h
ProcessLib/ThermoMechanicalPhaseField/ThermoMechanicalPhaseFieldFEM.h
ProcessLib/ThermoMechanics/ThermoMechanicsFEM-impl.h
ProcessLib/ThermoMechanics/ThermoMechanicsFEM.h
ProcessLib/VectorMatrixAssembler.cpp

Again a small extraction from the #2688

Pass local x to staggered assemblers

---

MeshLib/MeshGenerators/MeshGenerator.cpp
NumLib/Assembler/SerialExecutor.h
ProcessLib/HydroMechanics/HydroMechanicsProcess.h
ProcessLib/Process.h
ProcessLib/ThermoHydroMechanics/ThermoHydroMechanicsProcess.h
ProcessLib/ThermoMechanics/ThermoMechanicsProcess.h

Fix some clang-tidy warnings

---

Documentation/ProjectFile/prj/processes/process/HEAT_TRANSPORT_BHE/borehole_heat_exchangers/borehole_heat_exchanger/t_use_bhe_pipe_network.md
ProcessLib/HeatTransportBHE/BHE/CreateBHECoaxial.cpp
ProcessLib/HeatTransportBHE/BHE/CreateBHEUType.cpp
Tests/Data/Parabolic/T/3D_3BHEs_array/3bhes_1U.prj

[BHE] fix parameters' documentation

---

Applications/DataExplorer/NetCdfDialog/CMakeLists.txt
Applications/Utils/FileConverter/CMakeLists.txt
scripts/cmake/Find.cmake

[Conan] Fixed hdf5 linking errors on MSVC 2019.

---

MeshLib/MeshEditing/DuplicateMeshComponents.cpp
MeshLib/MeshEditing/DuplicateMeshComponents.h
ProcessLib/LiquidFlow/LiquidFlowProcess.cpp
ProcessLib/LiquidFlow/LiquidFlowProcess.h
scripts/cmake/test/AddTest.cmake

Formatting and small cmake issues

---

ProcessLib/ThermoHydroMechanics/ThermoHydroMechanicsProcess.cpp

Fixed a minor process-name artifact

fixed a naming issue in THM

---

Documentation/ProjectFile/material/fluid/density/c_density.md
Documentation/ProjectFile/material/fluid/viscosity/c_viscosity.md
MathLib/LinAlg/PETSc/PETScMatrix.h
MeshLib/MeshEditing/DuplicateMeshComponents.cpp
MeshLib/MeshEditing/DuplicateMeshComponents.h

Doxygen cleanups

---

BaseLib/Algorithm.h
MeshLib/MeshQuality/MeshValidation.cpp
MeshLib/PropertyVector.h

Clang format some code.

---

MaterialLib/MPL/Medium.h
MaterialLib/MPL/Phase.h
ProcessLib/HT/HTProcess.cpp
ProcessLib/HT/HTProcess.h
ProcessLib/HydroMechanics/CreateHydroMechanicsProcess.cpp

Using generalized MPL checker in HM and HT processes.

---

Jenkinsfile

Should fix dirty status on Doxygen.

[Jenkins] Update git submodules to fix dirty git state.

---

Documentation/ProjectFile/properties/property/RelativePermeabilityVanGenuchten/c_RelativePermeabilityVanGenuchten.md
Documentation/ProjectFile/properties/property/RelativePermeabilityVanGenuchten/t_exponent.md
Documentation/ProjectFile/properties/property/RelativePermeabilityVanGenuchten/t_minimum_relative_permeability_liquid.md
Documentation/ProjectFile/properties/property/RelativePermeabilityVanGenuchten/t_residual_gas_saturation.md
Documentation/ProjectFile/properties/property/RelativePermeabilityVanGenuchten/t_residual_liquid_saturation.md
Documentation/ProjectFile/properties/property/SaturationVanGenuchten/c_SaturationVanGenuchten.md
Documentation/ProjectFile/properties/property/SaturationVanGenuchten/t_entry_pressure.md
Documentation/ProjectFile/properties/property/SaturationVanGenuchten/t_exponent.md
Documentation/ProjectFile/properties/property/SaturationVanGenuchten/t_residual_gas_saturation.md
Documentation/ProjectFile/properties/property/SaturationVanGenuchten/t_residual_liquid_saturation.md
MaterialLib/MPL/CreateProperty.cpp
MaterialLib/MPL/Properties/CreateProperties.h
MaterialLib/MPL/Properties/CreateRelPermVanGenuchten.cpp
MaterialLib/MPL/Properties/CreateRelPermVanGenuchten.h
MaterialLib/MPL/Properties/CreateSaturationVanGenuchten.cpp
MaterialLib/MPL/Properties/CreateSaturationVanGenuchten.h
MaterialLib/MPL/Properties/Properties.h
MaterialLib/MPL/Properties/RelPermVanGenuchten.cpp
MaterialLib/MPL/Properties/RelPermVanGenuchten.h
MaterialLib/MPL/Properties/SaturationVanGenuchten.cpp
MaterialLib/MPL/Properties/SaturationVanGenuchten.h
Tests/MaterialLib/TestMPLRelPermVanGenuchten.cpp
Tests/MaterialLib/TestMPLSaturationVanGenuchten.cpp

Part of RM MPL conversion #2787 . CTests are there.

MPL van Genuchten saturation and relative permeability models.

---

web/content/docs/benchmarks/small-deformations/element_deactivation_2D.png
web/content/docs/benchmarks/small-deformations/element_deactivation_2D_3D_mesh.png
web/content/docs/benchmarks/small-deformations/element_deactivation_3D.png
web/content/docs/benchmarks/small-deformations/mechanics-linear-element_deactivation.pandoc

[web] Added a page for two mechanics benchmarks about the element deactivation approach

---

MaterialLib/MPL/VariableType.h

As preparation for new material models.

MPL; Add porosity, strain, vol. strain rate, and pressure rate.

---

Applications/DataExplorer/DataView/MeshLayerEditDialog.cpp
scripts/cmake/ConanSetup.cmake

Bump Conan Qt to 5.14.1 on Linux

---

MaterialLib/MPL/Component.cpp
MaterialLib/MPL/Component.h
MaterialLib/MPL/Phase.cpp
MaterialLib/MPL/Phase.h
ProcessLib/ComponentTransport/ComponentTransportProcess.cpp

Check MPL properties in ComponentTransport process.

---

ProcessLib/RichardsMechanics/IntegrationPointData.h
ProcessLib/RichardsMechanics/RichardsMechanicsFEM-impl.h
ProcessLib/RichardsMechanics/RichardsMechanicsProcess.cpp
ProcessLib/RichardsMechanics/RichardsMechanicsProcessData.h

[PL] RM; Porosity element average output.

---

MaterialLib/MPL/Properties/CreateDupuitPermeability.cpp
MaterialLib/MPL/Properties/CreateDupuitPermeability.h
MaterialLib/MPL/Properties/CreatePermeabilityOrthotropicPowerLaw.h
MaterialLib/MPL/VariableType.h

Small MPL cleanups

---

MaterialLib/MPL/Properties/CreateSaturationDependentSwelling.cpp
MaterialLib/MPL/Properties/CreateSaturationDependentSwelling.h
MaterialLib/MPL/Properties/PorosityFromMassBalance.cpp

- Two small fixes.
- Clamp porosity between 0 and 1.
See commit messages.

MPL porosity and swelling updates

---

ProcessLib/RichardsMechanics/RichardsMechanicsFEM-impl.h

Richards mechanics FEM fixes

---

Documentation/ProjectFile/prj/time_loop/processes/process/time_stepping/IterationNumberBasedTimeStepping/t_fixed_output_times.md
NumLib/TimeStepping/Algorithms/CreateIterationNumberBasedTimeStepping.cpp
NumLib/TimeStepping/Algorithms/EvolutionaryPIDcontroller.cpp
NumLib/TimeStepping/Algorithms/EvolutionaryPIDcontroller.h
NumLib/TimeStepping/Algorithms/IterationNumberBasedTimeStepping.cpp
NumLib/TimeStepping/Algorithms/IterationNumberBasedTimeStepping.h
NumLib/TimeStepping/Algorithms/TimeStepAlgorithm.cpp
NumLib/TimeStepping/Algorithms/TimeStepAlgorithm.h
Tests/Data/Parabolic/ComponentTransport/MassConservation/mass_conservation.prj
Tests/NumLib/TestTimeSteppingIterationNumber.cpp

2. [x] Tests covering your feature were added? New unit test. There are ctests using this feature.
3. [x] Any new feature or behavior change was documented? Documentation already available for this tag

Fixed output times for iteration number based time stepping algorithm

---

CODE_OF_CONDUCT.md
web/layouts/partials/global-footer-nav.html

Added a Code of Conduct because:
- it is a good thing to have
- it allows us to apply for [Netlifys Pro Plan](https://www.netlify.com/pricing/) ([for free](https://www.netlify.com/legal/open-source-policy/)) which raises the monthly build minutes limit (which we exceed since some time)

Code of Conduct

---

ProcessLib/GroundwaterFlow/GroundwaterFlowFEM.h
Tests/Data/Elliptic/cube_1x1x1_GroundWaterFlow/cube_1e4_anisotropic_pcs_0_ts_1_t_1.000000.vtu

Fixes wrong access to hydraulic conductivity in calculation of darcy velocity.

Correct Darcy velocity calculation in GroundwaterFlow process

---

ProcessLib/RichardsMechanics/CreateRichardsMechanicsProcess.cpp

[PL/RichardsMechanics] Rm unnecessary include.

---

ProcessLib/HeatTransportBHE/BHE/BHECommonCoaxial.cpp
ProcessLib/HeatTransportBHE/BHE/BHECommonCoaxial.h
ProcessLib/HeatTransportBHE/BHE/BHE_1U.cpp
ProcessLib/HeatTransportBHE/BHE/BHE_1U.h
ProcessLib/HeatTransportBHE/BHE/BHE_2U.cpp
ProcessLib/HeatTransportBHE/BHE/BHE_2U.h
ProcessLib/HeatTransportBHE/HeatTransportBHEProcess.cpp

This is part of the #2818 containing the common changes.

HT BHE cleanups

---

ProcessLib/SmallDeformation/Tests.cmake
Tests/Data/Mechanics/MohrCoulombAbboSloan/slope.gml
Tests/Data/Mechanics/MohrCoulombAbboSloan/slope.prj
Tests/Data/Mechanics/MohrCoulombAbboSloan/slope.vtu
Tests/Data/Mechanics/MohrCoulombAbboSloan/slope_pcs_0_ts_20_t_2.000000.vtu
Tests/Data/Mechanics/MohrCoulombAbboSloan/slope_pcs_0_ts_300_t_3.000000.vtu
web/content/docs/benchmarks/small-deformations/mechanics-slope-stability.pandoc
web/content/docs/benchmarks/small-deformations/slope_stability.pdf

1. [ ] Add a benchmark about  using strength reduction method to determine the factor of safety of a slope.
2. [ ] Tested and added testing benchmark.
3. [ ] The results could be obtained, but the program cannot stop running.  Please help optimize the code.

Strength reduction

---

ProcessLib/LiquidFlow/LiquidFlowLocalAssembler-impl.h
ProcessLib/LiquidFlow/LiquidFlowProcess.cpp
Tests/Data/Parabolic/LiquidFlow/AxiSymTheis/axisym_theis.prj
Tests/Data/Parabolic/LiquidFlow/BuildupTest/buildup_test.prj
Tests/Data/Parabolic/LiquidFlow/Flux/2D/square_1e1_calculatesurfaceflux.prj
Tests/Data/Parabolic/LiquidFlow/Flux/cube_1e3_calculatesurfaceflux.prj
Tests/Data/Parabolic/LiquidFlow/GravityDriven/gravity_driven.prj
Tests/Data/Parabolic/LiquidFlow/GravityDriven3D/anisotropic_gravity_driven3D.prj
Tests/Data/Parabolic/LiquidFlow/GravityDriven3D/isotropic_gravity_driven3D.prj
Tests/Data/Parabolic/LiquidFlow/LineDirichletNeumannBC/line_dirichlet_neumannBC.prj
Tests/Data/Parabolic/LiquidFlow/PressureBCatCornerOfAnisotropicSquare/pressureBC_at_corner_of_anisotropic_square.prj
Tests/Data/Parabolic/LiquidFlow/SimpleSynthetics/constraint_bc_1e3.prj
Tests/Data/Parabolic/LiquidFlow/TimeDependentHeterogeneousBoundaryConditions/TimeDependentHeterogeneousBoundaryConditions.prj
Tests/Data/Parabolic/LiquidFlow/TimeDependentHeterogeneousSourceTerm/TimeDependentHeterogeneousSourceTerm.prj
Tests/Data/Parabolic/LiquidFlow/TimeIntervalDirichletBC/TimeIntervalDirichletBC.prj
Tests/Data/Parabolic/LiquidFlow/Unconfined_Aquifer/BC_BC/TestSet_01.prj
Tests/Data/Parabolic/LiquidFlow/Unconfined_Aquifer/BC_BC_RECHARGE/TestSet_01.prj
Tests/Data/Parabolic/LiquidFlow/Unconfined_Aquifer/BC_BC_RECHARGE2/TestSet_01.prj
Tests/Data/Parabolic/LiquidFlow/Unconfined_Aquifer/BC_BC_STORAGE/TestSet_01.prj
Tests/Data/Parabolic/LiquidFlow/Verification/h1_1Dsource/h1_1Dsource.prj
Tests/Data/Parabolic/LiquidFlow/Verification/h1_1Dsteady/h1_1Dsteady.prj
Tests/Data/Parabolic/LiquidFlow/Verification/h1_3Dhydstat/h1_3Dhydstat.prj
Tests/Data/Parabolic/LiquidFlow/Verification/h2_1D1bt/h2_1D1bt.prj
Tests/Data/Parabolic/LiquidFlow/Verification/h2_1D2bt/h2_1D2bt.prj

Move MPL porosity to solid phase in LiquidFlow

---

MeshLib/IO/MPI_IO/NodePartitionedMeshReader.cpp
MeshLib/Vtk/VtkMappedMeshSource.cpp

As titled. Added the array with memory usage as smaller as possible.

Added an array of ghost element flags to mesh properties for parallel VTU ouput. 

---

Applications/DataExplorer/DataExplorer.cmake
CMakeLists.txt
scripts/cmake/Find.cmake

[CMake] Fixed OGS_USE_NETCDF logic when OGS_BUILD_GUI=OFF.

---

Jenkinsfile
web/content/docs/devguide/advanced/working-on-eve.pandoc
web/content/docs/userguide/basics/container.pandoc

Builds Singularity serial image with Python enabled and utils.
Closes #2759, #2761.

Container with Python enabled

---

ProcessLib/HeatTransportBHE/HeatTransportBHEProcess.cpp

[BHE/Python] Adjust BHE python BC for 1P process.

---

Applications/CLI/CMakeLists.txt
MathLib/LinAlg/PETSc/PETScVector.h

Small improvements for parallel computing

---

ProcessLib/LiquidFlow/CreateLiquidFlowProcess.cpp
ProcessLib/LiquidFlow/LiquidFlowLocalAssembler-impl.h
Tests/Data/Parabolic/LiquidFlow/AxiSymTheis/axisym_theis.prj
Tests/Data/Parabolic/LiquidFlow/BuildupTest/buildup_test.prj
Tests/Data/Parabolic/LiquidFlow/Flux/2D/square_1e1_calculatesurfaceflux.prj
Tests/Data/Parabolic/LiquidFlow/Flux/cube_1e3_calculatesurfaceflux.prj
Tests/Data/Parabolic/LiquidFlow/GravityDriven/gravity_driven.prj
Tests/Data/Parabolic/LiquidFlow/GravityDriven3D/anisotropic_gravity_driven3D.prj
Tests/Data/Parabolic/LiquidFlow/GravityDriven3D/isotropic_gravity_driven3D.prj
Tests/Data/Parabolic/LiquidFlow/LineDirichletNeumannBC/line_dirichlet_neumannBC.prj
Tests/Data/Parabolic/LiquidFlow/PressureBCatCornerOfAnisotropicSquare/pressureBC_at_corner_of_anisotropic_square.prj
Tests/Data/Parabolic/LiquidFlow/SimpleSynthetics/constraint_bc_1e3.prj
Tests/Data/Parabolic/LiquidFlow/TimeDependentHeterogeneousBoundaryConditions/TimeDependentHeterogeneousBoundaryConditions.prj
Tests/Data/Parabolic/LiquidFlow/TimeDependentHeterogeneousSourceTerm/TimeDependentHeterogeneousSourceTerm.prj
Tests/Data/Parabolic/LiquidFlow/TimeIntervalDirichletBC/TimeIntervalDirichletBC.prj
Tests/Data/Parabolic/LiquidFlow/Unconfined_Aquifer/BC_BC/TestSet_01.prj
Tests/Data/Parabolic/LiquidFlow/Unconfined_Aquifer/BC_BC_RECHARGE/TestSet_01.prj
Tests/Data/Parabolic/LiquidFlow/Unconfined_Aquifer/BC_BC_RECHARGE2/TestSet_01.prj
Tests/Data/Parabolic/LiquidFlow/Unconfined_Aquifer/BC_BC_STORAGE/TestSet_01.prj
Tests/Data/Parabolic/LiquidFlow/Verification/h1_1Dsource/h1_1Dsource.prj
Tests/Data/Parabolic/LiquidFlow/Verification/h1_1Dsteady/h1_1Dsteady.prj
Tests/Data/Parabolic/LiquidFlow/Verification/h1_3Dhydstat/h1_3Dhydstat.prj
Tests/Data/Parabolic/LiquidFlow/Verification/h2_1D1bt/h2_1D1bt.prj
Tests/Data/Parabolic/LiquidFlow/Verification/h2_1D2bt/h2_1D2bt.prj

LiquidFlow mv porosity/storage from MPL solid phase to medium scale.

---

Applications/DataExplorer/VtkVis/VtkCompositeThresholdFilter.cpp
Applications/DataExplorer/VtkVis/VtkRaster.cpp
Applications/DataExplorer/VtkVis/VtkVisTabWidget.cpp
Applications/FileIO/GMSInterface.cpp
Applications/FileIO/GMSInterface.h
Applications/FileIO/Gmsh/GMSHInterface.h
Applications/FileIO/GocadIO/GocadAsciiReader.cpp
Applications/FileIO/XmlIO/Qt/XmlPrjInterface.cpp
Applications/Utils/FileConverter/GocadTSurfaceReader.cpp
Applications/Utils/MeshEdit/Vtu2Grid.cpp
Applications/Utils/MeshGeoTools/createIntermediateRasters.cpp
Applications/Utils/ModelPreparation/PartitionMesh/NodeWiseMeshPartitioner.cpp
GeoLib/IO/XmlIO/Qt/XmlGmlInterface.cpp
MeshLib/MeshGenerators/QuadraticMeshGenerator.cpp
MeshLib/MeshGenerators/QuadraticMeshGenerator.h
MeshLib/findElementsWithinRadius.cpp
NumLib/ODESolver/ConvergenceCriterionPerComponentResidual.cpp
ProcessLib/Output/ProcessOutput.h

Small changes/fixes I found during update of logog to spdlog.

spdlog cleanups

---

BaseLib/RunTime.h

Get around strange windows code causing error
```
..\BaseLib/RunTime.h(45): error C3861: 'timeGetTime': identifier not found
```
in the #2875.

[BL] Use std::chrono::system_clock for wall-clock.

---

Applications/FileIO/SWMM/SWMMInterface.cpp
Applications/Utils/ModelPreparation/PartitionMesh/PartitionMesh.cpp
MaterialLib/SolidModels/MFront/CreateMFront.cpp

Various changes.

---

Jenkinsfile
scripts/docker/Dockerfile.web
web/content/docs/devguide/documentation/introduction.pandoc

Fix dead links and use urlchecker

---

CMakeLists.txt
ProcessLib/CMakeLists.txt
ThirdParty/CMakeLists.txt

[Cmake] Remove ChemistryLib and iphreeqc make for HeatTransportBHE process

---

web/content/docs/benchmarks/elliptic/elliptic-dirichlet-volumetric-source-term.pandoc
web/content/docs/benchmarks/elliptic/elliptic-dirichlet.pandoc
web/content/docs/benchmarks/elliptic/elliptic-neumann.pandoc
web/content/docs/benchmarks/elliptic/elliptic-robin.pandoc
web/content/docs/benchmarks/elliptic/poisson_equation.pandoc

I forgot to update the links in PR2860 (RenameGroundwaterFlowToEllipticProcess).

[web] Correct links to benchmark files.

---

Applications/Utils/SimpleMeshCreation/generateStructuredMesh.cpp
MeshLib/Elements/Element.h
MeshLib/Elements/PyramidRule5.cpp
MeshLib/MeshGenerators/MeshGenerator.cpp
MeshLib/MeshGenerators/MeshGenerator.h
Tests/MeshLib/TestMeshGenerator.cpp
web/content/docs/tools/meshing/structured-mesh-generation/index.pandoc

Create regular mesh consisting of pyramid elements.

---

MeshLib/Elements/MapBulkElementPoint.cpp
MeshLib/Elements/MapBulkElementPoint.h
ProcessLib/LiquidFlow/Tests.cmake
Tests/Data/Parabolic/LiquidFlow/Flux/3D/Pyramid/LF_cuboid_1x1x1_pyramid_6000_calculatesurfaceflux_pcs_0_ts_1_t_0.432000_expected.vtu
Tests/Data/Parabolic/LiquidFlow/Flux/3D/Pyramid/LF_cuboid_1x1x1_pyramid_6000_calculatesurfaceflux_pcs_0_ts_2_t_0.864000_expected.vtu
Tests/Data/Parabolic/LiquidFlow/Flux/3D/Pyramid/cuboid_1x1x1_pyramid_6000.vtu
Tests/Data/Parabolic/LiquidFlow/Flux/3D/Pyramid/cuboid_1x1x1_pyramid_6000_calculatesurfaceflux.prj
Tests/Data/Parabolic/LiquidFlow/Flux/3D/Pyramid/cuboid_1x1x1_pyramid_6000_entire_boundary.vtu
Tests/Data/Parabolic/LiquidFlow/Flux/3D/Pyramid/cuboid_1x1x1_pyramid_6000_entire_boundary_left_right_dirichlet_specific_flux_t_0.432000_expected.vtu
Tests/Data/Parabolic/LiquidFlow/Flux/3D/Pyramid/cuboid_1x1x1_pyramid_6000_entire_boundary_left_right_dirichlet_specific_flux_t_0.864000_expected.vtu
Tests/Data/Parabolic/LiquidFlow/Flux/3D/Pyramid/cuboid_1x1x1_pyramid_6000_left_boundary.vtu
Tests/Data/Parabolic/LiquidFlow/Flux/3D/Pyramid/cuboid_1x1x1_pyramid_6000_right_boundary.vtu

Add mapping from points of a pyramid face to points in the pyramid element. The feature is needed for the flux computations.
The [documentation](https://www.opengeosys.org/pdf/BulkElementMappings.pdf) was uploaded already in PR https://github.com/ufz/ogs/pull/2901.

Add mapping from points of a pyramid face to points in the pyramid element.

---

Jenkinsfile
scripts/docker/Dockerfile.web
web/content/books/bmb-4.pandoc
web/content/docs/devguide/documentation/introduction.pandoc

Fix web links

---

ProcessLib/Output/Output.cpp

[PL] Output: Rm debug output.

---

Jenkinsfile

build dir is now at `/tmp` on eve frontends as requested by the cluster guys.

[Jenkins] Eve tmpfs for build dir

---

web/content/docs/devguide/advanced/wsl.pandoc
web/content/docs/devguide/getting-started/prerequisites.pandoc
web/content/docs/devguide/troubleshooting/build.pandoc

Alternative Windows dev setup with the Windows Subsystem for Linux and Visual Studio Code. Highly recommended in my opinion!
[Preview is here](https://deploy-preview-2946--ogs.netlify.app/docs/devguide/advanced/wsl/)

[web] Added docs on WSL usage.

---

ProcessLib/Output/CreateOutput.cpp
ProcessLib/Output/Output.cpp
ProcessLib/Output/Output.h
ProcessLib/Output/ProcessOutput.cpp
ProcessLib/Output/ProcessOutput.h

It is based on the extracted Cleanup PR #2952. As soon as PR #2952 is merged i'll rebase.

Renames extracted from PR #2949

---

Applications/DataHolderLib/CMakeLists.txt
Applications/FileIO/Gmsh/GMSHInterface.h
Applications/FileIO/Gmsh/GMSHLine.h
Applications/FileIO/GocadIO/IndexCalculator.h
Applications/FileIO/Legacy/createSurface.h
Jenkinsfile
scripts/cmake/CheckHeaderCompilation.cmake
scripts/docker/Dockerfile.clang.gui

[Jenkins ] Check headers for full config

---

Jenkinsfile
scripts/cmake/conan/config/settings.yml

To reduce load on frontends as requested by the cluster guys.

[Jenkins] Run eve builds with nice

---

Jenkinsfile
scripts/docker/Dockerfile.gcc.full
scripts/docker/Dockerfile.gcc.gui

[Jenkins] Bump cppcheck to 2.0

---

Applications/ApplicationsLib/ProjectData.cpp
ProcessLib/ComponentTransport/Tests.cmake

[CL/T] Switch off the chemical solver option of PhreeqcKernel

---

ProcessLib/Output/CreateOutput.cpp

[PL/Out] Check if prefix contains '{:meshname}'.

---

Applications/ApplicationsLib/ProjectData.cpp
Applications/ApplicationsLib/ProjectData.h
ProcessLib/CreateTimeLoop.cpp
ProcessLib/CreateTimeLoop.h
ProcessLib/TimeLoop.cpp
ProcessLib/TimeLoop.h

[CL] Fix inconsistent parameter name.

---

Applications/ApplicationsLib/ProjectData.cpp
ChemistryLib/ChemicalSolverInterface.h
ChemistryLib/CreateChemicalSolverInterface.cpp
ChemistryLib/CreateChemicalSolverInterface.h
ChemistryLib/PhreeqcIO.cpp
ChemistryLib/PhreeqcIO.h
ChemistryLib/PhreeqcIOData/CreateAqueousSolution.cpp
ChemistryLib/PhreeqcIOData/CreateAqueousSolution.h
ChemistryLib/PhreeqcIOData/CreateSolutionComponent.cpp
ChemistryLib/PhreeqcIOData/CreateSolutionComponent.h
ProcessLib/ComponentTransport/ComponentTransportProcess.cpp
ProcessLib/ComponentTransport/ComponentTransportProcess.h
ProcessLib/ComponentTransport/CreateComponentTransportProcess.cpp
ProcessLib/ComponentTransport/CreateComponentTransportProcess.h

[CL] Remove mapping process id to component name

---

ProcessLib/RichardsMechanics/IntegrationPointData.h
ProcessLib/RichardsMechanics/LocalAssemblerInterface.h
ProcessLib/RichardsMechanics/RichardsMechanicsFEM-impl.h
ProcessLib/RichardsMechanics/RichardsMechanicsFEM.h
ProcessLib/RichardsMechanics/RichardsMechanicsProcess.cpp
Tests/Data/RichardsMechanics/deformation_dependent_porosity_swelling.prj
Tests/Data/RichardsMechanics/deformation_dependent_porosity_swelling_pcs_0_ts_102_t_3.500000.vtu
Tests/Data/RichardsMechanics/deformation_dependent_porosity_swelling_pcs_0_ts_107_t_4.000000.vtu
Tests/Data/RichardsMechanics/deformation_dependent_porosity_swelling_pcs_0_ts_14_t_0.500000.vtu
Tests/Data/RichardsMechanics/deformation_dependent_porosity_swelling_pcs_0_ts_19_t_1.000000.vtu
Tests/Data/RichardsMechanics/deformation_dependent_porosity_swelling_pcs_0_ts_33_t_1.500000.vtu
Tests/Data/RichardsMechanics/deformation_dependent_porosity_swelling_pcs_0_ts_38_t_2.000000.vtu
Tests/Data/RichardsMechanics/deformation_dependent_porosity_swelling_pcs_0_ts_63_t_2.500000.vtu
Tests/Data/RichardsMechanics/deformation_dependent_porosity_swelling_pcs_0_ts_88_t_3.000000.vtu

The quantities are for output only.

[PL/RM] Add dry densities output. Solid and pellet

---

MaterialLib/MPL/CreateComponent.h
MaterialLib/MPL/CreateMedium.cpp
MaterialLib/MPL/CreateMedium.h
MaterialLib/MPL/CreatePhase.h

1. missing `#pragma once` in header file.
This may cause weird behavior if a new file is added. I am not sure whether  there are other header files miss that include safe guard too. Does anyone know some methods to check this issue?
2. missing include in one file.

Two corrections in MPL classes

---

Applications/Utils/FileConverter/NetCdfConverter.cpp
ChemistryLib/PhreeqcKernelData/EquilibriumReactants.cpp
ChemistryLib/PhreeqcKernelData/EquilibriumReactants.h
MaterialLib/SolidModels/Lubby2.cpp
MaterialLib/SolidModels/Lubby2.h
MathLib/LinAlg/Eigen/EigenTools.h
MeshLib/MeshGenerators/MeshLayerMapper.cpp
MeshLib/MeshGenerators/MeshLayerMapper.h
ParameterLib/TimeDependentHeterogeneousParameter.cpp
ProcessLib/TwoPhaseFlowWithPrho/TwoPhaseFlowWithPrhoMaterialProperties.cpp

CppCheck constness

---

ChemistryLib/CreateChemicalSolverInterface.cpp
ChemistryLib/PhreeqcIO.cpp
ChemistryLib/PhreeqcIO.h
ChemistryLib/PhreeqcIOData/AqueousSolution.cpp
ChemistryLib/PhreeqcIOData/AqueousSolution.h
ChemistryLib/PhreeqcIOData/ChemicalSystem.h
ChemistryLib/PhreeqcIOData/CreateAqueousSolution.cpp
ChemistryLib/PhreeqcIOData/CreateAqueousSolution.h
ChemistryLib/PhreeqcIOData/CreateChemicalSystem.cpp
ChemistryLib/PhreeqcIOData/CreateChemicalSystem.h
ChemistryLib/PhreeqcIOData/CreateOutput.cpp
ChemistryLib/PhreeqcIOData/CreateSolutionComponent.cpp
ChemistryLib/PhreeqcIOData/CreateSolutionComponent.h
MathLib/LinAlg/MatrixVectorTraits.cpp
MathLib/LinAlg/MatrixVectorTraits.h

With this pull request, we improve the OGS-6#Phreeqc interface structure as follows
* Encapsulated the class members `AqueousSolution`, `KIneticReactant`, and `EquilibriumReactant` into `ChemicalSystem`;
* Used more proper data type for the class members of `AqueousSolution` and `Component`;

[CL] Encapsulated into ChemicalSystem

---

MeshGeoToolsLib/GeoMapper.cpp
MeshLib/MeshEditing/AddLayerToMesh.cpp
MeshLib/MeshEditing/FlipElements.cpp
MeshLib/MeshEditing/FlipElements.h

Clang format

---

Applications/ApplicationsLib/ProjectData.cpp

[A/AppLib] Fix spelling in ProjectData.

---

MeshLib/Elements/TemplateElement-impl.h
Tests/BaseLib/TestConfigTree.cpp
Tests/MaterialLib/TestCapillaryPressureSaturationModel.cpp
Tests/MaterialLib/TestFluidDensity.cpp
Tests/MaterialLib/TestFluidProperties.cpp
Tests/MaterialLib/TestFluidSpecificHeatCapacityModel.cpp
Tests/MaterialLib/TestFluidThermalConductivityModel.cpp
Tests/MaterialLib/TestFluidViscosity.cpp
Tests/MaterialLib/TestMPL.cpp
Tests/MaterialLib/TestMPL.h
Tests/MaterialLib/TestMPLCapillaryPressureRegularizedVanGenuchten.cpp
Tests/MaterialLib/TestMPLIdealGasLaw.cpp
Tests/MaterialLib/TestMPLParseMaterial.cpp
Tests/MaterialLib/TestMPLRelPermBrooksCorey.cpp
Tests/MaterialLib/TestMPLRelPermLiakopoulos.cpp
Tests/MaterialLib/TestMPLSaturationBrooksCorey.cpp
Tests/MaterialLib/TestMPLSaturationLiakopoulos.cpp
Tests/MaterialLib/TestPorousMediumStorage.cpp
Tests/MaterialLib/TestRelativePermeabilityModel.cpp
Tests/MathLib/TestLinearSolver.cpp
Tests/MathLib/TestPiecewiseLinearCurve.cpp
Tests/NumLib/TestODEInt.cpp
Tests/NumLib/TestTimeSteppingEvolutionaryPIDcontroller.cpp
Tests/ParameterLib/Parameter.cpp
Tests/TestTools.cpp
Tests/TestTools.h

* Set createTestProperty as a common function for MPL test.
* Added namespace to two common functions.
* Fixed the error that new file in Tests gives a conflict with VTK headers.

Some changes in Tests

---

ChemistryLib/CMakeLists.txt

Fix PhreeqcIO.cpp unity build

---

GeoLib/Polygon.cpp
MathLib/LinAlg/Eigen/EigenVector.h
MathLib/LinAlg/Lis/LisMatrix.h
MeshGeoToolsLib/BoundaryElementsSearcher.cpp
MeshGeoToolsLib/MeshNodeSearcher.cpp
NumLib/DOF/ComputeSparsityPattern.cpp
NumLib/DOF/LocalToGlobalIndexMap.cpp
NumLib/DOF/MeshComponentMap.cpp
NumLib/Extrapolation/LocalLinearLeastSquaresExtrapolator.cpp
ProcessLib/HydroMechanics/HydroMechanicsFEM.h
ProcessLib/LIE/Common/LevelSetFunction.cpp
ProcessLib/LIE/Common/MeshUtils.cpp
ProcessLib/LIE/SmallDeformation/SmallDeformationProcess.cpp
ProcessLib/Output/IntegrationPointWriter.cpp
ProcessLib/Process.cpp
ProcessLib/ProcessVariable.cpp
ProcessLib/SmallDeformation/SmallDeformationFEM.h
ProcessLib/SmallDeformationNonlocal/SmallDeformationNonlocalFEM.h
ProcessLib/TES/TESLocalAssembler-impl.h
ProcessLib/VectorMatrixAssembler.cpp
Tests/MeshGeoToolsLib/TestGeoMapper.cpp
Tests/MeshLib/TestMeshGenerator.cpp

Manual changes on selected for-loops as suggested by cppcheck.

Use STL algorithms instead of raw for-loops.

---

.gitmodules
Applications/DataExplorer/Base/RecentFiles.cpp
Applications/DataExplorer/VtkVis/NetCdfConfigureDialog.cpp
Applications/DataExplorer/VtkVis/NetCdfConfigureDialog.h
Applications/DataExplorer/VtkVis/VisualizationWidget.h
Applications/DataExplorer/mainwindow.cpp
Applications/DataExplorer/mainwindow.h
CONTRIBUTING.md
Documentation/bibliography/other.bib
Documentation/mainpage.dox
GeoLib/IO/XmlIO/Boost/BoostXmlGmlInterface.cpp
MathLib/Vector3.h
NumLib/DOF/LocalToGlobalIndexMap.h
scripts/ci/extends/rules-master-manual.yml
scripts/ci/jobs/build-docs.yml
scripts/ci/jobs/build-gui-linux.yml
scripts/ci/jobs/build-gui-mac.yml
scripts/ci/jobs/build-gui-win.yml
scripts/ci/jobs/build-linux-frontend.yml
scripts/ci/jobs/build_image.yml
scripts/cmake/DocumentationSetup.cmake

- a few GitLab CI things, no review necessary
- Fixed some links in Doxygen, some urls are not available anymore or have changed

Some GitLab preparation

---

MaterialLib/MPL/Properties/Exponential.cpp
Tests/Data/Parabolic/HT/FaultedCube/Ra_795_fault_bcgs_jacobi.prj
Tests/MaterialLib/TestMPLExponential.cpp

Previous version negates the exponent factor m internally, which is not obvious.

[MPL] Change exponential prop. to a*exp(m(x-x0)).

---

Documentation/ProjectFile/properties/property/PermeabilityMohrCoulombFailureIndexModel/c_PermeabilityMohrCoulombFailureIndexModel.md
Documentation/ProjectFile/properties/property/PermeabilityMohrCoulombFailureIndexModel/t_cohesion.md
Documentation/ProjectFile/properties/property/PermeabilityMohrCoulombFailureIndexModel/t_fitting_factor.md
Documentation/ProjectFile/properties/property/PermeabilityMohrCoulombFailureIndexModel/t_friction_angle.md
Documentation/ProjectFile/properties/property/PermeabilityMohrCoulombFailureIndexModel/t_initial_permeability.md
Documentation/ProjectFile/properties/property/PermeabilityMohrCoulombFailureIndexModel/t_maximum_permeability.md
Documentation/ProjectFile/properties/property/PermeabilityMohrCoulombFailureIndexModel/t_reference_permeability.md
Documentation/ProjectFile/properties/property/PermeabilityMohrCoulombFailureIndexModel/t_tensile_strength_parameter.md
Documentation/bibliography/other.bib
MaterialLib/MPL/CreateProperty.cpp
MaterialLib/MPL/Properties/CreatePermeabilityMohrCoulombFailureIndexModel.cpp
MaterialLib/MPL/Properties/CreatePermeabilityMohrCoulombFailureIndexModel.h
MaterialLib/MPL/Properties/CreateProperties.h
MaterialLib/MPL/Properties/PermeabilityMohrCoulombFailureIndexModel.cpp
MaterialLib/MPL/Properties/PermeabilityMohrCoulombFailureIndexModel.h
Tests/MaterialLib/TestMPLPermeabilityMohrCoulombFailureIndexModel.cpp

As titled.
1. [x] Feature description was added to the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.3.1).
2. [x] Tests covering your feature were added? Yes, it does. An unit test is added.
3. [x] Any new feature or behavior change was documented? Yes, it is. The formulas of the model and some references are provided in the source documentation, the input parameters are documented as well.
Reviewing can be started once PR #2971 and PR #2988 are merged.
Next PR: benchmark.

PermeabilityMohrCoulombFailureIndexModel

---

Applications/DataExplorer/DataView/MeshMapping2D.ui
Applications/DataExplorer/DataView/MeshMapping2DDialog.cpp
Applications/DataExplorer/DataView/MeshMapping2DDialog.h
Applications/DataExplorer/DataView/MeshView.cpp
MeshLib/MeshGenerators/MeshLayerMapper.cpp
MeshLib/MeshGenerators/MeshLayerMapper.h

*[Merging this isn't urgent, so we can wait until after the GitLab-migration if that helps]*
The change allows to map a mesh based on multiple DEMs with different files being used for patches of the mesh.

[GUI] Added option to ignore NoData values for mesh mapping

---

LICENSE.txt
README.md

To be discussed...
BSD-3-Clause is an approved OSI license.
- https://opensource.org/licenses/BSD-3-Clause
- https://en.wikipedia.org/wiki/BSD_licenses
2. [x] Add citing instructions to web site

Change license to BSD-3-Clause ("Modified BSD License").
